package com.zuehlke.pgadmissions.domain.helpers;

public enum NotificationListTestCase {

    DUE_TASK_REMINDER, //
    DUE_TASK_NOTIFICATION_NEVER_RECEIVED, //
    DUE_TASK_NOTIFICATION_RECEIVED_AGES_AGO, //
    DUE_UPDATE_NOTIFICATION_NEVER_RECEIVED, //
    DUE_UPDATE_NOTIFICATION_RECEIVED_AGES_AGO, //
    RECEIVED_RECENT_TASK_NOTIFICATION, //
    RECEIVED_RECENT_UPDATE_NOTIFICATION, //
    NOTIFICATION_WINDOW_EXPIRED, //
    NO_URGENT_ACTIONS, //
    NO_UPDATES, //
    OLD_UPDATES, //
    ACTION_NOT_SYNDICATED, //
    ROLE_NOT_SUBSCRIBED_TO_UPDATES, //
    USER_ACCOUNT_DISABLED, //
    USER_ACCOUNT_EXPIRED, //
    USER_ACCOUNT_LOCKED, //
    USER_CREDENTIALS_EXPIRED, //
    OPPORTUNITY_REQUEST_NOTIFICATION_NEVER_RECEIVED, //
    OPPORTUNITY_REQUEST_NOTIFICATION_RECEIVED_AGES_AGO, //
    RECEIVED_RECENT_OPPORTUNITY_REQUEST_NOTIFICATION, //
    ROLE_NOT_SUPERADMINISTRATOR;

}