package com.zuehlke.pgadmissions.domain.helpers;

public enum NotificationListTestCase {

    DUETASKREMINDER,
    DUETASKNOTIFICATIONNEVERRECEIVED,
    DUETASKNOTIFICATIONRECEIVEDAGESAGO,
    DUEUPDATENOTIFICATIONNEVERRECEIVED,
    DUEUPDATENOTIFICATIONRECEIVEDAGESAGO,
    RECEIVEDRECENTTASKNOTIFICATION,
    RECIEVEDRECENTUPDATENOTIFICATION,
    NOTIFICATIONWINDOWEXPIRED,
    NOURGENTACTIONS,
    NOUPDATES,
    OLDUPDATES,
    ACTIONNOTSYNDICATED,
    ROLENOTSUBSCRIBEDTOUPDATES,
    USERACCOUNTDISABLED,
    USERACCOUNTEXPIRED, 
    USERACCOUNTLOCKED, 
    USERCREDENTIALSEXPIRED;
    
}