package com.zuehlke.pgadmissions.domain.definitions;

public enum PrismAdvertDomain {

    PRECLINICAL_MEDICINE("A1"), //
    PRECLINICAL_DENTISTRY("A2"), //
    CLINICAL_MEDICINE("A3"), //
    CLINICAL_DENTISTRY("A4"), //
    ANATOMY_PHYSIOLOGY("B1"), //
    PHARMACOLOGY("B2"), //
    PHARMACY("B3"), //
    NUTRITION("B4"), //
    OPTHALMICS("B5"), //
    AUDIOLOGY("B6"), //
    NURSING("B7"), //
    MEDICAL_TECHNOLOGY("B8"), //
    BIOLOGY("C1"), //
    BOTANY("C2"), //
    ZOOLOGY("C3"), //
    GENETICS("C4"), //
    MICROBIOLOGY("C5"), //
    MOLECULAR_BIOLOGY_BIOPHYSICS("C6"), //
    BIOCHEMISTRY("C7"), //
    PSYCHOLOGY("C8"), //
    VETERINARY_SCIENCES("D1"), //
    AGRICULTURE("D2"), //
    FORESTRY("D3"), //
    FOOD_SCIENCE("D4"), //
    AGRICULTURAL_SCIENCE("D8"), //
    CHEMISTRY("F1"), //
    MATERIALS("F2"), //
    PHYSICS("F3"), //
    ARCHAEOLOGY("F4"), //
    ASTRONOMY("F5"), //
    GEOLOGY("F6"), //
    OCEANOGRAPHY("F7"), //
    GEOGRAPHY("F8"), //
    ENVIRONMENTAL_SCIENCE("F9"), //
    MATHEMATICS("G1"), //
    STATISTICS("G4"), //
    COMPUTER_SCIENCE("G5"), //
    CIVIL_ENGINEERING("H2"), //
    MECHANICAL_ENGINEERING("H3"), //
    AERONAUTICAL_ENGINEERING("H4"), //
    ELECTRICAL_ENGINEERING("H5"), //
    ELECTRONIC_ENGINEERING("H6"), //
    PRODUCTION_ENGINEERING("H7"), //
    CHEMICAL_ENGINEERING("H8"), //
    MINERALS_TECHNOLOGY("J1"), //
    METALLURGY("J2"), //
    CERAMICS_GLASSES("J3"), //
    POLYMERS_TEXTILES("J4"), //
    MARITIME_TECHNOLOGY("J6"), //
    BIOTECHNOLOGY("J7"), //
    ARCHITECTURE("K1"), //
    BUILDING("K2"), //
    ENVIRONMENTAL_TECHNOLOGY("K3"), //
    TOWN_PLANNING("K4"), //
    ECONOMICS("L1"), //
    SOCIOLOGY("L3"), //
    SOCIAL_POLICY_ADMINISTRATION("L4"), //
    SOCIAL_WORK("L5"), //
    ANTHROPOLOGY("L6"), //
    POLITICS("M1"), //
    BUSINESS_MANAGEMENT("N1"), //
    OPERATIONAL_RESEARCH("N2"), //
    FINANCIAL_MANAGEMENT("N3"), //
    ACCOUNTANCY("N4"), //
    MARKETING("N5"), //
    INDUSTRIAL_RELATIONS("N6"), //
    CATERING_HOSPITALITY("N7"), //
    ESTATE_MANAGEMENT("N8"), //
    TRANSPORT_MANAGEMENT("N9"), //
    LIBRARIANSHIP("P1"), //
    INFORMATION_SCIENCE("P2"), //
    COMMUNICATION_STUDIES("P3"), //
    MEDIA_STUDIES("P4"), //
    PUBLISHING("P5"), //
    JOURNALISM("P6"), //
    LINGUISTICS("Q1"), //
    COMPARATIVE_LITERATURE("Q2"), //
    ENGLISH("Q3"), //
    AMERICAN_STUDIES("Q4"), //
    CELTIC_LITERATURE_CULTURE("Q5"), //
    LATIN_LITERATURE_CULTURE("Q6"), //
    GREEK_LITERATURE_CULTURE("Q7"), //
    CLASSICS("Q8"), //
    ANCIENT_LANGUAGES("Q9"), //
    FRENCH_LITERATURE_CULTURE("R1"), //
    GERMAN_LITERATURE_CULTURE("R2"), //
    ITALIAN_LITERATURE_CULTURE("R3"), //
    SPANISH_LITERATURE_CULTURE("34"), //
    PORTUGUESE_LITERATURE_CULTURE("R5"), //
    LATIN_AMERICAN_LITERATURE_CULTURE("R6"), //
    SCANDINAVIAN_LITERATURE_CULTURE("R7"), //
    RUSSIAN_LITERATURE_CULTURE("R8"), //
    SLAVONIC_EAST_EUROPEAN_LITERATURE_CULTURE("T1"), //
    EUROPEAN_LITERATURE_CULTURE("T2"), //
    CHINESE_LITERATURE_CULTURE("T3"), //
    JAPANESE_LITERATURE_CULTURE("T4"), //
    ASIAN_LITERATURE_CULTURE("T5"), //
    MIDDLE_EAST_LITERATURE_CULTURE("T6"), //
    AFRICAN_LITERATURE_CULTURE("T7"), //
    HISTORY("V1"), //
    ECONOMIC_SOCIAL_HISTORY("V3"), //
    HISTORY_ART("V4"), //
    HISTORY_PHILOSOPHY_SCIENCE("V5"), //
    PHILOSOPHY("V7"), //
    THEOLOGY_RELIGION("V8"), //
    HUMANITIES("V9"), //
    FINE_ART("W1"), //
    DESIGN("W2"), //
    MUSIC("W3"), //
    DRAMA("W4"), //
    CINEMATICS("W5"), //
    CRAFTS("W6"), //
    BEAUTY_HAIRDRESSING("W8"), //
    TEACHER_TRAINING("X1"), //
    PHYSICAL_EDUCATION("X2"), //
    ACADEMIC_STUDIES("X3"), //
    CHILD_TEACHING("X4"), //
    ADULT_TEACHING("X5"), //
    SPECIAL_NEEDS_TEACHING("X6"), //
    EDUCATIONAL_TECHNOLOGY("X7"), //
    EDUCATION_MANAGEMENT("X8"), //
    COMBINED_SCIENCE("Y1"), //
    COMBINED_SOCIAL_SCIENCE("Y2"), //
    COMBINED_ART("Y3"), //
    RESEARCH_METHODS("Y6");

    private String hesaCode;

    PrismAdvertDomain(String hesaCode) {
        this.hesaCode = hesaCode;
    }

    public String getHesaCode() {
        return hesaCode;
    }

}
