package com.zuehlke.pgadmissions.domain.definitions;

public enum PrismDisplayPropertyCategory {

    SYSTEM_GLOBAL, //
    SYSTEM_COMMENT, //
    SYSTEM_NOTIFICATION, //
    SYSTEM_STATE_GROUP, //
    SYSTEM_VALIDATION_ERROR, //
    SYSTEM_ROLE, //
    SYSTEM_INTEGRATION, //
    INSTITUTION_GLOBAL, //
    INSTITUTION_COMMENT, //
    INSTITUTION_STATE_DURATION, //
    INSTITUTION_NOTIFICATION, //
    INSTITUTION_STATE_GROUP, //
    PROGRAM_GLOBAL, //
    PROGRAM_COMMENT, //
    PROGRAM_STATE_DURATION, //
    PROGRAM_NOTIFICATION, //
    PROGRAM_STATE_GROUP, //
    PROJECT_GLOBAL, //
    PROJECT_COMMENT, //
    PROJECT_STATE_DURATION, //
    PROJECT_NOTIFICATION, //
    PROJECT_STATE_GROUP, //
    APPLICATION_GLOBAL, //
    APPLICATION_PROGRAM_DETAIL, //
    APPLICATION_SUPERVISOR, //
    APPLICATION_PERSONAL_DETAIL, //
    APPLICATION_PASSPORT, //
    APPLICATION_LANGUAGE_QUALIFICATION, //
    APPLICATION_ADDRESS, //
    APPLICATION_QUALIFICATION, //
    APPLICATION_EMPLOYMENT_POSITION, //
    APPLICATION_FUNDING, //
    APPLICATION_PRIZE, //
    APPLICATION_REFEREE, //
    APPLICATION_DOCUMENT, //
    APPLICATION_ADDITIONAL_INFORMATION, //
    APPLICATION_COMMENT, //
    APPLICATION_STATE_DURATION, //
    APPLICATION_WORKFLOW, //
    APPLICATION_NOTIFICATION, //
    APPLICATION_REPORT, //
    APPLICATION_STATE_GROUP,
    APPLICATION_ACTION_CONFIRMATION_GROUP

}
