package com.zuehlke.pgadmissions.domain.definitions;

public enum PrismDisplayCategory {

    SYSTEM_GLOBAL, //
    SYSTEM_COMMENT, //
    INSTITUTION_GLOBAL, //
    INSTITUTION_COMMENT, //
    PROGRAM_GLOBAL, //
    PROGRAM_COMMENT, //
    PROJECT_GLOBAL, //
    PROJECT_COMMENT, //
    APPLICATION_GLOBAL, //
    APPLICATION_PROGRAM_DETAIL, //
    APPLICATION_SUPERVISOR, //
    APPLICATION_PERSONAL_DETAIL, //
    APPLICATION_PASSPORT, //
    APPLICATION_LANGUAGE_QUALIFICATION, //
    APPLICATION_ADDRESS, //
    APPLICATION_QUALIFICATION, //
    APPLICATION_EMPLOYMENT_POSITION, //
    APPLICATION_FUNDING, //
    APPLICATION_REFEREE, //
    APPLICATION_DOCUMENT, //
    APPLICATION_ADDITIONAL_INFORMATION, //
    APPLICATION_COMMENT;

}
