package com.zuehlke.pgadmissions.domain.definitions;

import com.zuehlke.pgadmissions.domain.definitions.workflow.PrismScope;

import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismScope.*;

public enum PrismDisplayPropertyCategory {

    SYSTEM_GLOBAL(SYSTEM),
    SYSTEM_COMMENT(SYSTEM),
    SYSTEM_NOTIFICATION(SYSTEM),
    SYSTEM_STATE_GROUP(SYSTEM),
    SYSTEM_STATE_TRANSITION(SYSTEM),
    SYSTEM_ACTION(SYSTEM),
    SYSTEM_ROLE(SYSTEM),
    SYSTEM_OPPORTUNITY_TYPE(SYSTEM),
    SYSTEM_YES_NO_UNSURE(SYSTEM),
    SYSTEM_STUDY_OPTION(SYSTEM),
    SYSTEM_OPPORTUNITY_CATEGORY(SYSTEM),
    SYSTEM_DURATION(SYSTEM),
    SYSTEM_FILTER_PROPERTY(SYSTEM),
    SYSTEM_FILTER_EXPRESSION(SYSTEM),
    SYSTEM_IMPORTED_ENTITY(SYSTEM),
    SYSTEM_ADVERT_INDUSTRY(SYSTEM),
    SYSTEM_ADVERT_FUNCTION(SYSTEM),
    SYSTEM_NOTIFICATION_TEMPLATE(SYSTEM),
    SYSTEM_REFEREE_TYPE(SYSTEM),
    SYSTEM_RESERVE_STATUS(SYSTEM),
    SYSTEM_DISPLAY_PROPERTY_CATEGORY(SYSTEM),
    SYSTEM_REPORT_INDICATOR_GROUP(SYSTEM),
    SYSTEM_VALIDATION_ERROR(SYSTEM),
    SYSTEM_INTEGRATION(SYSTEM),
    SYSTEM_STATE_DURATION(SYSTEM),
    SYSTEM_MONTH(SYSTEM),
    SYSTEM_WORKFLOW(SYSTEM),
    SYSTEM_DECLINE_ACTION(SYSTEM),
    SYSTEM_HTML_GENERAL_SECTION(SYSTEM),
    SYSTEM_AUTHENTICATE_SECTION(SYSTEM),
    SYSTEM_OPPORTUNITIES_SECTION(SYSTEM),
    SYSTEM_OPPORTUNITIES_ENQUIRY_SECTION(SYSTEM),
    SYSTEM_ADVERTISE_SECTION(SYSTEM),
    SYSTEM_RESOURCES_SECTION(SYSTEM),
    SYSTEM_RESOURCE_SECTION(SYSTEM),
    SYSTEM_ACCOUNT_SECTION(SYSTEM),
    SYSTEM_HTML_FIELDS(SYSTEM),
    SYSTEM_HTML_COMMON(SYSTEM),
    SYSTEM_HTML_ADDRESS(SYSTEM),
    SYSTEM_HTML_RESOURCE_PARENT(SYSTEM),
    SYSTEM_HTML_RESOURCE_OPPORTUNITY(SYSTEM),
    SYSTEM_HTML_CREATE_RESOURCE_FAMILY(SYSTEM),
    SYSTEM_HTML_RESOURCE_CONFIGURATION(SYSTEM),
    SYSTEM_HTML_MANAGE_USERS(SYSTEM),
    SYSTEM_HTML_EMAIL_TEMPLATE_CONFIGURATION(SYSTEM),
    SYSTEM_HTML_CUSTOM_FORMS_CONFIGURATION(SYSTEM),
    SYSTEM_HTML_WORKFLOW_CONFIGURATION(SYSTEM),
    SYSTEM_HTML_TRANSLATIONS_CONFIGURATION(SYSTEM),
    SYSTEM_PERFORMANCE_INDICATOR(SYSTEM),
    SYSTEM_RESOURCE_TARGETS(SYSTEM),
    SYSTEM_RESOURCE_COMPETENCES(SYSTEM),
    SYSTEM_RESOURCE_ADVERT(SYSTEM),
    SYSTEM_RESOURCE_FINANCIAL_DETAILS(SYSTEM),
    INSTITUTION_COMMENT(SYSTEM),
    INSTITUTION_FORM(SYSTEM),
    DEPARTMENT_COMMENT(SYSTEM),
    PROGRAM_COMMENT(SYSTEM),
    PROJECT_COMMENT(SYSTEM),
    APPLICATION_GLOBAL(SYSTEM),
    APPLICATION_PROGRAM_DETAIL(SYSTEM),
    APPLICATION_PERSONAL_DETAIL(SYSTEM),
    APPLICATION_ADDRESS(SYSTEM),
    APPLICATION_QUALIFICATION(SYSTEM),
    APPLICATION_EMPLOYMENT_POSITION(SYSTEM),
    APPLICATION_REFEREE(SYSTEM),
    APPLICATION_DOCUMENT(SYSTEM),
    APPLICATION_ADDITIONAL_INFORMATION(SYSTEM),
    APPLICATION_FORM(SYSTEM),
    APPLICATION_ACTION(SYSTEM),
    APPLICATION_COMMENT(SYSTEM),
    APPLICATION_REPORT(SYSTEM);

    private PrismScope scope;

    PrismDisplayPropertyCategory(PrismScope scope) {
        this.scope = scope;
    }

    public PrismScope getScope() {
        return scope;
    }
}
