<@compress single_line = true>
SELECT USER.id AS userId, 
	NOTIFICATION_TEMPLATE.id AS notificationTemplateId
FROM APPLICATION INNER JOIN USER_NOTIFICATION
	ON APPLICATION.system_id = USER_NOTIFICATION.system_id
INNER JOIN NOTIFICATION_TEMPLATE
	ON USER_NOTIFICATION.notification_template_id = NOTIFICATION_TEMPLATE.id
INNER JOIN USER_ROLE
	ON USER_NOTIFICATION.user_role_id = USER_ROLE.id
INNER JOIN USER
	ON USER_ROLE.user_id = USER.id
LEFT JOIN USER_ACCOUNT
	ON USER.user_account_id = USER_ACCOUNT.id
INNER JOIN STATE_ACTION_ASSIGNMENT
	ON USER_ROLE.role_id = STATE_ACTION_ASSIGNMENT.role_id
	AND (USER_ROLE.application_id = APPLICATION.id
		OR USER_ROLE.project_id = APPLICATION.project_id
		OR USER_ROLE.program_id = APPLICATION.program_id
		OR USER_ROLE.institution_id = APPLICATION.institution_id
		OR USER_ROLE.system_id = APPLICATION.system_id)
INNER JOIN STATE_ACTION
	ON STATE_ACTION_ASSIGNMENT.state_action_id = STATE_ACTION.id
INNER JOIN NOTIFICATION_CONFIGURATION
	ON NOTIFICATION_CONFIGURATION.notification_template_id = NOTIFICATION_TEMPLATE.id
	AND (APPLICATION.system_id = NOTIFICATION_CONFIGURATION.system_id
			AND NOTIFICATION_CONFIGURATION.institution_id IS NULL
			AND NOTIFICATION_CONFIGURATION.program_id IS NULL
		OR (APPLICATION.institution_id = NOTIFICATION_CONFIGURATION.institution_id
			AND NOTIFICATION_CONFIGURATION.program_id IS NULL)
		OR APPLICATION.program_id = NOTIFICATION_CONFIGURATION.program_id)
INNER JOIN CONFIGURATION
	ON (APPLICATION.system_id = CONFIGURATION.system_id
		AND CONFIGURATION.institution_id IS NULL
		AND CONFIGURATION.program_id IS NULL
	OR (APPLICATION.institution_id = CONFIGURATION.institution_id
		AND CONFIGURATION.program_id IS NULL)
	OR APPLICATION.program_id = CONFIGURATION.program_id)
	AND CONFIGURATION.configuration_parameter = "DAY_ACTION_EXPIRY_DURATION"
WHERE (NOTIFICATION_TEMPLATE.notification_purpose = "UPDATE"
		AND APPLICATION.updated_timestamp BETWEEN "2014-06-29 00:00:00" AND "2014-06-29 23:59:59")
	OR (NOTIFICATION_TEMPLATE.notification_purpose = "REQUEST"
		AND STATE_ACTION.raises_urgent_flag = 1)
	AND NOTIFICATION_TEMPLATE.scope_id = "APPLICATION"
	AND (USER.user_account_id IS NULL
		OR USER_ACCOUNT.enabled = 1)
	AND (USER_NOTIFICATION.created_date IS NULL
		OR DATEDIFF(CURRENT_DATE(), USER_NOTIFICATION.created_date) = NOTIFICATION_CONFIGURATION.day_reminder_interval)
	AND DATEDIFF(CURRENT_DATE(), APPLICATION.updated_timestamp) < CONFIGURATION.parameter_value
GROUP BY USER.id, NOTIFICATION_TEMPLATE.id
ORDER BY NOTIFICATION_TEMPLATE.notification_purpose,
	USER_NOTIFICATION.system_id DESC,
	USER_NOTIFICATION.institution_id DESC,
	USER_NOTIFICATION.program_id DESC,
	USER_NOTIFICATION.project_id DESC,
	USER_NOTIFICATION.application_id DESC;
</@compress>