SELECT APPLICATION_FORM_USER_ROLE.registered_user_id AS registered_user_id,
	REGISTERED_USER.lastName AS registered_user_last_name,
	REGISTERED_USER.email AS registered_user_email,
	MAX(APPLICATION_FORM_ACTION_REQUIRED.raises_urgent_flag) AS has_urgent_flag
FROM APPLICATION_FORM_USER_ROLE INNER JOIN REGISTERED_USER
	ON APPLICATION_FORM_USER_ROLE.registered_user_id = REGISTERED_USER.id
LEFT JOIN APPLICATION_FORM_ACTION_REQUIRED
	ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
LEFT JOIN ACTION
	ON APPLICATION_FORM_ACTION_REQUIRED.action_id = ACTION.id
WHERE ACTION.notification = "SYNDICATED"
  AND APPLICATION_FORM_ACTION_REQUIRED.raises_urgent_flag = 1
	AND DATE(REGISTERED_USER.latest_task_notification_date) = CURRENT_DATE() - INTERVAL :interval ${TIME_UNIT}
	AND CURRENT_DATE() < APPLICATION_FORM_ACTION_REQUIRED.deadline_timestamp + INTERVAL :notificationsDuration DAY
GROUP BY APPLICATION_FORM_USER_ROLE.registered_user_id
   HAVING MAX(APPLICATION_FORM_ACTION_REQUIRED.raises_urgent_flag) > 0;
