SELECT REGISTERED_USER.id
FROM APPLICATION_FORM INNER JOIN REGISTERED_USER
ON APPLICATION_FORM.applicant_id = REGISTERED_USER.id
INNER JOIN APPLICATION_FORM_UPDATE
ON APPLICATION_FORM.id = APPLICATION_FORM_UPDATE.application_form_id
INNER JOIN APPLICATION_FORM_LAST_ACCESS
ON APPLICATION_FORM.id = APPLICATION_FORM_LAST_ACCESS.application_form_id
WHERE APPLICATION_FORM.status IN ("VALIDATION", "REVIEW", "INTERVIEW", "APPROVAL")
AND DATE(APPLICATION_FORM_UPDATE.update_timestamp) = CURRENT_DATE() - INTERVAL 1 DAY
AND APPLICATION_FORM_UPDATE.update_timestamp > APPLICATION_FORM_LAST_ACCESS.last_access_timestamp
AND APPLICATION_FORM_UPDATE.update_visibility = 1
AND REGISTERED_USER.id = APPLICATION_FORM_LAST_ACCESS.user_id
AND REGISTERED_USER.accountNonExpired = 1
AND REGISTERED_USER.accountNonLocked = 1
GROUP BY REGISTERED_USER.id;
