SELECT APPLICATION_FORM_USER_ROLE.registered_user_id AS registered_user_id
FROM APPLICATION_FORM_USER_ROLE INNER JOIN REGISTERED_USER
	ON APPLICATION_FORM_USER_ROLE.registered_user_id = REGISTERED_USER.id
INNER JOIN APPLICATION_FORM_ACTION_REQUIRED
	ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
INNER JOIN ACTION
	ON APPLICATION_FORM_ACTION_REQUIRED.action_id = ACTION.id
WHERE ACTION.notification_type = "SYNDICATED"
	AND APPLICATION_FORM_USER_ROLE.raises_urgent_flag = 1
	AND DATE(REGISTERED_USER.latest_task_notification_date) = CURRENT_DATE() - INTERVAL :interval ${TIME_UNIT}
	AND CURRENT_DATE() < APPLICATION_FORM_ACTION_REQUIRED.deadline_timestamp + INTERVAL :notificationsDuration DAY
GROUP BY APPLICATION_FORM_USER_ROLE.registered_user_id;
