package uk.co.alumeni.prism.domain.definitions;

import uk.co.alumeni.prism.domain.definitions.workflow.PrismScope;

public enum PrismDisplayPropertyCategory {

    SYSTEM_GLOBAL(PrismScope.SYSTEM),
    SYSTEM_COMMENT(PrismScope.SYSTEM),
    SYSTEM_NOTIFICATION(PrismScope.SYSTEM),
    SYSTEM_STATE_GROUP(PrismScope.SYSTEM),
    SYSTEM_STATE_TRANSITION(PrismScope.SYSTEM),
    SYSTEM_ACTION(PrismScope.SYSTEM),
    SYSTEM_ROLE(PrismScope.SYSTEM),
    SYSTEM_YES_NO_UNSURE(PrismScope.SYSTEM),
    SYSTEM_SCOPE(PrismScope.SYSTEM),
    SYSTEM_OPPORTUNITY_CATEGORY(PrismScope.SYSTEM),
    SYSTEM_OPPORTUNITY_TYPE(PrismScope.SYSTEM),
    SYSTEM_STUDY_OPTION(PrismScope.SYSTEM),
    SYSTEM_AGE_RANGE(PrismScope.SYSTEM),
    SYSTEM_ETHNICITY(PrismScope.SYSTEM),
    SYSTEM_DISABILITY(PrismScope.SYSTEM),
    SYSTEM_GENDER(PrismScope.SYSTEM),
    SYSTEM_DOMICILE(PrismScope.SYSTEM),
    SYSTEM_REJECTION_REASON(PrismScope.SYSTEM),
    SYSTEM_DURATION(PrismScope.SYSTEM),
    SYSTEM_ENTITY(PrismScope.SYSTEM),
    SYSTEM_FILTER_PROPERTY(PrismScope.SYSTEM),
    SYSTEM_FILTER_EXPRESSION(PrismScope.SYSTEM),
    SYSTEM_ADVERT_BENEFIT(PrismScope.SYSTEM),
    SYSTEM_ADVERT_INDUSTRY(PrismScope.SYSTEM),
    SYSTEM_ADVERT_FUNCTION(PrismScope.SYSTEM),
    SYSTEM_DISPLAY_CATEGORY(PrismScope.SYSTEM),
    SYSTEM_REPORT_INDICATOR_GROUP(PrismScope.SYSTEM),
    SYSTEM_VALIDATION_ERROR(PrismScope.SYSTEM),
    SYSTEM_INTEGRATION(PrismScope.SYSTEM),
    SYSTEM_STATE_DURATION(PrismScope.SYSTEM),
    SYSTEM_MONTH(PrismScope.SYSTEM),
    SYSTEM_DECLINE_ACTION(PrismScope.SYSTEM),
    SYSTEM_GENERAL(PrismScope.SYSTEM),
    SYSTEM_ACTIVITY_SECTION(PrismScope.SYSTEM),
    SYSTEM_CONNECT_SECTION(PrismScope.SYSTEM),
    SYSTEM_AUTHENTICATE(PrismScope.SYSTEM),
    SYSTEM_OPPORTUNITIES(PrismScope.SYSTEM),
    SYSTEM_OPPORTUNITIES_ENQUIRY(PrismScope.SYSTEM),
    SYSTEM_ADVERTISE(PrismScope.SYSTEM),
    SYSTEM_INVITE(PrismScope.SYSTEM),
    SYSTEM_RESOURCES(PrismScope.SYSTEM),
    SYSTEM_RESOURCE(PrismScope.SYSTEM),
    SYSTEM_ACCOUNT(PrismScope.SYSTEM),
    SYSTEM_ADDRESS(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_PARENT(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_OPPORTUNITY(PrismScope.SYSTEM),
    SYSTEM_CREATE_RESOURCE_FAMILY(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_CONFIGURATION(PrismScope.SYSTEM),
    SYSTEM_MANAGE_USERS(PrismScope.SYSTEM),
    SYSTEM_TRANSLATIONS_CONFIGURATION(PrismScope.SYSTEM),
    SYSTEM_PERFORMANCE_INDICATOR(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_TARGETS(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_COMPETENCES(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_ADVERT(PrismScope.SYSTEM),
    SYSTEM_RESOURCE_FINANCIAL_DETAILS(PrismScope.SYSTEM),
    INSTITUTION_COMMENT(PrismScope.SYSTEM),
    DEPARTMENT_COMMENT(PrismScope.SYSTEM),
    PROGRAM_COMMENT(PrismScope.SYSTEM),
    PROJECT_COMMENT(PrismScope.SYSTEM),
    APPLICATION_GLOBAL(PrismScope.SYSTEM),
    APPLICATION_PROGRAM_DETAIL(PrismScope.SYSTEM),
    PROFILE_PERSONAL_DETAIL(PrismScope.SYSTEM),
    PROFILE_ADDRESS(PrismScope.SYSTEM),
    PROFILE_QUALIFICATION(PrismScope.SYSTEM),
    PROFILE_EMPLOYMENT_POSITION(PrismScope.SYSTEM),
    PROFILE_REFEREE(PrismScope.SYSTEM),
    PROFILE_DOCUMENT(PrismScope.SYSTEM),
    PROFILE_ADDITIONAL_INFORMATION(PrismScope.SYSTEM),
    APPLICATION_FORM(PrismScope.SYSTEM),
    PROFILE_FORM(PrismScope.SYSTEM),
    PROFILE_UPDATE(PrismScope.SYSTEM),
    APPLICATION_ACTION(PrismScope.SYSTEM),
    APPLICATION_COMMENT(PrismScope.SYSTEM),
    APPLICATION_REPORT(PrismScope.SYSTEM);

    private PrismScope scope;

    PrismDisplayPropertyCategory(PrismScope scope) {
        this.scope = scope;
    }

    public PrismScope getScope() {
        return scope;
    }
}
