package uk.co.alumeni.prism.domain.definitions.workflow;

public enum PrismRoleGroup {

    APPLICATION_PARENT_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROJECT_ADMINISTRATOR), //
    APPLICATION_PARENT_APPROVER_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.DEPARTMENT_APPROVER, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROGRAM_APPROVER, //
            PrismRole.PROJECT_ADMINISTRATOR, PrismRole.PROJECT_APPROVER), //
    APPLICATION_APPROVER_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.DEPARTMENT_APPROVER, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROGRAM_APPROVER, //
            PrismRole.PROJECT_ADMINISTRATOR, PrismRole.PROJECT_APPROVER), //
    APPLICATION_PARENT_VIEWER_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.INSTITUTION_APPROVER, PrismRole.INSTITUTION_VIEWER, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.DEPARTMENT_APPROVER, //
            PrismRole.DEPARTMENT_VIEWER, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROGRAM_APPROVER, PrismRole.PROGRAM_VIEWER, PrismRole.PROJECT_ADMINISTRATOR, PrismRole.PROJECT_APPROVER, PrismRole.PROJECT_VIEWER), //
    APPLICATION_POTENTIAL_SUPERVISOR_GROUP(PrismRole.APPLICATION_HIRING_MANAGER, PrismRole.APPLICATION_REVIEWER, PrismRole.APPLICATION_INTERVIEWER, PrismRole.APPLICATION_VIEWER_RECRUITER), //
    APPLICATION_POTENTIAL_INTERVIEW_GROUP(PrismRole.APPLICATION_POTENTIAL_INTERVIEWEE, PrismRole.APPLICATION_POTENTIAL_INTERVIEWER), //
    APPLICATION_SCHEDULED_INTERVIEW_GROUP(PrismRole.APPLICATION_SCHEDULED_INTERVIEWEE, PrismRole.APPLICATION_SCHEDULED_INTERVIEWER), //
    APPLICATION_CONFIRMED_INTERVIEW_GROUP(PrismRole.APPLICATION_INTERVIEWEE, PrismRole.APPLICATION_INTERVIEWER), //

    PROJECT_PARENT_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR), //
    PROJECT_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROJECT_ADMINISTRATOR), //
    PROJECT_STAFF_GROUP(PrismRole.PROJECT_ADMINISTRATOR, PrismRole.PROJECT_APPROVER, PrismRole.PROJECT_VIEWER), //
    PROJECT_VIEWER_GROUP(PrismRole.PROJECT_APPROVER, PrismRole.PROJECT_VIEWER), //

    PROGRAM_PARENT_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR), //
    PROGRAM_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR), //
    PROGRAM_STAFF_GROUP(PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROGRAM_APPROVER, PrismRole.PROGRAM_VIEWER), //
    PROGRAM_VIEWER_GROUP(PrismRole.PROGRAM_APPROVER, PrismRole.PROGRAM_VIEWER), //

    DEPARTMENT_PARENT_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR), //
    DEPARTMENT_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.DEPARTMENT_ADMINISTRATOR), //
    DEPARTMENT_STAFF_GROUP(PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.DEPARTMENT_APPROVER, PrismRole.DEPARTMENT_VIEWER), //
    DEPARTMENT_VIEWER_GROUP(PrismRole.DEPARTMENT_APPROVER, PrismRole.DEPARTMENT_STUDENT, PrismRole.DEPARTMENT_VIEWER), //

    INSTITUTION_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR), //
    INSTITUTION_STAFF_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.INSTITUTION_APPROVER, PrismRole.INSTITUTION_VIEWER), //
    INSTITUTION_VIEWER_GROUP(PrismRole.INSTITUTION_APPROVER, PrismRole.INSTITUTION_STUDENT, PrismRole.INSTITUTION_VIEWER), //

    PARTNERSHIP_MANAGER_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.INSTITUTION_APPROVER, PrismRole.DEPARTMENT_ADMINISTRATOR, PrismRole.DEPARTMENT_APPROVER);

    private PrismRole[] roles;

    private PrismRoleGroup(PrismRole... roles) {
        this.roles = roles;
    }

    public PrismRole[] getRoles() {
        return roles;
    }

}
