#!/bin/sh
### BEGIN INIT INFO
# Provides:          jboss
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop/Restart JBoss AS v7.1.1
### END INIT INFO
 
set -e
 
### declare the directory where is jboss/java installed
JAVA_HOME=/usr/lib/jvm/java-1.6.0
JBOSS_HOME=/usr/local/jboss/current
export PATH=${JAVA_HOME}/bin:${JBOSS_HOME}/bin:${PATH}
 
case $1 in
        start )
                echo -e "\aStarting JBoss ..."
                su -l jboss -c "${JBOSS_HOME}/bin/standalone.sh > /dev/null 2> /dev/null &"
        ;;
        stop )
                echo -e "\aStopping JBoss ..."
                su -l jboss -c "${JBOSS_HOME}/bin/jboss-cli.sh --connect command=:shutdown > /dev/null 2> /dev/null &"
        ;;
        restart )
                echo -e "\aRestarting the JBoss server ..."
                su -l jboss -c "${JBOSS_HOME}/bin/jboss-cli.sh --connect command=:shutdown > /dev/null 2> /dev/null"
                su -l jboss -c "${JBOSS_HOME}/bin/standalone.sh > /dev/null 2> /dev/null &"
        ;;
        * )
                echo -e "\aUsage: /etc/init.d/jboss {start|stop|restart}"
                exit 1
        ;;
esac
exit 0