SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM ADDRESS;

DELETE FROM APPLICATION_FORM;

DELETE FROM APPLICATION_FORM_ADDITIONAL_INFO;

DELETE FROM APPLICATION_FORM_EMPLOYMENT_POSITION;

DELETE FROM APPLICATION_FORM_FUNDING;

DELETE FROM APPLICATION_FORM_PERSONAL_DETAIL;

DELETE FROM APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS;

DELETE FROM APPLICATION_FORM_PERSONAL_DETAIL_PASSPORT;

DELETE FROM APPLICATION_FORM_PROGRAMME_DETAIL;

DELETE FROM APPLICATION_FORM_QUALIFICATION;

DELETE FROM APPLICATION_FORM_REFEREE;

DELETE FROM APPLICATION_FORM_TRANSFER;

DELETE FROM APPLICATION_FORM_TRANSFER_ERROR;

DELETE FROM APPROVAL_COMMENT;

DELETE FROM APPROVAL_EVALUATION_COMMENT;

DELETE FROM APPROVAL_ROUND;

DELETE FROM APPROVAL_STATE_CHANGE_EVENT;

DELETE FROM CANDIDATE_NATIONALITY_LINK;

DELETE FROM COMMENT;

DELETE FROM DOCUMENT;

DELETE FROM EVENT;

DELETE FROM INTERVIEW;

DELETE FROM INTERVIEW_COMMENT;

DELETE FROM INTERVIEW_EVALUATION_COMMENT;

DELETE FROM INTERVIEW_STATE_CHANGE_EVENT;

DELETE FROM INTERVIEWER;

DELETE FROM NOTIFICATION_RECORD;

DELETE FROM PENDING_ROLE_NOTIFICATION;

DELETE FROM PERSON;

DELETE FROM PROGRAM_ADMINISTRATOR_LINK;

DELETE FROM PROGRAM_APPROVER_LINK;

DELETE FROM PROGRAM_INTERVIEWER_LINK;

DELETE FROM PROGRAM_REVIEWER_LINK;

DELETE FROM PROGRAM_SUPERVISOR_LINK;

DELETE FROM PROGRAM_VIEWER_LINK;

DELETE FROM REFERENCE_COMMENT;

DELETE FROM REFERENCE_EVENT;

DELETE FROM REJECTION;

DELETE FROM REQUEST_RESTART_COMMENT;

DELETE FROM REVIEW_COMMENT;

DELETE FROM REVIEW_EVALUATION_COMMENT;

DELETE FROM REVIEW_ROUND;

DELETE FROM REVIEW_STATE_CHANGE_EVENT;

DELETE FROM REVIEWER;

DELETE FROM STATE_CHANGE_EVENT;

DELETE FROM STATECHANGE_COMMENT;

DELETE FROM SUGGESTED_SUPERVISOR;

DELETE FROM SUPERVISION_CONFIRMATION_COMMENT;

DELETE FROM VALIDATION_COMMENT;

SET FOREIGN_KEY_CHECKS = 1;