INSERT INTO STAGE_DURATION(stage, duration, unit) VALUES ('VALIDATION', 1, 'DAYS');
INSERT INTO STAGE_DURATION(stage, duration, unit) VALUES ('REVIEW', 1, 'WEEKS');
INSERT INTO STAGE_DURATION(stage, duration, unit) VALUES ('INTERVIEW', 2, 'DAYS');
INSERT INTO STAGE_DURATION(stage, duration, unit) VALUES ('APPROVAL', 3, 'DAYS');