CREATE TABLE REGISTERED_USER (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,  
  username VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,  
  accountNonExpired TINYINT(1) NOT NULL,
  accountNonLocked TINYINT(1) NOT NULL,
  credentialsNonExpired TINYINT(1) NOT NULL,
  enabled TINYINT(1) NOT NULL,
  UNIQUE (username),
  PRIMARY KEY (id)
)
ENGINE = InnoDB;

--//@UNDO

DROP TABLE IF EXISTS REGISTERED_USER;