CREATE TABLE APPLICATION_ROLE (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,   
  authority VARCHAR(200) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (authority)
)

ENGINE = InnoDB;

--//@UNDO

DROP TABLE IF EXISTS APPLICATION_ROLE;