DELETE IMPORTED_INSTITUTION.*
FROM IMPORTED_INSTITUTION INNER JOIN (
	SELECT min(id) AS id
	FROM IMPORTED_INSTITUTION
	GROUP BY institution_id, code
	HAVING COUNT(id) > 1) AS DUPLICATE_INSTITUTION
	ON IMPORTED_INSTITUTION.id = DUPLICATE_INSTITUTION.id
;
