DELETE IMPORTED_INSTITUTION.*
FROM IMPORTED_INSTITUTION INNER JOIN (
	SELECT code
	FROM IMPORTED_INSTITUTION
	GROUP BY institution_id, code
	HAVING COUNT(id) > 1) AS DUPLICATE_INSTITUTION
	ON IMPORTED_INSTITUTION.code = DUPLICATE_INSTITUTION.code
LEFT JOIN APPLICATION_QUALIFICATION
	ON IMPORTED_INSTITUTION.id = APPLICATION_QUALIFICATION.institution_id
WHERE APPLICATION_QUALIFICATION.id IS NULL
;
