CREATE TABLE APPLICATION_REVIEW (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	reviewer_user_id INTEGER UNSIGNED NOT NULL,
	application_form_id INTEGER UNSIGNED NOT NULL, 
	comment VARCHAR(500) NOT NULL,
	CONSTRAINT reviewer_user_fk1 FOREIGN KEY (reviewer_user_id) REFERENCES REGISTERED_USER(id),
	CONSTRAINT application_id_fk FOREIGN KEY (application_form_id) REFERENCES APPLICATION_FORM(id),
	PRIMARY KEY (id)
)

ENGINE = InnoDB;

--//@UNDO

DROP TABLE IF EXISTS APPLICATION_REVIEW;