ALTER TABLE APPLICATION_REVIEW DROP FOREIGN KEY reviewer_user_fk1, DROP COLUMN reviewer_user_id, 
ADD COLUMN user_id INTEGER UNSIGNED NOT NULL,
ADD CONSTRAINT review_user_fk FOREIGN KEY (user_id) REFERENCES REGISTERED_USER(id);