CREATE TABLE PROGRAM_APPROVER_LINK (
  registered_user_id INTEGER UNSIGNED NOT NULL,
  program_id INTEGER UNSIGNED NOT NULL,
  CONSTRAINT user_program_user_fk FOREIGN KEY (registered_user_id) REFERENCES REGISTERED_USER(id),
  CONSTRAINT user_program_program_fk FOREIGN KEY (program_id) REFERENCES PROGRAM(id)
)
ENGINE = InnoDB;

--//@UNDO

DROP CONSTRAINT IF EXISTS user_program_program_fk;
DROP CONSTRAINT IF EXISTS user_program_user_fk;
DROP TABLE IF EXISTS PROGRAM_APPROVER_LINK;