CREATE TABLE IF NOT EXISTS COUNTRIES(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  code char(2) NOT NULL DEFAULT '',
  name varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY(id)
)
ENGINE = InnoDB;

--//@UNDO

