INSERT INTO COUNTRIES (id, code, name)
VALUES
    (1,'AD',' Andorra'),
    (2,'AE',' United Arab Emirates'),
    (3,'AF',' Afghanistan'),
    (4,'AG',' Antigua and Barbuda'),
    (5,'AI',' Anguilla'),
    (6,'AL',' Albania'),
    (7,'AM',' Armenia'),
    (8,'AN',' Netherlands Antilles'),
    (9,'AO',' Angola'),
    (10,'AQ',' Antarctica'),
    (11,'AR',' Argentina'),
    (12,'AS',' American Samoa'),
    (13,'AT',' Austria'),
    (14,'AU',' Australia'),
    (15,'AW',' Aruba'),
    (16,'AZ',' Azerbaijan'),
    (17,'BA',' Bosnia and Herzegovina'),
    (18,'BB',' Barbados'),
    (19,'BD',' Bangladesh'),
    (20,'BE',' Belgium'),
    (21,'BF',' Burkina Faso'),
    (22,'BG',' Bulgaria'),
    (23,'BH',' Bahrain'),
    (24,'BI',' Burundi'),
    (25,'BJ',' Benin'),
    (26,'BM',' Bermuda'),
    (27,'BN',' Brunei Darrussalam'),
    (28,'BO',' Bolivia'),
    (29,'BR',' Brazil'),
    (30,'BS',' Bahamas'),
    (31,'BT',' Bhutan'),
    (32,'BV',' Bouvet Island'),
    (33,'BW',' Botswana'),
    (34,'BY',' Belarus'),
    (35,'BZ',' Belize'),
    (36,'CA',' Canada'),
    (37,'CC',' Cocos (keeling) Islands'),
    (38,'CD',' Congo (Democratic People’s Republic)'),
    (39,'CF',' Central African Republic'),
    (40,'CG',' Congo (Republic of)'),
    (41,'CH',' Switzerland'),
    (42,'CI',' Cote d’Ivoire'),
    (43,'CK',' Cook Islands'),
    (44,'CL',' Chile'),
    (45,'CM',' Cameroon'),
    (46,'CN',' China'),
    (47,'CO',' Colombia'),
    (48,'CR',' Costa Rica'),
    (49,'CS',' Serbia and Montenegro'),
    (50,'CU',' Cuba'),
    (51,'CV',' Cap Verde'),
    (52,'CS',' Christmas Island'),
    (53,'CY',' Cyprus Island'),
    (54,'CZ',' Czech Republic'),
    (55,'DE',' Germany'),
    (56,'DJ',' Djibouti'),
    (57,'DK',' Denmark'),
    (58,'DM',' Dominica'),
    (59,'DO',' Dominican Republic'),
    (60,'DZ',' Algeria'),
    (61,'EC',' Ecuador'),
    (62,'EE',' Estonia'),
    (63,'EG',' Egypt'),
    (64,'EH',' Western Sahara'),
    (65,'ER',' Eritrea'),
    (66,'ES',' Spain'),
    (67,'ET',' Ethiopia'),
    (68,'FI',' Finland'),
    (69,'FJ',' Fiji'),
    (70,'FK',' Falkland Islands (Malvina)'),
    (71,'FM',' Micronesia (Federal State of)'),
    (72,'FO',' Faroe Islands'),
    (73,'FR',' France'),
    (74,'GA',' Gabon'),
    (75,'GB',' United Kingdom (GB)'),
    (76,'GD',' Grenada'),
    (77,'GE',' Georgia'),
    (78,'GF',' French Guiana'),
    (79,'GG',' Guernsey'),
    (80,'GH',' Ghana'),
    (81,'GI',' Gibraltar'),
    (82,'GL',' Greenland'),
    (83,'GM',' Gambia'),
    (84,'GN',' Guinea'),
    (85,'GP',' Guadeloupe'),
    (86,'GQ',' Equatorial Guinea'),
    (87,'GR',' Greece'),
    (88,'GS',' South Georgia'),
    (89,'GT',' Guatemala'),
    (90,'GU',' Guam'),
    (91,'GW',' Guinea-Bissau'),
    (92,'GY',' Guyana'),
    (93,'HK',' Hong Kong'),
    (94,'HM',' Heard and McDonald Islands'),
    (95,'HN',' Honduras'),
    (96,'HR',' Croatia (Hrvatska)'),
    (97,'HT',' Haiti'),
    (98,'HU',' Hungary'),
    (99,'ID',' Indonesia'),
    (100,'IE',' Ireland'),
    (101,'IL',' Israel'),
    (102,'IM',' Isle of Man'),
    (103,'IN',' India'),
    (104,'IO',' British Indian Ocean Territory'),
    (105,'IQ',' Iraq'),
    (106,'IR',' Iran (Islamic Republic of)'),
    (107,'IS',' Iceland'),
    (108,'IT',' Italy'),
    (109,'JE',' Jersey'),
    (110,'JM',' Jamaica'),
    (111,'JO',' Jordan'),
    (112,'JP',' Japan'),
    (113,'KE',' Kenya'),
    (114,'KG',' Kyrgyzstan'),
    (115,'KH',' Cambodia'),
    (116,'KI',' Kiribati'),
    (117,'KM',' Comoros'),
    (118,'KN',' Saint Kitts and Nevis'),
    (119,'KP',' Korea (Democratic People’s Republic)'),
    (120,'KR',' Korea (Republic of)'),
    (121,'KW',' Kuwait'),
    (122,'KY',' Cayman Islands'),
    (123,'KZ',' Kazakhstan'),
    (124,'LA',' Lao People’s Democratic Republic'),
    (125,'LB',' Lebanon'),
    (126,'LC',' Saint Lucia'),
    (127,'LI',' Liechtenstein'),
    (128,'LK',' Sri Lanka'),
    (129,'LR',' Liberia'),
    (130,'LS',' Lesotho'),
    (131,'LT',' Lithuania'),
    (132,'LU',' Luxembourgh'),
    (133,'LV',' Latvia'),
    (134,'LY',' Libyan Arab Jamahiriya'),
    (135,'MA',' Morocco'),
    (136,'MC',' Monaco'),
    (137,'MD',' Moldova (Republic of)'),
    (138,'MG',' Madagascar'),
    (139,'MH',' Marshall Islands'),
    (140,'MK',' Macedonia'),
    (141,'ML',' Mali'),
    (142,'MM',' Myanmar'),
    (143,'MN',' Mongolia'),
    (144,'MO',' Macau'),
    (145,'MP',' Northern Mariana Islands'),
    (146,'MQ',' Martinique'),
    (147,'MR',' Mauritania'),
    (148,'MS',' Montserrat'),
    (149,'MT',' Malta'),
    (150,'MU',' Mauritius'),
    (151,'Mv',' Maldives'),
    (152,'MW','Malawi'),
    (153,'MX',' Mexico'),
    (154,'MY',' Malaysia'),
    (155,'MZ',' Mozambique'),
    (156,'NA',' Namibia'),
    (157,'NC',' New Caledonia'),
    (158,'NE',' Niger'),
    (159,'NF',' Norfolk Island'),
    (160,'NG',' Nigeria'),
    (161,'NI',' Nicaragua'),
    (162,'NL',' Netherlands'),
    (163,'NO',' Norway'),
    (164,'NP',' Nepal'),
    (165,'NR',' Nauru'),
    (166,'NU',' Niue'),
    (167,'NZ',' New Zealand'),
    (168,'OM',' Oman'),
    (169,'PA',' Panama'),
    (170,'PE',' Peru'),
    (171,'PF',' French Polynesia'),
    (172,'PG','Papua New Guinea'),
    (173,'PH',' Phillipines'),
    (174,'PK',' Pakistan'),
    (175,'PL',' Poland'),
    (176,'PM',' St. Pierre and Miquelon'),
    (177,'PN',' Pitcairn Island'),
    (178,'PR',' Puerto Rico'),
    (179,'PS',' Palestinian Territories'),
    (180,'PT',' Portugal'),
    (181,'PW',' Palau'),
    (182,'PY',' Paraguay'),
    (183,'QA',' Qatar'),
    (184,'RE',' Reunion Island'),
    (185,'RO',' Romania'),
    (186,'RU',' Russian Federation'),
    (187,'RW',' Rwanda'),
    (188,'SA',' Saudi Arabia'),
    (189,'SB',' Solomon Islands'),
    (190,'SC',' Seychelles'),
    (191,'SD',' Sudan'),
    (192,'SE',' Sweden'),
    (193,'SG',' Singapore'),
    (194,'SH',' St. Helena'),
    (195,'SI',' Slovenia'),
    (196,'SJ',' Svalbard and Jan Mayen Islands'),
    (197,'SK',' Slovak Republic'),
    (198,'SL',' Sierra Leone'),
    (199,'SM',' San Marino'),
    (200,'SN',' Senegal'),
    (201,'SO',' Somalia'),
    (202,'SR',' Suriname'),
    (203,'ST',' Sao Tome and Principe'),
    (204,'SV',' El Salvador'),
    (205,'SY',' Syrian Arab Republic'),
    (206,'SZ',' Swaziland'),
    (207,'TC',' Turks and Caicos Islands'),
    (208,'TD',' Chad'),
    (209,'TF',' French Southern Territories'),
    (210,'TG',' Togo'),
    (211,'TH',' Thailand'),
    (212,'TJ',' Tajikistan'),
    (213,'TK',' Tokelau'),
    (214,'TM',' Turkmenistan'),
    (215,'TN',' Tunisia'),
    (216,'TO',' Tonga'),
    (217,'TP',' East Timor'),
    (218,'TR',' Turkey'),
    (219,'TT',' Trinidad and Tobago'),
    (220,'TV',' Tuvalu'),
    (221,'TW',' Taiwan'),
    (222,'TZ',' Tanzania'),
    (223,'UA',' Ukraine'),
    (224,'UG',' Uganda'),
    (225,'UM',' US Minor Outlying Islands'),
    (226,'US',' United States'),
    (227,'UY',' Uruguay'),
    (228,'UZ',' Uzbekistan'),
    (229,'VA',' Holy See (City Vatican State)'),
    (230,'VC',' Saint Vincent and the Grenadines'),
    (231,'VE',' Venezuela'),
    (232,'VG',' Virgin Islands (British)'),
    (233,'VI',' Virgin Islands (USA)'),
    (234,'VN',' Vietnam'),
    (235,'VU',' Vanuatu'),
    (236,'WF',' Wallis and Futuna Islands'),
    (237,'WS',' Western Samoa'),
    (238,'YE',' Yemen'),
    (239,'YT',' Mayotte'),
    (240,'YU',' Yugoslavia'),
    (241,'ZA',' South Africa'),
    (242,'ZM',' Zambia'),
    (243,'ZW',' Zimbabwe');