CREATE TABLE MESSENGER(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  messenger_type VARCHAR(200) NOT NULL,
  address VARCHAR(2000) NOT NULL,
  referee_id INTEGER UNSIGNED,
  PRIMARY KEY(id)
)
ENGINE = InnoDB;

--//@UNDO

