CREATE TABLE TELEPHONE(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  telephone_type VARCHAR(200) NOT NULL,
  referee_id INTEGER UNSIGNED,
  number VARCHAR(2000) NOT NULL,
  PRIMARY KEY(id)
)
ENGINE = InnoDB;

--//@UNDO

