CREATE TABLE MESSENGER(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  messenger_type VARCHAR(200) NOT NULL,
  address VARCHAR(2000) NOT NULL,
  referee_id INTEGER UNSIGNED,
  CONSTRAINT referee_id_messenger_fk FOREIGN KEY (referee_id) REFERENCES APPLICATION_FORM_REFEREE(id),
  PRIMARY KEY(id)
)
ENGINE = InnoDB;

--//@UNDO

DROP CONSTRAINT IF EXISTS referee_id_telephone_fk;
