update comment
set application_export_exception = "This study will investigate the benefits of having a morphological system located at the forward end of the vessel to alter the hydrodynamic flow round the hull, to better suit the particular environment it is encountering.  This environment consists of the inherent status of the vessel (trim, draught, speed, etc.) and the weather system around it (wave system, currents, wind, etc.). The latest trend in vessels reducing their operating speeds to remain commercially competitive and within the emission regulation boundaries has resulted in a large portion of the active fleet operating at conditions that they were not designed to operate at.  The concept of improving flexibility has already been applied in technologies such as the controllable pitch propeller however in a different industry altogether, BMW developed the concept car GINA (Geometry and functions in N Adaptations) which by means of its flexible canvas and light structure beneath, it is able to alter its shape and aerodynamic profile according to the needs of the user. Presently, bulbous bows are used to change a vessels wave profile however, they are optimised for a very narrow band of environmental conditions which may result in the vessel operating inefficiently over a large portion of its course.  If the same concept of the BMW GINA had to be applied to the bulb, its shape may change in real time resulting in a flexible means of optimising a vessels performance. Such potential benefits may be investigated by means of traditional techniques such as initial hand calculations and systematic tow tank tests however by also making use of Computational Fluid Dynamic (CFD) software, simulations can be set up to explore the design space more efficiently. A combination of these approaches will yield a suitable methodology to design optimised bulbous bows based on a set of input parameters and will therefore determine how viable the proposed concept is."
where id in (135125, 135143)
;

update comment
set application_position_description = "The candidate will conduct research on Fundamental Studies towards Hydrogen-Rich-Fuel Gas Turbines. Gas turbines are used increasingly for power generation and marine/aviation propulsion. These sectors are of crucial importance to the UK economy but are subjected to increasingly stringent emission standards. To improve upon the already impressive fuel efficiency and emission level, cleaner fuels such as hydrogen-rich fuels should be considered for gas turbines. Fundamental studies on hydrogen-rich fuels will be conducted by the candidate to determine their combustion characteristics over a wide range of conditions. To facilitate the investigation, advanced numerical simulation techniques will be developed for prediction and diagnosis purposes. It is expected that physical sub-models for flow, mixing and chemical reactions require further development to be reliable for the new fuels proposed. The numerical predictions will be compared with experimental data collected at UCL, Imperial and Siemens. The validated numerical techniques will be employed for parametric studies to predict the performance, versatility and robustness of hydrogen-rich fuel gas turbines. Cutting-edge simulations will be conducted on the world-class national supercomputer ARCHER, leading to valuable databases that may facilitate fundamental exploration and R & D within the department and by industry."
where id in (135136, 135138)
;

update comment
set application_position_description = "In the quest for making city life more sustainable, research, mainly from the health sector, has linked urban form with health conditions, including social health. However, in order to deliver truly sustainable cities, deeper understanding on the impact of urban form on social dimensions is required. This research will analyse both conceptual and quantitative evidence to understand how is the quality of life or happiness affected by the rules for living imposed by urban form. Based on the review of relevant literature and the results of visioning workshops developed for the EPSRC programme grant, Transforming the Engineering of Cities, the research will have a conceptual phase to identify specific city archetypes based on the types of relationships and effects of urban environments in life styles and, consequently, on happiness and liveability. The second phase will comprise the quantitative analysis of case studies to understand the link between travel patterns, land-use patterns and quality of life indicators. The objective of this research is to gather substantive evidence to support better decision and policy making for future urban sustainability."
where id = 144168
;

update comment
set application_position_description = "Methane is the major component (70–90%) of natural gas and shale gas and also substantially exists in ocean as methane hydrate. Methane is also naturally generated from biosystems. Thus methane is quite cheap and can ideally be used as not only a fuel but also as a chemical carbon source. Unfortunately methane is the most stable hydrocarbon and the energy to break the C–H bond is 434 kJ mol-1, thus a huge energy input is required for methane conversion to high value product processes. For example, direct pyrolysis of CH4 requires temperature of nearly 1000C. In solar spectrum, photon in both UV and Visible region can provide energy larger than 1000C, enough to driven CH4 conversion. Furthermore the side reactions such as the formation of carbon dioxide in CH4 conventional conversion processes can be dramatically reduced due to the photocatalytic reaction taken place at room temperature. This would also bring out other advantages, such as high stability of catalyst, better safety and low cost for reactor and maintenance. Therefore the new project will target efficient CH4 conversion by photocatalysis at room temperature which has been less reported. The preferred products are long chain hydrocarbons which can be used a transportable fuel or high value chemicals."
where id = 144663
;
