CREATE TABLE PERSONAL_DETAIL_LANGUAGE_LINK (
  personal_detail_id INTEGER UNSIGNED NOT NULL,
  language_id INTEGER UNSIGNED NOT NULL,
  CONSTRAINT personal_fk FOREIGN KEY (personal_detail_id) REFERENCES APPLICATION_FORM_PERSONAL_DETAIL(id),
  CONSTRAINT personal_language_fk FOREIGN KEY (language_id) REFERENCES LANGUAGE(id)
)
ENGINE = InnoDB;

--//@UNDO

DROP CONSTRAINT IF EXISTS personal_fk;
DROP CONSTRAINT IF EXISTS personal_language_fk;
DROP TABLE IF EXISTS PERSONAL_DETAIL_LANGUAGE_LINK;