CREATE TABLE IF NOT EXISTS LANGUAGE_PROFICIENCY(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, 
  language_id INTEGER UNSIGNED,
  aptitude varchar(50),
  PRIMARY KEY(id),
  CONSTRAINT prof_lan_fk FOREIGN KEY (language_id) REFERENCES LANGUAGE(id)
)
ENGINE = InnoDB;

--//@UNDO

