CREATE TABLE APPLICANT_RECORD (
	 id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	 first_name VARCHAR(2000) NOT NULL,
  	 last_name VARCHAR(2000) NOT NULL,
  	 email VARCHAR(2000) NOT NULL,
  	 password VARCHAR(50) NOT NULL,
  	 PRIMARY KEY(id)
)

--//@UNDO

