CREATE TABLE REFERENCE (
  	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, 
  	comment VARCHAR(2000),
  	document_id INTEGER UNSIGNED,	
	updated_time_stamp TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	CONSTRAINT ref_doc_fk FOREIGN KEY (document_id) REFERENCES DOCUMENT(id),
  	PRIMARY KEY (id)
)
ENGINE = InnoDB;