CREATE TABLE PROGRAM_INSTANCE (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  sequence INTEGER UNSIGNED NOT NULL,
 deadline DATE NOT NULL,
 study_option varchar(50),
  PRIMARY KEY (id)
)
ENGINE = InnoDB;