alter table notification_definition
	drop foreign key notification_definition_ibfk_2,
	drop index reminder_notification_template_id,
	drop column reminder_definition_id
;

alter table notification_configuration
	drop column reminder_interval
;

delete 
from user_notification
where notification_definition_id not in (
	"APPLICATION_COMPLETE_NOTIFICATION",
	"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION",
	"APPLICATION_CONFIRM_OFFER_RECOMMENDATION_NOTIFICATION",
	"APPLICATION_CONFIRM_REJECTION_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST",
	"APPLICATION_PROVIDE_REFERENCE_REQUEST",
	"APPLICATION_RESERVE_NOTIFICATION",
	"APPLICATION_REVERSE_REJECTION_NOTIFICATION",
	"APPLICATION_TERMINATE_NOTIFICATION",
	"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"PROJECT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROJECT_CORRECT_REQUEST",
	"PROGRAM_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROGRAM_CORRECT_REQUEST",
	"DEPARTMENT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"DEPARTMENT_CORRECT_REQUEST",
	"INSTITUTION_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"INSTITUTION_CORRECT_REQUEST",
	"SYSTEM_INVITATION_NOTIFICATION",
	"SYSTEM_COMPLETE_REGISTRATION_REQUEST",
	"SYSTEM_PASSWORD_NOTIFICATION",
	"SYSTEM_ACTIVITY_NOTIFICATION")
;

delete 
from notification_configuration
where notification_definition_id not in (
	"APPLICATION_COMPLETE_NOTIFICATION",
	"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION",
	"APPLICATION_CONFIRM_OFFER_RECOMMENDATION_NOTIFICATION",
	"APPLICATION_CONFIRM_REJECTION_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST",
	"APPLICATION_PROVIDE_REFERENCE_REQUEST",
	"APPLICATION_RESERVE_NOTIFICATION",
	"APPLICATION_REVERSE_REJECTION_NOTIFICATION",
	"APPLICATION_TERMINATE_NOTIFICATION",
	"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"PROJECT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROJECT_CORRECT_REQUEST",
	"PROGRAM_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROGRAM_CORRECT_REQUEST",
	"DEPARTMENT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"DEPARTMENT_CORRECT_REQUEST",
	"INSTITUTION_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"INSTITUTION_CORRECT_REQUEST",
	"SYSTEM_INVITATION_NOTIFICATION",
	"SYSTEM_COMPLETE_REGISTRATION_REQUEST",
	"SYSTEM_PASSWORD_NOTIFICATION",
	"SYSTEM_ACTIVITY_NOTIFICATION")
;

delete 
from state_action_notification
where notification_definition_id not in (
	"APPLICATION_COMPLETE_NOTIFICATION",
	"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION",
	"APPLICATION_CONFIRM_OFFER_RECOMMENDATION_NOTIFICATION",
	"APPLICATION_CONFIRM_REJECTION_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST",
	"APPLICATION_PROVIDE_REFERENCE_REQUEST",
	"APPLICATION_RESERVE_NOTIFICATION",
	"APPLICATION_REVERSE_REJECTION_NOTIFICATION",
	"APPLICATION_TERMINATE_NOTIFICATION",
	"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"PROJECT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROJECT_CORRECT_REQUEST",
	"PROGRAM_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROGRAM_CORRECT_REQUEST",
	"DEPARTMENT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"DEPARTMENT_CORRECT_REQUEST",
	"INSTITUTION_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"INSTITUTION_CORRECT_REQUEST",
	"SYSTEM_INVITATION_NOTIFICATION",
	"SYSTEM_COMPLETE_REGISTRATION_REQUEST",
	"SYSTEM_PASSWORD_NOTIFICATION",
	"SYSTEM_ACTIVITY_NOTIFICATION")
;

update state_action
set notification_definition_id = null
where notification_definition_id not in (
	"APPLICATION_COMPLETE_NOTIFICATION",
	"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION",
	"APPLICATION_CONFIRM_OFFER_RECOMMENDATION_NOTIFICATION",
	"APPLICATION_CONFIRM_REJECTION_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST",
	"APPLICATION_PROVIDE_REFERENCE_REQUEST",
	"APPLICATION_RESERVE_NOTIFICATION",
	"APPLICATION_REVERSE_REJECTION_NOTIFICATION",
	"APPLICATION_TERMINATE_NOTIFICATION",
	"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"PROJECT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROJECT_CORRECT_REQUEST",
	"PROGRAM_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROGRAM_CORRECT_REQUEST",
	"DEPARTMENT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"DEPARTMENT_CORRECT_REQUEST",
	"INSTITUTION_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"INSTITUTION_CORRECT_REQUEST",
	"SYSTEM_INVITATION_NOTIFICATION",
	"SYSTEM_COMPLETE_REGISTRATION_REQUEST",
	"SYSTEM_PASSWORD_NOTIFICATION",
	"SYSTEM_ACTIVITY_NOTIFICATION")
;

delete
from notification_definition
where id not in (
	"APPLICATION_COMPLETE_NOTIFICATION",
	"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION",
	"APPLICATION_CONFIRM_OFFER_RECOMMENDATION_NOTIFICATION",
	"APPLICATION_CONFIRM_REJECTION_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST",
	"APPLICATION_PROVIDE_REFERENCE_REQUEST",
	"APPLICATION_RESERVE_NOTIFICATION",
	"APPLICATION_REVERSE_REJECTION_NOTIFICATION",
	"APPLICATION_TERMINATE_NOTIFICATION",
	"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION",
	"PROJECT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROJECT_CORRECT_REQUEST",
	"PROGRAM_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"PROGRAM_CORRECT_REQUEST",
	"DEPARTMENT_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"DEPARTMENT_CORRECT_REQUEST",
	"INSTITUTION_COMPLETE_APPROVAL_STAGE_NOTIFICATION",
	"INSTITUTION_CORRECT_REQUEST",
	"SYSTEM_INVITATION_NOTIFICATION",
	"SYSTEM_COMPLETE_REGISTRATION_REQUEST",
	"SYSTEM_PASSWORD_NOTIFICATION",
	"SYSTEM_ACTIVITY_NOTIFICATION")
;
