CREATE TABLE PROGRAM_INTERVIEWER_LINK (
  interviewer_id INTEGER UNSIGNED NOT NULL,
  program_id INTEGER UNSIGNED NOT NULL,
  CONSTRAINT interviewer_program_user_fk FOREIGN KEY (interviewer_id) REFERENCES REGISTERED_USER(id),
  CONSTRAINT interviewer_program_program_fk FOREIGN KEY (program_id) REFERENCES PROGRAM(id)
)
ENGINE = InnoDB;

--//@UNDO

DROP TABLE IF EXISTS PROGRAM_INTERVIEWER_LINK;