CREATE TABLE PENDING_ROLE_NOTIFICATION (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  role_id INTEGER UNSIGNED,
  program_id INTEGER UNSIGNED,
  user_id INTEGER UNSIGNED,
  CONSTRAINT role_pending_not_fk FOREIGN KEY (role_id) REFERENCES APPLICATION_ROLE(id),
  CONSTRAINT prog_pending_not_fk FOREIGN KEY (program_id) REFERENCES PROGRAM(id),
  CONSTRAINT user_pending_not_fk FOREIGN KEY (user_id) REFERENCES REGISTERED_USER(id),
  PRIMARY KEY (id)
)
ENGINE = InnoDB;