CREATE TABLE REVIEW_STATE_CHANGE_EVENT (
  id INTEGER UNSIGNED NOT NULL,
  review_round_id INTEGER UNSIGNED,
  CONSTRAINT review_round_event_fk FOREIGN KEY (review_round_id) REFERENCES REVIEW_ROUND(id),
  CONSTRAINT review_event_fk FOREIGN KEY (id) REFERENCES EVENT(id)
)
ENGINE = InnoDB;