CREATE TABLE REFERENCE_EVENT (
  id INTEGER UNSIGNED NOT NULL,
  referee_id INTEGER UNSIGNED,
  CONSTRAINT ref_event_referee_fk FOREIGN KEY (referee_id) REFERENCES APPLICATION_FORM_REFEREE(id),
  CONSTRAINT reference_event_fk FOREIGN KEY (id) REFERENCES EVENT(id)
)
ENGINE = InnoDB;