ALTER TABLE REFERENCE 
DROP FOREIGN KEY ref_doc_fk, 
DROP COLUMN comment_id,
DROP COLUMN document_id,
DROP PRIMARY KEY,
DROP COLUMN id,
ADD COLUMN comment_type VARCHAR(50),
ADD COLUMN id INTEGER UNSIGNED NOT NULL,
ADD  CONSTRAINT referencec_commentr_fk FOREIGN KEY (id) REFERENCES COMMENT(id);
