ALTER TABLE PERSON MODIFY firstname VARCHAR(30)
;
ALTER TABLE PERSON MODIFY lastname VARCHAR(40)
;
ALTER TABLE PERSON MODIFY email VARCHAR(255)
;
ALTER TABLE REGISTERED_USER MODIFY firstName VARCHAR(30)
;
ALTER TABLE REGISTERED_USER MODIFY lastName VARCHAR(40)
;
ALTER TABLE REGISTERED_USER MODIFY email VARCHAR(255)
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL MODIFY last_name VARCHAR(30)
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL MODIFY first_name VARCHAR(40)
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL MODIFY email VARCHAR(255)
;
