CREATE TABLE IF NOT EXISTS MODE_OF_ATTENDANCE (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY(id)
)
ENGINE = InnoDB
;
INSERT INTO MODE_OF_ATTENDANCE (name, enabled) VALUES 
	('Flexible study: distance learning', TRUE),
	('Full-time', TRUE),
	('Full-time: Exchange', TRUE),
	('Full-time: Full-time: off-campus thesis submited', TRUE),
	('Full-time: JYA with Fees', TRUE),
	('Full-time: Junior Year Abroad', TRUE),
	('Full-time: Technology Enterprise Scholarship Schm', TRUE),
	('Full-time: completing research', TRUE),
	('Full-time: completing research joint reg elsewhere', TRUE),
	('Full-time: completing research joint registration', TRUE),
	('Full-time: completing research off-campus scheme', TRUE),
	('Full-time: distance learning', TRUE),
	('Full-time: extension to completing research', TRUE),
	('Full-time: extensn to comp resrch off-campus schm', TRUE),
	('Full-time: extramural year', TRUE),
	('Full-time: incoming Erasmus', TRUE),
	('Full-time: incoming Socrates', TRUE),
	('Full-time: joint registration', TRUE),
	('Full-time: joint registration elsewhere', TRUE),
	('Full-time: non-resident research', TRUE),
	('Full-time: off-campus scheme', TRUE),
	('Full-time: registered elsewhere', TRUE),
	('Full-time: repeating period of study', TRUE),
	('Full-time: repeating study joint reg elsewhere', TRUE),
	('Full-time: sandwich', TRUE),
	('Full-time: study abroad', TRUE),
	('Full-time: study leave (research)', TRUE),
	('Full-time: study leave joint reg elsewhere', TRUE),
	('Full-time: study leave joint registration', TRUE),
	('Full-time: study leave off-campus scheme', TRUE),
	('Full-time: thesis submitted', TRUE),
	('Modular/flexible study', TRUE),
	('Modular/flexible study: joint reg elsewhere', TRUE),
	('Modular/flexible study: joint registration', TRUE),
	('Modular/flexible study: registered elsewhere', TRUE),
	('Not in attendance: was Full-time', TRUE),
	('Not in attendance: was Full-time - joint elsewhere', TRUE),
	('Not in attendance: was Full-time distance learning', TRUE),
	('Not in attendance: was Part-time', TRUE),
	('Not in attendance: was Part-time distance learning', TRUE),
	('Not in attendance: was flexible distance learning', TRUE),
	('Not in attendance: was mod/flex - joint elsewhere', TRUE),
	('Not in attendance: was mod/flex: joint reg elsewhr', TRUE),
	('Not in attendance: was modular/flexible', TRUE),
	('Not in attendance: was part-time - joint elsewhere', TRUE),
	('Part-time', TRUE),
	('Part-time: Exchange', TRUE),
	('Part-time: JYA', TRUE),
	('Part-time: completing research', TRUE),
	('Part-time: completing research non-resident', TRUE),
	('Part-time: completing research off-campus scheme', TRUE),
	('Part-time: compulsory study abroad', TRUE),
	('Part-time: distance learning', TRUE),
	('Part-time: extension to completing research', TRUE),
	('Part-time: extensn to comp resrch off-campus schm', TRUE),
	('Part-time: extramural year', TRUE),
	('Part-time: joint registration', TRUE),
	('Part-time: joint registration elsewhere', TRUE),
	('Part-time: non-resident research', TRUE),
	('Part-time: off-campus scheme', TRUE),
	('Part-time: off-campus, thesis submitted', TRUE),
	('Part-time: registered elsewhere', TRUE),
	('Part-time: repeating period of study', TRUE),
	('Part-time: repeating study joint reg elsewhere', TRUE),
	('Part-time: study leave (research)', TRUE),
	('Part-time: thesis submitted', TRUE),
	('Union Sabbatical Officer', TRUE)
;
