SET FOREIGN_KEY_CHECKS = 0
;
DELETE FROM COUNTRIES;
;
ALTER TABLE COUNTRIES ADD enabled BOOLEAN NOT NULL DEFAULT FALSE
;
INSERT INTO COUNTRIES (name, code, enabled) VALUES 
('Afghanistan','AF',TRUE),
('Åland Islands','AX',TRUE),
('Albania','AL',TRUE),
('Algeria','DZ',TRUE),
('American Samoa','AS',TRUE),
('Andorra','AD',TRUE),
('Angola','AO',TRUE),
('Anguilla','AI',TRUE),
('Antarctica','AQ',TRUE),
('Antigua And Barbuda','AG',TRUE),
('Argentina','AR',TRUE),
('Armenia','AM',TRUE),
('Aruba','AW',TRUE),
('Australia','AU',TRUE),
('Austria','AT',TRUE),
('Azerbaijan','AZ',TRUE),
('Bahamas, The','BS',TRUE),
('Bahrain','BH',TRUE),
('Bangladesh','BD',TRUE),
('Barbados','BB',TRUE),
('Belarus','BY',TRUE),
('Belgium','BE',TRUE),
('Belize','BZ',TRUE),
('Benin','BJ',TRUE),
('Bermuda','BM',TRUE),
('Bhutan','BT',TRUE),
('Bolivia','BO',TRUE),
('Bonaire, Sint Eustatius And Saba','BQ',TRUE),
('Bosnia And Herzegovina','BA',TRUE),
('Botswana','BW',TRUE),
('Bouvet Island','BV',TRUE),
('Brazil','BR',TRUE),
('British Indian Ocean Territory','IO',TRUE),
('British Virgin Islands','VG',TRUE),
('Brunei','BN',TRUE),
('Bulgaria','BG',TRUE),
('Burkina','BF',TRUE),
('Burma','MM',TRUE),
('Burundi','BI',TRUE),
('Cambodia','KH',TRUE),
('Cameroon','CM',TRUE),
('Canada','CA',TRUE),
('Cape Verde','CV',TRUE),
('Cayman Islands','KY',TRUE),
('Central African Republic','CF',TRUE),
('Chad','TD',TRUE),
('Channel Islands','XL',TRUE),
('Chile','CL',TRUE),
('China','CN',TRUE),
('Christmas Island','CX',TRUE),
('Cocos (Keeling) Islands','CC',TRUE),
('Colombia','CO',TRUE),
('Comoros','KM',TRUE),
('Congo','CG',TRUE),
('Congo (Democratic Republic)','CD',TRUE),
('Cook Islands','CK',TRUE),
('Costa Rica','CR',TRUE),
('Croatia','HR',TRUE),
('Cuba','CU',TRUE),
('Curaçao','CW',TRUE),
('Cyprus','XA',TRUE),
('Czech Republic','CZ',TRUE),
('Denmark','DK',TRUE),
('Djibouti','DJ',TRUE),
('Dominica','DM',TRUE),
('Dominican Republic','DO',TRUE),
('East Timor','TL',TRUE),
('Ecuador','EC',TRUE),
('Egypt','EG',TRUE),
('El Salvador','SV',TRUE),
('Equatorial Guinea','GQ',TRUE),
('Eritrea','ER',TRUE),
('Estonia','EE',TRUE),
('Ethiopia','ET',TRUE),
('Falkland Islands','FK',TRUE),
('Faroe Islands','FO',TRUE),
('Fiji','FJ',TRUE),
('Finland','FI',TRUE),
('France','FR',TRUE),
('French Guiana','GF',TRUE),
('French Polynesia','PF',TRUE),
('French Southern Territories','TF',TRUE),
('Gabon','GA',TRUE),
('Gambia, The','GM',TRUE),
('Georgia','GE',TRUE),
('Germany','DE',TRUE),
('Ghana','GH',TRUE),
('Gibraltar','GI',TRUE),
('Greece','GR',TRUE),
('Greenland','GL',TRUE),
('Grenada','GD',TRUE),
('Guadeloupe','GP',TRUE),
('Guam','GU',TRUE),
('Guatemala','GT',TRUE),
('Guinea','GN',TRUE),
('Guinea-Bissau','GW',TRUE),
('Guyana','GY',TRUE),
('Haiti','HT',TRUE),
('Heard Island And Mcdonald Islands','HM',TRUE),
('Honduras','HN',TRUE),
('Hong Kong (Special Administrative Region Of Chiina)','HK',TRUE),
('Hungary','HU',TRUE),
('Iceland','IS',TRUE),
('India','IN',TRUE),
('Indonesia','ID',TRUE),
('Iran','IR',TRUE),
('Iraq','IQ',TRUE),
('Ireland','IE',TRUE),
('Isle Of Man','IM',TRUE),
('Israel','IL',TRUE),
('Italy','IT',TRUE),
('Ivory Coast','CI',TRUE),
('Jamaica','JM',TRUE),
('Japan','JP',TRUE),
('Jordan','JO',TRUE),
('Kazakhstan','KZ',TRUE),
('Kenya','KE',TRUE),
('Kiribati','KI',TRUE),
('Korea (North)','KP',TRUE),
('Korea (South)','KR',TRUE),
('Kosovo','QO',TRUE),
('Kuwait','KW',TRUE),
('Kyrgyzstan','KG',TRUE),
('Laos','LA',TRUE),
('Latvia','LV',TRUE),
('Lebanon','LB',TRUE),
('Lesotho','LS',TRUE),
('Liberia','LR',TRUE),
('Libya','LY',TRUE),
('Liechtenstein','LI',TRUE),
('Lithuania','LT',TRUE),
('Luxembourg','LU',TRUE),
('Macao (Special Administrative Region Of Chiina)','MO',TRUE),
('Macedonia','MK',TRUE),
('Madagascar','MG',TRUE),
('Malawi','MW',TRUE),
('Malaysia','MY',TRUE),
('Maldives','MV',TRUE),
('Mali','ML',TRUE),
('Malta','MT',TRUE),
('Marshall Islands','MH',TRUE),
('Martinique','MQ',TRUE),
('Mauritania','MR',TRUE),
('Mauritius','MU',TRUE),
('Mayotte','YT',TRUE),
('Mexico','MX',TRUE),
('Micronesia','FM',TRUE),
('Moldova','MD',TRUE),
('Monaco','MC',TRUE),
('Mongolia','MN',TRUE),
('Montenegro','ME',TRUE),
('Montserrat','MS',TRUE),
('Morocco','MA',TRUE),
('Mozambique','MZ',TRUE),
('Namibia','NA',TRUE),
('Nauru','NR',TRUE),
('Nepal','NP',TRUE),
('Netherlands','NL',TRUE),
('New Caledonia','NC',TRUE),
('New Zealand','NZ',TRUE),
('Nicaragua','NI',TRUE),
('Niger','NE',TRUE),
('Nigeria','NG',TRUE),
('Niue','NU',TRUE),
('Norfolk Island','NF',TRUE),
('Northern Mariana Islands','MP',TRUE),
('Norway','NO',TRUE),
('Occupied Palestinian Territories','PS',TRUE),
('Oman','OM',TRUE),
('Pakistan','PK',TRUE),
('Palau','PW',TRUE),
('Panama','PA',TRUE),
('Papua New Guinea','PG',TRUE),
('Paraguay','PY',TRUE),
('Peru','PE',TRUE),
('Philippines','PH',TRUE),
('Pitcairn, Henderson, Ducie And Oeno Islands','PN',TRUE),
('Poland','PL',TRUE),
('Portugal','PT',TRUE),
('Puerto Rico','PR',TRUE),
('Qatar','QA',TRUE),
('Réunion','RE',TRUE),
('Romania','RO',TRUE),
('Russia','RU',TRUE),
('Rwanda','RW',TRUE),
('Saint Martin (French Part)','MF',TRUE),
('Samoa','WS',TRUE),
('San Marino','SM',TRUE),
('Sao Tome And Principe','ST',TRUE),
('Saudi Arabia','SA',TRUE),
('Senegal','SN',TRUE),
('Serbia','RS',TRUE),
('Seychelles','SC',TRUE),
('Sierra Leone','SL',TRUE),
('Singapore','SG',TRUE),
('Sint Maarten (Dutch Part)','SX',TRUE),
('Slovakia','SK',TRUE),
('Slovenia','SI',TRUE),
('Solomon Islands','SB',TRUE),
('Somalia','SO',TRUE),
('South Africa','ZA',TRUE),
('South Georgia And The South Sandwich Islands','GS',TRUE),
('South Sudan','SS',TRUE),
('Spain','ES',TRUE),
('Sri Lanka','LK',TRUE),
('St Barthélemy','BL',TRUE),
('St Helena, Ascension And Tristan Da Cunha','SH',TRUE),
('St Kitts And Nevis','KN',TRUE),
('St Lucia','LC',TRUE),
('St Pierre And Miquelon','PM',TRUE),
('St Vincent And The Grenadines','VC',TRUE),
('Sudan','SD',TRUE),
('Surinam','SR',TRUE),
('Svalbard And Jan Mayen','SJ',TRUE),
('Swaziland','SZ',TRUE),
('Sweden','SE',TRUE),
('Switzerland','CH',TRUE),
('Syria','SY',TRUE),
('Taiwan','TW',TRUE),
('Tajikistan','TJ',TRUE),
('Tanzania','TZ',TRUE),
('Thailand','TH',TRUE),
('Togo','TG',TRUE),
('Tokelau','TK',TRUE),
('Tonga','TO',TRUE),
('Trinidad And Tobago','TT',TRUE),
('Tunisia','TN',TRUE),
('Turkey','TR',TRUE),
('Turkmenistan','TM',TRUE),
('Turks And Caicos Islands','TC',TRUE),
('Tuvalu','TV',TRUE),
('Uganda','UG',TRUE),
('Ukraine','UA',TRUE),
('United Arab Emirates','AE',TRUE),
('United Kingdom','XK',TRUE),
('United States','US',TRUE),
('United States Minor Outlying Islands','UM',TRUE),
('United States Virgin Islands','VI',TRUE),
('Uruguay','UY',TRUE),
('Uzbekistan','UZ',TRUE),
('Vanuatu','VU',TRUE),
('Vatican City','VA',TRUE),
('Venezuela','VE',TRUE),
('Vietnam','VN',TRUE),
('Wallis And Futuna','WF',TRUE),
('Western Sahara','EH',TRUE),
('Yemen','YE',TRUE),
('Zambia','ZM',TRUE),
('Zimbabwe','ZW',TRUE)
;
SET FOREIGN_KEY_CHECKS = 1
;