SET FOREIGN_KEY_CHECKS = 0
;
DELETE FROM COUNTRIES;
;
ALTER TABLE COUNTRIES DROP code
;
INSERT INTO COUNTRIES (name, enabled) VALUES 
	 ("United Kingdom", TRUE),
	 ("Yemen", TRUE),
	 ("Afghanistan", TRUE),
	 ("Albania", TRUE),
	 ("Algeria", TRUE),
	 ("Andorra", TRUE),
	 ("Angola", TRUE),
	 ("Antigua (and Barbuda)", TRUE),
	 ("Argentina", TRUE),
	 ("Australia", TRUE),
	 ("Austria", TRUE),
	 ("Bahamas", TRUE),
	 ("Bahrain", TRUE),
	 ("Barbados", TRUE),
	 ("Belgium", TRUE),
	 ("Bermuda", TRUE),
	 ("Bhutan", TRUE),
	 ("Bolivia", TRUE),
	 ("Botswana", TRUE),
	 ("Brazil", TRUE),
	 ("Brunei", TRUE),
	 ("Bulgaria", TRUE),
	 ("Burma (Myanmar)", TRUE),
	 ("Burundi", TRUE),
	 ("Cambodia (Kampuchea)", TRUE),
	 ("Cameroon", TRUE),
	 ("Canada", TRUE),
	 ("Central African Republic", TRUE),
	 ("Sri Lanka", TRUE),
	 ("Chad", TRUE),
	 ("Chile", TRUE),
	 ("China, People's Republic", TRUE),
	 ("Colombia", TRUE),
	 ("Congo (Democratic Republic) (Zaire)", TRUE),
	 ("Congo, People's Republic", TRUE),
	 ("Costa Rica", TRUE),
	 ("Cuba", TRUE),
	 ("Antilles (Netherlands)", TRUE),
	 ("Czechoslovakia", TRUE),
	 ("Benin", TRUE),
	 ("Denmark", TRUE),
	 ("Dominica", TRUE),
	 ("Dominican Republic", TRUE),
	 ("Ecuador", TRUE),
	 ("El Salvador", TRUE),
	 ("Tuvalu", TRUE),
	 ("Ethiopia", TRUE),
	 ("Falkland Islands", TRUE),
	 ("Fiji", TRUE),
	 ("Finland", TRUE),
	 ("Taiwan", TRUE),
	 ("France", TRUE),
	 ("Gabon", TRUE),
	 ("Gambia", TRUE),
	 ("Germany", TRUE),
	 ("East Germany", TRUE),
	 ("Ghana", TRUE),
	 ("Gibraltar", TRUE),
	 ("Kiribati (Gilbert and Ellice Islands)", TRUE),
	 ("Greece", TRUE),
	 ("Grenada", TRUE),
	 ("Guatemala", TRUE),
	 ("Guinea", TRUE),
	 ("Guyana", TRUE),
	 ("Haiti", TRUE),
	 ("Honduras", TRUE),
	 ("Belize", TRUE),
	 ("Hong Kong", TRUE),
	 ("Hungary", TRUE),
	 ("Iceland", TRUE),
	 ("India", TRUE),
	 ("Indonesia", TRUE),
	 ("Iran", TRUE),
	 ("Iraq", TRUE),
	 ("Ireland (Republic)", TRUE),
	 ("Israel", TRUE),
	 ("Italy", TRUE),
	 ("Ivory Coast", TRUE),
	 ("Jamaica", TRUE),
	 ("Japan", TRUE),
	 ("Jordan", TRUE),
	 ("Kenya", TRUE),
	 ("Korea (Republic - South)", TRUE),
	 ("Korea (Dem Ppl Republic - North)", TRUE),
	 ("Kuwait", TRUE),
	 ("Laos", TRUE),
	 ("Lebanon", TRUE),
	 ("Leeward Islands", TRUE),
	 ("Lesotho", TRUE),
	 ("Liberia", TRUE),
	 ("Libya", TRUE),
	 ("Luxembourg", TRUE),
	 ("Macao", TRUE),
	 ("Madagascar", TRUE),
	 ("Malawi", TRUE),
	 ("Malaya", TRUE),
	 ("Malaysia", TRUE),
	 ("Mali", TRUE),
	 ("Malta", TRUE),
	 ("Mauritania", TRUE),
	 ("Mauritius", TRUE),
	 ("Mexico", TRUE),
	 ("Mongolia", TRUE),
	 ("Montserrat", TRUE),
	 ("Morocco", TRUE),
	 ("Mozambique", TRUE),
	 ("Oman", TRUE),
	 ("Nepal", TRUE),
	 ("Netherlands", TRUE),
	 ("New Caledonia", TRUE),
	 ("New Guinea", TRUE),
	 ("Vanuatu", TRUE),
	 ("New Zealand", TRUE),
	 ("Nicaragua", TRUE),
	 ("Niger", TRUE),
	 ("Nigeria", TRUE),
	 ("Norway", TRUE),
	 ("Pakistan", TRUE),
	 ("Panama", TRUE),
	 ("Papua New Guinea", TRUE),
	 ("Paraguay", TRUE),
	 ("Peru", TRUE),
	 ("Philippines", TRUE),
	 ("Poland", TRUE),
	 ("Portugal", TRUE),
	 ("Puerto Rico", TRUE),
	 ("Qatar", TRUE),
	 ("Zimbabwe", TRUE),
	 ("Romania", TRUE),
	 ("Rwanda", TRUE),
	 ("St Helena", TRUE),
	 ("St Kitts-Nevis", TRUE),
	 ("St Lucia", TRUE),
	 ("St Vincent", TRUE),
	 ("Sabah", TRUE),
	 ("Samoa", TRUE),
	 ("Sarawak", TRUE),
	 ("Saudi Arabia", TRUE),
	 ("Seychelles", TRUE),
	 ("Sierra Leone", TRUE),
	 ("Singapore", TRUE),
	 ("Solomon Islands", TRUE),
	 ("Somalia", TRUE),
	 ("Djibouti", TRUE),
	 ("South Africa", TRUE),
	 ("Spain", TRUE),
	 ("Sudan", TRUE),
	 ("Surinam", TRUE),
	 ("Swaziland", TRUE),
	 ("Sweden", TRUE),
	 ("Switzerland", TRUE),
	 ("Syria", TRUE),
	 ("Tanzania", TRUE),
	 ("Thailand", TRUE),
	 ("Tibet", TRUE),
	 ("Togo", TRUE),
	 ("Trinidad and Tobago", TRUE),
	 ("United Arab Emirates", TRUE),
	 ("Tunisia", TRUE),
	 ("Turkey", TRUE),
	 ("Uganda", TRUE),
	 ("Egypt", TRUE),
	 ("Burkina-Faso (Upper Volta)", TRUE),
	 ("Uruguay", TRUE),
	 ("U.S.A.", TRUE),
	 ("U.S.S.R.", TRUE),
	 ("Venezuela", TRUE),
	 ("Vietnam", TRUE),
	 ("Vietnam (N)", TRUE),
	 ("Virgin Islands (British)", TRUE),
	 ("West Indies", TRUE),
	 ("Windward Islands", TRUE),
	 ("Yemen Arab Republic (North Yemen)", TRUE),
	 ("Serbia", TRUE),
	 ("Zambia", TRUE),
	 ("Not Known", TRUE),
	 ("Stateless", TRUE),
	 ("Tonga", TRUE),
	 ("Senegal", TRUE),
	 ("Timor (Portuguese)", TRUE),
	 ("Bangladesh", TRUE),
	 ("Cape Verde Islands", TRUE),
	 ("Cayman Islands", TRUE),
	 ("Equatorial Guinea", TRUE),
	 ("French Guiana", TRUE),
	 ("French West Indies", TRUE),
	 ("Maldive Islands", TRUE),
	 ("Portuguese West Africa", TRUE),
	 ("Reunion", TRUE),
	 ("Guam", TRUE),
	 ("Sikkim", TRUE),
	 ("Namibia", TRUE),
	 ("Turks and Caicos Islands", TRUE),
	 ("Virgin Islands (US)", TRUE),
	 ("Antarctica (British)", TRUE),
	 ("Guinea Bissau", TRUE),
	 ("Sao Tome & Principe", TRUE),
	 ("Comoros", TRUE),
	 ("Nauru", TRUE),
	 ("Macedonia (Former Yugoslav Republic of)", TRUE),
	 ("Mayotte (French Territorial Collectives)", TRUE),
	 ("French Polynesia", TRUE),
	 ("Pitcairn Islands", TRUE),
	 ("Anguilla", TRUE),
	 ("Monaco", TRUE),
	 ("San Marino", TRUE),
	 ("Liechtenstein", TRUE),
	 ("Greenland (& Faroe Isles)", TRUE),
	 ("British Indian Ocean Territory", TRUE),
	 ("South Georgia and the South Sandwich Islands", TRUE),
	 ("Estonia", TRUE),
	 ("Latvia", TRUE),
	 ("Lithuania", TRUE),
	 ("Croatia", TRUE),
	 ("Slovenia", TRUE),
	 ("Armenia", TRUE),
	 ("Azerbaijan", TRUE),
	 ("Belarus", TRUE),
	 ("Kazakhstan", TRUE),
	 ("Kyrgyzstan", TRUE),
	 ("Moldova", TRUE),
	 ("Russia", TRUE),
	 ("Tajikistan", TRUE),
	 ("Turkmenistan", TRUE),
	 ("Ukraine", TRUE),
	 ("Uzbekistan", TRUE),
	 ("Georgia", TRUE),
	 ("Bosnia and Herzegovina", TRUE),
	 ("Czech Republic", TRUE),
	 ("Slovakia", TRUE),
	 ("Eritrea", TRUE),
	 ("Macedonia", TRUE),
	 ("Aland Islands", TRUE),
	 ("Eritrea", TRUE),
	 ("Marshall Islands", TRUE),
	 ("Micronesia (Federated States of)", TRUE),
	 ("East Timor", TRUE),
	 ("Montenegro", TRUE),
	 ("Palestine", TRUE),
	 ("Kosovo", TRUE),
	 ("Cyprus (EU)", TRUE),
	 ("Cyprus (Non EU)", TRUE)
;
SET FOREIGN_KEY_CHECKS = 1
;