SET FOREIGN_KEY_CHECKS = 0
;
CREATE TABLE DOMICILE (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) 
ENGINE=InnoDB
;
INSERT INTO DOMICILE (name, enabled) VALUES 
	 ("United Kingdom", TRUE),
	 ("Northern Ireland - General", TRUE),
	 ("Channel Islands", TRUE),
	 ("Wales - County not Known", TRUE),
	 ("England", TRUE),
	 ("Alderney", TRUE),
	 ("Guernsey", TRUE),
	 ("Jersey", TRUE),
	 ("Isle of Man", TRUE),
	 ("Yemen", TRUE),
	 ("Afghanistan", TRUE),
	 ("Albania", TRUE),
	 ("Algeria", TRUE),
	 ("Andorra", TRUE),
	 ("Angola", TRUE),
	 ("Antigua (and Barbuda)", TRUE),
	 ("Argentina", TRUE),
	 ("Australia", TRUE),
	 ("Austria", TRUE),
	 ("Bahamas", TRUE),
	 ("Bahrain", TRUE),
	 ("Barbados", TRUE),
	 ("Belgium", TRUE),
	 ("Bermuda", TRUE),
	 ("Bhutan", TRUE),
	 ("Bolivia", TRUE),
	 ("Botswana", TRUE),
	 ("Brazil", TRUE),
	 ("Brunei", TRUE),
	 ("Bulgaria", TRUE),
	 ("Burma (Myanmar)", TRUE),
	 ("Burundi", TRUE),
	 ("Cambodia (Kampuchea)", TRUE),
	 ("Cameroon", TRUE),
	 ("Canada", TRUE),
	 ("Central African Republic", TRUE),
	 ("Sri Lanka", TRUE),
	 ("Chad", TRUE),
	 ("Chile", TRUE),
	 ("China (People's Republic)", TRUE),
	 ("Colombia", TRUE),
	 ("Congo (Democratic Republic) (Zaire)", TRUE),
	 ("Congo (People's Republic)", TRUE),
	 ("Costa Rica", TRUE),
	 ("Cuba", TRUE),
	 ("Antilles (Netherlands)", TRUE),
	 ("Benin", TRUE),
	 ("Denmark", TRUE),
	 ("Dominica", TRUE),
	 ("Dominican Republic", TRUE),
	 ("Ecuador", TRUE),
	 ("El Salvador", TRUE),
	 ("Tuvalu", TRUE),
	 ("Ethiopia", TRUE),
	 ("Falkland Islands", TRUE),
	 ("Fiji", TRUE),
	 ("Finland", TRUE),
	 ("Taiwan", TRUE),
	 ("France", TRUE),
	 ("Gabon", TRUE),
	 ("Gambia", TRUE),
	 ("Germany", TRUE),
	 ("Ghana", TRUE),
	 ("Gibraltar", TRUE),
	 ("Kiribati (Gilbert and Ellice Islands)", TRUE),
	 ("Greece", TRUE),
	 ("Grenada", TRUE),
	 ("Guatemala", TRUE),
	 ("Guinea", TRUE),
	 ("Guyana", TRUE),
	 ("Haiti", TRUE),
	 ("Honduras", TRUE),
	 ("Belize", TRUE),
	 ("Hong Kong", TRUE),
	 ("Hungary", TRUE),
	 ("Iceland", TRUE),
	 ("India", TRUE),
	 ("Indonesia", TRUE),
	 ("Iran", TRUE),
	 ("Iraq", TRUE),
	 ("Ireland (Republic)", TRUE),
	 ("Israel", TRUE),
	 ("Italy", TRUE),
	 ("Ivory Coast", TRUE),
	 ("Jamaica", TRUE),
	 ("Japan", TRUE),
	 ("Jordan", TRUE),
	 ("Wales", TRUE),
	 ("Kenya", TRUE),
	 ("Korea (Republic - South)", TRUE),
	 ("Korea (Dem Ppl Republic - North)", TRUE),
	 ("Kuwait", TRUE),
	 ("Laos", TRUE),
	 ("Lebanon", TRUE),
	 ("Lesotho", TRUE),
	 ("Liberia", TRUE),
	 ("Libya", TRUE),
	 ("Luxembourg", TRUE),
	 ("Macao", TRUE),
	 ("Madagascar", TRUE),
	 ("Malawi", TRUE),
	 ("Malaysia", TRUE),
	 ("Mali", TRUE),
	 ("Malta", TRUE),
	 ("Mauritania", TRUE),
	 ("Mauritius", TRUE),
	 ("Mexico", TRUE),
	 ("Mongolia", TRUE),
	 ("Montserrat", TRUE),
	 ("Morocco", TRUE),
	 ("Mozambique", TRUE),
	 ("Oman", TRUE),
	 ("Nepal", TRUE),
	 ("Netherlands", TRUE),
	 ("New Caledonia", TRUE),
	 ("New Guinea", TRUE),
	 ("Vanuatu", TRUE),
	 ("New Zealand", TRUE),
	 ("Nicaragua", TRUE),
	 ("Niger", TRUE),
	 ("Nigeria", TRUE),
	 ("Norway", TRUE),
	 ("Pakistan", TRUE),
	 ("Panama", TRUE),
	 ("Papua New Guinea", TRUE),
	 ("Paraguay", TRUE),
	 ("Peru", TRUE),
	 ("Philippines", TRUE),
	 ("Poland", TRUE),
	 ("Portugal", TRUE),
	 ("Puerto Rico", TRUE),
	 ("Qatar", TRUE),
	 ("Zimbabwe", TRUE),
	 ("Romania", TRUE),
	 ("Rwanda", TRUE),
	 ("St Helena", TRUE),
	 ("St Kitts-Nevis", TRUE),
	 ("St Lucia", TRUE),
	 ("St Vincent and the Grenadines", TRUE),
	 ("Samoa", TRUE),
	 ("Saudi Arabia", TRUE),
	 ("Seychelles", TRUE),
	 ("Sierra Leone", TRUE),
	 ("Singapore", TRUE),
	 ("Solomon Islands", TRUE),
	 ("Somalia", TRUE),
	 ("Djibouti", TRUE),
	 ("South Africa", TRUE),
	 ("Spain", TRUE),
	 ("Sudan", TRUE),
	 ("Surinam", TRUE),
	 ("Swaziland", TRUE),
	 ("Sweden", TRUE),
	 ("Switzerland", TRUE),
	 ("Syria", TRUE),
	 ("Tanzania", TRUE),
	 ("Thailand", TRUE),
	 ("Togo", TRUE),
	 ("Trinidad and Tobago", TRUE),
	 ("United Arab Emirates", TRUE),
	 ("Tunisia", TRUE),
	 ("Turkey", TRUE),
	 ("Uganda", TRUE),
	 ("Egypt", TRUE),
	 ("Burkina-Faso", TRUE),
	 ("Uruguay", TRUE),
	 ("U.S.A.", TRUE),
	 ("U.S.S.R. Not Otherwise Specified", TRUE),
	 ("Venezuela", TRUE),
	 ("Vietnam", TRUE),
	 ("Virgin Islands (British)", TRUE),
	 ("Serbia", TRUE),
	 ("Zambia", TRUE),
	 ("Not Known", TRUE),
	 ("Scotland", TRUE),
	 ("Stateless", TRUE),
	 ("Tonga", TRUE),
	 ("Senegal", TRUE),
	 ("Bangladesh", TRUE),
	 ("Cape Verde Islands", TRUE),
	 ("Cayman Islands", TRUE),
	 ("Equatorial Guinea", TRUE),
	 ("French Guiana", TRUE),
	 ("Maldive Islands", TRUE),
	 ("Reunion", TRUE),
	 ("Guam", TRUE),
	 ("Namibia", TRUE),
	 ("Turks and Caicos Islands", TRUE),
	 ("Virgin Islands (US)", TRUE),
	 ("Guinea Bissau", TRUE),
	 ("Sao Tome & Principe", TRUE),
	 ("Comoros", TRUE),
	 ("Nauru", TRUE),
	 ("Mayotte (French Territorial Collectives)", TRUE),
	 ("French Polynesia", TRUE),
	 ("Pitcairn Islands", TRUE),
	 ("Anguilla", TRUE),
	 ("Monaco", TRUE),
	 ("San Marino", TRUE),
	 ("Liechtenstein", TRUE),
	 ("Greenland", TRUE),
	 ("South Georgia and the South Sandwich Islands", TRUE),
	 ("Estonia", TRUE),
	 ("Latvia", TRUE),
	 ("Lithuania", TRUE),
	 ("Croatia", TRUE),
	 ("Slovenia", TRUE),
	 ("Armenia", TRUE),
	 ("Azerbaijan", TRUE),
	 ("Belarus", TRUE),
	 ("Kazakhstan", TRUE),
	 ("Kyrgyzstan", TRUE),
	 ("Moldova", TRUE),
	 ("Russia", TRUE),
	 ("Tajikistan", TRUE),
	 ("Turkmenistan", TRUE),
	 ("Ukraine", TRUE),
	 ("Uzbekistan", TRUE),
	 ("Georgia", TRUE),
	 ("Bosnia and Herzegovina", TRUE),
	 ("Czech Republic", TRUE),
	 ("Slovakia", TRUE),
	 ("Eritrea", TRUE),
	 ("Macedonia (Former Yugoslav Republic of)", TRUE),
	 ("Aland Islands", TRUE),
	 ("Marshall Islands", TRUE),
	 ("Micronesia (Federated States of)", TRUE),
	 ("East Timor", TRUE),
	 ("Montenegro", TRUE),
	 ("Palestine", TRUE),
	 ("Cyprus (European Union)", TRUE),
	 ("Northern Ireland", TRUE),
	 ("Cyprus (Non-European Union)", TRUE)
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL 
	DROP FOREIGN KEY residence_country_fk,
	ADD COLUMN domicile_id  int(10) unsigned NOT NULL,
	ADD CONSTRAINT domicile_fk FOREIGN KEY(domicile_id) REFERENCES DOMICILE(id)
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL DROP COLUMN residence_country_id
;
SET FOREIGN_KEY_CHECKS = 1
;