SET FOREIGN_KEY_CHECKS = 0
;
ALTER TABLE APPLICATION_FORM_QUALIFICATION ADD COLUMN qualification_type_id INTEGER(10) UNSIGNED NOT NULL,
ADD CONSTRAINT qualification_type_fk FOREIGN KEY(qualification_type_id) REFERENCES QUALIFICATION_TYPE(id)
;
ALTER TABLE APPLICATION_FORM_QUALIFICATION DROP COLUMN qualification_type
;
SET FOREIGN_KEY_CHECKS = 1
;