SET FOREIGN_KEY_CHECKS = 0
;
ALTER TABLE APPLICATION_FORM_QUALIFICATION 
	DROP FOREIGN KEY country_inst_fk,
	ADD COLUMN institution_domicile_id INTEGER(10) UNSIGNED NOT NULL,
	ADD CONSTRAINT domicile_id_fk FOREIGN KEY(institution_domicile_id) REFERENCES DOMICILE(id)
;
ALTER TABLE APPLICATION_FORM_QUALIFICATION DROP COLUMN institution_country_id
;
SET FOREIGN_KEY_CHECKS = 1
;