SET FOREIGN_KEY_CHECKS = 0
;
DELETE FROM QUALIFICATION_TYPE
;
INSERT INTO QUALIFICATION_TYPE (name, enabled) VALUES 
	 ("Bachelors Degree - France", TRUE),
	 ("Bachelors Degree - India", TRUE),
	 ("Bachelors Degree - Spain", TRUE),
	 ("Bachelors Degree - Sweden", TRUE),
	 ("Bachelors Degree - not listed elsewhere", TRUE),
	 ("Bachelors degree - Czech Republic / Slovakia", TRUE),
	 ("Bachelors degree CGPA 4.0 grading scheme", TRUE),
	 ("Bachelors degree CGPA 4.3 grading scheme", TRUE),
	 ("Bachelors degree CGPA 4.5 grading scheme", TRUE),
	 ("Bachelors degree with 1-10 grading scheme", TRUE),
	 ("Bachelors degree with 1-12 grading scheme", TRUE),
	 ("Bachelors degree with 1-20 grading scheme", TRUE),
	 ("Bachelors degree with 1-5 grading scheme", TRUE),
	 ("Bachelors degree with 1-6 grading scheme", TRUE),
	 ("Bachelors degree with 1-7 grading scheme", TRUE),
	 ("Bachelors degree with 1-9 grading scheme", TRUE),
	 ("Bachelors degree with 5-10 grading scheme", TRUE),
	 ("Bachelors degree with A+ - F grading scheme", TRUE),
	 ("Bachelors degree with UK honours grading scheme", TRUE),
	 ("Bachelors degree with credit / merit grading scheme", TRUE),
	 ("Bachelors degree with grading scheme of Excel, V.Good, Good, Satisfactory", TRUE),
	 ("Bachelors degree with grading scheme of honours (pass)", TRUE),
	 ("Bachelors degree with precentage grading scheme", TRUE),
	 ("MEng UK degree with honours grading scheme", TRUE),
	 ("MPhil degree (Postgraduate)", TRUE),
	 ("MSci UK degree with honours grading scheme", TRUE),
	 ("Masters Degree - France", TRUE),
	 ("Masters Degree - Spain", TRUE),
	 ("Masters Degree - Sweden", TRUE),
	 ("Masters Degree - not listed elsewhere", TRUE),
	 ("Masters degree CGPA 4.0 grading scheme", TRUE),
	 ("Masters degree CGPA 4.3 grading scheme", TRUE),
	 ("Masters degree CGPA 4.5 grading scheme", TRUE),
	 ("Masters degree Czech Republic / Slovakia", TRUE),
	 ("Masters degree with 1-10 grading scheme", TRUE),
	 ("Masters degree with 1-12 grading scheme", TRUE),
	 ("Masters degree with 1-20 grading scheme", TRUE),
	 ("Masters degree with 1-5 grading scheme", TRUE),
	 ("Masters degree with 1-6 grading scheme", TRUE),
	 ("Masters degree with 1-7 grading scheme", TRUE),
	 ("Masters degree with 1-9 grading scheme", TRUE),
	 ("Masters degree with 5-10 grading scheme", TRUE),
	 ("Masters degree with A+ - F grading scheme", TRUE),
	 ("Masters degree with credit / merit grading scheme", TRUE),
	 ("Masters degree with grading scheme of Excel, V.Good, Good, Satisisfactory", TRUE),
	 ("Masters degree with grading scheme of honours (pass)", TRUE),
	 ("Masters degree with grading scheme of honours - India", TRUE),
	 ("Masters degree with percentage grading scheme", TRUE),
	 ("Non-Honours Ordinary Degree", TRUE),
	 ("Other examinations and/or information", TRUE),
	 ("PhD degree (postgraduate)", TRUE)
;
SET FOREIGN_KEY_CHECKS = 1
;