SET FOREIGN_KEY_CHECKS = 0
;
ALTER TABLE CANDIDATE_NATIONALITY_LINK 
	DROP FOREIGN KEY candidate_country_fk,
	ADD COLUMN candidate_language_id INTEGER(10) UNSIGNED NOT NULL,
	ADD CONSTRAINT candidate_language_fk FOREIGN KEY(candidate_language_id) REFERENCES LANGUAGE(id)
;
ALTER TABLE CANDIDATE_NATIONALITY_LINK DROP COLUMN candidate_country_id
;
SET FOREIGN_KEY_CHECKS = 1
;