ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL ADD COLUMN passport_number VARCHAR(35) DEFAULT NULL AFTER phone
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL ADD COLUMN passport_name VARCHAR(100) DEFAULT NULL AFTER passport_number
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL ADD COLUMN passport_issue_date DATE DEFAULT NULL AFTER passport_name
;
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL ADD COLUMN passport_expiry_date DATE DEFAULT NULL AFTER passport_issue_date
;
