CREATE TABLE `DOMICILE_TMP` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `code` varchar(2) NOT NULL DEFAULT '',
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

INSERT INTO DOMICILE_TMP (code, name, enabled) VALUES 
("AD", "Andorra", true), 
("AE", "United Arab Emirates", true), 
("AF", "Afghanistan", true), 
("AG", "Antigua (and Barbuda)", true), 
("AI", "Anguilla", true), 
("AL", "Albania", true), 
("AM", "Armenia", true), 
("AN", "Antilles (Netherlands)", true), 
("AO", "Angola", true), 
("AR", "Argentina", true), 
("AT", "Austria", true), 
("AU", "Australia", true), 
("AX", "Aland Islands", true), 
("AZ", "Azerbaijan", true), 
("BA", "Bosnia and Herzegovina", true), 
("BB", "Barbados", true), 
("BD", "Bangladesh", true), 
("BE", "Belgium", true), 
("BF", "Burkina-Faso", true), 
("BG", "Bulgaria", true), 
("BH", "Bahrain", true), 
("BI", "Burundi", true), 
("BJ", "Benin", true), 
("BM", "Bermuda", true), 
("BN", "Brunei", true), 
("BO", "Bolivia", true), 
("BR", "Brazil", true), 
("BS", "Bahamas", true), 
("BT", "Bhutan", true), 
("BW", "Botswana", true), 
("BY", "Belarus", true), 
("BZ", "Belize", true), 
("CA", "Canada", true), 
("CD", "Congo (Democratic Republic) (Zaire)", true), 
("CF", "Central African Republic", true), 
("CG", "Congo (People's Republic)", true), 
("CH", "Switzerland", true), 
("CI", "Ivory Coast", true), 
("CL", "Chile", true), 
("CM", "Cameroon", true), 
("CN", "China (People's Republic)", true), 
("CO", "Colombia", true), 
("CR", "Costa Rica", true), 
("CU", "Cuba", true), 
("CV", "Cape Verde Islands", true), 
("CZ", "Czech Republic", true), 
("DE", "Germany", true), 
("DJ", "Djibouti", true), 
("DK", "Denmark", true), 
("DM", "Dominica", true), 
("DO", "Dominican Republic", true), 
("DZ", "Algeria", true), 
("EC", "Ecuador", true), 
("EE", "Estonia", true), 
("EG", "Egypt", true), 
("ER", "Eritrea", true), 
("ES", "Spain", true), 
("ET", "Ethiopia", true), 
("FI", "Finland", true), 
("FJ", "Fiji", true), 
("FK", "Falkland Islands", true), 
("FM", "Micronesia (Federated States of)", true), 
("FR", "France", true), 
("GA", "Gabon", true), 
("GD", "Grenada", true), 
("GE", "Georgia", true), 
("GF", "French Guiana", true), 
("GG", "Guernsey", true), 
("GH", "Ghana", true), 
("GI", "Gibraltar", true), 
("GL", "Greenland", true), 
("GM", "Gambia", true), 
("GN", "Guinea", true), 
("GQ", "Equatorial Guinea", true), 
("GR", "Greece", true), 
("GS", "South Georgia and the South Sandwich Islands", true), 
("GT", "Guatemala", true), 
("GU", "Guam", true), 
("GW", "Guinea Bissau", true), 
("GY", "Guyana", true), 
("HK", "Hong Kong", true), 
("HN", "Honduras", true), 
("HR", "Croatia", true), 
("HT", "Haiti", true), 
("HU", "Hungary", true), 
("ID", "Indonesia", true), 
("IE", "Ireland (Republic)", true), 
("IL", "Israel", true), 
("IM", "Isle of Man", true), 
("IN", "India", true), 
("IQ", "Iraq", true), 
("IR", "Iran", true), 
("IS", "Iceland", true), 
("IT", "Italy", true), 
("JE", "Jersey", true), 
("JM", "Jamaica", true), 
("JO", "Jordan", true), 
("JP", "Japan", true), 
("KE", "Kenya", true), 
("KG", "Kyrgyzstan", true), 
("KH", "Cambodia (Kampuchea)", true), 
("KI", "Kiribati (Gilbert and Ellice Islands)", true), 
("KM", "Comoros", true), 
("KN", "St Kitts-Nevis", true), 
("KP", "Korea (Dem Ppl Republic - North)", true), 
("KR", "Korea (Republic - South)", true), 
("KW", "Kuwait", true), 
("KY", "Cayman Islands", true), 
("KZ", "Kazakhstan", true), 
("LA", "Laos", true), 
("LB", "Lebanon", true), 
("LC", "St Lucia", true), 
("LI", "Liechtenstein", true), 
("LK", "Sri Lanka", true), 
("LR", "Liberia", true), 
("LS", "Lesotho", true), 
("LT", "Lithuania", true), 
("LU", "Luxembourg", true), 
("LV", "Latvia", true), 
("LY", "Libya", true), 
("MA", "Morocco", true), 
("MC", "Monaco", true), 
("MD", "Moldova", true), 
("ME", "Montenegro", true), 
("MG", "Madagascar", true), 
("MH", "Marshall Islands", true), 
("MK", "Macedonia (Former Yugoslav Republic of)", true), 
("ML", "Mali", true), 
("MM", "Burma (Myanmar)", true), 
("MN", "Mongolia", true), 
("MO", "Macao", true), 
("MR", "Mauritania", true), 
("MS", "Montserrat", true), 
("MT", "Malta", true), 
("MU", "Mauritius", true), 
("MV", "Maldive Islands", true), 
("MW", "Malawi", true), 
("MX", "Mexico", true), 
("MY", "Malaysia", true), 
("MZ", "Mozambique", true), 
("NA", "Namibia", true), 
("NC", "New Caledonia", true), 
("NE", "Niger", true), 
("NG", "Nigeria", true), 
("NI", "Nicaragua", true), 
("NL", "Netherlands", true), 
("NO", "Norway", true), 
("NP", "Nepal", true), 
("NR", "Nauru", true), 
("NZ", "New Zealand", true), 
("OM", "Oman", true), 
("PA", "Panama", true), 
("PE", "Peru", true), 
("PF", "French Polynesia", true), 
("PG", "Papua New Guinea", true), 
("PH", "Philippines", true), 
("PK", "Pakistan", true), 
("PL", "Poland", true), 
("PN", "Pitcairn Islands", true), 
("PR", "Puerto Rico", true), 
("PS", "Palestine", true), 
("PT", "Portugal", true), 
("PY", "Paraguay", true), 
("QA", "Qatar", true), 
("RE", "Reunion", true), 
("RO", "Romania", true), 
("RS", "Serbia", true), 
("RU", "Russia", true), 
("RW", "Rwanda", true), 
("SA", "Saudi Arabia", true), 
("SB", "Solomon Islands", true), 
("SC", "Seychelles", true), 
("SD", "Sudan", true), 
("SE", "Sweden", true), 
("SG", "Singapore", true), 
("SH", "St Helena", true), 
("SI", "Slovenia", true), 
("SK", "Slovakia", true), 
("SL", "Sierra Leone", true), 
("SM", "San Marino", true), 
("SN", "Senegal", true), 
("SO", "Somalia", true), 
("SR", "Surinam", true), 
("ST", "Sao Tome & Principe", true), 
("SV", "El Salvador", true), 
("SY", "Syria", true), 
("SZ", "Swaziland", true), 
("TC", "Turks and Caicos Islands", true), 
("TD", "Chad", true), 
("TG", "Togo", true), 
("TH", "Thailand", true), 
("TJ", "Tajikistan", true), 
("TL", "East Timor", true), 
("TM", "Turkmenistan", true), 
("TN", "Tunisia", true), 
("TO", "Tonga", true), 
("TR", "Turkey", true), 
("TT", "Trinidad and Tobago", true), 
("TV", "Tuvalu", true), 
("TW", "Taiwan", true), 
("TZ", "Tanzania", true), 
("UA", "Ukraine", true), 
("UG", "Uganda", true), 
("US", "U.S.A.", true), 
("UY", "Uruguay", true), 
("UZ", "Uzbekistan", true), 
("VC", "St Vincent and the Grenadines", true), 
("VE", "Venezuela", true), 
("VG", "Virgin Islands (British)", true), 
("VI", "Virgin Islands (US)", true), 
("VN", "Vietnam", true), 
("VU", "Vanuatu", true), 
("WS", "Samoa", true), 
("XA", "Cyprus (European Union)", true), 
("XB", "Cyprus (Non-European Union)", true), 
("XF", "England", true), 
("XG", "Northern Ireland", true), 
("XG", "Northern Ireland - General", true), 
("XH", "Scotland", true), 
("XI", "Wales", true), 
("XK", "United Kingdom", true), 
("XL", "Channel Islands", true), 
("XL", "Alderney", true), 
("YE", "Yemen", true), 
("YT", "Mayotte (French Territorial Collectives)", true), 
("ZA", "South Africa", true), 
("ZM", "Zambia", true), 
("ZW", "Zimbabwe", true), 
("ZZ", "Not Known", true)
; 

ALTER TABLE DOMICILE ADD COLUMN code VARCHAR(2) NOT NULL DEFAULT '' AFTER name
;

ALTER TABLE DOMICILE ADD INDEX domicile_code_idx (code)
;

UPDATE DOMICILE a 
INNER JOIN DOMICILE_TMP b ON a.name = b.name 
SET a.code = b.code
;

UPDATE DOMICILE a 
SET a.enabled = false 
WHERE a.code = ''
;

INSERT INTO `DOMICILE` (name, code, enabled) 
SELECT t.name, t.code, true FROM DOMICILE_TMP t 
WHERE t.code NOT IN ( SELECT x.code FROM DOMICILE x)
;

DROP TABLE DOMICILE_TMP
;