CREATE TABLE `LANGUAGE_TMP` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `code` varchar(2) NOT NULL DEFAULT '',
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

INSERT INTO LANGUAGE_TMP (name, code, enabled) VALUES 
("Stateless", "AA", true), 
("Andorra", "AD", true), 
("United Arab Emirates", "AE", true), 
("Afghanistan", "AF", true), 
("Antigua (and Barbuda)", "AG", true), 
("Anguilla", "AI", true), 
("Albania", "AL", true), 
("Armenia", "AM", true), 
("Angola", "AO", true), 
("Argentina", "AR", true), 
("Samoa US", "AS", true), 
("Austria", "AT", true), 
("Australia", "AU", true), 
("Azerbaijan", "AZ", true), 
("Bosnia and Herzegovina", "BA", true), 
("Barbados", "BB", true), 
("Bangladesh", "BD", true), 
("Belgium", "BE", true), 
("Burkina-Faso", "BF", true), 
("Bulgaria", "BG", true), 
("Bahrain", "BH", true), 
("Burundi", "BI", true), 
("Benin", "BJ", true), 
("Bermuda", "BM", true), 
("Brunei", "BN", true), 
("Bolivia", "BO", true), 
("Brazil", "BR", true), 
("Bahamas", "BS", true), 
("Bhutan", "BT", true), 
("Botswana", "BW", true), 
("Belarus", "BY", true), 
("Belize", "BZ", true), 
("Canada", "CA", true), 
("Congo (Democratic Republic) (Zaire)", "CD", true), 
("Central African Republic", "CF", true), 
("Congo (People''s Republic)", "CG", true), 
("Switzerland", "CH", true), 
("Ivory Coast", "CI", true), 
("Chile", "CL", true), 
("Cameroon", "CM", true), 
("China (People''s Republic)", "CN", true), 
("Colombia", "CO", true), 
("Costa Rica", "CR", true), 
("Cuba", "CU", true), 
("Cape Verde Islands", "CV", true), 
("Czech Republic", "CZ", true), 
("Germany", "DE", true), 
("Djibouti", "DJ", true), 
("Denmark", "DK", true), 
("Dominica", "DM", true), 
("Dominican Republic", "DO", true), 
("Algeria", "DZ", true), 
("Ecuador", "EC", true), 
("Estonia", "EE", true), 
("Egypt", "EG", true), 
("Eritrea", "ER", true), 
("Spain", "ES", true), 
("Ethiopia", "ET", true), 
("Finland", "FI", true), 
("Fiji", "FJ", true), 
("Falkland Islands", "FK", true), 
("Micronesia ( Federated States of )", "FM", true), 
("Faroe Islands", "FO", true), 
("France", "FR", true), 
("Gabon", "GA", true), 
("British Overseas Citizen", "GB", true), 
("Wales", "GB", true), 
("British National", "GB", true), 
("United Kingdom", "GB", true), 
("England", "GB", true), 
("Scotland", "GB", true), 
("Northern Ireland", "GB", true), 
("Grenada", "GD", true), 
("Georgia", "GE", true), 
("Ghana", "GH", true), 
("Gibraltar", "GI", true), 
("Greenland (& Faroe Isles)", "GL", true), 
("Gambia", "GM", true), 
("Guinea", "GN", true), 
("Equatorial Guinea", "GQ", true), 
("Greece", "GR", true), 
("South Georgia and the South Sandwich Islands", "GS", true), 
("Guatemala", "GT", true), 
("Guam", "GU", true), 
("Guinea Bissau", "GW", true), 
("Guyana", "GY", true), 
("Hong Kong (SAR), People''s Republic of China", "HK", true), 
("Honduras", "HN", true), 
("Croatia", "HR", true), 
("Haiti", "HT", true), 
("Hungary", "HU", true), 
("Indonesia", "ID", true), 
("Ireland (Republic)", "IE", true), 
("Israel", "IL", true), 
("Isle of Man", "IM", true), 
("India", "IN", true), 
("British Indian Ocean Territory", "IO", true), 
("Iraq", "IQ", true), 
("Iran", "IR", true), 
("Iceland", "IS", true), 
("Italy", "IT", true), 
("Jamaica", "JM", true), 
("Jordan", "JO", true), 
("Japan", "JP", true), 
("Kenya", "KE", true), 
("Kyrgyzstan", "KG", true), 
("Cambodia (Kampuchea)", "KH", true), 
("Kiribati (Gilbert and Ellice Islands)", "KI", true), 
("Comoros", "KM", true), 
("St Kitts-Nevis", "KN", true), 
("Korea (Dem Ppl Republic - North)", "KP", true), 
("Korea (Republic - South)", "KR", true), 
("Kuwait", "KW", true), 
("Cayman Islands", "KY", true), 
("Kazakhstan", "KZ", true), 
("Laos", "LA", true), 
("Lebanon", "LB", true), 
("St Lucia", "LC", true), 
("Liechtenstein", "LI", true), 
("Sri Lanka", "LK", true), 
("Liberia", "LR", true), 
("Lesotho", "LS", true), 
("Lithuania", "LT", true), 
("Luxembourg", "LU", true), 
("Latvia", "LV", true), 
("Libya", "LY", true), 
("Morocco", "MA", true), 
("Monaco", "MC", true), 
("Moldova", "MD", true), 
("Montenegro", "ME", true), 
("Madagascar", "MG", true), 
("Marshall Islands", "MH", true), 
("Macedonia", "MK", true), 
("Mali", "ML", true), 
("Burma (Myanmar)", "MM", true), 
("Mongolia", "MN", true), 
("Macao", "MO", true), 
("Mauritania", "MR", true), 
("Montserrat", "MS", true), 
("Malta", "MT", true), 
("Mauritius", "MU", true), 
("Maldive Islands", "MV", true), 
("Malawi", "MW", true), 
("Mexico", "MX", true), 
("Malaysia", "MY", true), 
("Mozambique", "MZ", true), 
("Namibia", "NA", true), 
("Niger", "NE", true), 
("Nigeria", "NG", true), 
("Nicaragua", "NI", true), 
("Netherlands", "NL", true), 
("Norway", "NO", true), 
("Nepal", "NP", true), 
("Nauru", "NR", true), 
("New Zealand", "NZ", true), 
("Oman", "OM", true), 
("Panama", "PA", true), 
("Peru", "PE", true), 
("Papua New Guinea", "PG", true), 
("Philippines", "PH", true), 
("Pakistan", "PK", true), 
("Poland", "PL", true), 
("Pitcairn Islands", "PN", true), 
("Palestine", "PS", true), 
("Portugal", "PT", true), 
("Paraguay", "PY", true), 
("Qatar", "QA", true), 
("Kosovo", "QO", true), 
("Romania", "RO", true), 
("Serbia", "RS", true), 
("Russia", "RU", true), 
("Rwanda", "RW", true), 
("Saudi Arabia", "SA", true), 
("Solomon Islands", "SB", true), 
("Seychelles", "SC", true), 
("Sudan", "SD", true), 
("Sweden", "SE", true), 
("Singapore", "SG", true), 
("St Helena", "SH", true), 
("Slovenia", "SI", true), 
("Slovakia", "SK", true), 
("Sierra Leone", "SL", true), 
("San Marino", "SM", true), 
("Senegal", "SN", true), 
("Somalia", "SO", true), 
("Surinam", "SR", true), 
("Sao Tome & Principe", "ST", true), 
("El Salvador", "SV", true), 
("Syria", "SY", true), 
("Swaziland", "SZ", true), 
("Turks and Caicos Islands", "TC", true), 
("Chad", "TD", true), 
("Togo", "TG", true), 
("Thailand", "TH", true), 
("Tajikistan", "TJ", true), 
("Timor (Portuguese)", "TL", true), 
("Turkmenistan", "TM", true), 
("Tunisia", "TN", true), 
("Tonga", "TO", true), 
("Turkey", "TR", true), 
("Trinidad and Tobago", "TT", true), 
("Tuvalu", "TV", true), 
("Taiwan", "TW", true), 
("Tanzania", "TZ", true), 
("Ukraine", "UA", true), 
("Uganda", "UG", true), 
("U.S.A.", "US", true), 
("Uruguay", "UY", true), 
("Uzbekistan", "UZ", true), 
("St Vincent and the Grenadines", "VC", true), 
("Venezuela", "VE", true), 
("Virgin Islands (British)", "VG", true), 
("Vietnam", "VN", true), 
("Vanuatu", "VU", true), 
("Samoa", "WS", true), 
("Cyprus EU", "XA", true), 
("Cyprus Non EU", "XB", true), 
("Yemen", "YE", true), 
("South Africa", "ZA", true), 
("Zambia", "ZM", true), 
("Zimbabwe", "ZW", true), 
("Not known (Overseas)", "ZZ", true), 
("Not known", "ZZ", true), 
("Not Known", "ZZ", true)
;

ALTER TABLE LANGUAGE ADD COLUMN code varchar(2) NOT NULL DEFAULT '' AFTER name
;

ALTER TABLE LANGUAGE ADD INDEX language_code_idx (code)
;

UPDATE LANGUAGE a 
INNER JOIN LANGUAGE_TMP b ON a.name = b.name 
SET a.code = b.code
;

UPDATE LANGUAGE a 
SET a.enabled = false 
WHERE a.code = ''
;

INSERT INTO LANGUAGE (name, code, enabled) 
SELECT t.name, t.code, true FROM LANGUAGE_TMP t 
WHERE t.code NOT IN (SELECT x.code FROM LANGUAGE x)
;

DROP TABLE LANGUAGE_TMP
;
