ALTER TABLE DOCUMENT
DROP COLUMN SEND_TO_UCL
;

ALTER TABLE APPLICATION_FORM_REFEREE
ADD COLUMN SEND_TO_UCL BOOLEAN
;

ALTER TABLE APPLICATION_FORM_QUALIFICATION
ADD COLUMN SEND_TO_UCL BOOLEAN
;