ALTER TABLE APPLICATION_FORM_QUALIFICATION CHANGE SEND_TO_UCL send_to_ucl tinyint(1) DEFAULT false
;

UPDATE APPLICATION_FORM_QUALIFICATION SET send_to_ucl = false
;

ALTER TABLE APPLICATION_FORM_REFEREE CHANGE SEND_TO_UCL send_to_ucl tinyint(1) DEFAULT false
;

UPDATE APPLICATION_FORM_REFEREE SET send_to_ucl = false
;