ALTER TABLE COUNTRIES CHANGE COLUMN code code VARCHAR(10) NOT NULL DEFAULT ''
;

ALTER TABLE DOMICILE CHANGE COLUMN code code VARCHAR(10) NOT NULL DEFAULT ''
;

ALTER TABLE LANGUAGE CHANGE COLUMN code code VARCHAR(10) NOT NULL DEFAULT ''
;
