ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL DROP COLUMN first_name
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL DROP COLUMN last_name
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL DROP COLUMN email
;
