ALTER TABLE APPROVAL_ROUND CHANGE COLUMN project_title project_title VARCHAR(255) NULL DEFAULT NULL
;

ALTER TABLE APPROVAL_COMMENT CHANGE COLUMN project_title project_title VARCHAR(255) NULL DEFAULT NULL
;

ALTER TABLE SUPERVISION_CONFIRMATION_COMMENT CHANGE COLUMN project_title project_title VARCHAR(255) NULL DEFAULT NULL
;

