ALTER TABLE APPLICATIONS_FILTER ADD COLUMN search_predicate VARCHAR(50) NOT NULL
;

ALTER TABLE APPLICATIONS_FILTER MODIFY search_category VARCHAR(50) NOT NULL
;

ALTER TABLE APPLICATIONS_FILTER MODIFY search_term VARCHAR(50) NOT NULL
;
