ALTER TABLE REGISTERED_USER ADD COLUMN email_notification_type VARCHAR(45) NOT NULL DEFAULT 'INDIVIDUAL' AFTER firstName3
;

ALTER TABLE REGISTERED_USER ADD COLUMN digest_notification TINYINT(1) NOT NULL DEFAULT 0 AFTER email_notification_type
;
