ALTER TABLE APPLICATION_FORM_TRANSFER CHANGE COLUMN transfer_end_timepoint transfer_end_timepoint TIMESTAMP NULL DEFAULT NULL
;

ALTER TABLE APPLICATION_FORM_TRANSFER CHANGE COLUMN transfer_begin_timeppoint transfer_begin_timeppoint TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_FORM_TRANSFER ADD UNIQUE INDEX application_id_UNIQUE (application_id ASC)
;