CREATE TABLE INTERVIEW_PARTICIPANT (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  participant_position INTEGER UNSIGNED,
  interview_id INTEGER UNSIGNED,
  user_id INTEGER UNSIGNED,
  responded TINYINT(1) NOT NULL,

  CONSTRAINT participant_interview_fk FOREIGN KEY (interview_id) REFERENCES INTERVIEW(id),
  CONSTRAINT interview_participant_user_fk FOREIGN KEY (user_id) REFERENCES REGISTERED_USER(id),
  PRIMARY KEY(id)
) ENGINE = InnoDB
;

CREATE TABLE INTERVIEW_TIMESLOT (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  timeslot_position INTEGER UNSIGNED,
  interview_id INTEGER UNSIGNED,
  due_date DATE NOT NULL,
  start_time VARCHAR(5) NOT NULL,
  end_time VARCHAR(5) NOT NULL,

  CONSTRAINT timeslot_interview_fk FOREIGN KEY (interview_id) REFERENCES INTERVIEW(id),
  PRIMARY KEY(id)
) ENGINE = InnoDB
;

CREATE TABLE INTERVIEW_TIMESLOT_VOTE (
  participant_id INTEGER UNSIGNED NOT NULL,
  timeslot_id INTEGER UNSIGNED NOT NULL,
  CONSTRAINT vote_participant_fk FOREIGN KEY (participant_id) REFERENCES INTERVIEW_PARTICIPANT(id),
  CONSTRAINT vote_timeslot_fk FOREIGN KEY (timeslot_id) REFERENCES INTERVIEW_TIMESLOT(id),
  UNIQUE KEY (participant_id, timeslot_id)
) ENGINE = InnoDB
;
