CREATE TABLE IF NOT EXISTS DUE_DATE_COMMENT (
  id INTEGER UNSIGNED NOT NULL,
  comment_type VARCHAR(50) NOT NULL,
  due_date DATE NOT NULL,

  CONSTRAINT due_date_comment_fk FOREIGN KEY (id) REFERENCES COMMENT(id)
)
ENGINE = InnoDB
;
