CREATE TABLE IF NOT EXISTS APPLICATIONS_FILTERING (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  pre_filter VARCHAR(6) NOT NULL,
  PRIMARY KEY(id)
)
ENGINE = InnoDB
;

DELETE FROM APPLICATIONS_FILTER
;

ALTER TABLE APPLICATIONS_FILTER DROP FOREIGN KEY registered_user_fk
;

ALTER TABLE APPLICATIONS_FILTER DROP COLUMN user_id
;

ALTER TABLE APPLICATIONS_FILTER ADD COLUMN filter_position INTEGER UNSIGNED
;

ALTER TABLE APPLICATIONS_FILTER ADD filtering_id INTEGER UNSIGNED, 
	ADD CONSTRAINT filtering_fk FOREIGN KEY(filtering_id) REFERENCES APPLICATIONS_FILTERING(id)
;

ALTER TABLE REGISTERED_USER DROP COLUMN stored_filters
;

ALTER TABLE REGISTERED_USER ADD COLUMN filtering_id INTEGER UNSIGNED,
	ADD CONSTRAINT applications_filtering_fk FOREIGN KEY(filtering_id) REFERENCES APPLICATIONS_FILTERING(id)
;
