ALTER TABLE ADVERT DROP FOREIGN KEY program_fk_in_program_advert,
	DROP COLUMN program_id
;

DROP TABLE IF EXISTS ADVERT
;

CREATE TABLE ADVERT (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255),
  description VARCHAR(2000) NOT NULL,
  study_duration INTEGER(4) NOT NULL,
  funding VARCHAR(255),
  active TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB
;

ALTER TABLE PROGRAM
	ADD COLUMN advert_id INTEGER UNSIGNED,
	ADD CONSTRAINT program_advert_fk FOREIGN KEY (advert_id) REFERENCES ADVERT(id)
;
