ALTER TABLE REVIEW_COMMENT ADD CONSTRAINT UNIQUE(reviewer_id)
;

ALTER TABLE SUPERVISION_CONFIRMATION_COMMENT ADD CONSTRAINT UNIQUE(supervisor_id)
;

ALTER TABLE INTERVIEW_VOTE_COMMENT ADD CONSTRAINT UNIQUE(interview_participant_id)
;
