ALTER TABLE APPLICATION_FORM_PROGRAMME_DETAIL
	MODIFY COLUMN programme_name VARCHAR(2000),
	MODIFY COLUMN sources_of_interest_id INT(10) UNSIGNED,
	MODIFY COLUMN study_option VARCHAR(200),
	MODIFY COLUMN start_date DATE
;