DELETE FROM REMINDER_INTERVAL
;

ALTER TABLE REMINDER_INTERVAL
ADD COLUMN reminder_type VARCHAR(20) NOT NULL UNIQUE AFTER id
;

INSERT INTO REMINDER_INTERVAL (id, reminder_type, duration, unit) VALUES (1, 'REFERENCE', 1, 'WEEKS')
;

INSERT INTO REMINDER_INTERVAL (id, reminder_type, duration, unit) VALUES (2, 'INTERVIEW_SCHEDULE', 1, 'WEEKS')
;

INSERT INTO REMINDER_INTERVAL (id, reminder_type, duration, unit) VALUES (3, 'TASK', 4, 'DAYS')
;
