ALTER TABLE INTERVIEW_COMMENT
ADD COLUMN applicant_rating INT(10)
;

ALTER TABLE REVIEW_COMMENT
ADD COLUMN applicant_rating INT(10)
;

ALTER TABLE REFERENCE_COMMENT
ADD COLUMN applicant_rating INT(10)
;