ALTER TABLE INTERVIEW
ADD COLUMN avg_rating DECIMAL(3,2)
;

ALTER TABLE REVIEW_ROUND
ADD COLUMN avg_rating DECIMAL(3,2)
;

ALTER TABLE APPLICATION_FORM
ADD COLUMN avg_rating DECIMAL(3,2)
;
