ALTER TABLE ADDRESS DROP FOREIGN KEY `country_address_fk`
;
ALTER TABLE ADDRESS CHANGE COUNTRY_ID DOMICILE_ID INT(10)
;
CREATE TEMPORARY TABLE COUNTRIES_DOMICILE AS 
(SELECT COUNTRIES.ID AS COUNTRIES_ID,DOMICILE.ID AS DOMICILE_ID FROM DOMICILE JOIN COUNTRIES ON DOMICILE.CODE=COUNTRIES.CODE AND DOMICILE.ENABLED='1')
;
/*replace 'French West Indies' with 'St Martin (French Part)'*/
insert into COUNTRIES_DOMICILE select COUNTRIES.ID,DOMICILE.ID from DOMICILE join COUNTRIES where DOMICILE.code='MF' AND COUNTRIES.CODE='XW' AND DOMICILE.ENABLED='1'
;
/*'Eritrea' is not found using country code matching, making a special case for it*/
insert into COUNTRIES_DOMICILE select COUNTRIES.ID,DOMICILE.ID from DOMICILE join COUNTRIES where DOMICILE.name='Eritrea' AND COUNTRIES.NAME='Eritrea' AND DOMICILE.ENABLED='1'
;
/*'Malaya' should be mapped to 'Malaysia', making a special case for it*/
insert into COUNTRIES_DOMICILE select COUNTRIES.ID,DOMICILE.ID from DOMICILE join COUNTRIES where DOMICILE.name='Malaysia' AND COUNTRIES.NAME='Malaya' AND DOMICILE.ENABLED='1'
;

insert into COUNTRIES_DOMICILE select COUNTRIES.ID,DOMICILE.ID from DOMICILE join COUNTRIES where DOMICILE.name='United Kingdom' AND COUNTRIES.NAME='Antarctica (British)' AND DOMICILE.ENABLED='1'
;

insert into COUNTRIES_DOMICILE select COUNTRIES.ID,DOMICILE.ID from DOMICILE join COUNTRIES where DOMICILE.name='Russia' AND COUNTRIES.NAME='U.S.S.R.' AND DOMICILE.ENABLED='1'
;

insert into COUNTRIES_DOMICILE select COUNTRIES.ID,DOMICILE.ID from DOMICILE join COUNTRIES where DOMICILE.name='Macedonia' AND COUNTRIES.NAME = 'Macedonia (Former Yugoslav Republic of)' AND DOMICILE.ENABLED='1'
;

UPDATE ADDRESS SET DOMICILE_ID = (SELECT COUNTRIES_DOMICILE.DOMICILE_ID FROM COUNTRIES_DOMICILE WHERE ADDRESS.DOMICILE_ID=COUNTRIES_DOMICILE.COUNTRIES_ID)
;

ALTER TABLE ADDRESS MODIFY DOMICILE_ID INT UNSIGNED
;

ALTER TABLE ADDRESS ADD CONSTRAINT `domicile_address_fk` FOREIGN KEY (DOMICILE_ID) REFERENCES DOMICILE(ID)
;

DROP TEMPORARY TABLE COUNTRIES_DOMICILE 
;
