CREATE TEMPORARY TABLE BAD_BATCH_DEADLINES AS 
(SELECT ID 
FROM APPLICATION_FORM 
WHERE BATCH_DEADLINE IS NOT NULL AND 
SUBMITTED_ON_TIMESTAMP IS NOT NULL AND 
(EXTRACT(HOUR FROM BATCH_DEADLINE)!='0' OR 
EXTRACT(MINUTE FROM BATCH_DEADLINE)!='0' OR  
EXTRACT(SECOND FROM BATCH_DEADLINE)!='0'))
;

UPDATE APPLICATION_FORM SET BATCH_DEADLINE = NULL WHERE ID IN (SELECT ID FROM BAD_BATCH_DEADLINES)
;

DROP TEMPORARY TABLE BAD_BATCH_DEADLINES 
;


