ALTER TABLE PENDING_ROLE_NOTIFICATION DROP FOREIGN KEY role_pending_not_fk
;

ALTER TABLE USER_ROLE_LINK DROP FOREIGN KEY user_role_role_fk
;

ALTER TABLE PENDING_ROLE_NOTIFICATION MODIFY role_id VARCHAR(50) NOT NULL
;

ALTER TABLE USER_ROLE_LINK MODIFY application_role_id VARCHAR(50) NOT NULL
;

UPDATE PENDING_ROLE_NOTIFICATION INNER JOIN APPLICATION_ROLE
	ON PENDING_ROLE_NOTIFICATION.role_id = APPLICATION_ROLE.id
	SET PENDING_ROLE_NOTIFICATION.role_id = APPLICATION_ROLE.authority
;

UPDATE USER_ROLE_LINK INNER JOIN APPLICATION_ROLE
	ON USER_ROLE_LINK.application_role_id = APPLICATION_ROLE.id
SET USER_ROLE_LINK.application_role_id = APPLICATION_ROLE.authority
;

ALTER TABLE APPLICATION_ROLE MODIFY id VARCHAR(50) NOT NULL
;

UPDATE APPLICATION_ROLE
SET APPLICATION_ROLE.id = APPLICATION_ROLE.authority
;

ALTER TABLE APPLICATION_ROLE DROP COLUMN authority
;

ALTER TABLE PENDING_ROLE_NOTIFICATION ADD FOREIGN KEY (role_id) REFERENCES APPLICATION_ROLE (id)
;

ALTER TABLE USER_ROLE_LINK ADD FOREIGN KEY (application_role_id) REFERENCES APPLICATION_ROLE (id)
;

