CREATE TABLE NOTIFICATIONS_DURATION (
  id INTEGER UNSIGNED,
  duration INTEGER UNSIGNED, 	
  unit VARCHAR(50),
  PRIMARY KEY (id)
)
ENGINE = InnoDB
;

INSERT INTO NOTIFICATIONS_DURATION (id, duration, unit)
	VALUES (1, 8, 'WEEKS')
;
