UPDATE APPLICATION_FORM
SET APPLICATION_FORM.due_date = CURRENT_DATE(),
	APPLICATION_FORM.pending_approval_restart = 0
WHERE APPLICATION_FORM.pending_approval_restart = 1
;

UPDATE STATECHANGE_COMMENT
SET STATECHANGE_COMMENT.next_status = "APPROVAL"
	WHERE STATECHANGE_COMMENT.next_status = "REQUEST_RESTART_APPROVAL"
;