CREATE TABLE APPLICATION_FORM_USER_ROLE (
	application_form_id INT(10) UNSIGNED NOT NULL,
	registered_user_id INT(10) UNSIGNED NOT NULL,
	application_role_id VARCHAR(50) NOT NULL,
	is_current_role INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(application_form_id, registered_user_id, application_role_id),
	INDEX(application_role_id),
	INDEX(registered_user_id),
	INDEX(is_current_role),
	FOREIGN KEY (application_form_id) REFERENCES APPLICATION_FORM (id),
	FOREIGN KEY (registered_user_id) REFERENCES REGISTERED_USER (id),
	FOREIGN KEY (application_role_id) REFERENCES APPLICATION_ROLE (id))
ENGINE = INNODB
;

DROP TABLE PROGRAM_REVIEWER_LINK
;

DROP TABLE PROGRAM_INTERVIEWER_LINK
;

DROP TABLE PROGRAM_SUPERVISOR_LINK
;

DELETE FROM PROGRAM_VIEWER_LINK
;

INSERT INTO PROGRAM_VIEWER_LINK (viewer_id, program_id)
	SELECT * 
	FROM PROGRAM_ADMINISTRATOR_LINK
		UNION
	SELECT * 
	FROM PROGRAM_APPROVER_LINK
;
	
INSERT INTO APPLICATION_ROLE (id)
	SELECT "PROJECTADMINISTRATOR"
		UNION
	SELECT "REVIEWADMINISTRATOR"
		UNION
	SELECT "INTERVIEWADMINISTRATOR"
		UNION
	SELECT "APPROVALADMINISTRATOR"
		UNION
	SELECT "INTERVIEWPARTICIPANT"
;
