DELETE FROM APPLICATION_FORM_ACTION_OPTIONAL
WHERE application_role_id LIKE "%ADMINISTRATOR%"
;

INSERT INTO APPLICATION_FORM_ACTION_OPTIONAL (application_role_id, state_id, action_id)
	SELECT APPLICATION_ROLE.id, STATE.id, ACTION.id
	FROM APPLICATION_ROLE INNER JOIN STATE INNER JOIN ACTION
	WHERE APPLICATION_ROLE.id IN ("ADMINISTRATOR", "SUPERADMINISTRATOR", "PROJECTADMINISTATOR")
		AND STATE.id IN ("VALIDATION", "REVIEW", "INTERVIEW")
		AND ACTION.id IN ("COMMENT", "EMAIL_APPLICANT", "VIEW_EDIT")
;

INSERT INTO APPLICATION_FORM_ACTION_OPTIONAL (application_role_id, state_id, action_id)
	SELECT "REVIEWADMINISTRATOR", "REVIEW", ACTION.id
	FROM ACTION
	WHERE ACTION.id IN ("COMMENT", "EMAIL_APPLICANT", "VIEW_EDIT")
;

INSERT INTO APPLICATION_FORM_ACTION_OPTIONAL (application_role_id, state_id, action_id)
	SELECT "INTERVIEWADMINISTRATOR", "INTERVIEW", ACTION.id
	FROM ACTION
	WHERE ACTION.id IN ("COMMENT", "EMAIL_APPLICANT", "VIEW_EDIT")
;

INSERT INTO APPLICATION_FORM_ACTION_OPTIONAL (application_role_id, state_id, action_id)
	SELECT APPLICATION_ROLE.id, STATE.id, ACTION.id
	FROM APPLICATION_ROLE INNER JOIN STATE INNER JOIN ACTION
	WHERE APPLICATION_ROLE.id LIKE "%ADMINISTRATOR%"
		AND STATE.id IN ("APPROVAL", "APPROVED", "REJECTED", "WITHDRAWN")
		AND ACTION.id IN ("COMMENT", "EMAIL_APPLICANT", "VIEW")
;