UPDATE APPLICATION_FORM_TRANSFER
SET APPLICATION_FORM_TRANSFER.transfer_begin_timeppoint = NOW(),
	APPLICATION_FORM_TRANSFER.status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE DATE(APPLICATION_FORM_TRANSFER.transfer_begin_timeppoint) >= "2013-09-30"
	AND APPLICATION_FORM_TRANSFER.status NOT IN ("COMPLETED", "QUEUED_FOR_ATTACHMENTS_SENDING", "QUEUED_FOR_WEBSERVICE_CALL")
;
