INSERT INTO APPLICATION_ROLE (id, update_visibility, do_send_update_notification)
VALUES ("SAFETYNET", 0, 0)
;

ALTER TABLE APPLICATION_ROLE
	ADD COLUMN do_send_role_notification INT(1) UNSIGNED NOT NULL DEFAULT 0,
	ADD INDEX (do_send_role_notification)
;

UPDATE APPLICATION_ROLE
SET do_send_role_notification = 1
WHERE id IN ("SUPERADMINISTRATOR", "ADMITTER", "ADMINISTRATOR", "APPROVER", "VIEWER")
;

DELETE FROM USER_ROLE_LINK
;

INSERT INTO USER_ROLE_LINK (registered_user_id, application_role_id)
	SELECT registered_user_id, application_role_id
	FROM APPLICATION_FORM_USER_ROLE
	GROUP BY registered_user_id, application_role_id
;

INSERT INTO USER_ROLE_LINK (registered_user_id, application_role_id)
	SELECT registered_user_id, "SAFETYNET"
	FROM USER_ROLE_LINK
	GROUP BY registered_user_id
;

CREATE PROCEDURE DELETE_USER_FROM_PROJECT_ROLE (
	IN in_registered_user_id INT(10) UNSIGNED, 
	IN in_project_id INT(10) UNSIGNED, 
	IN in_application_role_id VARCHAR(50))
BEGIN
	
	DELETE APPLICATION_FORM_ACTION_REQUIRED.*
	FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_FORM_ACTION_REQUIRED
		ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
	INNER JOIN APPLICATION_FORM
		ON APPLICATION_FORM_USER_ROLE.application_form_id = APPLICATION_FORM.id
	WHERE APPLICATION_FORM_USER_ROLE.registered_user_id = in_registered_user_id
		AND APPLICATION_FORM.project_id = in_project_id
		AND APPLICATION_FORM_USER_ROLE.application_role_id = in_application_role_id;

	DELETE APPLICATION_FORM_USER_ROLE.*
	FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_FORM
		ON APPLICATION_FORM_USER_ROLE.application_form_id = APPLICATION_FORM.id
	WHERE APPLICATION_FORM_USER_ROLE.registered_user_id = in_registered_user_id
		AND APPLICATION_FORM.project_id = in_project_id
		AND APPLICATION_FORM_USER_ROLE.application_role_id = in_application_role_id;

END
;

CREATE PROCEDURE UPDATE_USER_PROJECT_ROLE (
	IN in_new_registered_user_id INT(10) UNSIGNED, 
	IN in_old_registered_user_id INT(10) UNSIGNED, 
	IN in_project_id INT(10) UNSIGNED, 
	IN application_role_id VARCHAR(50))
BEGIN
	
	UPDATE APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_FORM
		ON APPLICATION_FORM_USER_ROLE.application_form_id = APPLICATION_FORM.id
	SET APPLICATION_FORM_USER_ROLE.registered_user_id = in_new_registered_user_id,
		APPLICATION_FORM_USER_ROLE.update_timestamp = CURRENT_TIMESTAMP(),
		APPLICATION_FORM_USER_ROLE.raises_update_flag = 1
	WHERE APPLICATION_FORM_USER_ROLE.registered_user_id = in_old_registered_user_id
		AND APPLICATION_FORM.project_id = in_project_id
		AND APPLICATION_FORM_USER_ROLE.application_role_id = in_application_role_id;
	
	INSERT IGNORE INTO USER_ROLE_LINK (registered_user_id, application_role_id)
	VALUES (NEW.registered_user_id, NEW.application_role_id);
	
	CALL DELETE_USER_FROM_PROJECT_ROLE(in_old_registered_user_id, in_project_id, in_application_role_id);
	
END
;

ALTER TABLE APPLICATION_ROLE
	ADD COLUMN scope VARCHAR(50) NOT NULL DEFAULT "STATE",
	ADD INDEX (scope)
;

UPDATE APPLICATION_ROLE
SET scope = "SYSTEM"
WHERE id IN ("SUPERADMINISTRATOR", "ADMITTER")
;

UPDATE APPLICATION_ROLE
SET scope = "PROGRAM"
WHERE id IN ("ADMINISTRATOR", "APPROVER", "VIEWER")
; 

UPDATE APPLICATION_ROLE
SET scope = "PROJECT"
WHERE id IN ("PROJECTADMINISTRATOR")
; 

UPDATE APPLICATION_ROLE
SET scope = "APPLICATION"
WHERE id IN ("APPLICANT", "REFEREE", "SUGGESTEDSUPERVISOR")
;

DROP PROCEDURE DELETE_ACTIONS_FOR_STATE_BOUNDED_WORKERS
;

CREATE PROCEDURE DELETE_ACTIONS_FOR_STATE_BOUNDED_WORKERS (
	IN in_application_form_id INT(10) UNSIGNED)
BEGIN

	UPDATE APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_ROLE
		ON APPLICATION_FORM_USER_ROLE.application_role_id = APPLICATION_ROLE.id
	SET APPLICATION_FORM_USER_ROLE.raises_urgent_flag = 0
	WHERE APPLICATION_FORM_USER_ROLE.application_form_id = in_application_form_id
		AND APPLICATION_ROLE.scope = "STATE";
		
	DELETE APPLICATION_FORM_ACTION_REQUIRED.*
	FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_ROLE
		ON APPLICATION_FORM_USER_ROLE.application_role_id = APPLICATION_ROLE.id
	INNER JOIN APPLICATION_FORM_ACTION_REQUIRED
		ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
	WHERE APPLICATION_FORM_USER_ROLE.application_form_id = in_application_form_id
		AND APPLICATION_ROLE.scope = "STATE";
		
	DELETE USER_ROLE_LINK.*
	FROM USER_ROLE_LINK INNER JOIN (
		SELECT APPLICATION_FORM_USER_ROLE.registered_user_id, APPLICATION_FORM_USER_ROLE.application_role_id
		FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_ROLE
			ON APPLICATION_FORM_USER_ROLE.application_role_id = APPLICATION_ROLE.id
		INNER JOIN (
			SELECT APPLICATION_FORM_USER_ROLE.registered_user_id
			FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_ROLE
				ON APPLICATION_FORM_USER_ROLE.application_role_id = APPLICATION_ROLE.id
			WHERE APPLICATION_FORM_USER_ROLE.application_form_id = in_application_form_id
				AND APPLICATION_ROLE.scope = "STATE"
			GROUP BY APPLICATION_FORM_USER_ROLE.registered_user_id) AS AFFECTED_USER
			ON APPLICATION_FORM_USER_ROLE.registered_user_id = AFFECTED_USER.registered_user_id
		LEFT JOIN APPLICATION_FORM_ACTION_REQUIRED
			ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
		WHERE APPLICATION_ROLE.scope = "STATE"
		GROUP BY APPLICATION_FORM_USER_ROLE.registered_user_id, APPLICATION_FORM_USER_ROLE.application_role_id
		HAVING COUNT(APPLICATION_FORM_ACTION_REQUIRED.id) = 0) AS ORPHANED_USER_ROLE
		ON USER_ROLE_LINK.registered_user_id = ORPHANED_USER_ROLE.registered_user_id
			AND USER_ROLE_LINK.application_role_id = ORPHANED_USER_ROLE.application_role_id;
			
END
;

DROP PROCEDURE DELETE_APPLICATION_FORM_ACTIONS
;

CREATE PROCEDURE DELETE_APPLICATION_FORM_ACTIONS (
	IN in_application_form_id INT(10) UNSIGNED)
BEGIN

	UPDATE APPLICATION_FORM_USER_ROLE
	SET APPLICATION_FORM_USER_ROLE.raises_urgent_flag = 0
 	WHERE APPLICATION_FORM_USER_ROLE.application_form_id = in_application_form_id;
 	
	DELETE APPLICATION_FORM_ACTION_REQUIRED.*
	FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_FORM_ACTION_REQUIRED
		ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
	WHERE APPLICATION_FORM_USER_ROLE.application_form_id = in_application_form_id;
	
	DELETE USER_ROLE_LINK.*
	FROM USER_ROLE_LINK INNER JOIN (
		SELECT APPLICATION_FORM_USER_ROLE.registered_user_id, APPLICATION_FORM_USER_ROLE.application_role_id
		FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_ROLE
			ON APPLICATION_FORM_USER_ROLE.application_role_id = APPLICATION_ROLE.id
		INNER JOIN (
			SELECT APPLICATION_FORM_USER_ROLE.registered_user_id
			FROM APPLICATION_FORM_USER_ROLE INNER JOIN APPLICATION_ROLE
				ON APPLICATION_FORM_USER_ROLE.application_role_id = APPLICATION_ROLE.id
			WHERE APPLICATION_FORM_USER_ROLE.application_form_id = in_application_form_id
				AND APPLICATION_ROLE.scope IN ("APPLICATION", "STATE")
			GROUP BY APPLICATION_FORM_USER_ROLE.registered_user_id) AS AFFECTED_USER
			ON APPLICATION_FORM_USER_ROLE.registered_user_id = AFFECTED_USER.registered_user_id
		LEFT JOIN APPLICATION_FORM_ACTION_REQUIRED
			ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
		WHERE APPLICATION_ROLE.scope IN ("APPLICATION", "STATE")
		GROUP BY APPLICATION_FORM_USER_ROLE.registered_user_id, APPLICATION_FORM_USER_ROLE.application_role_id
		HAVING COUNT(APPLICATION_FORM_ACTION_REQUIRED.id) = 0) AS ORPHANED_USER_ROLE
		ON USER_ROLE_LINK.registered_user_id = ORPHANED_USER_ROLE.registered_user_id
			AND USER_ROLE_LINK.application_role_id = ORPHANED_USER_ROLE.application_role_id;

END
;