ALTER TABLE APPLICATION_FORM
	ADD COLUMN previous_status VARCHAR(50) AFTER status,
	ADD INDEX (previous_status)
;

UPDATE APPLICATION_FORM
SET previous_status = status_when_withdrawn
;

ALTER TABLE APPLICATION_FORM
	DROP FOREIGN KEY application_form_status_when_withdrawn_fk_idx,
	DROP COLUMN status_when_withdrawn
;

UPDATE APPLICATION_FORM
SET previous_status = "UNSUBMITTED"
WHERE status = "VALIDATION"
;

UPDATE APPLICATION_FORM INNER JOIN COMMENT
	ON APPLICATION_FORM.id = COMMENT.application_form_id
INNER JOIN STATECHANGE_COMMENT 
	ON COMMENT.id = STATECHANGE_COMMENT.id
INNER JOIN (	
	SELECT MAX(COMMENT.id) AS comment_id, 
		APPLICATION_FORM.id AS application_form_id
	FROM APPLICATION_FORM INNER JOIN COMMENT
		ON APPLICATION_FORM.id = COMMENT.application_form_id
	INNER JOIN STATECHANGE_COMMENT
		ON COMMENT.id = STATECHANGE_COMMENT.id
	GROUP BY APPLICATION_FORM.id) = LATEST_STATECHANGE_COMMENT
	ON STATECHANGE_COMMENT.id = LATEST_STATECHANGE_COMMENT.comment_id
		AND APPLICATION_FORM.id = LATEST_STATECHANGE_COMMENT.application_form_id
SET APPLICATION_FORM.previous_status = SUBSTRING_INDEX(STATECHANGE_COMMENT.comment_type, "_", 1)
;
