CREATE TABLE ACTION_SCOPE (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
;

INSERT INTO ACTION_SCOPE (id)
VALUES
	("APPLICATION"),
	("STATE")
;

ALTER TABLE ACTION
	ADD COLUMN action_scope_id VARCHAR (50),
	ADD INDEX (action_scope_id),
	ADD FOREIGN KEY (action_scope_id) REFERENCES ACTION_SCOPE (id)
;

UPDATE ACTION
SET action_scope_id = "STATE"
WHERE id IN ("MOVE_TO_DIFFERENT_STAGE", "RETRACT_INTERVIEW_AVAILABILITY", "PROVIDE_INTERVIEW_AVAILABILITY",
	"ASSIGN_INTERVIEWERS", "ASSIGN_REVIEWERS", "ASSIGN_SUPERVISORS", "COMPLETE_APPROVAL_STAGE", "COMPLETE_INTERVIEW_STAGE",
	"COMPLETE_REVIEW_STAGE", "COMPLETE_VALIDATION_STAGE", "CONFIRM_INTERVIEW_ARRANGEMENTS", "CONFIRM_OFFER_RECOMMENDATION",
	"CONFIRM_PRIMARY_SUPERVISION", "CONFIRM_REJECTION", "PROVIDE_INTERVIEW_FEEDBACK", "PROVIDE_REVIEW")
;


UPDATE ACTION
SET action_scope_id = "APPLICATION"
WHERE id IN ("VIEW_EDIT", "WITHDRAW", "PROVIDE_REFERENCE", "CONFIRM_ELIGIBILITY", "COMMENT", "EMAIL_APPLICANT", "VIEW")
;

ALTER TABLE ACTION
	MODIFY action_scope_id VARCHAR (50) NOT NULL
;

UPDATE ACTION
SET notification = "SYNDICATED"
WHERE id = "MOVE_TO_DIFFERENT_STAGE"
;

UPDATE APPLICATION_FORM_ACTION_OPTIONAL
SET action_id = "VIEW_EDIT"
WHERE application_role_id = "STATEADMINISTRATOR"
	AND state_id IN ("REVIEW", "INTERVIEW")
	AND action_id = "VIEW"
;

INSERT INTO APPLICATION_FORM_ACTION_OPTIONAL (application_role_id, state_id, action_id, raises_urgent_flag)
VALUES ("APPROVER", "VALIDATION", "COMMENT", 0),
	("APPROVER", "VALIDATION", "EMAIL_APPLICANT", 0),
	("APPROVER", "VALIDATION", "VIEW", 0)
;

CREATE TEMPORARY TABLE ACTION_TO_REMAP (
	application_role_id VARCHAR(50) NOT NULL,
	state_id VARCHAR(50) NOT NULL,
	action_id VARCHAR(50) NOT NULL,
	raises_urgent_flag INT(1) UNSIGNED DEFAULT 0,
	INDEX (application_role_id),
	INDEX (state_id),
	INDEX (action_id),
	INDEX (raises_urgent_flag))
SELECT * 
FROM APPLICATION_FORM_ACTION_OPTIONAL
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "RECRUITMENTDIRECTOR"
WHERE application_role_id = "APPROVER"
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "RECRUITMENTOFFICER"
WHERE application_role_id IN ("SUPERADMINISTRATOR", "ADMINISTRATOR", "PROJECTADMINISTRATOR", "STATEADMINISTRATOR")
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "ADMISSIONSOFFICER"
WHERE application_role_id = "ADMITTER"
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "APPLICATIONAUTHOR"
WHERE application_role_id = "APPLICANT"
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "REFERENCEAUTHOR"
WHERE application_role_id = "REFEREE"
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "COMMENTAUTHOR"
WHERE application_role_id NOT IN ("RECRUITMENTDIRECTOR", "RECRUITMENTOFFICER", "ENTRANCEOFFICER", 
	"APPLICATIONAUTHOR", "REFERENCEAUTHOR")
;

UPDATE ACTION_TO_REMAP
SET application_role_id = "APPLICATIONAUTHOR"
WHERE application_role_id = "APPLICANT"
;

DROP TABLE APPLICATION_FORM_ACTION_OPTIONAL
;

CREATE TABLE APPLICATION_FORM_ACTION_OPTIONAL (
	authority_group_type_id VARCHAR(50) NOT NULL,
	state_id VARCHAR(50) NOT NULL,
	action_id VARCHAR(50) NOT NULL,
	raises_urgent_flag INT(1) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (authority_group_type_id, state_id, action_id),
	INDEX state_id (state_id),
	INDEX action_id (action_id),
	INDEX raises_urgent_flag (raises_urgent_flag),
	FOREIGN KEY (authority_group_type_id) REFERENCES AUTHORITY_GROUP_TYPE (id),
	FOREIGN KEY (state_id) REFERENCES STATE (id),
	FOREIGN KEY (action_id) REFERENCES ACTION (id)
) ENGINE = InnoDB
;

INSERT INTO APPLICATION_FORM_ACTION_OPTIONAL (authority_group_type_id, state_id, action_id, raises_urgent_flag)
	SELECT *
	FROM ACTION_TO_REMAP
	GROUP BY application_role_id, state_id, action_id
;

DROP TABLE ACTION_TO_REMAP
;

CREATE TABLE AUTHORITY_GROUP_RECRUITMENT_ACTION (
	authority_group_type_id VARCHAR(50) NOT NULL,
	action_id VARCHAR(50) NOT NULL,
	PRIMARY KEY (authority_group_type_id, action_id),
	INDEX (action_id),
	FOREIGN KEY (authority_group_type_id) REFERENCES AUTHORITY_GROUP_TYPE (id),
	FOREIGN KEY (action_id) REFERENCES ACTION (id)
) ENGINE = INNODB
;

INSERT INTO AUTHORITY_GROUP_RECRUITMENT_ACTION (authority_group_type_id, action_id)
VALUES ("ADMISSIONSOFFICER", "CONFIRM_ELIGIBILITY")
;

INSERT INTO AUTHORITY_GROUP_RECRUITMENT_ACTION (authority_group_type_id, action_id)
VALUES ("RECRUITMENTOFFICER", "COMPLETE_VALIDATION_STAGE"),
	("RECRUITMENTOFFICER", "ASSIGN_REVIEWERS"),
	("RECRUITMENTOFFICER", "COMPLETE_REVIEW_STAGE"),
	("RECRUITMENTOFFICER", "ASSIGN_INTERVIEWERS"),
	("RECRUITMENTOFFICER", "CONFIRM_INTERVIEW_ARRANGEMENTS"),
	("RECRUITMENTOFFICER", "COMPLETE_INTERVIEW_STAGE"),
	("RECRUITMENTOFFICER", "ASSIGN_SUPERVISORS"),
	("RECRUITMENTOFFICER", "COMPLETE_APPROVAL_STAGE"),
	("RECRUITMENTOFFICER", "MOVE_TO_DIFFERENT_STAGE")
;

INSERT INTO AUTHORITY_GROUP_RECRUITMENT_ACTION (authority_group_type_id, action_id)
VALUES ("RECRUITMENTDIRECTOR", "COMPLETE_APPROVAL_STAGE"),
	("RECRUITMENTDIRECTOR", "CONFIRM_OFFER_RECOMMENDATION"),
	("RECRUITMENTDIRECTOR", "CONFIRM_REJECTION"),
	("RECRUITMENTDIRECTOR", "MOVE_TO_DIFFERENT_STAGE")
;
