UPDATE REGISTERED_USER INNER JOIN APPLICATION_FORM_USER_ROLE
	ON REGISTERED_USER.id = APPLICATION_FORM_USER_ROLE.registered_user_id
SET REGISTERED_USER.activationCode = UUID()
WHERE REGISTERED_USER.activationCode IS NULL
	AND APPLICATION_FORM_USER_ROLE.application_role_id != "APPLICANT"
;