UPDATE APPLICATION_FORM INNER JOIN PROGRAM
	ON APPLICATION_FORM.program_id = PROGRAM.id
SET APPLICATION_FORM.excluded = 1,
	PROGRAM.enabled = 0
WHERE program_id = 63
;

UPDATE APPLICATION_FORM INNER JOIN APPLICATION_FORM_TRANSFER
	ON APPLICATION_FORM.id = APPLICATION_FORM_TRANSFER.application_id
INNER JOIN (SELECT MAX(APPLICATION_FORM_TRANSFER_ERROR.id) AS id,
	APPLICATION_FORM_TRANSFER_ERROR.transfer_id AS transfer_id
	FROM APPLICATION_FORM_TRANSFER_ERROR
	GROUP BY APPLICATION_FORM_TRANSFER_ERROR.transfer_id) AS LAST_FAILURE
	ON APPLICATION_FORM_TRANSFER.id = LAST_FAILURE.transfer_id
INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON LAST_FAILURE.id = APPLICATION_FORM_TRANSFER_ERROR.id
SET APPLICATION_FORM_TRANSFER.transfer_begin_timeppoint = NOW(),
	APPLICATION_FORM_TRANSFER.status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE APPLICATION_FORM.excluded = 0
	AND APPLICATION_FORM.status IN ("APPROVED", "REJECTED", "WITHDRAWN")
	AND (APPLICATION_FORM.status_when_withdrawn IS NULL OR
		APPLICATION_FORM.status_when_withdrawn != "UNSUBMITTED")
	AND APPLICATION_FORM_TRANSFER.status NOT IN ("COMPLETED", "QUEUED_FOR_WEBSERVICE_CALL")
	AND APPLICATION_FORM_TRANSFER_ERROR.problem_classification = "WEBSERVICE_UNREACHABLE"
;

DELETE APPLICATION_FORM_TRANSFER_ERROR.*
FROM APPLICATION_FORM_TRANSFER INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON APPLICATION_FORM_TRANSFER.id = APPLICATION_FORM_TRANSFER_ERROR.transfer_id
WHERE APPLICATION_FORM_TRANSFER.application_id = `
;

DELETE FROM APPLICATION_FORM_TRANSFER
WHERE APPLICATION_FORM_TRANSFER.application_id = 6236
;

UPDATE APPLICATION_FORM
SET excluded = 1
WHERE id = 6236
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE application_id = 5514
;

DELETE APPLICATION_FORM_TRANSFER_ERROR.*
FROM APPLICATION_FORM_TRANSFER INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON APPLICATION_FORM_TRANSFER.id = APPLICATION_FORM_TRANSFER_ERROR.transfer_id
WHERE APPLICATION_FORM_TRANSFER.application_id = 6004
;

DELETE FROM APPLICATION_FORM_TRANSFER
WHERE APPLICATION_FORM_TRANSFER.application_id = 6004
;

UPDATE APPLICATION_FORM
SET excluded = 1
WHERE id = 6004
;

DELETE APPLICATION_FORM_TRANSFER_ERROR.*
FROM APPLICATION_FORM_TRANSFER INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON APPLICATION_FORM_TRANSFER.id = APPLICATION_FORM_TRANSFER_ERROR.transfer_id
WHERE APPLICATION_FORM_TRANSFER.application_id = 6275
;

DELETE FROM APPLICATION_FORM_TRANSFER
WHERE APPLICATION_FORM_TRANSFER.application_id = 6275
;

UPDATE APPLICATION_FORM
SET excluded = 1
WHERE id = 6275
;

UPDATE APPLICATION_FORM_REFEREE
SET email = REPLACE(email, "@mdx.ac.uk@mdx.ac.uk", "@mdx.ac.uk")
WHERE email = "s.rahman@mdx.ac.uk@mdx.ac.uk"
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE application_id = 6644
;

UPDATE APPLICATION_FORM_REFEREE
SET email = REPLACE(email, "cmouaha.@", "cmouaha@")
WHERE email = "cmouaha.@yahoo.fr"
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE application_id = 3224
;

CREATE TABLE SUBSTITUTE_COUNTRY (
	prism_id	INT(10) UNSIGNED NOT NULL,
	portico_id VARCHAR(10),
	substitute_prism_id INT(10) UNSIGNED,
	UNIQUE INDEX (prism_id),
	UNIQUE INDEX (portico_id),
	INDEX (substitute_prism_id),
	FOREIGN KEY (prism_id) REFERENCES COUNTRIES (id),
	FOREIGN KEY (substitute_prism_id) REFERENCES COUNTRIES (id)
) ENGINE = INNODB
;

INSERT INTO SUBSTITUTE_COUNTRY (prism_id, portico_id)
	SELECT id, code
	FROM countries 
	WHERE enabled = 0
;

