UPDATE APPLICATION_FORM INNER JOIN PROGRAM
	ON APPLICATION_FORM.program_id = PROGRAM.id
SET APPLICATION_FORM.excluded = 1,
	PROGRAM.enabled = 0
WHERE program_id = 63
;

UPDATE APPLICATION_FORM INNER JOIN APPLICATION_FORM_TRANSFER
	ON APPLICATION_FORM.id = APPLICATION_FORM_TRANSFER.application_id
INNER JOIN (SELECT MAX(APPLICATION_FORM_TRANSFER_ERROR.id) AS id,
	APPLICATION_FORM_TRANSFER_ERROR.transfer_id AS transfer_id
	FROM APPLICATION_FORM_TRANSFER_ERROR
	GROUP BY APPLICATION_FORM_TRANSFER_ERROR.transfer_id) AS LAST_FAILURE
	ON APPLICATION_FORM_TRANSFER.id = LAST_FAILURE.transfer_id
INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON LAST_FAILURE.id = APPLICATION_FORM_TRANSFER_ERROR.id
SET APPLICATION_FORM_TRANSFER.transfer_begin_timeppoint = NOW(),
	APPLICATION_FORM_TRANSFER.status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE APPLICATION_FORM.excluded = 0
	AND APPLICATION_FORM.status IN ("APPROVED", "REJECTED", "WITHDRAWN")
	AND (APPLICATION_FORM.status_when_withdrawn IS NULL OR
		APPLICATION_FORM.status_when_withdrawn != "UNSUBMITTED")
	AND APPLICATION_FORM_TRANSFER.status NOT IN ("COMPLETED", "QUEUED_FOR_WEBSERVICE_CALL")
	AND APPLICATION_FORM_TRANSFER_ERROR.problem_classification = "WEBSERVICE_UNREACHABLE"
;

DELETE APPLICATION_FORM_TRANSFER_ERROR.*
FROM APPLICATION_FORM_TRANSFER INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON APPLICATION_FORM_TRANSFER.id = APPLICATION_FORM_TRANSFER_ERROR.transfer_id
WHERE APPLICATION_FORM_TRANSFER.application_id = 6236
;

DELETE FROM APPLICATION_FORM_TRANSFER
WHERE APPLICATION_FORM_TRANSFER.application_id = 6236
;

UPDATE APPLICATION_FORM
SET excluded = 1
WHERE id = 6236
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE application_id = 5514
;

DELETE APPLICATION_FORM_TRANSFER_ERROR.*
FROM APPLICATION_FORM_TRANSFER INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON APPLICATION_FORM_TRANSFER.id = APPLICATION_FORM_TRANSFER_ERROR.transfer_id
WHERE APPLICATION_FORM_TRANSFER.application_id = 6004
;

DELETE FROM APPLICATION_FORM_TRANSFER
WHERE APPLICATION_FORM_TRANSFER.application_id = 6004
;

UPDATE APPLICATION_FORM
SET excluded = 1
WHERE id = 6004
;

DELETE APPLICATION_FORM_TRANSFER_ERROR.*
FROM APPLICATION_FORM_TRANSFER INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON APPLICATION_FORM_TRANSFER.id = APPLICATION_FORM_TRANSFER_ERROR.transfer_id
WHERE APPLICATION_FORM_TRANSFER.application_id = 6275
;

DELETE FROM APPLICATION_FORM_TRANSFER
WHERE APPLICATION_FORM_TRANSFER.application_id = 6275
;

UPDATE APPLICATION_FORM
SET excluded = 1
WHERE id = 6275
;

UPDATE APPLICATION_FORM_REFEREE
SET email = REPLACE(email, "@mdx.ac.uk@mdx.ac.uk", "@mdx.ac.uk")
WHERE email = "s.rahman@mdx.ac.uk@mdx.ac.uk"
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE application_id = 6644
;

UPDATE APPLICATION_FORM_REFEREE
SET email = REPLACE(email, "cmouaha.@", "cmouaha@")
WHERE email = "cmouaha.@yahoo.fr"
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE application_id = 3224
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL
	MODIFY first_nationality INT(10) UNSIGNED NOT NULL,
	MODIFY second_nationality INT(10) UNSIGNED,
	ADD INDEX (first_nationality),
	ADD INDEX (second_nationality),
	ADD FOREIGN KEY (first_nationality) REFERENCES LANGUAGE (id),
	ADD FOREIGN KEY (second_nationality) REFERENCES LANGUAGE (id)
;

UPDATE APPLICATION_FORM_PERSONAL_DETAIL
SET country_id = 493
WHERE country_id = 787
;

UPDATE APPLICATION_FORM_PERSONAL_DETAIL
SET first_nationality = 544
WHERE first_nationality = 547
;

UPDATE APPLICATION_FORM_PERSONAL_DETAIL
SET second_nationality = 544
WHERE second_nationality = 547
;

UPDATE APPLICATION_FORM_PERSONAL_DETAIL
SET first_nationality = 616
WHERE first_nationality = 855
;

UPDATE APPLICATION_FORM_PERSONAL_DETAIL
SET second_nationality = 616
WHERE second_nationality = 855
;

UPDATE ADDRESS
SET domicile_id = 167
WHERE domicile_id = 257
;

UPDATE PROGRAM INNER JOIN APPLICATION_FORM 
	ON APPLICATION_FORM.program_id = PROGRAM.id
INNER JOIN APPLICATION_FORM_TRANSFER
	ON APPLICATION_FORM.id = APPLICATION_FORM_TRANSFER.application_id
INNER JOIN (SELECT MAX(APPLICATION_FORM_TRANSFER_ERROR.id) AS id,
	APPLICATION_FORM_TRANSFER_ERROR.transfer_id AS transfer_id
	FROM APPLICATION_FORM_TRANSFER_ERROR
	GROUP BY APPLICATION_FORM_TRANSFER_ERROR.transfer_id) AS LAST_FAILURE
	ON APPLICATION_FORM_TRANSFER.id = LAST_FAILURE.transfer_id
INNER JOIN APPLICATION_FORM_TRANSFER_ERROR
	ON LAST_FAILURE.id = APPLICATION_FORM_TRANSFER_ERROR.id
SET APPLICATION_FORM_TRANSFER.transfer_begin_timeppoint = NOW(),
	APPLICATION_FORM_TRANSFER.status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE PROGRAM.enabled = 1
	AND APPLICATION_FORM.excluded = 0
	AND APPLICATION_FORM.status IN ("APPROVED", "REJECTED", "WITHDRAWN")
	AND (APPLICATION_FORM.status_when_withdrawn IS NULL OR
		APPLICATION_FORM.status_when_withdrawn != "UNSUBMITTED")
	AND APPLICATION_FORM_TRANSFER.status NOT IN ("COMPLETED", "QUEUED_FOR_WEBSERVICE_CALL")
	AND APPLICATION_FORM_TRANSFER_ERROR.problem_classification = "WEBSERVICE_SOAP_FAULT"
;
