UPDATE PROGRAM INNER JOIN PROJECT
	ON PROGRAM.id = PROJECT.program_id
INNER JOIN ADVERT AS PROGRAM_ADVERT
	ON PROGRAM.advert_id = PROGRAM_ADVERT.id
LEFT JOIN ADVERT AS PROJECT_ADVERT
	ON PROJECT.advert_id = PROJECT_ADVERT.id
SET PROJECT_ADVERT.study_duration = PROGRAM_ADVERT.study_duration
WHERE PROJECT_ADVERT.study_duration IS NULL
;
