 ALTER TABLE OPPORTUNITY_REQUEST 
	ADD COLUMN status VARCHAR(255) NOT NULL,
	ADD COLUMN created_date DATETIME NOT NULL,
	ADD COLUMN study_duration INTEGER(4) NOT NULL,
	ADD COLUMN atas_required TINYINT(1) NOT NULL,
	ADD COLUMN application_start_date DATE NOT NULL,
	ADD COLUMN advertising_duration INTEGER(2) NOT NULL
;
