-- personal detail
ALTER TABLE APPLICATION_FORM
 ADD COLUMN personal_detail_id INT(10) UNSIGNED
;

UPDATE APPLICATION_FORM INNER JOIN APPLICATION_FORM_PERSONAL_DETAIL
 ON APPLICATION_FORM.id = APPLICATION_FORM_PERSONAL_DETAIL.application_form_id
SET APPLICATION_FORM.personal_detail_id = APPLICATION_FORM_PERSONAL_DETAIL.id
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL
 DROP FOREIGN KEY application_form_personal_details_fk,
 DROP COLUMN application_form_id
;

ALTER TABLE APPLICATION_FORM
 ADD INDEX (personal_detail_id),
 ADD CONSTRAINT application_form_personal_detail_fk FOREIGN KEY (personal_detail_id) REFERENCES APPLICATION_FORM_PERSONAL_DETAIL (id)
;

--language qualification
ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL
 ADD COLUMN language_qualification_id INT(10) UNSIGNED
;

UPDATE APPLICATION_FORM_PERSONAL_DETAIL INNER JOIN APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS
 ON APPLICATION_FORM_PERSONAL_DETAIL.id = APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS.application_form_personal_detail_id
SET APPLICATION_FORM_PERSONAL_DETAIL.language_qualification_id = APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS.id
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS
 DROP FOREIGN KEY application_form_personal_detail_lang_fk,
 DROP COLUMN application_form_personal_detail_id
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL
 ADD INDEX (language_qualification_id),
 ADD CONSTRAINT personal_detail_language_qualification_id FOREIGN KEY (language_qualification_id) REFERENCES APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS (id)
;

ALTER TABLE APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS
	DROP COLUMN send_to_ucl
;


