 DELETE DOCUMENT.*
 FROM DOCUMENT LEFT JOIN APPLICATION_FORM
	ON DOCUMENT.id = APPLICATION_FORM.cv_id
 LEFT JOIN APPLICATION_FORM AS APPLICATION_FORM2
	ON DOCUMENT.id = APPLICATION_FORM2.personal_statement_id
 LEFT JOIN APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS
	ON DOCUMENT.id = APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS.language_qualification_document_id
 LEFT JOIN APPLICATION_FORM_QUALIFICATION
	ON DOCUMENT.id = APPLICATION_FORM_QUALIFICATION.proof_of_award_id
 LEFT JOIN APPLICATION_FORM_FUNDING
	ON DOCUMENT.id = APPLICATION_FORM_FUNDING.document_id
 WHERE DOCUMENT.comment_id IS NULL
	AND APPLICATION_FORM.cv_id IS NULL
	AND APPLICATION_FORM2.personal_statement_id IS NULL
	AND APPLICATION_FORM_PERSONAL_DETAIL_LANGUAGE_QUALIFICATIONS.language_qualification_document_id IS NULL
	AND APPLICATION_FORM_QUALIFICATION.proof_of_award_id IS NULL
	AND APPLICATION_FORM_FUNDING.document_id IS NULL
;

ALTER TABLE DOCUMENT
	ADD COLUMN is_referenced INT(1) UNSIGNED DEFAULT 0,
	ADD INDEX (is_referenced),
	ADD INDEX (uploaded_time_stamp)
;

UPDATE DOCUMENT
SET is_referenced = 1
;

