ALTER TABLE APPLICATION_FORM_ACTION_REQUIRED
	ADD COLUMN last_notified_timestamp DATE,
	ADD INDEX (last_notified_timestamp)
;

UPDATE APPLICATION_FORM_REFEREE INNER JOIN APPLICATION_FORM_USER_ROLE
	ON APPLICATION_FORM_REFEREE.application_form_id = APPLICATION_FORM_USER_ROLE.application_form_id
	AND APPLICATION_FORM_REFEREE.registered_user_id = APPLICATION_FORM_USER_ROLE.registered_user_id
INNER JOIN APPLICATION_FORM_ACTION_REQUIRED
	ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
SET APPLICATION_FORM_ACTION_REQUIRED.last_notified_timestamp = DATE(APPLICATION_FORM_REFEREE.last_notified)
WHERE APPLICATION_FORM_USER_ROLE.application_role_id = "REFEREE"
	AND APPLICATION_FORM_ACTION_REQUIRED.action_id = "PROVIDE_REFERENCE"
;

UPDATE INTERVIEW_PARTICIPANT INNER JOIN INTERVIEW
	ON INTERVIEW_PARTICIPANT.interview_id = INTERVIEW.id
INNER JOIN APPLICATION_FORM_USER_ROLE
	ON INTERVIEW.application_form_id = APPLICATION_FORM_USER_ROLE.application_form_id
	AND INTERVIEW_PARTICIPANT.user_id = APPLICATION_FORM_USER_ROLE.registered_user_id
INNER JOIN APPLICATION_FORM_ACTION_REQUIRED
	ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
SET APPLICATION_FORM_ACTION_REQUIRED.last_notified_timestamp = DATE(INTERVIEW_PARTICIPANT.last_notified)
WHERE APPLICATION_FORM_USER_ROLE.application_role_id = "INTERVIEWER"
	AND APPLICATION_FORM_ACTION_REQUIRED.action_id = "PROVIDE_INTERVIEW_AVAILABILITY"
;

ALTER TABLE REVIEWER
	DROP COLUMN last_notified
;

ALTER TABLE INTERVIEW_PARTICIPANT
	DROP COLUMN last_notified
;

ALTER TABLE INTERVIEWER
	DROP COLUMN last_notified
;

ALTER TABLE SUPERVISOR
	DROP COLUMN last_notified
;

ALTER TABLE APPLICATION_FORM_REFEREE
	DROP COLUMN last_notified
;
