ALTER TABLE APPLICATION_FORM
 ADD COLUMN additional_info_id INT(10) UNSIGNED
;

UPDATE APPLICATION_FORM INNER JOIN APPLICATION_FORM_ADDITIONAL_INFO
 ON APPLICATION_FORM.id = APPLICATION_FORM_ADDITIONAL_INFO.application_form_id
SET APPLICATION_FORM.additional_info_id = APPLICATION_FORM_ADDITIONAL_INFO.id
;

ALTER TABLE APPLICATION_FORM_ADDITIONAL_INFO
 DROP FOREIGN KEY application_form_additional_info_fk,
 DROP COLUMN application_form_id
;

ALTER TABLE APPLICATION_FORM
 ADD INDEX (additional_info_id),
 ADD CONSTRAINT application_form_additional_info_fk FOREIGN KEY (additional_info_id) REFERENCES APPLICATION_FORM_ADDITIONAL_INFO (id)
;

