INSERT INTO APPLICATION_FORM_ACTION_REQUIRED (application_form_user_role_id, action_id, deadline_timestamp,
	bind_deadline_to_due_date, raises_urgent_flag)
	SELECT APPLICATION_FORM_USER_ROLE.id, 
		IF(APPLICATION_FORM.status = "VALIDATION", "COMPLETE_VALIDATION_STAGE", "COMPLETE_REVIEW_STAGE"),
		DATE(APPLICATION_FORM.due_date), 1, IF(DATE(APPLICATION_FORM.due_date) < CURRENT_DATE(), 1, 0)
	FROM APPLICATION_FORM LEFT JOIN APPLICATION_FORM_USER_ROLE
		ON APPLICATION_FORM.id = APPLICATION_FORM_USER_ROLE.application_form_id
	LEFT JOIN APPLICATION_FORM_ACTION_REQUIRED
		ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
	INNER JOIN USER_ROLE_LINK
	INNER JOIN ACTION
	WHERE APPLICATION_FORM.status IN ("VALIDATION", "REVIEW", "INTERVIEW", "APPROVAL")
		AND APPLICATION_FORM_USER_ROLE.application_role_id = "SUPERADMINISTRATOR"
		AND USER_ROLE_LINK.application_role_id = "SUPERADMINISTRATOR"
		AND ACTION.id IN ("COMPLETE_VALIDATION_STAGE", "COMPLETE_REVIEW_STAGE")
	GROUP BY APPLICATION_FORM_USER_ROLE.id
	HAVING COUNT(APPLICATION_FORM_ACTION_REQUIRED.id) = 0
;

INSERT INTO APPLICATION_FORM_ACTION_REQUIRED (application_form_user_role_id, action_id, deadline_timestamp,
	bind_deadline_to_due_date, raises_urgent_flag)
	SELECT APPLICATION_FORM_USER_ROLE.id, 
		IF(APPLICATION_FORM.status = "VALIDATION", "COMPLETE_VALIDATION_STAGE", "COMPLETE_REVIEW_STAGE"),
		DATE(APPLICATION_FORM.due_date), 1, IF(DATE(APPLICATION_FORM.due_date) < CURRENT_DATE(), 1, 0)
	FROM APPLICATION_FORM LEFT JOIN APPLICATION_FORM_USER_ROLE
		ON APPLICATION_FORM.id = APPLICATION_FORM_USER_ROLE.application_form_id
	LEFT JOIN APPLICATION_FORM_ACTION_REQUIRED
		ON APPLICATION_FORM_USER_ROLE.id = APPLICATION_FORM_ACTION_REQUIRED.application_form_user_role_id
	INNER JOIN PROGRAM_ADMINISTRATOR_LINK
	INNER JOIN ACTION
	WHERE APPLICATION_FORM.status IN ("VALIDATION", "REVIEW", "INTERVIEW", "APPROVAL")
		AND APPLICATION_FORM_USER_ROLE.application_role_id = "ADMINISTRATOR"
		AND ACTION.id IN ("COMPLETE_VALIDATION_STAGE", "COMPLETE_REVIEW_STAGE")
	GROUP BY APPLICATION_FORM_USER_ROLE.id
	HAVING COUNT(APPLICATION_FORM_ACTION_REQUIRED.id) = 0
;
