DELETE ADMITTER_COMMENT.*
FROM ADMITTER_COMMENT LEFT JOIN COMMENT
	ON ADMITTER_COMMENT.id = COMMENT.id
WHERE COMMENT.id IS NULL
;

ALTER TABLE ADMITTER_COMMENT
	ENGINE = INNODB,
	ADD FOREIGN KEY (id) REFERENCES COMMENT (id)
;

ALTER TABLE CHANGELOG
	ENGINE = INNODB
;

DELETE CONFIRM_ELIGIBILITY_EVENT.*
FROM CONFIRM_ELIGIBILITY_EVENT LEFT JOIN EVENT
	ON CONFIRM_ELIGIBILITY_EVENT.id = EVENT.id
WHERE EVENT.id IS NULL
;

DELETE CONFIRM_ELIGIBILITY_EVENT.*
FROM CONFIRM_ELIGIBILITY_EVENT LEFT JOIN ADMITTER_COMMENT
	ON CONFIRM_ELIGIBILITY_EVENT.admitter_comment_id = ADMITTER_COMMENT.id
WHERE ADMITTER_COMMENT.id IS NULL
;

ALTER TABLE CONFIRM_ELIGIBILITY_EVENT
	ENGINE = INNODB,
	ADD FOREIGN KEY (id) REFERENCES EVENT (id),
	ADD FOREIGN KEY (admitter_comment_id) REFERENCES COMMENT (id)
;

DELETE PROGRAM_CLOSING_DATES.*
FROM PROGRAM_CLOSING_DATES LEFT JOIN PROGRAM
	ON PROGRAM_CLOSING_DATES.program_id = PROGRAM.id
WHERE PROGRAM.id IS NULL
;

ALTER TABLE PROGRAM_CLOSING_DATES
	ENGINE = INNODB,
	ADD FOREIGN KEY (program_id) REFERENCES PROGRAM (id)
;

DELETE RESEARCH_OPPORTUNITIES_FEED.*
FROM RESEARCH_OPPORTUNITIES_FEED LEFT JOIN REGISTERED_USER
	ON RESEARCH_OPPORTUNITIES_FEED.registered_user_id = REGISTERED_USER.id
WHERE REGISTERED_USER.id IS NULL
;

ALTER TABLE RESEARCH_OPPORTUNITIES_FEED
	ENGINE = INNODB,
	ADD FOREIGN KEY (registered_user_id) REFERENCES REGISTERED_USER (id)
;

DELETE RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK.*
FROM RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK LEFT JOIN RESEARCH_OPPORTUNITIES_FEED
	ON RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK.feed_id = RESEARCH_OPPORTUNITIES_FEED.id
WHERE RESEARCH_OPPORTUNITIES_FEED.id IS NULL
;

DELETE RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK.*
FROM RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK LEFT JOIN PROGRAM
	ON RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK.program_id = PROGRAM.id
WHERE PROGRAM.id IS NULL
;

ALTER TABLE RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK
	ENGINE = INNODB,
	ADD FOREIGN KEY (feed_id) REFERENCES RESEARCH_OPPORTUNITIES_FEED (id),
	ADD FOREIGN KEY (program_id) REFERENCES PROGRAM (id)
;
