ALTER TABLE APPLICATION_FORM
	ADD COLUMN advert_id INT(10) UNSIGNED,
	ADD INDEX (advert_id),
	ADD CONSTRAINT advert_fk FOREIGN KEY (advert_id) REFERENCES ADVERT (id)
;

UPDATE APPLICATION_FORM
SET advert_id = program_id
;

UPDATE APPLICATION_FORM
SET advert_id = project_id
WHERE project_id IS NOT NULL
;

ALTER TABLE APPLICATION_FORM
	MODIFY advert_id INT(10) UNSIGNED NOT NULL
;
