CREATE PROCEDURE SP_DELETE_INACTIVE_ADVERTS ()
BEGIN

	UPDATE PROGRAM LEFT JOIN (
		SELECT PROGRAM.id
		FROM PROGRAM INNER JOIN PROGRAM_INSTANCE
			ON PROGRAM.id = PROGRAM_INSTANCE.program_id
		WHERE PROGRAM_INSTANCE.disabled_date IS NULL
			OR PROGRAM_INSTANCE.disabled_date > CURRENT_DATE()
		GROUP BY PROGRAM.id) AS ACTIVE_PROGRAM
		ON PROGRAM.id = ACTIVE_PROGRAM.id
	LEFT JOIN ADVERT AS PROGRAM_ADVERT
		ON PROGRAM.id = PROGRAM_ADVERT.id
	LEFT JOIN PROGRAM_INSTANCE
		ON PROGRAM.id = PROGRAM_INSTANCE.program_id
	LEFT JOIN PROJECT
		ON PROGRAM.id = PROJECT.program_id
	LEFT JOIN ADVERT AS PROJECT_ADVERT
		ON PROJECT.id = PROJECT_ADVERT.id
	SET PROGRAM_ADVERT.active = 0,
		PROGRAM_ADVERT.enabled = 0,
		PROGRAM_INSTANCE.enabled = 0,
		PROJECT_ADVERT.active = 0,
		PROJECT_ADVERT.enabled = 0
	WHERE ACTIVE_PROGRAM.id IS NULL;

END
;
