UPDATE APPLICATION_FORM_QUALIFICATION
	SET grade = "TBC"
WHERE LENGTH(grade) = 0
;

UPDATE APPLICATION_FORM_TRANSFER
SET transfer_begin_timeppoint = NOW(),
	status = "QUEUED_FOR_WEBSERVICE_CALL"
WHERE id IN (1708, 1709, 1710, 1816)
;
