ALTER TABLE advert
	ADD COLUMN advert_type VARCHAR(50),
	ADD INDEX (advert_type)
;

UPDATE ADVERT INNER JOIN PROGRAM
	ON ADVERT.id = PROGRAM.id
SET ADVERT.advert_type = "PROGRAM"
;

UPDATE ADVERT INNER JOIN PROJECT
	ON ADVERT.id = PROJECT.id
SET ADVERT.advert_type = "PROJECT"
;

ALTER TABLE ADVERT
	MODIFY advert_type VARCHAR(50) NOT NULL
;
