ALTER TABLE ACTION
	ADD COLUMN update_visibility INT(1),
	ADD INDEX (update_visibility)
;

UPDATE ACTION INNER JOIN (
	SELECT ACTION.id AS action_id
	FROM ACTION LEFT JOIN APPLICATION_FORM_ACTION_OPTIONAL
		ON ACTION.id = APPLICATION_FORM_ACTION_OPTIONAL.action_id
	WHERE APPLICATION_FORM_ACTION_OPTIONAL.action_id IS NULL
		OR APPLICATION_FORM_ACTION_OPTIONAL.action_id IN ("WITHDRAW", "COMMENT"))
	AS UPDATE_ACTION
	ON ACTION.id = UPDATE_ACTION.action_id
SET update_visibility = 1
;

UPDATE ACTION
SET update_visibility = 0
WHERE id IN ("COMPLETE_APPLICATION", "ASSIGN_REVIEWERS", "ASSIGN_INTERVIEWERS", 
	"CONFIRM_INTERVIEW_ARRANGEMENTS", "ASSIGN_SUPERVISORS", "PROVIDE_REFERENCE",
	"CONFIRM_OFFER_RECOMMENDATION", "CONFIRM_REJECTION",
	"WITHDRAW")
;
