CREATE TABLE STATE_TRANSITION_TYPE (
	id VARCHAR (50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
	SELECT "COMMITMENT" AS id
		UNION
	SELECT "SUGGESTION" AS id
;

ALTER TABLE STATE_TRANSITION
	ADD COLUMN state_transition_type_id VARCHAR(50),
	ADD INDEX (state_transition_type_id),
	ADD FOREIGN KEY (state_transition_type_id) REFERENCES STATE_TRANSITION_TYPE (id)
;

UPDATE STATE_TRANSITION
SET state_transition_type_id = "COMMITMENT"
;

ALTER TABLE STATE_TRANSITION
	MODIFY COLUMN state_transition_type_id VARCHAR(50) NOT NULL
;
