RENAME TABLE EMAIL_TEMPLATE TO NOTIFICATION_TEMPLATE
;

CREATE TABLE NOTIFICATION_TEMPLATE_TYPE (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
	SELECT name AS id
	FROM NOTIFICATION_TEMPLATE
	GROUP BY name
;

UPDATE NOTIFICATION_TEMPLATE
SET version = "2012-09-30 00:00:00"
WHERE version IS NULL
;

UPDATE NOTIFICATION_TEMPLATE
SET active = 0
WHERE active IS NULL
;

ALTER TABLE NOTIFICATION_TEMPLATE
	CHANGE COLUMN name notification_template_type_id VARCHAR(50) NOT NULL,
	ADD INDEX (notification_template_type_id),
	ADD FOREIGN KEY (notification_template_type_id) REFERENCES NOTIFICATION_TEMPLATE_TYPE (id),
	ADD COLUMN version_number INT(10) UNSIGNED AFTER notification_template_type_id,
	CHANGE COLUMN version version_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFY COLUMN active INT(1) UNSIGNED NOT NULL,
	MODIFY COLUMN content TEXT NOT NULL
;

ALTER TABLE NOTIFICATION_TEMPLATE
	DROP COLUMN version_number,
	ADD COLUMN notification_template_id INT(10) UNSIGNED,
	ADD INDEX (notification_template_id),
	ADD FOREIGN KEY (notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id),
	DROP INDEX name_version,
	CHANGE COLUMN version_timestamp created_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
;

UPDATE NOTIFICATION_TEMPLATE INNER JOIN (
	SELECT id, notification_template_type_id
	FROM NOTIFICATION_TEMPLATE
	WHERE active = 1) AS PRIMARY_VERSION
	ON NOTIFICATION_TEMPLATE.notification_template_type_id =
		PRIMARY_VERSION.notification_template_type_id
SET NOTIFICATION_TEMPLATE.notification_template_id = PRIMARY_VERSION.id
;

ALTER TABLE NOTIFICATION_TEMPLATE
	DROP COLUMN active
;

ALTER TABLE USER
	CHANGE COLUMN user_id parent_user_id INT(10) UNSIGNED
;

ALTER TABLE NOTIFICATION_TEMPLATE
	MODIFY COLUMN subject VARCHAR(255) NOT NULL,
	DROP FOREIGN KEY notification_template_ibfk_2,
	CHANGE COLUMN notification_template_id parent_notification_template_id INT(10) UNSIGNED,
	ADD FOREIGN KEY (parent_notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id)
;

CREATE TABLE PROGRAM_NOTIFICATION_TEMPLATE (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	program_id INT(10) UNSIGNED NOT NULL,
	notification_template_type_id VARCHAR(50) NOT NULL,
	content TEXT NOT NULL,
	created_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	subject VARCHAR(250) NOT NULL,
	parent_program_notification_template_id INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (id),
	INDEX (program_id),
	INDEX	(notification_template_type_id),
	INDEX (parent_program_notification_template_id),
	FOREIGN KEY (program_id) REFERENCES PROGRAM (id),
	FOREIGN KEY (notification_template_type_id) REFERENCES NOTIFICATION_TEMPLATE_TYPE (id),
	FOREIGN KEY (parent_program_notification_template_id) REFERENCES PROGRAM_NOTIFICATION_TEMPLATE (id)
) ENGINE = INNODB
	SELECT NULL AS id, PROGRAM.id AS program_id, 
		NOTIFICATION_TEMPLATE.notification_template_type_id AS notification_template_type_id,
		NOTIFICATION_TEMPLATE.content AS content, 
		NOTIFICATION_TEMPLATE.created_timestamp AS created_timestamp, 
		NOTIFICATION_TEMPLATE.subject AS subject
	FROM PROGRAM INNER JOIN NOTIFICATION_TEMPLATE
	WHERE NOTIFICATION_TEMPLATE.id = NOTIFICATION_TEMPLATE.parent_notification_template_id
;

UPDATE PROGRAM_NOTIFICATION_TEMPLATE
SET parent_program_notification_template_id = id
;

UPDATE STATE_TRANSITION
SET state_id = CONCAT("APPLICATION_", state_id)
;

CREATE TABLE PROGRAM_STATE_TRANSITION (
	program_id INT(10) UNSIGNED NOT NULL,
	action_id VARCHAR(100) NOT NULL,
	state_id VARCHAR(50) NOT NULL,
	display_order INT(1) UNSIGNED NULL DEFAULT NULL,
	state_transition_type_id VARCHAR(50) NOT NULL,
	PRIMARY KEY (program_id, action_id, state_id),
	INDEX (action_id),
	INDEX (state_id),
	INDEX (display_order),
	INDEX state_transition_type_id (state_transition_type_id),
	FOREIGN KEY (program_id) REFERENCES PROGRAM (id),
	FOREIGN KEY (action_id) REFERENCES ACTION (id),
	FOREIGN KEY (state_id) REFERENCES STATE (id),
	FOREIGN KEY (state_transition_type_id) REFERENCES STATE_TRANSITION_TYPE (id)
) ENGINE = INNODB
	SELECT PROGRAM.id AS program_id, STATE_TRANSITION.action_id AS action_id,
		STATE_TRANSITION.state_id, STATE_TRANSITION.display_order,
		STATE_TRANSITION.state_transition_type_id
	FROM PROGRAM INNER JOIN STATE_TRANSITION
;

RENAME TABLE STUDY_OPTION TO PROGRAM_STUDY_OPTION
;

ALTER TABLE APPLICATION_PROGRAM_DETAIL
	CHANGE COLUMN study_option_id program_study_option_id VARCHAR(50) NOT NULL
;

ALTER TABLE PROGRAM_INSTANCE
	CHANGE COLUMN study_option_id program_study_option_id VARCHAR(50) NOT NULL
;

CREATE TABLE SYSTEM_CONFIGURATION (
	id VARCHAR(50) NOT NULL,
	value INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
	SELECT "APPLICATION_EXPORT_ENABLED" AS id, 1 AS value
		UNION
	SELECT "APPLICATION_EXPORT_BATCH_SIZE" AS id, 50 AS value
		UNION
	SELECT "APPLICATION_PROCESSING_BUFFER_DURATION" AS id, 2419200 AS value
		UNION
	SELECT "APPLICATION_ACTION_EXPIRY_DURATION" AS id, 4838400 AS value
;

DROP TABLE THROTTLE
;

DROP TABLE NOTIFICATIONS_DURATION
;

DROP TABLE INSTITUTION_REFERENCE
;

RENAME TABLE COUNTRIES TO COUNTRY
;

ALTER TABLE APPLICATION_PERSONAL_DETAIL
	CHANGE COLUMN country_id country_id INT(10) UNSIGNED NOT NULL
;

RENAME TABLE LANGUAGE TO NATIONALITY
;

ALTER TABLE APPLICATION_PERSONAL_DETAIL
	DROP FOREIGN KEY APPLICATION_FORM_PERSONAL_DETAIL_ibfk_1,
	CHANGE COLUMN first_nationality nationality_id1 INT(10) UNSIGNED NOT NULL,
	ADD FOREIGN KEY (nationality_id1) REFERENCES NATIONALITY (id),
	DROP FOREIGN KEY APPLICATION_FORM_PERSONAL_DETAIL_ibfk_2,
	CHANGE COLUMN second_nationality nationality_id2 INT(10) UNSIGNED,
	ADD FOREIGN KEY (nationality_id2) REFERENCES NATIONALITY (id)
;
