ALTER TABLE APPLICATION_ACTION_OPTIONAL
	ADD INDEX (role_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (role_id, state_id, action_id)
;

ALTER TABLE APPLICATION_ACTION_OPTIONAL
	DROP INDEX role_id
;

ALTER TABLE APPLICATION_USER_ROLE
	ADD INDEX (application_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (application_id, user_id, role_id)
;

ALTER TABLE APPLICATION_USER_ROLE
	DROP INDEX application_id
;

ALTER TABLE APPLICATION_ACTION_REQUIRED
	ADD INDEX (application_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD COLUMN application_user_role_id INT(10) UNSIGNED AFTER id,
	ADD INDEX (application_user_role_id),
	ADD FOREIGN KEY (application_user_role_id) REFERENCES APPLICATION_USER_ROLE (id)
;

UPDATE APPLICATION_USER_ROLE INNER JOIN APPLICATION_ACTION_REQUIRED
	ON APPLICATION_USER_ROLE.application_id = APPLICATION_ACTION_REQUIRED.application_id
	AND APPLICATION_USER_ROLE.user_id = APPLICATION_ACTION_REQUIRED.user_id
	AND APPLICATION_USER_ROLE.role_id = APPLICATION_ACTION_REQUIRED.role_id
SET APPLICATION_ACTION_REQUIRED.application_user_role_id = APPLICATION_USER_ROLE.id
;

ALTER TABLE APPLICATION_ACTION_REQUIRED
	MODIFY COLUMN application_user_role_id INT(10) UNSIGNED NOT NULL,
	DROP FOREIGN KEY application_action_required_ibfk_1,
	DROP COLUMN application_id,
	DROP FOREIGN KEY fk_application_action_required_user_id,
	DROP COLUMN user_id,
	DROP FOREIGN KEY application_action_required_ibfk_3,
	DROP COLUMN role_id
;

ALTER TABLE APPLICATION_UPDATE
	ADD INDEX (application_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (application_id, update_scope_id)
;

ALTER TABLE APPLICATION_UPDATE
	DROP INDEX application_id
;

ALTER TABLE APPLICATION_USER_ROLE
	ADD INDEX (user_id),
	ADD INDEX (role_id),
	DROP INDEX application_form_id_2,
	DROP INDEX registered_user_id,
	DROP INDEX registered_user_id_2,
	DROP INDEX application_role_id,
	DROP INDEX application_role_id_2,
	ADD INDEX (is_interested_in_applicant),
	ADD INDEX (raises_urgent_flag)
;

ALTER TABLE APPLICATION_UPDATE_VIEW
	ADD INDEX (application_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD COLUMN application_update_id INT(10) UNSIGNED AFTER id,
	ADD INDEX (application_update_id),
	ADD FOREIGN KEY (application_update_id) REFERENCES APPLICATION_UPDATE (id)
;

UPDATE APPLICATION_UPDATE INNER JOIN APPLICATION_UPDATE_VIEW
	ON APPLICATION_UPDATE.application_id = APPLICATION_UPDATE_VIEW.application_id
	AND APPLICATION_UPDATE.update_scope_id = APPLICATION_UPDATE_VIEW.update_scope_id
SET APPLICATION_UPDATE_VIEW.application_update_id = APPLICATION_UPDATE.id
;

ALTER TABLE APPLICATION_UPDATE_VIEW
	DROP FOREIGN KEY application_update_view_ibfk_1,
	DROP COLUMN application_id,
	DROP FOREIGN KEY application_update_view_ibfk_2,
	DROP COLUMN update_scope_id
;

ALTER TABLE APPLICATION_UPDATE_VIEW
	ADD UNIQUE INDEX (application_update_id, user_id),
	DROP INDEX application_update_id
;

ALTER TABLE APPLICATION_ACTION_REQUIRED
	ADD UNIQUE INDEX (application_user_role_id, action_id),
	DROP INDEX application_user_role_id
;

ALTER TABLE INSTITUTION_USER_ROLE
	ADD INDEX (institution_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (institution_id, user_id, role_id)
;

ALTER TABLE INSTITUTION_USER_ROLE
	DROP INDEX institution_id
;

ALTER TABLE INSTITUTION_USER_ROLE
	ADD INDEX (user_id),
	ADD INDEX (role_id),
	DROP INDEX registered_user_id,
	DROP INDEX registered_user_id_2,
	DROP INDEX application_role_id,
	DROP INDEX application_role_id_2,
	DROP INDEX institution_id_2
;

ALTER TABLE PROGRAM_USER_ROLE
	ADD INDEX (program_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (program_id, user_id, role_id)
;

ALTER TABLE PROGRAM_USER_ROLE
	DROP INDEX program_id
;

ALTER TABLE PROGRAM_USER_ROLE
	ADD INDEX (user_id),
	ADD INDEX (role_id),
	DROP INDEX registered_user_id,
	DROP INDEX registered_user_id_2,
	DROP INDEX application_role_id,
	DROP INDEX application_role_id_2,
	DROP INDEX program_id_2
;

ALTER TABLE PROJECT_USER_ROLE
	ADD INDEX (project_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (project_id, user_id, role_id)
;

ALTER TABLE PROJECT_USER_ROLE
	DROP INDEX project_id
;

ALTER TABLE PROJECT_USER_ROLE
	ADD INDEX (user_id),
	ADD INDEX (role_id),
	DROP INDEX registered_user_id,
	DROP INDEX registered_user_id_2,
	DROP INDEX application_role_id,
	DROP INDEX application_role_id_2,
	DROP INDEX project_id_2
;

ALTER TABLE SYSTEM_USER_ROLE
	ADD INDEX (user_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (user_id, role_id)
;

ALTER TABLE SYSTEM_USER_ROLE
	ADD INDEX (role_id),
	DROP INDEX application_role_id
;

ALTER TABLE SYSTEM_USER_ROLE
	DROP INDEX user_id
;

ALTER TABLE PROGRAM_STATE_DURATION
	ADD INDEX (program_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (program_id, state_id)
;

ALTER TABLE PROGRAM_STATE_DURATION
	DROP INDEX program_id
;

ALTER TABLE PROGRAM_STATE_TRANSITION
	ADD INDEX (program_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (program_id, action_id, state_id)
;

ALTER TABLE PROGRAM_STATE_TRANSITION
	DROP INDEX program_id
;

ALTER TABLE STATE_TRANSITION
	ADD INDEX (action_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (action_id, state_id)
;

ALTER TABLE STATE_TRANSITION
	DROP INDEX action_id
;

ALTER TABLE USER_INSTITUTION_IDENTITY
	ADD INDEX (user_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (user_id, institution_id, user_identity_type_id)
;

ALTER TABLE USER_INSTITUTION_IDENTITY
	DROP INDEX user_id
;

ALTER TABLE USER_BATCH_NOTIFICATION
	ADD INDEX (user_id),
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	CHANGE COLUMN application_role_scope_id scope_id VARCHAR(50) NOT NULL,
	ADD UNIQUE INDEX (user_id, scope_id, notification_purpose_id)
;

ALTER TABLE USER_BATCH_NOTIFICATION
	DROP INDEX user_id
;

RENAME TABLE PROGRAM_FEED TO PROGRAM_IMPORT
;

ALTER TABLE PROGRAM
	CHANGE COLUMN feed_id program_import_id INT(10) UNSIGNED
;

RENAME TABLE RESEARCH_OPPORTUNITIES_FEED TO PROGRAM_EXPORT
;

CREATE TABLE PROGRAM_EXPORT_FORMAT (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
;

INSERT INTO PROGRAM_EXPORT_FORMAT
VALUES ("LARGE"),
	("SMALL")
;

ALTER TABLE PROGRAM_EXPORT
	CHANGE COLUMN feed_format program_export_format_id VARCHAR(50) NOT NULL,
	ADD INDEX (program_export_format_id),
	ADD FOREIGN KEY (program_export_format_id) REFERENCES PROGRAM_EXPORT_FORMAT (id)
;

ALTER TABLE PROGRAM_EXPORT
	ADD UNIQUE INDEX (user_id, title),
	DROP INDEX registered_user_feed_fk_idx
;

CREATE TABLE PROGRAM_EXPORT_PROGRAM (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	program_export_id INT(10) UNSIGNED NOT NULL,
	program_id INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	INDEX (program_export_id),
	INDEX (program_id),
	FOREIGN KEY (program_export_id) REFERENCES PROGRAM_EXPORT (id),
	FOREIGN KEY (program_id) REFERENCES PROGRAM (id)
) ENGINE = INNODB
	SELECT NULL AS id, feed_id AS program_export_id, program_id
	FROM RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK
;

DROP TABLE RESEARCH_OPPORTUNITIES_FEED_PROGRAM_LINK
;

