ALTER TABLE SYSTEM_USER_ROLE
	ADD COLUMN requesting_user_id INT(10) UNSIGNED,
	ADD COLUMN assigned_timestamp DATETIME
;

UPDATE SYSTEM_USER_ROLE
SET requesting_user_id = id,
	assigned_timestamp = "2012-09-30 00:00:00"
;

ALTER TABLE SYSTEM_USER_ROLE
	MODIFY COLUMN requesting_user_id INT(10) UNSIGNED NOT NULL,
	MODIFY COLUMN assigned_timestamp DATETIME NOT NULL
;

ALTER TABLE INSTITUTION_USER_ROLE
	ADD COLUMN requesting_user_id INT(10) UNSIGNED,
	ADD COLUMN assigned_timestamp DATETIME
;

UPDATE INSTITUTION_USER_ROLE
SET requesting_user_id = (
	SELECT MIN(user_id)
	FROM SYSTEM_USER_ROLE),
	assigned_timestamp = "2013-09-30 00:00:00"
;

ALTER TABLE INSTITUTION_USER_ROLE
	MODIFY COLUMN requesting_user_id INT(10) UNSIGNED NOT NULL,
	MODIFY COLUMN assigned_timestamp DATETIME NOT NULL
;

ALTER TABLE PROGRAM_USER_ROLE
	ADD COLUMN requesting_user_id INT(10) UNSIGNED,
	ADD COLUMN assigned_timestamp DATETIME
;

UPDATE PROGRAM_USER_ROLE
SET PROGRAM_USER_ROLE.requesting_user_id = (
	SELECT MIN(user_id)
	FROM SYSTEM_USER_ROLE),
	assigned_timestamp = (
		SELECT MIN(start_date)
		FROM PROGRAM_INSTANCE
		WHERE PROGRAM_INSTANCE.program_id = PROGRAM_USER_ROLE.program_id)
;

ALTER TABLE PROGRAM_USER_ROLE
	MODIFY COLUMN requesting_user_id INT(10) UNSIGNED NOT NULL,
	MODIFY COLUMN assigned_timestamp DATETIME NOT NULL
;

ALTER TABLE PROJECT_USER_ROLE
	ADD COLUMN requesting_user_id INT(10) UNSIGNED,
	ADD COLUMN assigned_timestamp DATETIME
;

UPDATE PROJECT_USER_ROLE
SET PROJECT_USER_ROLE.requesting_user_id = (
	SELECT ADVERT.user_id
	FROM PROJECT INNER JOIN ADVERT
		ON PROJECT.id = ADVERT.id
	WHERE PROJECT.id = PROJECT_USER_ROLE.project_id),
	assigned_timestamp = (
		SELECT MIN(APPLICATION_USER_ROLE.assigned_timestamp)
		FROM APPLICATION_USER_ROLE INNER JOIN APPLICATION
			ON APPLICATION_USER_ROLE.application_id = APPLICATION.id
		WHERE APPLICATION.project_id = PROJECT_USER_ROLE.project_id)
;

UPDATE PROJECT_USER_ROLE
SET assigned_timestamp = "2013-12-31 00:00:00"
WHERE assigned_timestamp IS NULL
;

ALTER TABLE PROJECT_USER_ROLE
	MODIFY COLUMN requesting_user_id INT(10) UNSIGNED NOT NULL,
	MODIFY COLUMN assigned_timestamp DATETIME NOT NULL
;

ALTER TABLE APPLICATION_USER_ROLE
	ADD COLUMN requesting_user_id INT(10) UNSIGNED AFTER raises_urgent_flag
;

UPDATE APPLICATION_USER_ROLE INNER JOIN APPLICATION
	ON APPLICATION_USER_ROLE.application_id = APPLICATION.id
SET APPLICATION_USER_ROLE.requesting_user_id = APPLICATION.user_id
WHERE APPLICATION_USER_ROLE.role_id 
	IN ("APPLICATION_REFEREE", "APPLICATION_SUGGESTED_SUPERVISOR")
;

UPDATE APPLICATION_USER_ROLE INNER JOIN APPLICATION
	ON APPLICATION_USER_ROLE.application_id = APPLICATION.id
INNER JOIN (
	SELECT MIN(user_id) AS user_id,
		program_id AS program_id
	FROM PROGRAM_USER_ROLE
	WHERE role_id = "PROGRAM_ADMINISTRATOR"
	GROUP BY program_id) AS PROGRAM_ADMINSTRATOR
	ON APPLICATION.program_id = PROGRAM_ADMINSTRATOR.program_id
SET APPLICATION_USER_ROLE.requesting_user_id = PROGRAM_ADMINSTRATOR.user_id
WHERE APPLICATION_USER_ROLE.requesting_user_id IS NULL
	AND APPLICATION.project_id IS NULL
;

UPDATE APPLICATION_USER_ROLE INNER JOIN APPLICATION
	ON APPLICATION_USER_ROLE.application_id = APPLICATION.id
INNER JOIN (
	SELECT MIN(user_id) AS user_id,
		project_id AS project_id
	FROM PROJECT_USER_ROLE
	WHERE role_id = "PROJECT_ADMINISTRATOR"
	GROUP BY project_id) AS PROJECT_ADMINSTRATOR
	ON APPLICATION.project_id = PROJECT_ADMINSTRATOR.project_id
SET APPLICATION_USER_ROLE.requesting_user_id = PROJECT_ADMINSTRATOR.user_id
WHERE APPLICATION_USER_ROLE.requesting_user_id IS NULL
;

UPDATE APPLICATION_USER_ROLE INNER JOIN APPLICATION
	ON APPLICATION_USER_ROLE.application_id = APPLICATION.id
INNER JOIN (
	SELECT MIN(user_id) AS user_id,
		program_id AS program_id
	FROM PROGRAM_USER_ROLE
	WHERE role_id = "PROGRAM_ADMINISTRATOR"
	GROUP BY program_id) AS PROGRAM_ADMINSTRATOR
	ON APPLICATION.program_id = PROGRAM_ADMINSTRATOR.program_id
SET APPLICATION_USER_ROLE.requesting_user_id = PROGRAM_ADMINSTRATOR.user_id
WHERE APPLICATION_USER_ROLE.requesting_user_id IS NULL
;

UPDATE APPLICATION_USER_ROLE
SET is_interested_in_applicant = NULL
WHERE role_id IN ("APPLICATION_APPLICANT", "APPLICATION_REFEREE")
;

UPDATE APPLICATION_USER_ROLE
SET requesting_user_id = (
	SELECT MIN(user_id)
	FROM SYSTEM_USER_ROLE)
WHERE requesting_user_id IS NULL
;

ALTER TABLE APPLICATION_USER_ROLE
	MODIFY COLUMN requesting_user_id INT(10) UNSIGNED NOT NULL
;

DROP TABLE PENDING_ROLE_NOTIFICATION
;
