DROP TABLE SYSTEM_ACTION_OPTIONAL
;

DROP TABLE SYSTEM_USER_ROLE
;

DROP TABLE INSTITUTION_ACTION_OPTIONAL
;

DROP TABLE INSTITUTION_USER_ROLE
;

DROP TABLE PROGRAM_ACTION_OPTIONAL
;

DROP TABLE PROGRAM_ACTION_REQUIRED
;

DROP TABLE PROGRAM_USER_ROLE
;

DROP TABLE PROJECT_ACTION_OPTIONAL
;

DROP TABLE PROJECT_USER_ROLE
;

ALTER TABLE APPLICATION
	ADD INDEX (created_timestamp),
	ADD INDEX (submitted_timestamp),
	ADD COLUMN display_range_timestamp DATE,
	ADD INDEX (display_range_timestamp)
;

UPDATE APPLICATION
SET display_range_timestamp = DATE(created_timestamp)
;

UPDATE APPLICATION
SET display_range_timestamp = DATE(submitted_timestamp)
WHERE submitted_timestamp IS NOT NULL
;

ALTER TABLE APPLICATION
	MODIFY COLUMN display_range_timestamp DATE NOT NULL
;

RENAME TABLE APPLICATION_ACTION_OPTIONAL TO ACTION_OPTIONAL
;

RENAME TABLE APPLICATION_ACTION_REQUIRED TO ACTION_REQUIRED
;

ALTER TABLE STATE
	DROP COLUMN is_completed,
	DROP COLUMN is_modifiable,
	DROP COLUMN is_submitted,
	DROP COLUMN is_under_consideration
;

UPDATE STATE
SET duration = 0
WHERE duration IS NULL
;

ALTER TABLE STATE
	CHANGE duration completion_duration INT(10) UNSIGNED NOT NULL
;

INSERT INTO STATE
	SELECT "PROGRAM_APPROVAL", "PROGRAM", 0
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM", 0
		UNION
	SELECT "PROGRAM_REJECTED", "PROGRAM", 0
		UNION
	SELECT "PROGRAM_DEACTIVATED", "PROGRAM", 0
		UNION
	SELECT "PROGRAM_DISABLED", "PROGRAM", 0
		UNION
	SELECT "PROJECT_APPROVED", "PROJECT", 0
		UNION
	SELECT "PROJECT_DEACTIVATED", "PROJECT", 0
		UNION
	SELECT "PROJECT_DISABLED", "PROJECT", 0
		UNION
	SELECT "INSTITUTION_APPROVED", "INSTITUTION", 0
		UNION
	SELECT "SYSTEM_APPROVED", "SYSTEM", 0
; 

INSERT INTO ACTION_TYPE
	SELECT "PROGRAM_COMPLETE_APPROVAL_STAGE", "PROGRAM"
		UNION
	SELECT "PROGRAM_CONFIGURE", "PROGRAM"
		UNION
	SELECT "PROGRAM_EMAIL_APPLICANT", "PROGRAM"
		UNION
	SELECT "SYSTEM_CONFIGURE", "SYSTEM"
		UNION
	SELECT "INSTITUTION_CONFIGURE", "INSTITUTION"
		UNION
	SELECT "PROJECT_CONFIGURE", "PROJECT"
		UNION
	SELECT "PROGRAM_CREATE_PROJECT", "PROGRAM"
;

ALTER TABLE ACTION_TYPE
	DROP FOREIGN KEY action_type_ibfk_1,
	DROP COLUMN scope_id
;

ALTER TABLE ACTION
	DROP FOREIGN KEY action_ibfk_4,
	DROP COLUMN scope_id
;

ALTER TABLE ROLE
	DROP FOREIGN KEY role_ibfk_1,
	DROP COLUMN scope_id
;

ALTER TABLE STATE
	DROP FOREIGN KEY state_ibfk_1,
	DROP COLUMN scope_id
;

INSERT INTO NOTIFICATION_PURPOSE
	SELECT "APPLICATION_TASK"
		UNION
	SELECT "APPLICATION_UPDATE"
		UNION
	SELECT "PROGRAM_TASK"
;

UPDATE USER_BATCH_NOTIFICATION
SET notification_purpose_id = CONCAT(scope_id, "_", notification_purpose_id)
;

DELETE FROM NOTIFICATION_PURPOSE
WHERE id IN ("TASK", "UPDATE")
;

ALTER TABLE USER_BATCH_NOTIFICATION
	DROP FOREIGN KEY user_batch_notification_ibfk_2,
	DROP COLUMN scope_id
;

DROP TABLE SCOPE
;

INSERT INTO SYSTEM_CONFIGURATION
	SELECT "APPLICATION_TASK_REMINDER_FREQUENCY", 259200
		UNION
	SELECT "PROGRAM_TASK_REMINDER_FREQUENCY", 259200
		UNION
	SELECT "REFERENCE_REQUEST_REMINDER_FREQUENCY", 604800
		UNION
	SELECT "INTERVIEW_AVAILABILITY_REQUEST_REMINDER_FREQUENCY", 86400
;

DROP TABLE REMINDER_INTERVAL
;

INSERT INTO STATE_TRANSITION (action_id, state_id, display_order, state_transition_type_id)
	SELECT "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPLICATION_ADMINISTRATOR", STATE_TRANSITION.state_id, 
		STATE_TRANSITION.display_order, STATE_TRANSITION.state_transition_type_id
	FROM STATE_TRANSITION
	WHERE action_id = "APPLICATION_COMPLETE_REVIEW_STAGE_AS_APPLICATION_ADMINISTRATOR"
;


INSERT INTO STATE_TRANSITION (action_id, state_id, display_order, state_transition_type_id)
	SELECT "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_PROGRAM_ADMINISTRATOR", STATE_TRANSITION.state_id, 
		STATE_TRANSITION.display_order, STATE_TRANSITION.state_transition_type_id
	FROM STATE_TRANSITION
	WHERE action_id = "APPLICATION_COMPLETE_REVIEW_STAGE_AS_PROGRAM_ADMINISTRATOR"
;


INSERT INTO STATE_TRANSITION (action_id, state_id, display_order, state_transition_type_id)
	SELECT "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_PROGRAM_APPROVER", STATE_TRANSITION.state_id, 
		STATE_TRANSITION.display_order, STATE_TRANSITION.state_transition_type_id
	FROM STATE_TRANSITION
	WHERE action_id = "APPLICATION_COMPLETE_REVIEW_STAGE_AS_PROGRAM_ADMINISTRATOR"
;

INSERT INTO STATE_TRANSITION (action_id, state_id, display_order, state_transition_type_id)
VALUES ("APPLICATION_COMPLETE_APPROVAL_STAGE_AS_PROGRAM_APPROVER", "APPLICATION_APPROVED", 3, "COMMITMENT")
;

UPDATE STATE_TRANSITION
SET display_order = 4
WHERE action_id = "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_PROGRAM_APPROVER"
	AND state_id = "APPLICATION_REJECTED"
;

INSERT INTO ACTION
	SELECT id, id, 0, NULL, "INTERNAL"
	FROM ACTION_TYPE
	WHERE id NOT LIKE "APPLICATION%"
;

UPDATE ACTION
SET notification_method_id = "INDIVIDUAL"
WHERE id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
;
