ALTER TABLE APPLICATION_REFEREE
	ADD COLUMN comment_id INT(10) UNSIGNED,
	ADD INDEX (comment_id),
	ADD FOREIGN KEY (comment_id) REFERENCES COMMENT (id)
;

UPDATE APPLICATION_REFEREE INNER JOIN REFERENCE_COMMENT
	ON APPLICATION_REFEREE.id = REFERENCE_COMMENT.referee_id
SET APPLICATION_REFEREE.comment_id = REFERENCE_COMMENT.id
;

ALTER TABLE USER
	ADD COLUMN first_name_2 VARCHAR(30) AFTER first_name,
	ADD COLUMN first_name_3 VARCHAR(30) AFTER first_name_2
;

UPDATE USER INNER JOIN USER_ACCOUNT
	ON USER.user_account_id = USER_ACCOUNT.id
SET USER.first_name_2 = USER_ACCOUNT.first_name_2,
	USER.first_name_3 = USER_ACCOUNT.first_name_3
;

ALTER TABLE USER_ACCOUNT
	DROP COLUMN first_name_2,
	DROP COLUMN first_name_3
;
