DROP TABLE ACTION_OPTIONAL
;

UPDATE ACTION
SET id = REPLACE(id, "APPLICANT", "CREATOR")
;

CREATE TABLE STATE_ACTION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_id VARCHAR(50) NOT NULL,
	action_id VARCHAR(100) NOT NULL,
	raises_urgent_flag INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_id, action_id, raises_urgent_flag),
	INDEX (action_id),
	INDEX (raises_urgent_flag),
	FOREIGN KEY (state_id) REFERENCES STATE (id),
	FOREIGN KEY (action_id) REFERENCES ACTION (id)
) ENGINE = INNODB
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_COMPLETE_APPLICATION", 0
		UNION
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_WITHDRAW", 0
		UNION
	SELECT "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPLICATION", 1
		UNION
	SELECT "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 1
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_VALIDATION", "APPLICATION_ASSESS_ELIGIBILITY", 1
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_CONFIRM_ELIGIBILITY", 1
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_COMPLETE_VALIDATION_STAGE", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_COMPLETE_VALIDATION_STAGE", 1
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REVIEW", "APPLICATION_ASSIGN_REVIEWERS", 1
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR", 1
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER", 1
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_WITHDRAW", 0
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_VIEW_AS_REFEREE", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_COMPLETE_REVIEW_STAGE", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REVIEW", 1
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_COMPLETE_REVIEW_STAGE", 1
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REVIEW", 1
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_ASSIGN_INTERVIEWERS", 1
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR", 1
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER", 1
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVAL", "APPLICATION_ASSIGN_SUPERVISORS", 1
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR", 1
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER", 1
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_ADMINISTRATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION", 1
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_ADMINISTRATOR", 1
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER", 1
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION", 1
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVED", "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR", 1
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER", 1
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_CORRECT_APPLICATION", 1
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REJECTED", "APPLICATION_CONFIRM_REJECTION", 1
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR", 1
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER", 1
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_PROVIDE_REFERENCE", 1
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_RECRUITER", 0
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_WITHDRAW", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_CORRECT_APPLICATION", 1
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_CORRECT_APPLICATION", 1
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_REFEREE", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_COMMENT", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_EMAIL_CREATOR", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_CREATOR", 0
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "PROJECT_APPROVED", "PROJECT_CONFIGURE", 0
		UNION
	SELECT "PROJECT_DEACTIVATED", "PROJECT_CONFIGURE", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "PROGRAM_APPROVAL", "PROGRAM_COMPLETE_APPROVAL_STAGE", 1
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_CONFIGURE", 0
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_CREATE_PROJECT", 0
		UNION
	SELECT "PROGRAM_DEACTIVATED", "PROGRAM_CREATE_PROJECT", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "INSTITUTION_APPROVED", "INSTITUTION_CONFIGURE", 0
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
	SELECT "SYSTEM_APPROVED", "SYSTEM_CONFIGURE", 0
;

CREATE TABLE STATE_ACTION_ASSIGNMENT (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED,
	role_id VARCHAR(50) NOT NULL,
	notification_template_id VARCHAR(100),
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, role_id),
	INDEX (role_id),
	INDEX (notification_template_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id)
) ENGINE = INNODB
;

CREATE TABLE STATE_ACTION_NOTIFICATION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED,
	role_id VARCHAR(50) NOT NULL,
	notification_template_id VARCHAR(100),
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, role_id),
	INDEX (role_id),
	INDEX (notification_template_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id)
) ENGINE = INNODB
;

ALTER TABLE ROLE
	DROP COLUMN do_send_update_notification
;

INSERT INTO ROLE (id)
VALUES ("INSTITUTION_ADMINISTRATOR")
;

INSERT INTO USER_ROLE (institution_id, user_id, role_id, requesting_user_id)
VALUES (5243, 1024, "INSTITUTION_ADMINISTRATOR", 1024)
;

UPDATE USER_ROLE
SET requesting_user_id = 1024
WHERE system_id IS NOT NULL
;

ALTER TABLE USER
	DROP COLUMN is_system_user
;
