DROP TABLE ACTION_OPTIONAL
;

UPDATE ACTION
SET id = REPLACE(id, "APPLICANT", "CREATOR")
;

CREATE TABLE STATE_ACTION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_id VARCHAR(50) NOT NULL,
	action_id VARCHAR(100) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_id, action_id),
	INDEX (action_id),
	FOREIGN KEY (state_id) REFERENCES STATE (id),
	FOREIGN KEY (action_id) REFERENCES ACTION (id)
) ENGINE = INNODB
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_COMPLETE_APPLICATION"
		UNION
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_WITHDRAW"
		UNION
	SELECT "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPLICATION"
		UNION
	SELECT "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", "APPLICATION_WITHDRAW"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_VALIDATION", "APPLICATION_ASSESS_ELIGIBILITY"
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_CONFIRM_ELIGIBILITY"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_COMPLETE_VALIDATION_STAGE"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REVIEW", "APPLICATION_ASSIGN_REVIEWERS"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_COMPLETE_REVIEW_STAGE"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REVIEW"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_COMPLETE_REVIEW_STAGE"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REVIEW"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_ASSIGN_INTERVIEWERS"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVAL", "APPLICATION_ASSIGN_SUPERVISORS"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_WITHDRAW"	
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_WITHDRAW"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVED", "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_WITHDRAW"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_CORRECT_APPLICATION"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REJECTED", "APPLICATION_CONFIRM_REJECTION"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_PROVIDE_REFERENCE"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_RECRUITER"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_WITHDRAW"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_CORRECT_APPLICATION"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_CORRECT_APPLICATION"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_REFEREE"
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_COMMENT"
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_EMAIL_CREATOR"
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_CREATOR"
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "PROJECT_APPROVED", "PROJECT_CONFIGURE"
		UNION
	SELECT "PROJECT_DEACTIVATED", "PROJECT_CONFIGURE"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "PROGRAM_APPROVAL", "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_CONFIGURE"
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_CREATE_PROJECT"
		UNION
	SELECT "PROGRAM_DEACTIVATED", "PROGRAM_CREATE_PROJECT"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "INSTITUTION_APPROVED", "INSTITUTION_CONFIGURE"
;

INSERT INTO STATE_ACTION (state_id, action_id)
	SELECT "SYSTEM_APPROVED", "SYSTEM_CONFIGURE"
;

CREATE TABLE STATE_ACTION_PERMISSION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED,
	role_id VARCHAR(50) NOT NULL,
	raises_urgent_flag INT(1) UNSIGNED NOT NULL,
	notification_template_id VARCHAR(100),
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, role_id),
	INDEX (role_id),
	INDEX (raises_urgent_flag),
	INDEX (notification_template_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id)
) ENGINE = INNODB
;

CREATE TABLE STATE_ACTION_NOTIFICATION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED,
	role_id VARCHAR(50) NOT NULL,
	notification_template_id VARCHAR(100),
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, role_id),
	INDEX (role_id),
	INDEX (notification_template_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id)
) ENGINE = INNODB
;
