DROP TABLE ACTION_OPTIONAL
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ACTION_TYPE
SET id = REPLACE(id, "APPLICANT", "CREATOR")
;

UPDATE ACTION
SET action_type_id = REPLACE(action_type_id, "APPLICANT", "CREATOR")
;

SET FOREIGN_KEY_CHECKS = 1
;

UPDATE ACTION
SET id = REPLACE(id, "APPLICANT", "CREATOR")
;

DELETE FROM STATE_TRANSITION
WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
;

DELETE FROM ACTION
WHERE id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
;

DELETE ROLE_TRANSITION.*
FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
	ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
WHERE STATE_TRANSITION.action_id = "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER"
;

DELETE FROM STATE_TRANSITION
WHERE action_id = "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER"
;

DELETE FROM ACTION
WHERE id = "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER"
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ACTION
SET id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
WHERE id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
;

UPDATE STATE_TRANSITION
SET action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
;

UPDATE ACTION
SET id = "APPLICATION_COMPLETE_APPROVAL_STAGE"
WHERE id = "APPLICATION_COMPLETE_APPROVAL_STAGE_AS_ADMINISTRATOR"
;

UPDATE STATE_TRANSITION
SET action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
;


UPDATE ACTION
SET id = "APPLICATION_COMPLETE"
WHERE id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE ACTION
SET id = "APPLICATION_CORRECT"
WHERE id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE STATE_TRANSITION
SET action_id = "APPLICATION_COMPLETE"
WHERE action_id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE STATE_TRANSITION
SET action_id = "APPLICATION_CORRECT"
WHERE action_id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE USER
SET action_id = "APPLICATION_COMPLETE"
WHERE action_id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE USER
SET action_id = "APPLICATION_CORRECT"
WHERE action_id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE NOTIFICATION_TEMPLATE
SET id = "APPLICATION_COMPLETE_NOTIFICATION"
WHERE id = "APPLICATION_COMPLETE_APPLICATION_NOTIFICATION"
;

UPDATE NOTIFICATION_TEMPLATE_VERSION
SET notification_template_id = "APPLICATION_COMPLETE_NOTIFICATION"
WHERE notification_template_id = "APPLICATION_COMPLETE_APPLICATION_NOTIFICATION"
;

SET FOREIGN_KEY_CHECKS = 1
;

INSERT INTO NOTIFICATION_TEMPLATE (id, notification_type_id)
VALUES ("APPLICATION_COMPLETE_REQUEST", "INDIVIDUAL"),
	("APPLICATION_COMPLETE_REQUEST_REMINDER", "INDIVIDUAL")
;

UPDATE NOTIFICATION_TEMPLATE
SET reminder_notification_template_id = "APPLICATION_COMPLETE_REQUEST_REMINDER",
	reminder_interval = 604800
WHERE id = "APPLICATION_COMPLETE_REQUEST"
;

ALTER TABLE NOTIFICATION_TEMPLATE_VERSION
	MODIFY subject VARCHAR(255) NOT NULL AFTER notification_template_id
;

INSERT INTO NOTIFICATION_TEMPLATE_VERSION (notification_template_id, subject, content)
VALUES ("APPLICATION_COMPLETE_REQUEST", "Application %1$s for UCL %2$s - Pending Completion", 
	"To be completed."),
	("APPLICATION_COMPLETE_REQUEST_REMINDER", 
	"REMINDER: Application %1$s for UCL %2$s - Pending Completion", "To be completed.")
;

UPDATE NOTIFICATION_TEMPLATE INNER JOIN NOTIFICATION_TEMPLATE_VERSION
	ON NOTIFICATION_TEMPLATE.id = NOTIFICATION_TEMPLATE_VERSION.notification_template_id
SET NOTIFICATION_TEMPLATE.notification_template_version_id = NOTIFICATION_TEMPLATE_VERSION.id
WHERE NOTIFICATION_TEMPLATE.notification_template_version_id IS NULL
;

INSERT INTO ACTION_TYPE (id)
VALUES ("APPLICATION_ESCALATE"),
	("PROJECT_ESCALATE"),
	("PROGRAM_ESCALATE")
;

INSERT INTO ACTION (id, action_type_id, precedence)
VALUES ("APPLICATION_ESCALATE", "APPLICATION_ESCALATE", 0),
	("PROJECT_ESCALATE", "PROJECT_ESCALATE", 0),
	("PROGRAM_ESCALATE", "PROGRAM_ESCALATE", 0)	
;

UPDATE STATE
SET parent_state_id = REPLACE(parent_state_id, "DEACTIVATED", "APPROVED")
;

INSERT INTO STATE (id, parent_state_id)
VALUES ("PROGRAM_DISABLED_PENDING_COMPLETION", "PROGRAM_DISABLED"),
	("PROGRAM_DISABLED_COMPLETED", "PROGRAM_DISABLED"),
	("PROJECT_DISABLED_PENDING_COMPLETION", "PROJECT_DISABLED"),
	("PROJECT_DISABLED_COMPLETED", "PROJECT_DISABLED")
;

UPDATE ADVERT
SET state_id = REPLACE(state_id, "DISABLED", "DISABLED_COMPLETED")
;

INSERT INTO STATE_DURATION (system_id, state_id, expiry_duration)
VALUES (1, "PROGRAM_DISABLED_PENDING_COMPLETION", 2419200),
	(1, "PROJECT_DISABLED_PENDING_COMPLETION", 2419200),
	(1, "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", 2149200),
	(1, "APPLICATION_VALIDATION_PENDING_FEEDBACK", 259200)
;

INSERT INTO STATE_DURATION (institution_id, state_id, expiry_duration)
VALUES (5243, "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", 2149200),
	(5243, "APPLICATION_VALIDATION_PENDING_FEEDBACK", 259200)
;

INSERT INTO STATE_DURATION (program_id, state_id, expiry_duration)
	SELECT id, "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", 2419200
	FROM PROGRAM
;

INSERT INTO STATE_DURATION (program_id, state_id, expiry_duration)
	SELECT id, "APPLICATION_VALIDATION_PENDING_FEEDBACK", 259200
	FROM PROGRAM
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE NOTIFICATION_TEMPLATE_VERSION
SET notification_template_id = "APPLICATION_CORRECT_REQUEST"
WHERE notification_template_id = "APPLICATION_EXPORT_ERROR_NOTIFICATION"
;

UPDATE NOTIFICATION_TEMPLATE
SET id = "APPLICATION_CORRECT_REQUEST"
WHERE id = "APPLICATION_EXPORT_ERROR_NOTIFICATION"
;

SET FOREIGN_KEY_CHECKS = 1
;

UPDATE APPLICATION INNER JOIN STATE
	ON APPLICATION.state_id = STATE.id
INNER JOIN COMMENT
	ON APPLICATION.id = COMMENT.application_form_id
INNER JOIN VALIDATION_COMMENT
	ON COMMENT.id = VALIDATION_COMMENT.id
INNER JOIN COMMENT AS COMMENT2
	ON APPLICATION.id = COMMENT2.application_form_id
LEFT JOIN ADMITTER_COMMENT
	ON COMMENT2.id = ADMITTER_COMMENT.id
SET APPLICATION.due_date = DATE(submitted_timestamp) + INTERVAL 259200 SECOND,
	APPLICATION.state_id = "APPLICATION_VALIDATION_PENDING_FEEDBACK"
WHERE ("UNSURE" IN (VALIDATION_COMMENT.qualified_for_phd,
		VALIDATION_COMMENT.english_compentency_ok,
		VALIDATION_COMMENT.home_or_overseas)
		AND ADMITTER_COMMENT.id IS NULL
		AND CURRENT_DATE() < APPLICATION.submitted_timestamp + INTERVAL 4838400 SECOND)
		AND (STATE.parent_state_id IN ("APPLICATION_REVIEW", 
			"APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
			OR STATE.id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED"))
;

UPDATE APPLICATION
SET state_id = "APPLICATION_VALIDATION_PENDING_COMPLETION"
WHERE state_id LIKE "APPLICATION_VALIDATION%"
	AND due_date < CURRENT_DATE()
;

INSERT INTO STATE (id, parent_state_id)
VALUES ("PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_DISABLED"),
	("PROJECT_DISABLED_PENDING_REACTIVATION", "PROJECT_DISABLED")
;

INSERT INTO NOTIFICATION_TEMPLATE (id, notification_type_id)
VALUES ("PROJECT_TASK_REQUEST", "SYNDICATED")
;

INSERT INTO NOTIFICATION_TEMPLATE_VERSION (notification_template_id, subject, content)
	SELECT "PROJECT_TASK_REQUEST", REPLACE(subject, "Programmes", "Projects"), content
	FROM NOTIFICATION_TEMPLATE_VERSION INNER JOIN NOTIFICATION_TEMPLATE
		ON NOTIFICATION_TEMPLATE.notification_template_version_id = NOTIFICATION_TEMPLATE_VERSION.id
	WHERE NOTIFICATION_TEMPLATE.id = "PROGRAM_TASK_REQUEST"
;

UPDATE NOTIFICATION_TEMPLATE
SET notification_template_version_id = LAST_INSERT_ID()
WHERE id = "PROJECT_TASK_REQUEST"
;

INSERT INTO NOTIFICATION_TEMPLATE (id, notification_type_id)
VALUES ("PROJECT_TASK_REQUEST_REMINDER", "SYNDICATED")
;

INSERT INTO NOTIFICATION_TEMPLATE_VERSION (notification_template_id, subject, content)
	SELECT "PROJECT_TASK_REQUEST_REMINDER", REPLACE(subject, "Programmes", "Projects"), content
	FROM NOTIFICATION_TEMPLATE_VERSION INNER JOIN NOTIFICATION_TEMPLATE
		ON NOTIFICATION_TEMPLATE.notification_template_version_id = NOTIFICATION_TEMPLATE_VERSION.id
	WHERE NOTIFICATION_TEMPLATE.id = "PROGRAM_TASK_REQUEST_REMINDER"
;

UPDATE NOTIFICATION_TEMPLATE
SET notification_template_version_id = LAST_INSERT_ID()
WHERE id = "PROJECT_TASK_REQUEST_REMINDER"
;

UPDATE NOTIFICATION_TEMPLATE
SET reminder_notification_template_id = "PROJECT_TASK_REQUEST_REMINDER",
	reminder_interval = 259200
WHERE id = "PROJECT_TASK_REQUEST"
;

CREATE TABLE STATE_ACTION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_id VARCHAR(50) NOT NULL,
	action_id VARCHAR(100) NOT NULL,
	raises_urgent_flag INT(1) UNSIGNED NOT NULL,
	notification_template_id VARCHAR(100),
	PRIMARY KEY (id),
	UNIQUE INDEX (state_id, action_id, raises_urgent_flag, notification_template_id),
	INDEX (action_id),
	INDEX (notification_template_id),
	INDEX (raises_urgent_flag),
	FOREIGN KEY (state_id) REFERENCES STATE (id),
	FOREIGN KEY (action_id) REFERENCES ACTION (id),
	FOREIGN KEY (notification_template_id) REFERENCES NOTIFICATION_TEMPLATE (id)
) ENGINE = INNODB
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_COMPLETE", 0, NULL
		UNION
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_UNSUBMITTED", "APPLICATION_ESCALATE", 0, NULL
		UNION
	SELECT "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", "APPLICATION_COMPLETE", 1, "APPLICATION_COMPLETE_REQUEST"
		UNION
	SELECT "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_VALIDATION", "APPLICATION_ASSESS_ELIGIBILITY", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION", "APPLICATION_WITHDRAW", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_CONFIRM_ELIGIBILITY", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_COMPLETE_VALIDATION_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_COMPLETE_VALIDATION_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_VALIDATION_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0, NULL	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REVIEW", "APPLICATION_ASSIGN_REVIEWERS", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_COMPLETE_REVIEW_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REVIEW", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_FEEDBACK", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_COMPLETE_REVIEW_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REVIEW", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_REVIEW_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0, NULL	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_ASSIGN_INTERVIEWERS", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_MOVE_TO_DIFFERENT_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW", "APPLICATION_WITHDRAW", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY", 1, "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY", 1, "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_COMPLETE_INTERVIEW_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_INTERVIEW_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0, NULL	
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVAL", "APPLICATION_ASSIGN_SUPERVISORS", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_MOVE_TO_DIFFERENT_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_EDIT_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL", "APPLICATION_EDIT_AS_ADMINISTRATOR", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMPLETE_APPROVAL_STAGE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_WITHDRAW", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_ESCALATE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMPLETE_APPROVAL_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_CONFIRM_PRIMARY_SUPERVISION", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVAL_PENDING_COMPLETION", "APPLICATION_WITHDRAW", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVED", "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED", "APPLICATION_WITHDRAW", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_EXPORT", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_CORRECT", 1, "APPLICATION_CORRECT_REQUEST"
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_APPROVED_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REJECTED", "APPLICATION_CONFIRM_REJECTION", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_MOVE_TO_DIFFERENT_STAGE", 1, "APPLICATION_TASK_REQUEST"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_PROVIDE_REFERENCE", 1, "APPLICATION_PROVIDE_REFERENCE_REQUEST"
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED", "APPLICATION_WITHDRAW", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_EXPORT", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_CORRECT", 1, "APPLICATION_CORRECT_REQUEST"
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_REJECTED_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_EXPORT", "APPLICATION_EXPORT", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_CORRECT", 1, "APPLICATION_CORRECT_REQUEST"
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_REFEREE", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_COMMENT", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_CREATOR", 0, NULL
		UNION
	SELECT "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_VIEW_AS_RECRUITER", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "PROJECT_APPROVED", "PROJECT_CONFIGURE", 0, NULL
		UNION
	SELECT "PROJECT_APPROVED", "PROJECT_ESCALATE", 0, NULL
		UNION
	SELECT "PROJECT_DEACTIVATED", "PROJECT_CONFIGURE", 0, NULL
		UNION
	SELECT "PROJECT_DEACTIVATED", "PROJECT_ESCALATE", 0, NULL
		UNION
	SELECT "PROJECT_DISABLED_PENDING_COMPLETION", "PROJECT_ESCALATE", 0, NULL
		UNION
	SELECT "PROJECT_DISABLED_PENDING_REACTIVATION", "PROJECT_ESCALATE", 0, NULL
		UNION
	SELECT "PROJECT_DISABLED_PENDING_REACTIVATION", "PROJECT_CONFIGURE", 1, "PROJECT_TASK_REQUEST"
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "PROGRAM_APPROVAL", "PROGRAM_COMPLETE_APPROVAL_STAGE", 1, "PROGRAM_TASK_REQUEST"
		UNION
	SELECT "PROGRAM_APPROVAL", "PROGRAM_EMAIL_CREATOR", 0, NULL
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_CONFIGURE", 0, NULL
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_CREATE_PROJECT", 0, NULL
		UNION
	SELECT "PROGRAM_APPROVED", "PROGRAM_ESCALATE", 0, NULL
		UNION
	SELECT "PROGRAM_DEACTIVATED", "PROGRAM_CONFIGURE", 0, NULL
		UNION
	SELECT "PROGRAM_DEACTIVATED", "PROGRAM_CREATE_PROJECT", 0, NULL
		UNION
	SELECT "PROGRAM_DEACTIVATED", "PROGRAM_ESCALATE", 0, NULL
		UNION
	SELECT "PROGRAM_DISABLED_PENDING_COMPLETION", "PROGRAM_ESCALATE", 0, NULL
		UNION
	SELECT "PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_ESCALATE", 0, NULL
		UNION
	SELECT "PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_CONFIGURE", 1, "PROGRAM_TASK_REQUEST"
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "INSTITUTION_APPROVED", "INSTITUTION_CONFIGURE", 0, NULL
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag, notification_template_id)
	SELECT "SYSTEM_APPROVED", "SYSTEM_CONFIGURE", 0, NULL
;
