DELETE FROM STATE_TRANSITION
WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
;

DELETE FROM STATE_ACTION
WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
;

DELETE FROM ACTION
WHERE id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_APPROVER"
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE STATE_ACTION
SET action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
;

UPDATE ACTION
SET id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
WHERE id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE_AS_ADMINISTRATOR"
;

SET FOREIGN_KEY_CHECKS = 1
;

UPDATE STATE
SET parent_state_id = REPLACE(parent_state_id, "DEACTIVATED", "APPROVED")
;

INSERT INTO STATE (id, parent_state_id)
VALUES ("PROGRAM_DISABLED_PENDING_RESUMPTION", "PROGRAM_DISABLED"),
	("PROGRAM_DISABLED_PENDING_COMPLETION", "PROGRAM_DISABLED"),
	("PROGRAM_DISABLED_COMPLETED", "PROGRAM_DISABLED"),
	("PROJECT_DISABLED_PENDING_RESUMPTION", "PROJECT_DISABLED"),
	("PROJECT_DISABLED_PENDING_COMPLETION", "PROJECT_DISABLED"),
	("PROJECT_DISABLED_COMPLETED", "PROJECT_DISABLED")
;

UPDATE ADVERT
SET state_id = REPLACE(state_id, "DISABLED", "DISABLED_COMPLETED")
;

INSERT INTO STATE_DURATION (system_id, state_id, expiry_duration)
VALUES (1, "PROGRAM_DISABLED_PENDING_RESUMPTION", 2419200),
	(1, "PROGRAM_DISABLED_PENDING_COMPLETION", 2419200),
	(1, "PROJECT_DISABLED_PENDING_RESUMPTION", 2419200),
	(1, "PROJECT_DISABLED_PENDING_COMPLETION", 2419200)
;

INSERT INTO STATE_DURATION (institution_id, state_id, expiry_duration)
VALUES (5243, "PROGRAM_DISABLED_PENDING_RESUMPTION", 2419200),
	(5243, "PROGRAM_DISABLED_PENDING_COMPLETION", 2419200),
	(5243, "PROJECT_DISABLED_PENDING_RESUMPTION", 2419200),
	(5243, "PROJECT_DISABLED_PENDING_COMPLETION", 2419200)
;

INSERT INTO STATE_DURATION (program_id, state_id, expiry_duration)
	SELECT PROGRAM.id, STATE.id, 2419200
	FROM PROGRAM INNER JOIN STATE
	WHERE STATE.id IN ("PROGRAM_DISABLED_PENDING_RESUMPTION", 
		"PROGRAM_DISABLED_PENDING_COMPLETION", "PROJECT_DISABLED_PENDING_RESUMPTION",
		"PROJECT_DISABLED_PENDING_COMPLETION")
;

UPDATE STATE_TRANSITION
SET STATE_TRANSITION.state_id = "PROGRAM_DISABLED_PENDING_RESUMPTION"
WHERE state_id = "PROGRAM_DISABLED"
	AND state_transition_type_id = "DUE_DATE_EXPIRY"
;

UPDATE STATE_TRANSITION
SET STATE_TRANSITION.state_id = "PROGRAM_DISABLED_PENDING_COMPLETION"
WHERE state_id = "PROGRAM_DISABLED"
	AND state_transition_type_id = "ONE_COMPLETED"
;

UPDATE STATE_TRANSITION
SET STATE_TRANSITION.state_id = "PROJECT_DISABLED_PENDING_RESUMPTION"
WHERE state_id = "PROJECT_DISABLED"
	AND state_transition_type_id = "DUE_DATE_EXPIRY"
;

UPDATE STATE_TRANSITION
SET STATE_TRANSITION.state_id = "PROJECT_DISABLED_PENDING_COMPLETION"
WHERE state_id = "PROJECT_DISABLED"
	AND state_transition_type_id = "ONE_COMPLETED"
;

DROP TABLE STATE_TRANSITION_PROPAGATION
;

CREATE TABLE STATE_TRANSITION_PROPAGATION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	trigger_state_id VARCHAR(50) NOT NULL,
	current_state_id VARCHAR(50) NULL DEFAULT NULL,
	amended_state_id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX state_id (trigger_state_id, current_state_id, amended_state_id),
	INDEX (current_state_id),
	INDEX (amended_state_id),
	FOREIGN KEY (trigger_state_id) REFERENCES STATE (id),
	FOREIGN KEY (current_state_id) REFERENCES STATE (id),
	FOREIGN KEY (amended_state_id) REFERENCES STATE (id)
) ENGINE = INNODB
;

INSERT INTO STATE_TRANSITION_PROPAGATION
	SELECT NULL, "PROGRAM_DISABLED_PENDING_COMPLETION", id, "PROJECT_DISABLED_PENDING_COMPLETION"
	FROM STATE
	WHERE id IN ("PROJECT_APPROVED", "PROJECT_DEACTIVATED")
		UNION
	SELECT NULL, "PROGRAM_DISABLED_COMPLETED", id, "PROJECT_DISABLED_COMPLETED"
	FROM STATE
	WHERE id IN ("PROJECT_DISABLED_PENDING_RESUMPTION", "PROJECT_DISABLED_PENDING_COMPLETION")
		UNION
	SELECT NULL, "PROGRAM_DISABLED_COMPLETED", id, "APPLICATION_REJECTED"
	FROM STATE
	WHERE id LIKE "APPLICATION%"
		AND id NOT LIKE "%UNSUBMITTED%"
		AND	id NOT LIKE "%WITHDRAWN%"
		AND	id NOT LIKE "%APPROVED%"
		AND id NOT LIKE "%REJECTED%"
		UNION
	SELECT NULL, "PROGRAM_DISABLED_COMPLETED", id, "APPLICATION_REJECTED"
	FROM STATE
	WHERE id LIKE "APPLICATION%"
		AND id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		UNION
	SELECT NULL, "PROGRAM_DISABLED_COMPLETED", id, "APPLICATION_WITHDRAWN"
	FROM STATE
	WHERE id LIKE "APPLICATION%"
		AND id LIKE "APPLICATION_UNSUBMITTED%"
		UNION
	SELECT NULL, "PROJECT_DISABLED_COMPLETED", id, "APPLICATION_REJECTED"
	FROM STATE
	WHERE id LIKE "APPLICATION%"
		AND id NOT LIKE "%UNSUBMITTED%"
		AND	id NOT LIKE "%WITHDRAWN%"
		AND	id NOT LIKE "%APPROVED%"
		AND id NOT LIKE "%REJECTED%"	
		UNION
	SELECT NULL, "PROJECT_DISABLED_COMPLETED", id, "APPLICATION_REJECTED"
	FROM STATE
	WHERE id LIKE "APPLICATION%"
		AND id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")	
		UNION
	SELECT NULL, "PROJECT_DISABLED_COMPLETED", id, "APPLICATION_WITHDRAWN"
	FROM STATE
	WHERE id LIKE "APPLICATION%"
		AND id LIKE "APPLICATION_UNSUBMITTED%"
		UNION
	SELECT NULL, "PROGRAM_DISABLED_PENDING_RESUMPTION", id, "PROJECT_DISABLED_PENDING_RESUMPTION"
	FROM STATE
	WHERE id IN ("PROJECT_APPROVED", "PROJECT_DEACTIVATED")
		UNION
	SELECT NULL, "PROGRAM_APPROVED", "PROJECT_DISABLED_PENDING_RESUMPTION", "PROJECT_APPROVED"
;

SET FOREIGN_KEY_CHECKS = 0
;

DELETE FROM STATE
WHERE id = "INSTITUTION_DISABLED"
;

SET FOREIGN_KEY_CHECKS = 1
;

ALTER TABLE PROGRAM
	DROP COLUMN locked
;

ALTER TABLE ADVERT
	ADD COLUMN due_date DATE,
	ADD INDEX (due_date)
;

UPDATE ADVERT INNER JOIN (
	SELECT PROGRAM_INSTANCE.program_id AS program_id, 
		MAX(PROGRAM_INSTANCE.disabled_date) AS due_date
	FROM PROGRAM_INSTANCE
	WHERE PROGRAM_INSTANCE.identifier = "CUSTOM"
	GROUP BY PROGRAM_INSTANCE.program_id) AS PROGRAM_DUE_DATE
	ON ADVERT.id = PROGRAM_DUE_DATE.program_id
SET ADVERT.due_date = PROGRAM_DUE_DATE.due_date
;

UPDATE ADVERT INNER JOIN PROJECT
	ON ADVERT.id = PROJECT.program_id
INNER JOIN ADVERT AS PROJECT_ADVERT
	ON PROJECT.id = PROJECT_ADVERT.id
SET PROJECT_ADVERT.due_date = ADVERT.due_date
;

UPDATE ADVERT INNER JOIN ADVERT_CLOSING_DATE
	ON ADVERT.advert_closing_date_id = ADVERT_CLOSING_DATE.id
SET ADVERT.due_date = ADVERT_CLOSING_DATE.closing_date
WHERE ADVERT.advert_type = "PROJECT"
	AND ADVERT.due_date IS NULL
	OR ADVERT.due_date > ADVERT_CLOSING_DATE.closing_date
;

UPDATE ADVERT
SET due_date = NULL
WHERE state_id LIKE "%DISABLED_COMPLETED"
;

DELETE FROM SYSTEM_CONFIGURATION
WHERE id = "APPLICATION_PROCESSING_BUFFER_DURATION"
;

UPDATE SYSTEM_CONFIGURATION
SET id = "ACTION_EXPIRY_DURATION"
WHERE id = "APPLICATION_ACTION_EXPIRY_DURATION"
;

UPDATE STATE_TRANSITION
SET display_order = 0
WHERE state_id LIKE "%DISABLED_PENDING_COMPLETION"
;

UPDATE STATE_TRANSITION
SET display_order = 2
WHERE action_id = "PROGRAM_CONFIGURE"
	AND state_id = "PROGRAM_DEACTIVATED"
;

UPDATE STATE_TRANSITION
SET display_order = 3
WHERE action_id = "PROGRAM_CONFIGURE"
	AND state_id = "PROGRAM_DISABLED_PENDING_COMPLETION"
;

INSERT INTO STATE_TRANSITION (action_id, state_id, state_transition_type_id, display_order)
VALUES ("PROGRAM_CONFIGURE", "PROGRAM_APPROVED", "ONE_COMPLETED", 0),
	("PROGRAM_CONFIGURE", "PROGRAM_APPROVAL", "ONE_COMPLETED", 1),
	("PROGRAM_CONFIGURE", "PROGRAM_DISABLED_COMPLETED", "DUE_DATE_EXPIRY", 1)
;

UPDATE STATE_TRANSITION
SET display_order = 1
WHERE action_id = "PROJECT_CONFIGURE"
	AND state_id = "PROJECT_DISABLED_PENDING_COMPLETION"
;

INSERT INTO STATE_ACTION (state_id, action_id, raises_urgent_flag)
VALUES ("PROGRAM_DISABLED_PENDING_RESUMPTION", "PROGRAM_CONFIGURE", 1)
;
