SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ACTION_TYPE
SET id = "APPLICATION_COMPLETE"
WHERE id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE ACTION_TYPE
SET id = "APPLICATION_CORRECT"
WHERE id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE ACTION
SET id = "APPLICATION_COMPLETE",
	action_type_id = "APPLICATION_COMPLETE"
WHERE action_type_id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE ACTION
SET id = "APPLICATION_CORRECT",
	action_type_id = "APPLICATION_CORRECT"
WHERE action_type_id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE STATE_TRANSITION
SET action_id = "APPLICATION_COMPLETE"
WHERE action_id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE STATE_TRANSITION
SET action_id = "APPLICATION_CORRECT"
WHERE action_id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE USER
SET action_id = "APPLICATION_COMPLETE"
WHERE action_id = "APPLICATION_COMPLETE_APPLICATION"
;

UPDATE USER
SET action_id = "APPLICATION_CORRECT"
WHERE action_id = "APPLICATION_CORRECT_APPLICATION"
;

UPDATE ACTION_TYPE
SET id = REPLACE(id, "APPLICANT", "CREATOR")
;

UPDATE ACTION
SET action_type_id = REPLACE(action_type_id, "APPLICANT", "CREATOR")
;

SET FOREIGN_KEY_CHECKS = 1
;

DELETE 
FROM ROLE
WHERE id = "PROGRAM_PRACTITIONER"
;

/* Application creator actions */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, id, "APPLICATION_CREATOR", NULL
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_UNSUBMITTED"
		UNION
	SELECT NULL, id, "APPLICATION_CREATOR", "APPLICATION_COMPLETE_APPLICATION_REQUEST"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_UNSUBMITTED_PENDING_COMPLETION"
		UNION
	SELECT NULL, id, "APPLICATION_CREATOR", NULL
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_EDIT_AS_CREATOR",
		"APPLICATION_VIEW_AS_CREATOR", "APPLICATION_WITHDRAW")
		AND state_id NOT LIKE "%UNSUBMITTED%"
;

/* Application administrator actions */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR")
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROJECT_ADMINISTRATOR", "APPLICATION_ADMINISTRATOR")
		AND STATE.parent_state_id != "APPLICATION_UNSUBMITTED"
;

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_VIEW_AS_RECRUITER"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROJECT_ADMINISTRATOR", "APPLICATION_ADMINISTRATOR")
		AND STATE.parent_state_id IN ("APPLICATION_VALIDATION", 
			"APPLICATION_APPROVAL", "APPLICATION_APPROVED",
			"APPLICATION_REJECTED", "APPLICATION_WITHDRAWN")
;

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_EDIT_AS_ADMINISTRATOR"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROJECT_ADMINISTRATOR", "APPLICATION_ADMINISTRATOR")
		AND STATE.parent_state_id IN ("REVIEW", "INTERVIEW")
;

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, "APPLICATION_TASK_REQUEST"
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id IN ("APPLICATION_ASSESS_ELIGIBILITY", 
		"APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_ASSIGN_REVIEWERS", 
		"APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_ASSIGN_INTERVIEWERS",
		"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_ASSIGN_SUPERVISORS",
		"APPLICATION_COMPLETE_APPROVAL_STAGE_AS_ADMINISTRATOR", 
		"APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 
		"APPLICATION_CONFIRM_REJECTION", "APPLICATION_MOVE_TO_DIFFERENT_STAGE")
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROJECT_ADMINISTRATOR", "APPLICATION_ADMINISTRATOR")
;

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, id, "INSTITUTION_ADMINISTRATOR", 
		"APPLICATION_TASK_REQUEST"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CORRECT"
;

/* Application approver actions */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "PROGRAM_APPROVER", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER",
		"APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPROVER", 
		"APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 
		"APPLICATION_CONFIRM_REJECTION")
		AND STATE.parent_state_id != "APPLICATION_UNSUBMITTED"
;

/* Application admitter actions */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "INSTITUTION_ADMITTER", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER",
		"APPLICATION_CONFIRM_ELIGIBILITY", "APPLICATION_CORRECT")
		AND STATE.parent_state_id != "APPLICATION_UNSUBMITTED"
;

/* Application referee action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_REFEREE", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_REFEREE",
		"APPLICATION_PROVIDE_REFERENCE")
		AND STATE.parent_state_id NOT IN ("APPLICATION_UNSUBMITTED",
			"APPLICATION_VALIDATION")
;

/* Application reviewer action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_REVIEWER", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER",
		"APPLICATION_PROVIDE_REVIEW")
		AND STATE.parent_state_id = "APPLICATION_REVIEW"
;

/* Application interviewer action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_INTERVIEWER", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER",
		"APPLICATION_PROVIDE_INTERVIEW_FEEDBACK")
		AND STATE.parent_state_id = "APPLICATION_INTERVIEW"
;

/* Application primary supervisor action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_PRIMARY_SUPERVISOR", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER",
		"APPLICATION_CONFIRM_PRIMARY_SUPERVISION")
		AND STATE.parent_state_id = "APPLICATION_APPROVAL"
;

/* Application secondary supervisor action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_SECONDARY_SUPERVISOR", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER")
		AND STATE.parent_state_id = "APPLICATION_APPROVAL"
;

/* Application viewer (internal) action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_VIEWER_RECRUITER", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_RECRUITER")
		AND STATE.parent_state_id NOT IN ("APPLICATION_UNSUBMITTED",
			"APPLICATION_VALIDATION")
;

/* Application viewer (external) action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, "APPLICATION_VIEWER_REFEREE", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMMENT", 
		"APPLICATION_EMAIL_CREATOR", "APPLICATION_VIEW_AS_REFEREE")
		AND STATE.parent_state_id NOT IN ("APPLICATION_UNSUBMITTED",
			"APPLICATION_VALIDATION")
;

/* System configuration action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, id, "SYSTEM_ADMINISTRATOR", NULL
	FROM STATE_ACTION
	WHERE action_id = "SYSTEM_CONFIGURE"
;

/* Institution configuration action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "INSTITUTION_CONFIGURE"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "INSTITUTION_ADMITTER")
		UNION
	SELECT NULL, id, "INSTITUTION_ADMINISTRATOR", NULL
	FROM STATE_ACTION
	WHERE action_id IN ("PROGRAM_COMPLETE_APPROVAL_STAGE", 
		"PROGRAM_EMAIL_CREATOR")
;

/* Program configuration action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "PROGRAM_CONFIGURE"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR")
;

/* Program creation action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "INSTITUTION_CREATE_PROGRAM"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"INSTITUTION_PROGRAM_CREATOR", "PROGRAM_CREATOR")
;

/* Project configuration action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "PROJECT_CONFIGURE"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROJECT_ADMINISTRATOR")
;

/* Project creation action */

INSERT INTO STATE_ACTION_ASSIGNMENT
	SELECT NULL, STATE_ACTION.id, ROLE.id, NULL
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_PROJECT"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROGRAM_PROJECT_CREATOR")
;
