CREATE TABLE ROLE_TRANSITION_TYPE (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
;

INSERT INTO ROLE_TRANSITION_TYPE (id)
VALUES ("CREATE_ONE"),
	("CREATE_ALL"),
	("REMOVE_ONE"),
	("UPDATE_ONE"),
	("REMOVE_ALL"),
	("UPDATE_ALL")
;

INSERT INTO ROLE (id)
VALUES ("APPLICATION_INTERVIEWEE")
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ROLE
SET id = "APPLICATION_POTENTIAL_INTERVIEWEE"
WHERE id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWEE"
;

UPDATE ROLE
SET id = "APPLICATION_POTENTIAL_INTERVIEWER"
WHERE id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWER"
;

UPDATE ROLE_INHERITANCE
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWEE"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWEE"
;

UPDATE ROLE_INHERITANCE
SET inherited_role_id = "APPLICATION_POTENTIAL_INTERVIEWEE"
WHERE inherited_role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWEE"
;

UPDATE ROLE_INHERITANCE
SET inherited_role_id = "APPLICATION_POTENTIAL_INTERVIEWER"
WHERE inherited_role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWER"
;

UPDATE STATE_ACTION_ASSIGNMENT
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWEE"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWEE"
;

UPDATE STATE_ACTION_ASSIGNMENT
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWER"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWER"
;

UPDATE STATE_ACTION_NOTIFICATION
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWEE"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWEE"
;

UPDATE STATE_ACTION_NOTIFICATION
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWER"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWER"
;

UPDATE USER_ROLE
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWEE"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWEE"
;

UPDATE USER_ROLE
SET role_id = "APPLICATION_POTENTIAL_INTERVIEWER"
WHERE role_id = "APPLICATION_INTERVIEW_PARTICIPANT_INTERVIEWER"
;

SET FOREIGN_KEY_CHECKS = 1
;

INSERT INTO STATE_ACTION_ASSIGNMENT (state_action_id, role_id)
	SELECT STATE_ACTION.id, ROLE.id
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_RETRACT_INTERVIEW_AVAILABILITY"
	AND ROLE.id IN ("APPLICATION_INTERVIEWEE", "APPLICATION_INTERVIEWER")
;

UPDATE APPLICATION
SET due_date = DATE(created_timestamp) + INTERVAL 2419200 SECOND
WHERE state_id = "APPLICATION_UNSUBMITTED"
;

UPDATE APPLICATION
SET state_id = "APPLICATION_UNSUBMITTED_PENDING_COMPLETION"
WHERE state_id = "APPLICATION_UNSUBMITTED"
	AND due_date < CURRENT_DATE()
;
