INSERT INTO USER_ROLE (application_id, user_id, role_id, requesting_user_id, assigned_timestamp)
	SELECT APPLICATION.id, APPLICATION.user_id, "APPLICATION_INTERVIEWEE", ADVERT.user_id, INTERVIEW.created_date
	FROM APPLICATION INNER JOIN ADVERT
		ON APPLICATION.program_id = ADVERT.id
	INNER JOIN INTERVIEW
		ON APPLICATION.latest_interview_id = INTERVIEW.id
	WHERE APPLICATION.state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		AND APPLICATION.project_id IS NULL
;

INSERT INTO USER_ROLE (application_id, user_id, role_id, requesting_user_id, assigned_timestamp)
	SELECT APPLICATION.id, APPLICATION.user_id, "APPLICATION_INTERVIEWEE", ADVERT.user_id, INTERVIEW.created_date
	FROM APPLICATION INNER JOIN ADVERT
		ON APPLICATION.project_id = ADVERT.id
	INNER JOIN INTERVIEW
		ON APPLICATION.latest_interview_id = INTERVIEW.id
	WHERE APPLICATION.state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
;

INSERT IGNORE INTO USER_ROLE (application_id, user_id, role_id, requesting_user_id, assigned_timestamp)
	SELECT APPLICATION.id, SUPERVISOR.user_id, "APPLICATION_SECONDARY_SUPERVISOR", ADVERT.user_id, APPROVAL_ROUND.created_date
	FROM APPLICATION INNER JOIN ADVERT
		ON APPLICATION.program_id = ADVERT.id
	INNER JOIN APPROVAL_ROUND
		ON APPLICATION.latest_approval_round_id = APPROVAL_ROUND.id
	INNER JOIN SUPERVISOR
		ON APPROVAL_ROUND.id = SUPERVISOR.approval_round_id
	INNER JOIN USER_ROLE
		ON APPLICATION.id = USER_ROLE.application_id
		AND USER_ROLE.role_id = "APPLICATION_PRIMARY_SUPERVISOR"
	WHERE APPLICATION.project_id IS NULL
		AND SUPERVISOR.is_primary = 0
		AND APPLICATION.state_id IN ("APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_APPROVAL_PENDING_COMPLETION")
;

INSERT IGNORE INTO USER_ROLE (application_id, user_id, role_id, requesting_user_id, assigned_timestamp)
	SELECT APPLICATION.id, SUPERVISOR.user_id, "APPLICATION_SECONDARY_SUPERVISOR", ADVERT.user_id, APPROVAL_ROUND.created_date
	FROM APPLICATION INNER JOIN ADVERT
		ON APPLICATION.project_id = ADVERT.id
	INNER JOIN APPROVAL_ROUND
		ON APPLICATION.latest_approval_round_id = APPROVAL_ROUND.id
	INNER JOIN SUPERVISOR
		ON APPROVAL_ROUND.id = SUPERVISOR.approval_round_id
	INNER JOIN USER_ROLE
		ON APPLICATION.id = USER_ROLE.application_id
		AND USER_ROLE.role_id = "APPLICATION_PRIMARY_SUPERVISOR"
	WHERE SUPERVISOR.is_primary = 0
		AND APPLICATION.state_id IN ("APPLICATION_APPROVAL_PENDING_FEEDBACK", "APPLICATION_APPROVAL_PENDING_COMPLETION")
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ACTION
SET id = REPLACE(id, "RETRACT", "UPDATE")
;

UPDATE STATE_ACTION
SET action_id = REPLACE(action_id, "RETRACT", "UPDATE")
;

SET FOREIGN_KEY_CHECKS = 1
;

INSERT INTO STATE_ACTION_NOTIFICATION
	SELECT NULL, id, "APPLICATION_ADMINISTRATOR", 
		"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_UPDATE_INTERVIEW_AVAILABILITY"
;

INSERT INTO STATE_ACTION_NOTIFICATION
	SELECT NULL, STATE_ACTION.id, ROLE.id, 
		"APPLICATION_UPDATE_INTERVIEW_AVAILABILITY_NOTIFICATION"
	FROM STATE_ACTION INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_UPDATE_INTERVIEW_AVAILABILITY"
		AND ROLE.id IN ("INSTITUTION_ADMINISTRATOR", "PROGRAM_ADMINISTRATOR", 
			"PROJECT_ADMINISTRATOR")
;

INSERT INTO STATE_ACTION_NOTIFICATION
	SELECT NULL, id, "APPLICATION_INTERVIEWEE", 
		"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION_INTERVIEWEE"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		UNION
	SELECT NULL, id, "APPLICATION_INTERVIEWER", 
		"APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS_NOTIFICATION_INTERVIEWER"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
;

UPDATE APPLICATION
SET state_id = "APPLICATION_WITHDRAWN_COMPLETED"
WHERE state_id = "APPLICATION_WITHDRAWN_UNSUBMITTED"
;

DELETE FROM STATE
WHERE id = "APPLICATION_WITHDRAWN_UNSUBMITTED"
;

UPDATE ADVERT
SET state_id = "PROGRAM_DISABLED"
WHERE state_id = "PROGRAM_DISABLED_PENDING_COMPLETION"
;

UPDATE STATE_ACTION
SET state_id = "PROGRAM_DISABLED"
WHERE state_id = "PROGRAM_DISABLED_PENDING_COMPLETION"
;

UPDATE STATE_DURATION
SET state_id = "PROGRAM_DISABLED"
WHERE state_id = "PROGRAM_DISABLED_PENDING_COMPLETION"
;

UPDATE ADVERT
SET state_id = "PROJECT_DISABLED"
WHERE state_id = "PROJECT_DISABLED_PENDING_COMPLETION"
;

UPDATE STATE_ACTION
SET state_id = "PROJECT_DISABLED"
WHERE state_id = "PROJECT_DISABLED_PENDING_COMPLETION"
;

UPDATE STATE_DURATION
SET state_id = "PROJECT_DISABLED"
WHERE state_id = "PROJECT_DISABLED_PENDING_COMPLETION"
;

DELETE FROM STATE
WHERE id IN ("PROGRAM_DISABLED_PENDING_COMPLETION", "PROJECT_DISABLED_PENDING_COMPLETION")
;

UPDATE APPLICATION
SET state_id = "APPLICATION_WITHDRAWN"
WHERE state_id = "APPLICATION_WITHDRAWN_PENDING_EXPORT"
;

UPDATE STATE_ACTION
SET state_id = "APPLICATION_WITHDRAWN"
WHERE state_id = "APPLICATION_WITHDRAWN_PENDING_EXPORT"
;

DELETE FROM STATE
WHERE id = "APPLICATION_WITHDRAWN_PENDING_EXPORT"
;

CREATE TABLE STATE_TRANSITION_EVALUATION (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
	SELECT "PROJECT_CONFIGURATION_OUTCOME" AS id
		UNION
	SELECT "PROJECT_STATE_REVERSION"
		UNION
	SELECT "PROGRAM_APPROVAL_OUTCOME"
		UNION
	SELECT "PROGRAM_CONFIGURATION_OUTCOME"
		UNION
	SELECT "PROGRAM_STATE_REVERSION_OUTCOME"
		UNION
	SELECT "PROGRAM_EXPIRY_OUTCOME"
		UNION
	SELECT "APPLICATION_STATE_COMPLETION_OUTCOME"
		UNION
	SELECT "APPLICATION_ASSESSMENT_OUTCOME"
		UNION
	SELECT "APPLICATION_EXPORT_REQUIREMENT"
		UNION
	SELECT "APPLICATION_INTERVIEW_SCHEDULING_OUTCOME"
		UNION
	SELECT "APPLICATION_EXPORT_OUTCOME"
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE STATE_ACTION
SET action_id = "APPLICATION_CONFIRM_SUPERVISION"
WHERE action_id = "APPLICATION_CONFIRM_PRIMARY_SUPERVISION"
;

UPDATE ACTION
SET id = "APPLICATION_CONFIRM_SUPERVISION"
WHERE id = "APPLICATION_CONFIRM_PRIMARY_SUPERVISION"
;
	
SET FOREIGN_KEY_CHECKS = 1
;

CREATE TABLE STATE_TRANSITION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED NOT NULL,
	state_transition_type_id VARCHAR(50) NOT NULL,
	transition_state_id VARCHAR(50) NOT NULL,
	state_transition_evaluation_id VARCHAR(50),
	display_order INT(3) UNSIGNED,
	processing_order INT(1) UNSIGNED,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, state_transition_type_id, transition_state_id),
	INDEX (state_action_id),
	INDEX (state_transition_type_id),
	INDEX (transition_state_id),
	INDEX (state_transition_evaluation_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (state_transition_type_id) REFERENCES STATE_TRANSITION_TYPE (id),
	FOREIGN KEY (transition_state_id) REFERENCES STATE (id),
	FOREIGN KEY (state_transition_evaluation_id) REFERENCES STATE_TRANSITION_EVALUATION (id)
) ENGINE = INNODB
;

CREATE TABLE ROLE_TRANSITION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_transition_id INT(10) UNSIGNED NOT NULL,
	role_id VARCHAR(50) NOT NULL,
	role_transition_type_id VARCHAR(50) NOT NULL,
	transition_role_id VARCHAR(50),
	processing_order INT(1) UNSIGNED,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_transition_id, role_id, role_transition_type_id, transition_role_id),
	INDEX (role_id),
	INDEX (role_transition_type_id),
	INDEX (transition_role_id),
	FOREIGN KEY (state_transition_id) REFERENCES STATE_TRANSITION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (role_transition_type_id) REFERENCES ROLE_TRANSITION_TYPE (id),
	FOREIGN KEY (transition_role_id) REFERENCES ROLE (id)
) ENGINE = INNODB
;

/* Application escalate (unsubmitted) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_UNSUBMITTED_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_UNSUBMITTED"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application withdraw */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", "APPLICATION_WITHDRAWN_COMPLETED", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_UNSUBMITTED"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_ACTION.id, "ONE_COMPLETED", TRANSITION_STATE.id, "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN STATE AS TRANSITION_STATE
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND TRANSITION_STATE.id IN ("APPLICATION_WITHDRAWN", "APPLICATION_WITHDRAWN_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND STATE.id IN ("APPLICATION_WITHDRAWN", "APPLICATION_WITHDRAWN_COMPLETED")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_REVIEW"
		AND STATE.id != "APPLICATION_REVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"	
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_INTERVIEW"
		AND STATE.id != "APPLICATION_INTERVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING",
		"APPLICATION_INTERVIEW_PENDING_INTERVIEW")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWER", "APPLICATION_POTENTIAL_INTERVIEWEE")
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE.parent_state_id = "APPLICATION_APPROVAL"
		AND STATE.id != "APPLICATION_APPROVAL"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;
		
/* Application terminate */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT STATE_ACTION.id, "PROPAGATION", "APPLICATION_WITHDRAWN_COMPLETED", NULL
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_UNSUBMITTED"
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", TRANSITION_STATE.id, "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN STATE AS TRANSITION_STATE
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND TRANSITION_STATE.id IN ("APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_REJECTED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE.id IN ("APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_REJECTED_COMPLETED")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_REVIEW"
		AND STATE.id != "APPLICATION_REVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_INTERVIEW"
		AND STATE.id != "APPLICATION_INTERVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING",
		"APPLICATION_INTERVIEW_PENDING_INTERVIEW")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDIGN_SCHEDULING")
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		AND ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWER", "APPLICATION_POTENTIAL_INTERVIEWEE")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_SECONDARY_SUPERVISOR", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE.parent_state_id = "APPLICATION_APPROVAL"
		AND STATE.id != "APPLICATION_APPROVAL"
		AND STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;

/* Application submit */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_VALIDATION"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_COMPLETE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "CREATE_ALL", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "APPEND_ALL", "APPLICATION_VIEWER_REFEREE", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE"
;

/* Application assess eligibility */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_ASSESSMENT_OUTCOME"
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSESS_ELIGIBILITY"
		AND STATE.id IN ("APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_VALIDATION_PENDING_COMPLETION")
;

/* Application confirm eligibility */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_VALIDATION_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_ELIGIBILITY"
;

/* Application complete stage */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, display_order)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 0
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STATE_COMPLETION_OUTCOME", 2
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STATE_COMPLETION_OUTCOME", 3
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STATE_COMPLETION_OUTCOME", 4
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE_ONE", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_VALIDATION_STAGE"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "APPEND_ALL", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_VALIDATION_STAGE"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "REMOVE_ALL", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE_ONE", NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "APPEND_ALL", "APPLICATION_VIEWER_RECRUITER", 2
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "REMOVE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_REVIEW_STAGE"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWEE", "APPLICATION_POTENTIAL_INTERVIEWER", 
			"APPLICATION_INTERVIEWEE", "APPLICATION_INTERVIEWER")	
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")	
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_APPROVAL_STAGE"
;

/* Application move to different stage */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, display_order)
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STATE_COMPLETION_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STATE_COMPLETION_OUTCOME", 2
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STATE_COMPLETION_OUTCOME", 3
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STATE_COMPLETION_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STATE_COMPLETION_OUTCOME", 2
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STATE_COMPLETION_OUTCOME", 3
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STATE_COMPLETION_OUTCOME", 2
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STATE_COMPLETION_OUTCOME", 3
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STATE_COMPLETION_OUTCOME", 2
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STATE_COMPLETION_OUTCOME", 3
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STATE_COMPLETION_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STATE_COMPLETION_OUTCOME", 2
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STATE_COMPLETION_OUTCOME", 3
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
;	

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "REMOVE_ALL", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE_ONE", NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "APPEND_ALL", "APPLICATION_VIEWER_RECRUITER", 2
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE_ONE", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "APPEND_ALL", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
;

/* Application provide reference */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", state_id
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REFERENCE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROVIDE_REFERENCE"
;

/* Application assign reviewers */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW_PENDING_FEEDBACK"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_ASSIGN_REVIEWERS"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "CREATE_ALL", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_REVIEWERS"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "APPEND_ALL", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_REVIEWERS"
;

/* Application provide review */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order)
	SELECT id, "ONE_COMPLETED", state_id, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REVIEW"
		AND state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_REVIEW_PENDING_COMPLETION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REVIEW"
		AND state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REVIEW"
		AND state_id = "APPLICATION_REVIEW_PENDING_COMPLETION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROVIDE_REVIEW"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
;

/* Application escalate (review) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REVIEW_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application assign interviewers */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_INTERVIEW_SCHEDULING_OUTCOME"
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "CREATE_ONE", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "APPEND_ALL", "APPLICATION_POTENTIAL_INTERVIEWEE", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "CREATE_ONE", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "CREATE_ALL", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "APPEND_ALL", "APPLICATION_POTENTIAL_INTERVIEWER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "CREATE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
;

/* Application provide interview availability */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order)
	SELECT id, "ONE_COMPLETED", state_id, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_INTERVIEW_PENDING_SCHEDULING", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
		AND ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWEE", "APPLICATION_POTENTIAL_INTERVIEWER")
;

/* Application escalate (interview scheduling) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application confirm interview arrangements */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_INTERVIEW_SCHEDULING_OUTCOME"
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE.id IN ("APPLICATION_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "REMOVE_ALL", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE_ONE", NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "APPEND_ALL", "APPLICATION_VIEWER_RECRUITER", 2
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWEE", "APPLICATION_POTENTIAL_INTERVIEWER", 
			"APPLICATION_INTERVIEWEE", "APPLICATION_INTERVIEWER")	
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWEE", "APPLICATION_POTENTIAL_INTERVIEWER")	
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id = "APPLICATION_INTERVIEWEE"
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
;

/* Application update interview availability */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_UPDATE_INTERVIEW_AVAILABILITY"
;

/* Application interview taken place */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_ESCALATE"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id = "APPLICATION_INTERVIEWEE"
	WHERE STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_ACTION.state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		AND STATE_TRANSITION.state_transition_type_id = "DUE_DATE_EXPIRY"
;

/* Application provide interview feedback */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order)
	SELECT id, "ONE_COMPLETED", state_id, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_INTERVIEW_PENDING_COMPLETION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_COMPLETION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
;

/* Application escalate (interview) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_COMPLETION"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application assign supervisors */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL_PENDING_FEEDBACK"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_ASSIGN_SUPERVISORS"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order)
	SELECT STATE_TRANSITION.id, ROLE.id, "CREATE_ONE", NULL, 0
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_REVIEWERS"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "APPEND_ONE", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_REVIEWERS"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;

/* Application confirm supervision */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order)
	SELECT id, "ONE_COMPLETED", state_id, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_APPROVAL_PENDING_COMPLETION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND state_id = "APPLICATION_APPROVAL_PENDING_COMPLETION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, ROLE.id, "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;

/* Application escalate (approval) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVAL_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application confirm offer recommendation */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED_COMPLETED", "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
;

/* Application confirm rejection */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_REJECTION"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED_COMPLETED", "APPLICATION_EXPORT_REQUIREMENT"
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_REJECTION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_REJECTION"
;

/* Application approved pending export */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVED_COMPLETED", "APPLICATION_EXPORT_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_EXPORT_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
;

/* Application approved pending correction */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED_PENDING_EXPORT"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVED_PENDING_CORRECTION"
		AND action_id = "APPLICATION_CORRECT"
;

/* Application rejected pending export */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REJECTED_COMPLETED", "APPLICATION_EXPORT_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REJECTED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_EXPORT_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REJECTED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
;

/* Application rejected pending correction */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED_PENDING_EXPORT"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REJECTED_PENDING_CORRECTION"
		AND action_id = "APPLICATION_CORRECT"
;

/* Application withdrawn pending export */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_EXPORT_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_WITHDRAWN"
		AND action_id = "APPLICATION_EXPORT"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_EXPORT_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_WITHDRAWN"
		AND action_id = "APPLICATION_EXPORT"
;

/* Application withdrawn pending correction */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_WITHDRAWN"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_WITHDRAWN_PENDING_CORRECTION"
		AND action_id = "APPLICATION_CORRECT"
;

/* Create program */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL"
	FROM STATE_ACTION
	WHERE state_id = "INSTITUTION_APPROVED"
		AND action_id = "INSTITUTION_CREATE_PROGRAM"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "PROGRAM_ADMINISTRATOR", "CREATE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "INSTITUTION_CREATE_PROGRAM"
;

/* Approve program */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_APPROVAL_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL_PENDING_CORRECTION", "PROGRAM_APPROVAL_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_APPROVAL_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_REJECTED", "PROGRAM_APPROVAL_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
;

/* Edit program application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL"
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_EDIT"
;

/* Withdraw program application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL"
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_WITHDRAWN"
;

/* Program configure */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DEACTIVATED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DISABLED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DISABLED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION	
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DEACTIVATED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DISABLED", "PROGRAM_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
;

/* Program create application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_UNSUBMITTED"
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_CREATE_APPLICATION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "PROGRAM_APPLICATION_CREATOR", "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_APPLICATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_CREATOR", "CREATE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_APPLICATION"
;

/* Program expired */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_EXPIRY_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id IN ("PROGRAM_APPROVED", "PROGRAM_DEACTIVATED")
		AND action_id = "PROGRAM_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION", "PROGRAM_EXPIRY_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id IN ("PROGRAM_APPROVED", "PROGRAM_DEACTIVATED")
		AND action_id = "PROGRAM_ESCALATE"
;

/* Program terminated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_COMPLETED"
	FROM STATE_ACTION
	WHERE state_id IN ("PROGRAM_DISABLED", "PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION")
		AND action_id = "PROGRAM_ESCALATE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "PROGRAM_APPLICATION_CREATOR", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id = "PROGRAM_DISABLED_COMPLETED"
;

/* Program reactivated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "PROPAGATION", "PROGRAM_APPROVED", "PROGRAM_STATE_REVERSION_OUTCOME"
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_REACTIVATE"
		UNION
	SELECT id, "PROPAGATION", "PROGRAM_DEACTIVATED", "PROGRAM_STATE_REVERSION_OUTCOME"
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_REACTIVATE"
;

/* Project configure */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "ONE_COMPLETED", "PROJECT_DEACTIVATED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_APPROVED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DISABLED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_APPROVED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_APPROVED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DEACTIVATED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DISABLED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DEACTIVATED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_APPROVED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DEACTIVATED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DISABLED", "PROJECT_CONFIGURATION_OUTCOME"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
;

/* Project create application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "ONE_COMPLETED", "APPLICATION_UNSUBMITTED"
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_CREATE_APPLICATION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "PROJECT_APPLICATION_CREATOR", "REMOVE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROJECT_CREATE_APPLICATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_CREATOR", "CREATE_ONE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROJECT_CREATE_APPLICATION"
;

/* Project expired */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "PROJECT_DISABLED_PENDING_REACTIVATION"
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_ESCALATE"
		AND state_id IN ("PROJECT_APPROVED", "PROJECT_DEACTIVATED")
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_ESCALATE"
		AND state_id IN ("PROJECT_APPROVED", "PROJECT_DEACTIVATED", "PROJECT_DISABLED_PENDING_REACTIVATION")
;
		
/* Project terminated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_COMPLETED"
	FROM STATE_ACTION
	WHERE state_id IN ("PROJECT_DISABLED", "PROJECT_DISABLED_PENDING_REACTIVATION")
		AND action_id = "PROGRAM_ESCALATE"
		UNION
	SELECT id, "PROPAGATION", "PROGRAM_DISABLED_COMPLETED"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROGRAM_ESCALATE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "PROJECT_APPLICATION_CREATOR", "REMOVE_ALL"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id = "PROJECT_DISABLED_COMPLETED"
;

/* Project reactivated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id)
	SELECT id, "PROPAGATION", "PROJECT_APPROVED", "PROJECT_STATE_REVERSION"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROJECT_REACTIVATE"
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DEACTIVATED", "PROJECT_STATE_REVERSION"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROJECT_REACTIVATE"
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DISABLED_PENDING_REACTIVATION", "PROJECT_STATE_REVERSION"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROJECT_REACTIVATE"
;

CREATE TABLE STATE_TRANSITION_PROPAGATION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_transition_id INT(10) UNSIGNED NOT NULL,
	propagated_state_transition_id INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_transition_id, propagated_state_transition_id),
	INDEX (propagated_state_transition_id),
	FOREIGN KEY (state_transition_id) REFERENCES STATE_TRANSITION (id),
	FOREIGN KEY (propagated_state_transition_id) REFERENCES STATE_TRANSITION (id)
) ENGINE = INNODB
	SELECT NULL AS id, STATE_TRANSITION.id AS state_transition_id, 
		PROPAGATED_STATE_TRANSITION.id AS propagated_state_transition_id
	FROM STATE_TRANSITION INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id IN ("PROGRAM_DISABLED_COMPLETED", "PROJECT_DISABLED_COMPLETED")
		AND PROPAGATED_STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		AND PROPAGATED_STATE_TRANSITION.transition_state_id LIKE "APPLICATION_%"
		UNION
	SELECT NULL AS id, STATE_TRANSITION.id AS state_transition_id, 
		PROPAGATED_STATE_TRANSITION.id AS propagated_state_transition_id
	FROM STATE_TRANSITION INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id IN ("PROGRAM_APPROVED", "PROGRAM_DEACTIVATED")
		AND PROPAGATED_STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		AND PROPAGATED_STATE_TRANSITION.transition_state_id LIKE "PROJECT_%"
		AND PROPAGATED_STATE_TRANSITION.state_transition_evaluation_id = "PROJECT_STATE_REVERSION"
		UNION
	SELECT NULL AS id, STATE_TRANSITION.id AS state_transition_id, 
		PROPAGATED_STATE_TRANSITION.id AS propagated_state_transition_id
	FROM STATE_TRANSITION INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id IN ("PROGRAM_DISABLED_PENDING_REACTIVATION", 
		"PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION")
		AND PROPAGATED_STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		AND PROPAGATED_STATE_TRANSITION.transition_state_id LIKE "PROJECT_%"
		AND PROPAGATED_STATE_TRANSITION.state_transition_evaluation_id = NULL
;
