CREATE TABLE STATE_TRANSITION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED NOT NULL,
	state_transition_type_id VARCHAR(50) NOT NULL,
	transition_state_id VARCHAR(50),
	display_order INT(3) UNSIGNED,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, state_transition_type_id, transition_state_id, display_order),
	INDEX (state_action_id),
	INDEX (state_transition_type_id),
	INDEX (transition_state_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (state_transition_type_id) REFERENCES STATE_TRANSITION_TYPE (id),
	FOREIGN KEY (transition_state_id) REFERENCES STATE (id)
) ENGINE = INNODB
;

CREATE TABLE ROLE_TRANSITION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_transition_id INT(10) UNSIGNED NOT NULL,
	role_id VARCHAR(50) NOT NULL,
	role_transition_type_id VARCHAR(50) NOT NULL,
	transition_role_id VARCHAR(50),
	PRIMARY KEY (id),
	UNIQUE INDEX (state_transition_id, role_id, role_transition_type_id, transition_role_id),
	INDEX (role_id),
	INDEX (role_transition_type_id),
	INDEX (transition_role_id),
	FOREIGN KEY (state_transition_id) REFERENCES STATE_TRANSITION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (role_transition_type_id) REFERENCES ROLE_TRANSITION_TYPE (id),
	FOREIGN KEY (transition_role_id) REFERENCES ROLE (id)
) ENGINE = INNODB
;

UPDATE APPLICATION
SET state_id = "APPLICATION_WITHDRAWN_COMPLETED"
WHERE state_id = "APPLICATION_WITHDRAWN_UNSUBMITTED"
;

DELETE FROM STATE
WHERE id = "APPLICATION_WITHDRAWN_UNSUBMITTED"
;

/* Due date expiry */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_UNSUBMITTED_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_UNSUBMITTED"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_WITHDRAWN_COMPLETED"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_UNSUBMITTED_PENDING_COMPLETION"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REVIEW_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVAL_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_COMPLETED"
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_COMPLETION"
		AND action_id = "PROGRAM_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "PROJECT_DISABLED_PENDING_COMPLETION"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_APPROVED"
		AND action_id = "PROJECT_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "PROJECT_DISABLED_COMPLETED"
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_COMPLETION"
		AND action_id = "PROJECT_ESCALATE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWEE", "REMOVE", NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.state_id = "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_COMPLETION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "REMOVE", NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.state_id = "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_COMPLETION"
		UNION
	SELECT id, "APPLICATION_INTERVIEWEE", "REMOVE", NULL
	FROM STATE_TRANSITION
	WHERE transition_state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
;

/* Single User Action Completed */

/* Group User Action Completed */
