CREATE TABLE STATE_TRANSITION_EVALUATION (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
	SELECT "PROJECT_CONFIGURED_OUTCOME" AS id
		UNION
	SELECT "PROJECT_REACTIVATED_OUTCOME"
		UNION
	SELECT "PROGRAM_APPROVED_OUTCOME"
		UNION
	SELECT "PROGRAM_CONFIGURED_OUTCOME"
		UNION
	SELECT "PROGRAM_REACTIVATED_OUTCOME"
		UNION
	SELECT "PROGRAM_CREATED_OUTCOME"
		UNION
	SELECT "PROGRAM_EXPIRED_OUTCOME"
		UNION
	SELECT "APPLICATION_STAGE_COMPLETED_OUTCOME"
		UNION
	SELECT "APPLICATION_ELIGIBILITY_ASSESSED_OUTCOME"
		UNION
	SELECT "APPLICATION_PROCESSING_COMPLETED_OUTCOME"
		UNION
	SELECT "APPLICATION_INTERVIEW_SCHEDULED_OUTCOME"
		UNION
	SELECT "APPLICATION_EXPORTED_OUTCOME"
		UNION
	SELECT "APPLICATION_COMPLETED_OUTCOME"
		UNION
	SELECT "APPLICATION_RECRUITMENT_OUTCOME"
;

/* Workflow state transition */

CREATE TABLE STATE_TRANSITION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_action_id INT(10) UNSIGNED NOT NULL,
	state_transition_type_id VARCHAR(50) NOT NULL,
	transition_state_id VARCHAR(50) NOT NULL,
	transition_action_id VARCHAR(100),
	processing_order INT(1) UNSIGNED,
	state_transition_evaluation_id VARCHAR(50),
	display_order INT(3) UNSIGNED,
	do_post_comment INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_action_id, state_transition_type_id, transition_state_id),
	INDEX (state_action_id),
	INDEX (state_transition_type_id),
	INDEX (transition_state_id),
	INDEX (transition_action_id),
	INDEX (state_transition_evaluation_id),
	FOREIGN KEY (state_action_id) REFERENCES STATE_ACTION (id),
	FOREIGN KEY (state_transition_type_id) REFERENCES STATE_TRANSITION_TYPE (id),
	FOREIGN KEY (transition_state_id) REFERENCES STATE (id),
	FOREIGN KEY (transition_action_id) REFERENCES ACTION (id),
	FOREIGN KEY (state_transition_evaluation_id) REFERENCES STATE_TRANSITION_EVALUATION (id)
) ENGINE = INNODB
;

/* Permitted role transition types */

CREATE TABLE ROLE_TRANSITION_TYPE (
	id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB
	SELECT "BRANCH" AS id
		UNION
	SELECT "CREATE"
		UNION
	SELECT "UPDATE"
		UNION
	SELECT "REJOIN"
		UNION
	SELECT "REMOVE"
;

/* Roles created, updated and removed during workflow transitions */

CREATE TABLE ROLE_TRANSITION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_transition_id INT(10) UNSIGNED NOT NULL,
	role_id VARCHAR(50) NOT NULL,
	role_transition_type_id VARCHAR(50) NOT NULL,
	processing_order INT(1) UNSIGNED,
	transition_role_id VARCHAR(50),
	minimum_permitted INT(1) UNSIGNED,
	maximum_permitted INT(1) UNSIGNED,
	restrict_to_invoker INT(1) UNSIGNED,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_transition_id, role_id, role_transition_type_id, transition_role_id),
	INDEX (role_id),
	INDEX (role_transition_type_id),
	INDEX (transition_role_id),
	FOREIGN KEY (state_transition_id) REFERENCES STATE_TRANSITION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id),
	FOREIGN KEY (role_transition_type_id) REFERENCES ROLE_TRANSITION_TYPE (id),
	FOREIGN KEY (transition_role_id) REFERENCES ROLE (id)
) ENGINE = INNODB
;

/* Roles excluded from transitions (e.g. application administrator cannot be application referee) */

CREATE TABLE ROLE_TRANSITION_EXCLUSION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	role_transition_id INT(10) UNSIGNED NOT NULL,
	role_id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id),
	INDEX (role_transition_id),
	INDEX (role_id),
	FOREIGN KEY (role_transition_id) REFERENCES ROLE_TRANSITION (id),
	FOREIGN KEY (role_id) REFERENCES ROLE (id)
) ENGINE = INNODB
;

/* Application escalate (unsubmitted) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_UNSUBMITTED_PENDING_COMPLETION", 0
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_UNSUBMITTED"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application withdraw */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", "APPLICATION_WITHDRAWN_COMPLETED", NULL, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_UNSUBMITTED"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_ACTION.id, "ONE_COMPLETED", TRANSITION_STATE.id, "APPLICATION_PROCESSING_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN STATE AS TRANSITION_STATE
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND TRANSITION_STATE.id IN ("APPLICATION_WITHDRAWN", "APPLICATION_WITHDRAWN_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_PROCESSING_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND STATE.id IN ("APPLICATION_WITHDRAWN", "APPLICATION_WITHDRAWN_COMPLETED")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_REVIEW"
		AND STATE.id != "APPLICATION_REVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"	
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_INTERVIEW"
		AND STATE.id != "APPLICATION_INTERVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING",
		"APPLICATION_INTERVIEW_PENDING_INTERVIEW")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE.parent_state_id = "APPLICATION_APPROVAL"
		AND STATE.id != "APPLICATION_APPROVAL"
		AND STATE_ACTION.action_id = "APPLICATION_WITHDRAW"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;
		
/* Application terminate */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT STATE_ACTION.id, "PROPAGATION", "APPLICATION_WITHDRAWN_COMPLETED", NULL, 1
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_UNSUBMITTED"
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", TRANSITION_STATE.id, "APPLICATION_PROCESSING_COMPLETED_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN STATE AS TRANSITION_STATE
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND TRANSITION_STATE.id IN ("APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_REJECTED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_PROCESSING_COMPLETED_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE.id IN ("APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_REJECTED_COMPLETED")
;


INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE" 
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_VALIDATION", "APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_REVIEW"
		AND STATE.id != "APPLICATION_REVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.parent_state_id = "APPLICATION_INTERVIEW"
		AND STATE.id != "APPLICATION_INTERVIEW"
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING",
		"APPLICATION_INTERVIEW_PENDING_INTERVIEW")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	WHERE STATE.id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "UPDATE", "APPLICATION_VIEWER_RECRUITER"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE
		ON STATE_ACTION.state_id = STATE.id
	INNER JOIN ROLE
	WHERE STATE.parent_state_id = "APPLICATION_APPROVAL"
		AND STATE.id != "APPLICATION_APPROVAL"
		AND STATE_ACTION.action_id = "APPLICATION_TERMINATE"
		AND STATE_TRANSITION.state_transition_type_id = "PROPAGATION"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;

/* Application comment */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_COMMENT"
;

/* Application submit */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, "APPLICATION_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_COMPLETE"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_VALIDATION", "APPLICATION_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_COMPLETE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, minimum_permitted, maximum_permitted)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "CREATE", 3, 3
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_SUGGESTED_SUPERVISOR", "CREATE", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE"
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE"
;

/* Application assess eligibility */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_ELIGIBILITY_ASSESSED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSESS_ELIGIBILITY"
		AND STATE.id IN ("APPLICATION_VALIDATION_PENDING_FEEDBACK", "APPLICATION_VALIDATION_PENDING_COMPLETION")
;

/* Application escalate (validation pending feedback) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_VALIDATION_PENDING_COMPLETION", 0
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_VALIDATION_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
;


/* Application confirm eligibility */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_VALIDATION_PENDING_COMPLETION", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_ELIGIBILITY"
;

/* Application edit */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_EDIT_AS_CREATOR", "APPLICATION_EDIT_AS_ADMINISTRATOR")
;

/* Application complete stage */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, display_order, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 0, "APPLICATION_ASSIGN_REVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 1, "APPLICATION_ASSIGN_INTERVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STAGE_COMPLETED_OUTCOME", 2, "APPLICATION_ASSIGN_SUPERVISORS", 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 3, "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 4, "APPLICATION_CONFIRM_REJECTION", 1
	FROM STATE_ACTION
	WHERE action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order, maximum_permitted)
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE", NULL, NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_VALIDATION_STAGE"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER", 0, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE", NULL, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_REVIEW_STAGE", "APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_REVIEW_STAGE"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "APPLICATION_INTERVIEW_PENDING_INTERVIEW")	
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "UPDATE", "APPLICATION_INTERVIEWER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_INTERVIEW_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_INTERVIEW_PENDING_AVAILABILITY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING")
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "UPDATE", "APPLICATION_VIEWER_RECRUITER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")	
	WHERE STATE_ACTION.action_id = "APPLICATION_COMPLETE_APPROVAL_STAGE"
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id IN ("APPLICATION_COMPLETE_VALIDATION_STAGE", "APPLICATION_COMPLETE_REVIEW_STAGE", 
		"APPLICATION_COMPLETE_INTERVIEW_STAGE", "APPLICATION_COMPLETE_APPROVAL_STAGE")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND ROLE_TRANSITION.role_id = "APPLICATION_ADMINISTRATOR"
		AND ROLE_TRANSITION.role_transition_type_id = "CREATE"
;

/* Application move to different stage */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, display_order, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 0, "APPLICATION_ASSIGN_INTERVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STAGE_COMPLETED_OUTCOME", 1, "APPLICATION_ASSIGN_SUPERVISORS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 2, "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 3, "APPLICATION_CONFIRM_REJECTION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 0, "APPLICATION_ASSIGN_REVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STAGE_COMPLETED_OUTCOME", 1, "APPLICATION_ASSIGN_SUPERVISORS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 2, "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 3, "APPLICATION_CONFIRM_REJECTION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 0, "APPLICATION_ASSIGN_REVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 1, "APPLICATION_ASSIGN_INTERVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 2, "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 3, "APPLICATION_CONFIRM_REJECTION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVAL"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 0, "APPLICATION_ASSIGN_REVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 1, "APPLICATION_ASSIGN_INTERVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STAGE_COMPLETED_OUTCOME", 2, "APPLICATION_ASSIGN_SUPERVISORS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 3, "APPLICATION_CONFIRM_REJECTION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_APPROVED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 0, "APPLICATION_ASSIGN_REVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW", "APPLICATION_STAGE_COMPLETED_OUTCOME", 1, "APPLICATION_ASSIGN_INTERVIEWERS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
		UNION		
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL", "APPLICATION_STAGE_COMPLETED_OUTCOME", 2, "APPLICATION_ASSIGN_SUPERVISORS", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED", "APPLICATION_STAGE_COMPLETED_OUTCOME", 3, "APPLICATION_CONFIRM_OFFER_RECOMMENDATION", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND state_id = "APPLICATION_REJECTED"
;	

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order, maximum_permitted)
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER", 0, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE", NULL, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE", NULL, NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_ACTION.state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_APPROVED", "APPLICATION_REJECTED")
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_MOVE_TO_DIFFERENT_STAGE"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_REVIEW", "APPLICATION_INTERVIEW", "APPLICATION_APPROVAL")
		AND ROLE_TRANSITION.role_id = "APPLICATION_ADMINISTRATOR"
		AND ROLE_TRANSITION.role_transition_type_id = "CREATE"
;

/* Application provide reference */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REFERENCE"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_REFERENCE"
;

/* Application assign reviewers */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REVIEW_PENDING_FEEDBACK", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_ASSIGN_REVIEWERS"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "CREATE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_REVIEWERS"
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_REVIEWERS"
;

/* Application provide review */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, 0, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REVIEW"
		AND state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_REVIEW_PENDING_COMPLETION", 1, NULL, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REVIEW"
		AND state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_REVIEW"
		AND state_id = "APPLICATION_REVIEW_PENDING_COMPLETION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "APPLICATION_REVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_REVIEW"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
;

/* Application escalate (review) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REVIEW_PENDING_COMPLETION", 0
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REVIEW_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application assign interviewers */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_INTERVIEW_SCHEDULED_OUTCOME", "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE.id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_INTERVIEW_SCHEDULED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE.id IN ("APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, minimum_permitted)
	SELECT STATE_TRANSITION.id, "APPLICATION_CREATOR", "BRANCH", "APPLICATION_POTENTIAL_INTERVIEWEE", NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "CREATE", NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_CREATOR", "BRANCH", "APPLICATION_INTERVIEWEE", NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "CREATE", NULL, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_INTERVIEWERS"
		AND ROLE_TRANSITION.role_transition_type_id = "CREATE"
;

/* Application provide interview availability */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, 0, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_INTERVIEW_PENDING_SCHEDULING", 1, NULL, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_SCHEDULING"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "UPDATE", "APPLICATION_INTERVIEWER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWEE", "REJOIN", "APPLICATION_CREATOR", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
;

/* Application escalate (interview scheduling) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_SCHEDULING", 0
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application confirm interview arrangements */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT STATE_ACTION.id, "ONE_COMPLETED", STATE.id, "APPLICATION_INTERVIEW_SCHEDULED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE.id IN ("APPLICATION_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, processing_order, maximum_permitted)
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "UPDATE", "APPLICATION_VIEWER_RECRUITER", 0, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_ADMINISTRATOR", "CREATE", NULL, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWEE", "UPDATE", "APPLICATION_INTERVIEWEE", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "REJOIN", "APPLICATION_CREATOR", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_INTERVIEW_PENDING_FEEDBACK", "APPLICATION_INTERVIEW")
		AND ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWEE", "APPLICATION_INTERVIEWEE")
		UNION
	SELECT STATE_TRANSITION.id, "APPLICATION_POTENTIAL_INTERVIEWER", "UPDATE", "APPLICATION_INTERVIEWER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id IN ("APPLICATION_INTERVIEW_PENDING_INTERVIEW", "APPLICATION_INTERVIEW_PENDING_FEEDBACK")
		UNION
	SELECT STATE_TRANSITION.id, ROLE.id, "UPDATE", "APPLICATION_VIEWER_RECRUITER", NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND STATE_TRANSITION.transition_state_id = "APPLICATION_INTERVIEW"
		AND ROLE.id IN ("APPLICATION_POTENTIAL_INTERVIEWER", "APPLICATION_INTERVIEWER")
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS"
		AND ROLE_TRANSITION.role_transition_type_id = "CREATE"
;

/* Application update interview availability */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_INTERVIEW_PENDING_SCHEDULING", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_UPDATE_INTERVIEW_AVAILABILITY"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
;

/* Application interview taken place */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_FEEDBACK", 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_ESCALATE"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id)
	SELECT STATE_TRANSITION.id, ROLE.id, "REJOIN", "APPLICATION_CREATOR"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
		ON ROLE.id = "APPLICATION_INTERVIEWEE"
	WHERE STATE_ACTION.action_id = "APPLICATION_ESCALATE"
		AND STATE_ACTION.state_id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW"
		AND STATE_TRANSITION.state_transition_type_id = "DUE_DATE_EXPIRY"
;

/* Application provide interview feedback */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, 0, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_INTERVIEW_PENDING_COMPLETION", 1, NULL, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND state_id = "APPLICATION_INTERVIEW_PENDING_COMPLETION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "APPLICATION_INTERVIEWER", "UPDATE", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_PROVIDE_INTERVIEW_FEEDBACK"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
;

/* Application escalate (interview) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_INTERVIEW_PENDING_COMPLETION", 0
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application assign supervisors */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVAL_PENDING_FEEDBACK", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_ASSIGN_SUPERVISORS"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, minimum_permitted, maximum_permitted)
	SELECT STATE_TRANSITION.id, ROLE.id, "CREATE", 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_SUPERVISORS"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, "APPLICATION_CREATOR"
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_ASSIGN_SUPERVISORS"
;

/* Application confirm supervision */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, processing_order, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, 0, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		UNION
	SELECT id, "ALL_COMPLETED", "APPLICATION_APPROVAL_PENDING_COMPLETION", 1, NULL, 0
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, NULL, "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND state_id = "APPLICATION_APPROVAL_PENDING_COMPLETION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, ROLE.id, "UPDATE", "APPLICATION_VIEWER_RECRUITER", 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_SUPERVISION"
		AND STATE_TRANSITION.state_transition_type_id = "ONE_COMPLETED"
		AND ROLE.id IN ("APPLICATION_PRIMARY_SUPERVISOR", "APPLICATION_SECONDARY_SUPERVISOR")
;

/* Application escalate (approval) */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVAL_PENDING_COMPLETION", 0
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVAL_PENDING_FEEDBACK"
		AND action_id = "APPLICATION_ESCALATE"
;

/* Application confirm offer recommendation */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED_PENDING_EXPORT", "APPLICATION_PROCESSING_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED_COMPLETED", "APPLICATION_PROCESSING_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
;

/* Application confirm rejection */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED_PENDING_EXPORT", "APPLICATION_PROCESSING_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_REJECTION"
		UNION
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED_COMPLETED", "APPLICATION_PROCESSING_COMPLETED_OUTCOME", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "APPLICATION_CONFIRM_REJECTION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id)
	SELECT STATE_TRANSITION.id, "APPLICATION_REFEREE", "UPDATE", "APPLICATION_VIEWER_REFEREE"
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_REJECTION"
;

/* Application approved pending export */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVED_COMPLETED", "APPLICATION_EXPORTED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_APPROVED_PENDING_CORRECTION", "APPLICATION_EXPORTED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
;

/* Application approved pending correction */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_APPROVED_PENDING_EXPORT", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_APPROVED_PENDING_CORRECTION"
		AND action_id = "APPLICATION_CORRECT"
;

/* Application rejected pending export */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REJECTED_COMPLETED", "APPLICATION_EXPORTED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REJECTED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_EXPORTED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REJECTED_PENDING_EXPORT"
		AND action_id = "APPLICATION_EXPORT"
;

/* Application rejected pending correction */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_REJECTED_PENDING_EXPORT", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_REJECTED_PENDING_CORRECTION"
		AND action_id = "APPLICATION_CORRECT"
;

/* Application withdrawn pending export */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_WITHDRAWN_COMPLETED", "APPLICATION_EXPORTED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_WITHDRAWN"
		AND action_id = "APPLICATION_EXPORT"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "APPLICATION_WITHDRAWN_PENDING_CORRECTION", "APPLICATION_EXPORTED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_WITHDRAWN"
		AND action_id = "APPLICATION_EXPORT"
;

/* Application withdrawn pending correction */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_WITHDRAWN", "SYSTEM_VIEW_APPLICATION_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "APPLICATION_WITHDRAWN_PENDING_CORRECTION"
		AND action_id = "APPLICATION_CORRECT"
;

/* Create program */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CREATED_OUTCOME", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "INSTITUTION_CREATE_PROGRAM"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_CREATED_OUTCOME", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "INSTITUTION_CREATE_PROGRAM"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, minimum_permitted, maximum_permitted, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "PROGRAM_ADMINISTRATOR", "CREATE", 1, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "INSTITUTION_CREATE_PROGRAM"
		AND STATE_TRANSITION.transition_state_id = "PROGRAM_APPROVED"
;

/* Approve program */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_APPROVED_OUTCOME", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL_PENDING_CORRECTION", "PROGRAM_APPROVED_OUTCOME", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_APPROVED_OUTCOME", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_REJECTED", "PROGRAM_APPROVED_OUTCOME", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVAL"
		AND action_id = "PROGRAM_COMPLETE_APPROVAL_STAGE"
;

/* Edit program application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_EDIT"
;

/* Withdraw program application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "PROGRAM_WITHDRAWN", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_WITHDRAW"
;

/* Program configure */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DEACTIVATED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DISABLED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_APPROVED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DISABLED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DEACTIVATED"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVAL", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION	
	SELECT id, "ONE_COMPLETED", "PROGRAM_APPROVED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DEACTIVATED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROGRAM_DISABLED", "PROGRAM_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROGRAM_CONFIGURE"
;

/* Program create application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_UNSUBMITTED", "APPLICATION_COMPLETE", 1
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_CREATE_APPLICATION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, minimum_permitted, maximum_permitted, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "APPLICATION_CREATOR", "CREATE", 1, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_APPLICATION"
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, ROLE.id
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_APPLICATION"
		AND ROLE.id NOT LIKE "APPLICATION_%"
		AND ROLE.id NOT LIKE "PROJECT_%"
;

/* Program expired */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_EXPIRED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id IN ("PROGRAM_APPROVED", "PROGRAM_DEACTIVATED")
		AND action_id = "PROGRAM_ESCALATE"
		UNION
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION", "PROGRAM_EXPIRED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id IN ("PROGRAM_APPROVED", "PROGRAM_DEACTIVATED")
		AND action_id = "PROGRAM_ESCALATE"
;

/* Program terminated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "PROGRAM_DISABLED_COMPLETED", 1
	FROM STATE_ACTION
	WHERE state_id IN ("PROGRAM_DISABLED", "PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION")
		AND action_id = "PROGRAM_ESCALATE"
;

/* Program recruitment completed */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROGRAM_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROGRAM_APPROVED"
		AND STATE.id IN ("PROGRAM_APPROVED", "PROGRAM_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROGRAM_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROGRAM_DEACTIVATED"
		AND STATE.id IN ("PROGRAM_DEACTIVATED", "PROGRAM_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROGRAM_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROGRAM_DISABLED"
		AND STATE.id IN ("PROGRAM_DISABLED", "PROGRAM_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROGRAM_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROGRAM_DISABLED_PENDING_REACTIVATION"
		AND STATE.id IN ("PROGRAM_DISABLED_PENDING_REACTIVATION", "PROGRAM_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROGRAM_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION"
		AND STATE.id IN ("PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION", "PROGRAM_DISABLED_COMPLETED")
;

/* Program reactivated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "PROPAGATION", "PROGRAM_APPROVED", "PROGRAM_REACTIVATED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_REACTIVATE"
		UNION
	SELECT id, "PROPAGATION", "PROGRAM_DEACTIVATED", "PROGRAM_REACTIVATED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_REACTIVATE"
;

/* Create project */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "PROJECT_APPROVED", "SYSTEM_VIEW_PROGRAM_LIST", 1
	FROM STATE_ACTION
	WHERE action_id = "PROGRAM_CREATE_PROJECT"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, minimum_permitted, maximum_permitted, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "PROJECT_ADMINISTRATOR", "CREATE", NULL, 1, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_PROJECT"
		UNION
	SELECT STATE_TRANSITION.id, "PROJECT_PRIMARY_SUPERVISOR", "CREATE", NULL, 1, 1, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_PROJECT"
		UNION
	SELECT STATE_TRANSITION.id, "PROJECT_ADMINISTRATOR", "CREATE", NULL, NULL, 1, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_PROJECT"
		UNION
	SELECT STATE_TRANSITION.id, "PROJECT_SECONDARY_SUPERVISOR", "CREATE", NULL, NULL, 1, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_CREATE_PROJECT"
;

/* Project configure */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", state_id, "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_APPROVED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DEACTIVATED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_APPROVED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DISABLED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_APPROVED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_APPROVED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DEACTIVATED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DEACTIVATED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DISABLED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DEACTIVATED"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_APPROVED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DEACTIVATED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", state_id, "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
		UNION
	SELECT id, "ONE_COMPLETED", "PROJECT_DISABLED", "PROJECT_CONFIGURED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND action_id = "PROJECT_CONFIGURE"
;

/* Project create application */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, transition_action_id, do_post_comment)
	SELECT id, "ONE_COMPLETED", "APPLICATION_UNSUBMITTED", "APPLICATION_COMPLETE", 1
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_CREATE_APPLICATION"
;

INSERT INTO ROLE_TRANSITION (state_transition_id, role_id, role_transition_type_id, transition_role_id, minimum_permitted, maximum_permitted, restrict_to_invoker)
	SELECT STATE_TRANSITION.id, "APPLICATION_CREATOR", "CREATE", NULL, 1, 1, 1
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROJECT_CREATE_APPLICATION"
		UNION
	SELECT STATE_TRANSITION.id, "PROJECT_PRIMARY_SUPERVISOR", "BRANCH", "APPLICATION_SUGGESTED_SUPERVISOR", NULL, NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROJECT_CREATE_APPLICATION"
		UNION
	SELECT STATE_TRANSITION.id, "PROJECT_SECONDARY_SUPERVISOR", "BRANCH", "APPLICATION_SUGGESTED_SUPERVISOR", NULL, NULL, NULL
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROJECT_CREATE_APPLICATION"
;

INSERT INTO ROLE_TRANSITION_EXCLUSION (role_transition_id, role_id)
	SELECT ROLE_TRANSITION.id, ROLE.id
	FROM ROLE_TRANSITION INNER JOIN STATE_TRANSITION
		ON ROLE_TRANSITION.state_transition_id = STATE_TRANSITION.id
	INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN ROLE
	WHERE STATE_ACTION.action_id = "PROJECT_CREATE_APPLICATION"
		AND ROLE.id NOT LIKE "APPLICATION_%"
;

/* Project expired */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "PROJECT_DISABLED_PENDING_REACTIVATION", 1
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_ESCALATE"
		AND state_id IN ("PROJECT_APPROVED", "PROJECT_DEACTIVATED")
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION", 1
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_SUSPEND"
;

/* Project terminated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, do_post_comment)
	SELECT id, "DUE_DATE_EXPIRY", "PROJECT_DISABLED_COMPLETED", 1
	FROM STATE_ACTION
	WHERE state_id IN ("PROJECT_DISABLED", "PROJECT_DISABLED_PENDING_REACTIVATION")
		AND action_id = "PROJECT_ESCALATE"
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DISABLED_COMPLETED", 1
	FROM STATE_ACTION
	WHERE action_id = "PROJECT_TERMINATE"
;

/* Project recruitment completed */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROJECT_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROJECT_APPROVED"
		AND STATE.id IN ("PROJECT_APPROVED", "PROJECT_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROJECT_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROJECT_DEACTIVATED"
		AND STATE.id IN ("PROJECT_DEACTIVATED", "PROJECT_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROJECT_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROJECT_DISABLED"
		AND STATE.id IN ("PROJECT_DISABLED", "PROJECT_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROJECT_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROJECT_DISABLED_PENDING_REACTIVATION"
		AND STATE.id IN ("PROJECT_DISABLED_PENDING_REACTIVATION", "PROJECT_DISABLED_COMPLETED")
		UNION
	SELECT STATE_ACTION.id, "PROPAGATION", STATE.id, "APPLICATION_RECRUITMENT_OUTCOME", 1
	FROM STATE_ACTION INNER JOIN STATE
	WHERE STATE_ACTION.action_id = "PROJECT_COMPLETE_RECRUITMENT"
		AND STATE_ACTION.state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND STATE.id IN ("PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION", "PROJECT_DISABLED_COMPLETED")
;

/* Project reactivated */

INSERT INTO STATE_TRANSITION (state_action_id, state_transition_type_id, transition_state_id, state_transition_evaluation_id, do_post_comment)
	SELECT id, "PROPAGATION", "PROJECT_APPROVED", "PROJECT_REACTIVATED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROJECT_REACTIVATE"
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DEACTIVATED", "PROJECT_REACTIVATED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROJECT_REACTIVATE"
		UNION
	SELECT id, "PROPAGATION", "PROJECT_DISABLED_PENDING_REACTIVATION", "PROJECT_REACTIVATED_OUTCOME", 1
	FROM STATE_ACTION
	WHERE state_id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION"
		AND action_id = "PROJECT_REACTIVATE"
;	

CREATE TABLE STATE_TRANSITION_PROPAGATION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	state_transition_id INT(10) UNSIGNED NOT NULL,
	propagated_state_transition_id INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (state_transition_id, propagated_state_transition_id),
	INDEX (propagated_state_transition_id),
	FOREIGN KEY (state_transition_id) REFERENCES STATE_TRANSITION (id),
	FOREIGN KEY (propagated_state_transition_id) REFERENCES STATE_TRANSITION (id)
) ENGINE = INNODB
;

/* Terminate project/program on recruitment */

INSERT INTO STATE_TRANSITION_PROPAGATION (state_transition_id, propagated_state_transition_id)
	SELECT STATE_TRANSITION.id, PROPAGATED_STATE_TRANSITION.id
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION AS PROPAGATED_STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = PROPAGATED_STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "APPLICATION_CONFIRM_OFFER_RECOMMENDATION"
		AND PROPAGATED_STATE_ACTION.action_id IN ("PROGRAM_COMPLETE_RECRUITMENT", "PROJECT_COMPLETE_RECRUITMENT")
;

/* Terminate applications when program/project terminated */

INSERT INTO STATE_TRANSITION_PROPAGATION (state_transition_id, propagated_state_transition_id)
	SELECT STATE_TRANSITION.id, PROPAGATED_STATE_TRANSITION.id
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION AS PROPAGATED_STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = PROPAGATED_STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id IN ("PROGRAM_DISABLED_COMPLETED", "PROJECT_DISABLED_COMPLETED")
		AND PROPAGATED_STATE_ACTION.action_id = "APPLICATION_TERMINATE"
;

/* Expire projects when program expires */

INSERT INTO STATE_TRANSITION_PROPAGATION (state_transition_id, propagated_state_transition_id)
	SELECT STATE_TRANSITION.id, PROPAGATED_STATE_TRANSITION.id
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION AS PROPAGATED_STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = PROPAGATED_STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id IN ("PROGRAM_DISABLED_PENDING_REACTIVATION",
		"PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION")
		AND PROPAGATED_STATE_ACTION.action_id = "PROJECT_SUSPEND"
;

/* Terminate projects when program is terminated */

INSERT INTO STATE_TRANSITION_PROPAGATION (state_transition_id, propagated_state_transition_id)
	SELECT STATE_TRANSITION.id, PROPAGATED_STATE_TRANSITION.id
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION AS PROPAGATED_STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = PROPAGATED_STATE_ACTION.id
	WHERE STATE_TRANSITION.transition_state_id = "PROGRAM_DISABLED_COMPLETED"
		AND PROPAGATED_STATE_ACTION.action_id = "PROJECT_TERMINATE"
;

/* Reactivate projects when program reactivates */

INSERT INTO STATE_TRANSITION_PROPAGATION (state_transition_id, propagated_state_transition_id)
	SELECT STATE_TRANSITION.id, PROPAGATED_STATE_TRANSITION.id
	FROM STATE_TRANSITION INNER JOIN STATE_ACTION
		ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
	INNER JOIN STATE_TRANSITION AS PROPAGATED_STATE_TRANSITION
	INNER JOIN STATE_ACTION AS PROPAGATED_STATE_ACTION
		ON PROPAGATED_STATE_TRANSITION.state_action_id = PROPAGATED_STATE_ACTION.id
	WHERE STATE_ACTION.action_id = "PROGRAM_REACTIVATE"
		AND PROPAGATED_STATE_ACTION.action_id = "PROJECT_REACTIVATE"
;
