/* Separate out program correct action so it can be urgent */

INSERT INTO ACTION (id, action_type, scope_id)
VALUES ("PROGRAM_CORRECT", "USER_INVOCATION", "PROGRAM")
;

DELETE 
FROM STATE_ACTION_ENHANCEMENT
WHERE action_enhancement_type LIKE "PROGRAM_%"
;

ALTER TABLE STATE_TRANSITION_PROPAGATION
	CHANGE COLUMN action_id propagated_action_id VARCHAR(100) NOT NULL
;

SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ACTION
SET id = "PROGRAM_VIEW"
WHERE id = "PROGRAM_VIEW_EDIT"
;

UPDATE ACTION_REDACTION
SET action_id = "PROGRAM_VIEW"
WHERE action_id = "PROGRAM_VIEW_EDIT"
;

UPDATE COMMENT
SET action_id = "PROGRAM_VIEW"
WHERE action_id = "PROGRAM_VIEW_EDIT"
;

UPDATE COMMENT
SET action_on_parent_resource_id = "PROGRAM_VIEW"
WHERE action_on_parent_resource_id = "PROGRAM_VIEW_EDIT"
;

UPDATE COMMENT_CUSTOM_QUESTION
SET action_id = "PROGRAM_VIEW"
WHERE action_id = "PROGRAM_VIEW_EDIT"
;

UPDATE STATE_ACTION
SET action_id = "PROGRAM_VIEW"
WHERE action_id = "PROGRAM_VIEW_EDIT"
;

UPDATE STATE_ACTION_ENHANCEMENT
SET delegated_action_id = "PROGRAM_VIEW"
WHERE delegated_action_id = "PROGRAM_VIEW_EDIT"
;

UPDATE STATE_TRANSITION
SET transition_action_id = "PROGRAM_VIEW"
WHERE transition_action_id = "PROGRAM_VIEW_EDIT"
;

UPDATE STATE_TRANSITION_PROPAGATION
SET propagated_action_id = "PROGRAM_VIEW"
WHERE propagated_action_id = "PROGRAM_VIEW_EDIT"
;

SET FOREIGN_KEY_CHECKS = 1
;

UPDATE STATE_TRANSITION INNER JOIN STATE_ACTION
	ON STATE_TRANSITION.state_action_id = STATE_ACTION.id
SET STATE_ACTION.action_id = "PROGRAM_CORRECT"
WHERE STATE_ACTION.action_id = "PROGRAM_VIEW"
;

