/* Scope in notification template */

ALTER TABLE NOTIFICATION_TEMPLATE
	ADD COLUMN scope_id VARCHAR(50),
	ADD INDEX (scope_id),
	ADD FOREIGN KEY (scope_id) REFERENCES SCOPE (id)
;

UPDATE NOTIFICATION_TEMPLATE INNER JOIN SCOPE
SET NOTIFICATION_TEMPLATE.scope_id = SCOPE.id
WHERE NOTIFICATION_TEMPLATE.id LIKE CONCAT(SCOPE.id, "%")
;

ALTER TABLE NOTIFICATION_TEMPLATE
	MODIFY COLUMN scope_id VARCHAR(50) NOT NULL
;

/* Notification purpose */

ALTER TABLE NOTIFICATION_TEMPLATE
	ADD COLUMN notification_purpose VARCHAR(50) AFTER notification_type
;

UPDATE NOTIFICATION_TEMPLATE
SET notification_purpose = "UPDATE"
WHERE id LIKE "%_NOTIFICATION"
;

UPDATE NOTIFICATION_TEMPLATE
SET notification_purpose = "REMINDER"
WHERE id LIKE "%_REMINDER"
;

UPDATE NOTIFICATION_TEMPLATE
SET notification_purpose = "REQUEST"
WHERE id LIKE "%_REQUEST"
;

ALTER TABLE NOTIFICATION_TEMPLATE
	MODIFY COLUMN notification_purpose VARCHAR(50) NOT NULL
;

ALTER TABLE NOTIFICATION_TEMPLATE
	MODIFY COLUMN scope_id VARCHAR(50) NOT NULL AFTER notification_purpose
;
