ALTER TABLE STATE
	DROP INDEX scope_id,
	ADD INDEX (scope_id)
;

UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_APPROVAL_PENDING_COMPLETION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_APPROVAL_PENDING_FEEDBACK";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_APPROVED_COMPLETED";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_APPROVED_PENDING_CORRECTION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_APPROVED_PENDING_EXPORT";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_INTERVIEW_PENDING_AVAILABILITY";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_INTERVIEW_PENDING_COMPLETION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_INTERVIEW_PENDING_FEEDBACK";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_INTERVIEW_PENDING_INTERVIEW";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_INTERVIEW_PENDING_SCHEDULING";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_REJECTED_COMPLETED";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_REJECTED_PENDING_CORRECTION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_REJECTED_PENDING_EXPORT";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_REVIEW_PENDING_COMPLETION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_REVIEW_PENDING_FEEDBACK";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_UNSUBMITTED_PENDING_COMPLETION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_VALIDATION_PENDING_COMPLETION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_VALIDATION_PENDING_FEEDBACK";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_WITHDRAWN_COMPLETED";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_WITHDRAWN_PENDING_CORRECTION";
UPDATE STATE SET sequence_order = NULL WHERE id = "APPLICATION_WITHDRAWN_PENDING_EXPORT";
UPDATE STATE SET sequence_order = 1 WHERE id = "APPLICATION_UNSUBMITTED";
UPDATE STATE SET sequence_order = 2 WHERE id = "APPLICATION_VALIDATION";
UPDATE STATE SET sequence_order = 3 WHERE id = "APPLICATION_REVIEW";
UPDATE STATE SET sequence_order = 4 WHERE id = "APPLICATION_INTERVIEW";
UPDATE STATE SET sequence_order = 5 WHERE id = "APPLICATION_APPROVAL";
UPDATE STATE SET sequence_order = 6 WHERE id = "APPLICATION_APPROVED";
UPDATE STATE SET sequence_order = 7 WHERE id = "APPLICATION_REJECTED";
UPDATE STATE SET sequence_order = 8 WHERE id = "APPLICATION_WITHDRAWN";
UPDATE STATE SET sequence_order = 1 WHERE id = "INSTITUTION_APPROVED";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROGRAM_APPROVAL_PENDING_CORRECTION";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROGRAM_DEACTIVATED";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROGRAM_DISABLED_COMPLETED";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROGRAM_DISABLED_PENDING_REACTIVATION";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROJECT_APPROVAL_PENDING_CORRECTION";
UPDATE STATE SET sequence_order = 1 WHERE id = "PROGRAM_APPROVAL";
UPDATE STATE SET sequence_order = 2 WHERE id = "PROGRAM_APPROVED";
UPDATE STATE SET sequence_order = 3 WHERE id = "PROGRAM_REJECTED";
UPDATE STATE SET sequence_order = 4 WHERE id = "PROGRAM_DISABLED";
UPDATE STATE SET sequence_order = 5 WHERE id = "PROGRAM_WITHDRAWN";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROJECT_DEACTIVATED";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROJECT_DISABLED_COMPLETED";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION";
UPDATE STATE SET sequence_order = NULL WHERE id = "PROJECT_DISABLED_PENDING_REACTIVATION";
UPDATE STATE SET sequence_order = 1 WHERE id = "PROJECT_APPROVAL";
UPDATE STATE SET sequence_order = 2 WHERE id = "PROJECT_APPROVED";
UPDATE STATE SET sequence_order = 3 WHERE id = "PROJECT_REJECTED";
UPDATE STATE SET sequence_order = 4 WHERE id = "PROJECT_DISABLED";
UPDATE STATE SET sequence_order = 5 WHERE id = "PROJECT_WITHDRAWN";
UPDATE STATE SET sequence_order = 1 WHERE id = "SYSTEM_APPROVED";

ALTER TABLE STATE
	DROP INDEX scope_id,
	ADD UNIQUE INDEX (scope_id, sequence_order)
;
