ALTER TABLE ACTION
	ADD COLUMN do_save_comment INT(1) NOT NULL DEFAULT 0 AFTER action_type,
	ADD INDEX (do_save_comment)
;

ALTER TABLE ACTION
	MODIFY COLUMN do_save_comment INT(1) UNSIGNED NOT NULL
;

DELETE STATE_ACTION_ASSIGNMENT.* 
FROM STATE_ACTION_ASSIGNMENT INNER JOIN STATE_ACTION
	ON STATE_ACTION_ASSIGNMENT.state_action_id = STATE_ACTION.id
WHERE STATE_ACTION.action_id LIKE "%_EXPORT_%"
;

DELETE FROM STATE_ACTION
WHERE action_id LIKE "%_EXPORT_%"
;

DELETE FROM
ACTION WHERE id LIKE "%_EXPORT_%"
;

UPDATE ACTION
SET do_save_comment = 0
WHERE id LIKE "%_ESCALATE"
;

UPDATE ACTION LEFT JOIN (
	SELECT action_id AS action_id, 
		MIN(do_post_comment) AS do_not_post, 
		MAX(do_post_comment) AS do_post
	FROM STATE_ACTION
	GROUP BY action_id
	ORDER BY action_id) AS USE_SUMMARY
	ON ACTION.id = USE_SUMMARY.action_id
SET ACTION.do_save_comment = USE_SUMMARY.do_post
;

ALTER TABLE STATE_ACTION
	DROP COLUMN do_post_comment
;

ALTER TABLE SYSTEM
	CHANGE COLUMN name code VARCHAR(50) NOT NULL,
	ADD COLUMN previous_state_id VARCHAR(50),
	ADD COLUMN due_date DATE,
	ADD COLUMN created_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ADD COLUMN updated_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE SYSTEM
	MODIFY COLUMN created_timestamp DATETIME NOT NULL,
	MODIFY COLUMN updated_timestamp DATETIME NOT NULL
;
