ALTER TABLE ACTION
	ADD COLUMN action_category VARCHAR(50) AFTER action_type
;

UPDATE ACTION
SET action_category = "EMAIL_RESOURCE_CREATOR"
WHERE id LIKE "%_EMAIL_%"
;

UPDATE ACTION
SET action_category = "VIEW_RESOURCE_LIST"
WHERE id LIKE "%_LIST%"
;

UPDATE ACTION
SET action_category = "VIEW_RESOURCE"
WHERE (id LIKE "%_VIEW"
	OR id LIKE "%_VIEW_EDIT")
	AND id NOT LIKE "%_LIST"
;

UPDATE ACTION
SET action_category = NULL
WHERE id = "APPLICATION_PROVIDE_REVIEW"
;

UPDATE ACTION
SET action_category = "CREATE_RESOURCE"
WHERE id LIKE "%_CREATE_%"
;

UPDATE ACTION
SET action_category = "WITHDRAW_RESOURCE"
WHERE id LIKE "%_WITHDRAW"
;

UPDATE ACTION
SET action_category = "CONFIGURE_RESOURCE"
WHERE id LIKE "%_CONFIGURE"
;

UPDATE ACTION
SET action_type = "SYSTEM_IMPORT"
WHERE id LIKE "%_IMPORT_PROGRAM"
;

UPDATE ACTION
SET action_category = "EXPEDITE_RESOURCE"
WHERE action_type LIKE "SYSTEM_%"
;

UPDATE ACTION
SET action_category = "CONFIGURE_ACCOUNT"
WHERE id LIKE "%_ACCOUNT"
;

UPDATE ACTION
SET action_category = "PROCESS_RESOURCE"
WHERE action_category IS NULL
;

ALTER TABLE ACTION
	MODIFY COLUMN action_category VARCHAR(50) NOT NULL
;
