ALTER TABLE STATE_ACTION
	ADD COLUMN action_enhancement VARCHAR(50) AFTER is_default_action,
	ADD INDEX (action_enhancement)
;

ALTER TABLE STATE_ACTION_ASSIGNMENT
	ADD COLUMN action_enhancement VARCHAR(50) AFTER role_id,
	ADD INDEX (action_enhancement)
;

ALTER TABLE STATE_ACTION_ASSIGNMENT
	ADD COLUMN delegated_action_id VARCHAR(100) AFTER action_enhancement_type,
	ADD INDEX (delegated_action_id),
	ADD FOREIGN KEY (delegated_action_id) REFERENCES ACTION (id)
;

DROP TABLE STATE_ACTION_ENHANCEMENT
;

DELETE 
FROM ROLE_TRANSITION
;

DELETE
FROM STATE_TRANSITION_PROPAGATION
;

DELETE
FROM STATE_TRANSITION
;

DELETE
FROM STATE_ACTION_ASSIGNMENT
;

DELETE
FROM STATE_ACTION_NOTIFICATION
;

DELETE
FROM STATE_ACTION
;
