ALTER TABLE STATE_TRANSITION_PENDING
	MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT
;

ALTER TABLE APPLICATION
	ADD COLUMN do_retain INT(1) UNSIGNED NOT NULL DEFAULT 0 AFTER application_additional_information_id,
	ADD INDEX (do_retain)
;

ALTER TABLE APPLICATION
	MODIFY COLUMN do_retain INT(1) UNSIGNED NOT NULL
;
