UPDATE APPLICATION
SET state_id = REPLACE(state_id, "_PENDING_CORRECTION", "_COMPLETED")
WHERE state_id IN ("APPLICATION_APPROVED_PENDING_CORRECTION", 
	"APPLICATION_REJECTED_PENDING_CORRECTION", "APPLICATION_WITHDRAWN_PENDING_CORRECTION")
	AND updated_timestamp <= (CURRENT_DATE() - INTERVAL 2 MONTH)
;

ALTER TABLE ADVERT
	ADD COLUMN apply_link TEXT AFTER description
;
