ALTER TABLE APPLICATION
	ADD COLUMN rating_count INT(10) UNSIGNED AFTER application_additional_information_id,
	MODIFY COLUMN average_rating DECIMAL(3,2) AFTER rating_count,
	MODIFY COLUMN submitted_timestamp DATETIME AFTER created_timestamp,
	ADD INDEX (user_id, sequence_identifier),
	ADD INDEX (institution_id, sequence_identifier),
	ADD INDEX (program_id, sequence_identifier),
	ADD INDEX (project_id, sequence_identifier),
	ADD INDEX (code, sequence_identifier),
	ADD INDEX (closing_date, sequence_identifier),
	ADD INDEX (state_id, sequence_identifier),
	ADD INDEX (created_timestamp, sequence_identifier),
	ADD INDEX (submitted_timestamp, sequence_identifier),
	ADD INDEX (updated_timestamp, sequence_identifier),
	ADD INDEX (rating_count, sequence_identifier),
	ADD INDEX (average_rating, sequence_identifier)
;

ALTER TABLE ADVERT
	ADD INDEX (immediate_start),
	ADD INDEX (fee_annualised),
	ADD INDEX (pay_annualised)
;

ALTER TABLE ADVERT_CLOSING_DATE
	ADD INDEX (closing_date)
;

ALTER TABLE PROJECT
	ADD INDEX (code, sequence_identifier),
	ADD INDEX (institution_id, sequence_identifier),
	ADD INDEX (program_id, sequence_identifier),
	ADD INDEX (title, sequence_identifier),
	ADD INDEX (state_id, sequence_identifier),
	ADD INDEX (created_timestamp, sequence_identifier),
	ADD INDEX (updated_timestamp, sequence_identifier),
	ADD COLUMN application_created_count INT(10) UNSIGNED AFTER title,
	ADD COLUMN application_submitted_count INT(10) UNSIGNED AFTER application_created_count,
	ADD COLUMN application_approved_count INT(10) UNSIGNED AFTER application_submitted_count,
	ADD COLUMN application_rejected_count INT(10) UNSIGNED AFTER application_approved_count,
	ADD COLUMN application_withdrawn_count INT(10) UNSIGNED AFTER application_rejected_count,
	ADD COLUMN applicant_rating_percentile_05 DECIMAL(3,2) AFTER application_withdrawn_count,
	ADD COLUMN applicant_rating_percentile_20 DECIMAL(3,2) AFTER applicant_rating_percentile_05,
	ADD COLUMN applicant_rating_percentile_35 DECIMAL(3,2) AFTER applicant_rating_percentile_20,
	ADD COLUMN applicant_rating_percentile_50 DECIMAL(3,2) AFTER applicant_rating_percentile_35,
	ADD COLUMN applicant_rating_percentile_65 DECIMAL(3,2) AFTER applicant_rating_percentile_50,
	ADD COLUMN applicant_rating_percentile_80 DECIMAL(3,2) AFTER applicant_rating_percentile_65,
	ADD COLUMN applicant_rating_percentile_95 DECIMAL(3,2) AFTER applicant_rating_percentile_80,
	ADD INDEX (application_created_count, sequence_identifier),
	ADD INDEX (application_submitted_count, sequence_identifier),
	ADD INDEX (application_approved_count, sequence_identifier),
	ADD INDEX (application_rejected_count, sequence_identifier),
	ADD INDEX (application_withdrawn_count, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_05, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_20, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_35, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_50, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_65, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_80, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_95, sequence_identifier)
;

ALTER TABLE PROGRAM
	ADD INDEX (code, sequence_identifier),
	ADD INDEX (imported_code, sequence_identifier),
	ADD INDEX (institution_id, sequence_identifier),
	ADD INDEX (program_type, sequence_identifier),
	ADD INDEX (title, sequence_identifier),
	ADD INDEX (state_id, sequence_identifier),
	ADD INDEX (created_timestamp, sequence_identifier),
	ADD INDEX (updated_timestamp, sequence_identifier),
	ADD COLUMN application_created_count INT(10) UNSIGNED AFTER require_project_definition,
	ADD COLUMN application_submitted_count INT(10) UNSIGNED AFTER application_created_count,
	ADD COLUMN application_approved_count INT(10) UNSIGNED AFTER application_submitted_count,
	ADD COLUMN application_rejected_count INT(10) UNSIGNED AFTER application_approved_count,
	ADD COLUMN application_withdrawn_count INT(10) UNSIGNED AFTER application_rejected_count,
	ADD COLUMN applicant_rating_percentile_05 DECIMAL(3,2) AFTER application_withdrawn_count,
	ADD COLUMN applicant_rating_percentile_20 DECIMAL(3,2) AFTER applicant_rating_percentile_05,
	ADD COLUMN applicant_rating_percentile_35 DECIMAL(3,2) AFTER applicant_rating_percentile_20,
	ADD COLUMN applicant_rating_percentile_50 DECIMAL(3,2) AFTER applicant_rating_percentile_35,
	ADD COLUMN applicant_rating_percentile_65 DECIMAL(3,2) AFTER applicant_rating_percentile_50,
	ADD COLUMN applicant_rating_percentile_80 DECIMAL(3,2) AFTER applicant_rating_percentile_65,
	ADD COLUMN applicant_rating_percentile_95 DECIMAL(3,2) AFTER applicant_rating_percentile_80,
	ADD INDEX (application_created_count, sequence_identifier),
	ADD INDEX (application_submitted_count, sequence_identifier),
	ADD INDEX (application_approved_count, sequence_identifier),
	ADD INDEX (application_rejected_count, sequence_identifier),
	ADD INDEX (application_withdrawn_count, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_05, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_20, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_35, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_50, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_65, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_80, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_95, sequence_identifier)
;

ALTER TABLE INSTITUTION
	ADD INDEX (code, sequence_identifier),
	ADD INDEX (user_id, sequence_identifier),
	ADD INDEX (institution_domicile_id, sequence_identifier),
	ADD INDEX (name, sequence_identifier),
	ADD INDEX (institution_address_id, sequence_identifier),
	ADD INDEX (state_id, sequence_identifier),
	ADD INDEX (created_timestamp, sequence_identifier),
	ADD INDEX (updated_timestamp, sequence_identifier),
	ADD COLUMN application_created_count INT(10) UNSIGNED AFTER is_ucl_institution,
	ADD COLUMN application_submitted_count INT(10) UNSIGNED AFTER application_created_count,
	ADD COLUMN application_approved_count INT(10) UNSIGNED AFTER application_submitted_count,
	ADD COLUMN application_rejected_count INT(10) UNSIGNED AFTER application_approved_count,
	ADD COLUMN application_withdrawn_count INT(10) UNSIGNED AFTER application_rejected_count,
	ADD COLUMN applicant_rating_percentile_05 DECIMAL(3,2) AFTER application_withdrawn_count,
	ADD COLUMN applicant_rating_percentile_20 DECIMAL(3,2) AFTER applicant_rating_percentile_05,
	ADD COLUMN applicant_rating_percentile_35 DECIMAL(3,2) AFTER applicant_rating_percentile_20,
	ADD COLUMN applicant_rating_percentile_50 DECIMAL(3,2) AFTER applicant_rating_percentile_35,
	ADD COLUMN applicant_rating_percentile_65 DECIMAL(3,2) AFTER applicant_rating_percentile_50,
	ADD COLUMN applicant_rating_percentile_80 DECIMAL(3,2) AFTER applicant_rating_percentile_65,
	ADD COLUMN applicant_rating_percentile_95 DECIMAL(3,2) AFTER applicant_rating_percentile_80,
	ADD INDEX (application_created_count, sequence_identifier),
	ADD INDEX (application_submitted_count, sequence_identifier),
	ADD INDEX (application_approved_count, sequence_identifier),
	ADD INDEX (application_rejected_count, sequence_identifier),
	ADD INDEX (application_withdrawn_count, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_05, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_20, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_35, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_50, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_65, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_80, sequence_identifier),
	ADD INDEX (applicant_rating_percentile_95, sequence_identifier)
;

CREATE TABLE APPLICATION_PROCESSING (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	application_id INT(10) UNSIGNED NOT NULL,
	state_group_id VARCHAR(50) NOT NULL,
	instance_count INT(10) UNSIGNED NOT NULL,
	day_duration_sum INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (application_id, state_group_id),
	INDEX (state_group_id),
	INDEX (instance_count),
	INDEX (day_duration_sum),
	FOREIGN KEY (application_id) REFERENCES APPLICATION (id),
	FOREIGN KEY (state_group_id) REFERENCES STATE_GROUP (id)
) ENGINE = INNODB
;

CREATE TABLE APPLICATION_PROCESSING_SUMMARY (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	institution_id INT(10) UNSIGNED,
	program_id INT(10) UNSIGNED,
	project_id INT(10) UNSIGNED,
	state_group_id VARCHAR(50) NOT NULL,
	instance_count_percentile_05 INT(10) UNSIGNED NOT NULL,
	instance_count_percentile_20 INT(10) UNSIGNED NOT NULL,
	instance_count_percentile_35 INT(10) UNSIGNED NOT NULL,
	instance_count_percentile_50 INT(10) UNSIGNED NOT NULL,
	instance_count_percentile_65 INT(10) UNSIGNED NOT NULL,
	instance_count_percentile_80 INT(10) UNSIGNED NOT NULL,
	instance_count_percentile_95 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_05 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_20 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_35 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_50 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_65 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_80 INT(10) UNSIGNED NOT NULL,
	day_duration_sum_percentile_95 INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (institution_id, state_group_id),
	UNIQUE INDEX (program_id, state_group_id),
	UNIQUE INDEX (project_id, state_group_id),
	INDEX (state_group_id),
	INDEX (instance_count_percentile_05),
	INDEX (instance_count_percentile_20),
	INDEX (instance_count_percentile_35),
	INDEX (instance_count_percentile_50),
	INDEX (instance_count_percentile_65),
	INDEX (instance_count_percentile_80),
	INDEX (instance_count_percentile_95),
	INDEX (day_duration_sum_percentile_05),
	INDEX (day_duration_sum_percentile_20),
	INDEX (day_duration_sum_percentile_35),
	INDEX (day_duration_sum_percentile_50),
	INDEX (day_duration_sum_percentile_65),
	INDEX (day_duration_sum_percentile_80),
	INDEX (day_duration_sum_percentile_95),
	FOREIGN KEY (institution_id) REFERENCES INSTITUTION (id),
	FOREIGN KEY (program_id) REFERENCES PROGRAM (id),
	FOREIGN KEY (project_id) REFERENCES PROJECT (id),
	FOREIGN KEY (state_group_id) REFERENCES STATE_GROUP (id)
) ENGINE = INNODB
;
