ALTER TABLE INSTITUTION_DOMICILE
	ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT "TEMPORARY" AFTER name,
	ADD INDEX (currency)
;

ALTER TABLE INSTITUTION_DOMICILE
	MODIFY COLUMN currency VARCHAR(10) NOT NULL 
;

ALTER TABLE INSTITUTION
	ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT "GBP" AFTER title,
	ADD INDEX (currency)
;

ALTER TABLE INSTITUTION
	MODIFY COLUMN currency VARCHAR(10) NOT NULL
;

