ALTER TABLE COMMENT_ASSIGNED_USER
	MODIFY COLUMN comment_id INT(10) UNSIGNED
;

ALTER TABLE COMMENT_APPOINTMENT_TIMESLOT
	MODIFY COLUMN comment_id INT(10) UNSIGNED
;

ALTER TABLE COMMENT_APPOINTMENT_PREFERENCE
	MODIFY COLUMN comment_id INT(10) UNSIGNED
;

ALTER TABLE DOCUMENT
	MODIFY COLUMN comment_id INT(10) UNSIGNED
;
