ALTER TABLE APPLICATION
	CHANGE COLUMN do_retain retain INT(1) UNSIGNED NOT NULL
;

ALTER TABLE APPLICATION_SUPERVISOR
	ADD COLUMN application_id INT(10) UNSIGNED AFTER id,
	ADD UNIQUE INDEX (application_id, user_id),
	ADD FOREIGN KEY (application_id) REFERENCES APPLICATION (id)
;

UPDATE APPLICATION_SUPERVISOR INNER JOIN APPLICATION_PROGRAM_DETAIL
	ON APPLICATION_SUPERVISOR.application_program_detail_id = APPLICATION_PROGRAM_DETAIL.id 
INNER JOIN APPLICATION
	ON APPLICATION_PROGRAM_DETAIL.id = APPLICATION.application_program_detail_id
SET APPLICATION_SUPERVISOR.application_id = APPLICATION.id
;

ALTER TABLE APPLICATION_SUPERVISOR
	DROP FOREIGN KEY application_supervisor_ibfk_1,
	DROP INDEX application_program_detail_id,
	DROP COLUMN application_program_detail_id,
	MODIFY COLUMN application_id INT(10) UNSIGNED NOT NULL
;

ALTER TABLE COMMENT_ASSIGNED_USER
	MODIFY comment_id INT(10) UNSIGNED NOT NULL
;

ALTER TABLE COMMENT_APPOINTMENT_TIMESLOT
	MODIFY comment_id INT(10) UNSIGNED NOT NULL
;	

ALTER TABLE COMMENT_APPOINTMENT_PREFERENCE
	MODIFY comment_id INT(10) UNSIGNED NOT NULL
;

UPDATE APPLICATION
SET due_date = due_date + INTERVAL 168 DAY
WHERE state_id IN ("APPLICATION_APPROVED_COMPLETED", "APPLICATION_REJECTED_COMPLETED", "APPLICATION_WITHDRAWN_COMPLETED")
;

DELETE FROM APPLICATION_FUNDING
WHERE id = 398
;

ALTER TABLE APPLICATION_FUNDING
	DROP INDEX funding_doc_fk,
	ADD UNIQUE INDEX (document_id)
;

DELETE FROM APPLICATION_QUALIFICATION
WHERE id IN (3573, 3678, 8587, 9273, 10889)
;

ALTER TABLE APPLICATION_QUALIFICATION
	DROP INDEX proof_of_award_fk,
	ADD UNIQUE INDEX (document_id)
;
