ALTER TABLE COMMENT_ASSIGNED_USER
	ADD COLUMN role_transition_type VARCHAR(50) NOT NULL DEFAULT "CREATE",
	ADD INDEX (role_transition_type)
;

ALTER TABLE COMMENT_ASSIGNED_USER
	MODIFY COLUMN role_transition_type VARCHAR(50) NOT NULL
;
