ALTER TABLE INSTITUTION_DOMICILE_REGION
	ADD COLUMN nested_path VARCHAR(255) NOT NULL DEFAULT "UNASSIGNED" AFTER parent_region_id,
	ADD COLUMN nested_level INTEGER(2) UNSIGNED NOT NULL DEFAULT 0 AFTER nested_path,
	ADD INDEX (institution_domicile_id, nested_path)
;

ALTER TABLE INSTITUTION_DOMICILE_REGION
	MODIFY COLUMN nested_path VARCHAR(255) NOT NULL,
	MODIFY COLUMN nested_level INTEGER(2) UNSIGNED
;
