DROP TABLE ADVERT_TARGET
;

CREATE TABLE ADVERT_TARGET_INSTITUTION (
	advert_id INT(10) UNSIGNED NOT NULL,
	institution_id INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (advert_id, institution_id),
	INDEX (institution_id),
	FOREIGN KEY (advert_id) REFERENCES ADVERT (id),
	FOREIGN KEY (institution_id) REFERENCES INSTITUTION (id)
) ENGINE = INNODB
;

CREATE TABLE ADVERT_TARGET_PROGRAM_TYPE (
	advert_id INT(10) UNSIGNED NOT NULL,
	program_type VARCHAR(50) NOT NULL,
	PRIMARY KEY (advert_id, program_type),
	INDEX (program_type),
	FOREIGN KEY (advert_id) REFERENCES ADVERT (id)
) ENGINE = INNODB
;

DROP TABLE ADVERT_KEYWORD
;

DROP TABLE ADVERT_OPPORTUNITY_CATEGORY
;

CREATE TABLE ADVERT_SUBJECT (
	advert_id INT(10) UNSIGNED NOT NULL,
	subject_category VARCHAR(50) NOT NULL,
	PRIMARY KEY (advert_id, subject_category),
	INDEX (subject_category),
	FOREIGN KEY (advert_id) REFERENCES ADVERT (id)
) ENGINE = INNODB
;

CREATE TABLE ADVERT_INDUSTRY (
	advert_id INT(10) UNSIGNED NOT NULL,
	industry_category VARCHAR(50) NOT NULL,
	PRIMARY KEY (advert_id, industry_category),
	INDEX (industry_category),
	FOREIGN KEY (advert_id) REFERENCES ADVERT (id)
) ENGINE = INNODB
;

DELETE INSTITUTION_DOMICILE_REGION.*
FROM INSTITUTION_DOMICILE INNER JOIN INSTITUTION_DOMICILE_REGION
	ON INSTITUTION_DOMICILE.id = INSTITUTION_DOMICILE_REGION.institution_domicile_id
WHERE INSTITUTION_DOMICILE.currency = "TEMPORARY"
;

DELETE INSTITUTION_DOMICILE_REGION.*, INSTITUTION_DOMICILE.*
FROM INSTITUTION_DOMICILE INNER JOIN INSTITUTION_DOMICILE_REGION
	ON INSTITUTION_DOMICILE.id = INSTITUTION_DOMICILE_REGION.institution_domicile_id
WHERE INSTITUTION_DOMICILE.currency = "TEMPORARY"
;

ALTER TABLE INSTITUTION_DOMICILE
	ADD COLUMN location_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER currency,
	ADD COLUMN location_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_x,
	ADD COLUMN location_view_ne_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_y,
	ADD COLUMN location_view_ne_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_ne_x,
	ADD COLUMN location_view_sw_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_ne_y,
	ADD COLUMN location_view_sw_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_sw_x,
	ADD INDEX (location_x),
	ADD INDEX (location_y)
;

ALTER TABLE INSTITUTION_DOMICILE
	MODIFY COLUMN location_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_y DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_ne_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_ne_y DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_sw_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_sw_y DECIMAL(18,14) NOT NULL
;

ALTER TABLE INSTITUTION_DOMICILE_REGION
	ADD COLUMN location_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER name,
	ADD COLUMN location_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_x,
	ADD COLUMN location_view_ne_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_y,
	ADD COLUMN location_view_ne_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_ne_x,
	ADD COLUMN location_view_sw_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_ne_y,
	ADD COLUMN location_view_sw_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_sw_x,
	ADD INDEX (location_x),
	ADD INDEX (location_y)
;

ALTER TABLE INSTITUTION_DOMICILE_REGION
	MODIFY COLUMN location_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_y DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_ne_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_ne_y DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_sw_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_sw_y DECIMAL(18,14) NOT NULL
;

ALTER TABLE INSTITUTION_ADDRESS
	ADD COLUMN location_x DECIMAL(18,14) NOT NULL DEFAULT 0.00,
	ADD COLUMN location_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_x,
	ADD COLUMN location_view_ne_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_y,
	ADD COLUMN location_view_ne_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_ne_x,
	ADD COLUMN location_view_sw_x DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_ne_y,
	ADD COLUMN location_view_sw_y DECIMAL(18,14) NOT NULL DEFAULT 0.00 AFTER location_view_sw_x,
	ADD INDEX (location_x),
	ADD INDEX (location_y)
;

ALTER TABLE INSTITUTION_ADDRESS
	MODIFY COLUMN location_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_y DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_ne_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_ne_y DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_sw_x DECIMAL(18,14) NOT NULL,
	MODIFY COLUMN location_view_sw_y DECIMAL(18,14) NOT NULL
;
