SET foreign_key_checks = 0
;

ALTER TABLE PROGRAM
	MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT
;

ALTER TABLE PROJECT
	MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT
;

SET foreign_key_checks = 1
;
