ALTER TABLE INSTITUTION
	ADD COLUMN google_identifier VARCHAR(255) AFTER homepage,
	ADD INDEX (google_identifier),
	ADD COLUMN linkedin_identifier VARCHAR(255) AFTER google_identifier,
	ADD INDEX (linkedin_identifier),
	ADD UNIQUE INDEX (title, google_identifier)
;

ALTER TABLE INSTITUTION
	MODIFY COLUMN title VARCHAR(255) NOT NULL
;

ALTER TABLE INSTITUTION_DOMICILE
	MODIFY COLUMN name VARCHAR(255) NOT NULL
;

ALTER TABLE INSTITUTION_DOMICILE_REGION
	MODIFY COLUMN region_type VARCHAR(255) NOT NULL,
	MODIFY COLUMN name VARCHAR(255) NOT NULL
;

ALTER TABLE INSTITUTION_ADDRESS
	MODIFY COLUMN address_line_1 VARCHAR(255) NOT NULL,
	MODIFY COLUMN address_line_2 VARCHAR(255),
	MODIFY COLUMN address_town VARCHAR(255),
	MODIFY COLUMN address_code VARCHAR(255)
;

ALTER TABLE INSTITUTION_ADDRESS
	ADD COLUMN institution_id INT(10) UNSIGNED AFTER institution_domicile_region_id,
	ADD INDEX (institution_id),
	ADD FOREIGN KEY (institution_id) REFERENCES INSTITUTION (id)
;

UPDATE INSTITUTION_ADDRESS INNER JOIN INSTITUTION
	ON INSTITUTION_ADDRESS.id = INSTITUTION.institution_address_id
SET INSTITUTION_ADDRESS.institution_id = INSTITUTION.id
;

UPDATE INSTITUTION_ADDRESS INNER JOIN ADVERT
	ON INSTITUTION_ADDRESS.id = ADVERT.institution_address_id
INNER JOIN PROJECT
	ON ADVERT.id = PROJECT.advert_id
SET INSTITUTION_ADDRESS.institution_id = PROJECT.institution_id
;

UPDATE INSTITUTION_ADDRESS INNER JOIN ADVERT
	ON INSTITUTION_ADDRESS.id = ADVERT.institution_address_id
INNER JOIN PROGRAM
	ON ADVERT.id = PROGRAM.advert_id
SET INSTITUTION_ADDRESS.institution_id = PROGRAM.institution_id
;
