DELETE
FROM INSTITUTION_ADDRESS
WHERE institution_id IS NULL
;

ALTER TABLE INSTITUTION_ADDRESS
	DROP FOREIGN KEY institution_address_ibfk_4,
	MODIFY COLUMN institution_id INT(10) UNSIGNED NOT NULL,
	ADD FOREIGN KEY (institution_id) REFERENCES INSTITUTION (id)
;

ALTER TABLE INSTITUTION_ADDRESS
	MODIFY COLUMN address_town VARCHAR(255) NOT NULL
;
