ALTER TABLE IMPORTED_ENTITY
	DROP INDEX institution_id_2
;

ALTER TABLE IMPORTED_INSTITUTION
	DROP INDEX institution_id_2
;

ALTER TABLE IMPORTED_LANGUAGE_QUALIFICATION_TYPE
	DROP INDEX institution_id_2
;

ALTER TABLE COMMENT_CUSTOM_QUESTION
	ADD COLUMN system_id INT(10) UNSIGNED AFTER id,
	ADD COLUMN institution_id INT(10) UNSIGNED AFTER system_id,
	MODIFY COLUMN program_id INT(10) UNSIGNED,
	ADD INDEX (system_id),
	ADD INDEX (institution_id),
	ADD FOREIGN KEY (system_id) REFERENCES SYSTEM (id),
	ADD FOREIGN KEY (institution_id) REFERENCES INSTITUTION (id)
;

ALTER TABLE SYSTEM
	DROP INDEX code,
	DROP INDEX sequence_identifier,
	ADD UNIQUE INDEX (code),
	ADD UNIQUE INDEX (sequence_identifier)
;

ALTER TABLE INSTITUTION
	ADD UNIQUE INDEX (code),
	ADD UNIQUE INDEX (sequence_identifier)
;

ALTER TABLE PROGRAM
	ADD UNIQUE INDEX (code),
	ADD UNIQUE INDEX (sequence_identifier)
;

ALTER TABLE PROJECT
	ADD UNIQUE INDEX (code),
	ADD UNIQUE INDEX (sequence_identifier)
;

ALTER TABLE APPLICATION
	ADD UNIQUE INDEX (code),
	ADD UNIQUE INDEX (sequence_identifier)
;
