CREATE TABLE DISPLAY_CONFIGURATION (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	system_id INT(10) UNSIGNED,
	locale VARCHAR(10) NOT NULL,
	institution_id INT(10) UNSIGNED,
	program_id INT(10) UNSIGNED,
	property_category VARCHAR(50) NOT NULL,
	property_key VARCHAR(50) NOT NULL,
	property_value TEXT NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (system_id, locale, property_category, property_key),
	UNIQUE INDEX (institution_id, property_category, property_key),
	UNIQUE INDEX (program_id, property_category, property_key),
	FOREIGN KEY (system_id) REFERENCES SYSTEM (id),
	FOREIGN KEY (institution_id) REFERENCES INSTITUTION (id),
	FOREIGN KEY (program_id) REFERENCES PROGRAM (id)
) ENGINE = INNODB
;

ALTER TABLE INSTITUTION
	ADD COLUMN locale VARCHAR(10) NOT NULL DEFAULT "EN_GB" AFTER title
;

ALTER TABLE INSTITUTION
	MODIFY COLUMN locale VARCHAR(10) NOT NULL
;

ALTER TABLE PROGRAM
	MODIFY COLUMN code VARCHAR(50) AFTER id,
	MODIFY COLUMN advert_id INT(10) UNSIGNED AFTER user_id,
	MODIFY COLUMN system_id INT(10) UNSIGNED AFTER user_id,
	MODIFY COLUMN institution_id INT(10) UNSIGNED AFTER system_id,
	ADD COLUMN locale VARCHAR(10) NOT NULL DEFAULT "EN_GB" AFTER title
;

ALTER TABLE PROGRAM
	MODIFY COLUMN locale VARCHAR(10) NOT NULL
;

ALTER TABLE SYSTEM
	ADD COLUMN locale VARCHAR(10) NOT NULL DEFAULT "EN_GB" AFTER title
;

ALTER TABLE SYSTEM
	MODIFY COLUMN locale VARCHAR(10) NOT NULL
;

ALTER TABLE COMMENT_CUSTOM_QUESTION
	DROP COLUMN is_enabled,
	DROP INDEX system_id,
	DROP INDEX institution_id,
	ADD UNIQUE INDEX (system_id, action_id),
	ADD UNIQUE INDEX (institution_id, action_id)
;

ALTER TABLE COMMENT_CUSTOM_QUESTION_VERSION
	ADD COLUMN name VARCHAR(50) NOT NULL DEFAULT "Extended Questions" AFTER comment_custom_question_id,
	ADD UNIQUE INDEX (comment_custom_question_id, name)
;

ALTER TABLE COMMENT_CUSTOM_QUESTION_VERSION
	MODIFY COLUMN name VARCHAR(50) NOT NULL
;

ALTER TABLE NOTIFICATION_CONFIGURATION
	ADD COLUMN subject VARCHAR(255) AFTER notification_template_version_id,
	ADD COLUMN content TEXT AFTER subject
;

UPDATE NOTIFICATION_CONFIGURATION INNER JOIN NOTIFICATION_TEMPLATE_VERSION
	ON NOTIFICATION_CONFIGURATION.notification_template_version_id = NOTIFICATION_TEMPLATE_VERSION.id
SET NOTIFICATION_CONFIGURATION.subject = NOTIFICATION_TEMPLATE_VERSION.subject,
	NOTIFICATION_CONFIGURATION.content = NOTIFICATION_TEMPLATE_VERSION.content
;

ALTER TABLE NOTIFICATION_CONFIGURATION
	MODIFY COLUMN subject VARCHAR(255) NOT NULL,
	MODIFY COLUMN content TEXT NOT NULL,
	DROP FOREIGN KEY notification_configuration_ibfk_5,
	DROP COLUMN notification_template_version_id
;

DROP TABLE NOTIFICATION_TEMPLATE_VERSION
;

ALTER TABLE COMMENT_CUSTOM_QUESTION_VERSION
	DROP COLUMN created_timestamp
;

ALTER TABLE COMMENT_CUSTOM_QUESTION
	DROP FOREIGN KEY comment_custom_question_ibfk_3,
	DROP COLUMN comment_custom_question_version_id
;

DROP TABLE CONFIGURATION
;
