UPDATE COMMENT
SET state_id = transition_state_id
WHERE state_id IS NULL
;

SET FOREIGN_KEY_CHECKS = 0
;

ALTER TABLE DISPLAY_CATEGORY
	MODIFY COLUMN id VARCHAR(100) NOT NULL
;

ALTER TABLE DISPLAY_PROPERTY
	MODIFY COLUMN display_category_id VARCHAR(100) NOT NULL,
	MODIFY COLUMN property_index VARCHAR(100) NOT NULL
;

SET FOREIGN_KEY_CHECKS = 1
;
