ALTER TABLE ADVERT_DOMAIN
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (advert_id, domain)
;

ALTER TABLE ADVERT_FUNCTION
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (advert_id, function)
;

ALTER TABLE ADVERT_INDUSTRY
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (advert_id, industry)
;

ALTER TABLE ADVERT_TARGET_INSTITUTION
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (advert_id, institution_id)
;

ALTER TABLE ADVERT_TARGET_PROGRAM_TYPE
	DROP PRIMARY KEY,
	ADD COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id),
	ADD UNIQUE INDEX (advert_id, program_type)
;
