ALTER TABLE STATE_ACTION_NOTIFICATION
	ADD COLUMN notify_invoker INT(1) UNSIGNED NOT NULL DEFAULT 0,
	ADD INDEX (notify_invoker)
;

ALTER TABLE STATE_ACTION_NOTIFICATION
	MODIFY COLUMN notify_invoker INT(1) UNSIGNED NOT NULL
;
