DROP TABLE APPLICATION_SECONDARY_PROJECT
;

CREATE TABLE ADVERT_THEME (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	advert_id INT(10) UNSIGNED NOT NULL,
	theme VARCHAR(50) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX (theme, advert_id),
	UNIQUE INDEX (advert_id, theme),
	CONSTRAINT FOREIGN KEY (advert_id) REFERENCES ADVERT (id)
) ENGINE=InnoDB
;
