UPDATE COMMENT
SET state_id = "APPLICATION_APPROVAL"
WHERE action_id = "APPLICATION_COMPLETE_APPROVAL_STAGE"
;

UPDATE COMMENT
SET state_id = "APPLICATION_INTERVIEW"
WHERE action_id = "APPLICATION_COMPLETE_INTERVIEW_STAGE"
;

UPDATE COMMENT
SET state_id = "APPLICATION_REVIEW"
WHERE action_id = "APPLICATION_COMPLETE_REVIEW_STAGE"
;

UPDATE COMMENT
SET state_id = "APPLICATION_VALIDATION"
WHERE action_id = "APPLICATION_COMPLETE_VALIDATION_STAGE"
;

UPDATE COMMENT
SET state_id = "APPLICATION_UNSUBMITTED"
WHERE action_id = "PROGRAM_CREATE_APPLICATION"
;

UPDATE COMMENT
SET state_id = "APPLICATION_UNSUBMITTED"
WHERE action_id = "PROJECT_CREATE_APPLICATION"
;
