INSERT INTO STATE (id, state_group_id, scope_id)
VALUES("INSTITUTION_APPROVED_COMPLETED", "INSTITUTION_APPROVED", "INSTITUTION")
;

UPDATE INSTITUTION INNER JOIN IMPORTED_ENTITY_FEED
	ON INSTITUTION.id = IMPORTED_ENTITY_FEED.institution_id
SET INSTITUTION.state_id = "INSTITUTION_APPROVED_COMPLETED"
WHERE INSTITUTION.state_id = "INSTITUTION_APPROVED"
;
