ALTER TABLE DISPLAY_PROPERTY
	ADD COLUMN program_type VARCHAR(50) NOT NULL DEFAULT "STUDY_POSTGRADUATE_RESEARCH" AFTER system_id
;

ALTER TABLE DISPLAY_PROPERTY
	MODIFY COLUMN program_type VARCHAR(50) NOT NULL
;
