SET FOREIGN_KEY_CHECKS = 0
;

UPDATE ACTION
SET id = REPLACE(id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE ACTION
SET fallback_action_id = REPLACE(fallback_action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE ACTION_REDACTION
SET action_id = REPLACE(action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE STATE_ACTION
SET action_id = REPLACE(action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE STATE_TRANSITION
SET transition_action_id = REPLACE(transition_action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE STATE_TRANSITION_PROPAGATION
SET propagated_action_id = REPLACE(propagated_action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE STATE_ACTION_ASSIGNMENT
SET delegated_action_id = REPLACE(delegated_action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE COMMENT
SET action_id = REPLACE(action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

UPDATE COMMENT_CUSTOM_QUESTION
SET action_id = REPLACE(action_id, "CONFIRM_SUPERVISION", "CONFIRM_PRIMARY_SUPERVISION")
;

SET FOREIGN_KEY_CHECKS = 1
;
