ALTER TABLE COMMENT_CUSTOM_QUESTION
	ADD COLUMN content TEXT after action_id
;

UPDATE COMMENT_CUSTOM_QUESTION INNER JOIN COMMENT_CUSTOM_QUESTION_VERSION
	ON COMMENT_CUSTOM_QUESTION.id = COMMENT_CUSTOM_QUESTION_VERSION.comment_custom_question_id
SET COMMENT_CUSTOM_QUESTION.content = COMMENT_CUSTOM_QUESTION_VERSION.content
;

ALTER TABLE COMMENT
	ADD COLUMN comment_custom_question_id INT(10) UNSIGNED AFTER comment_custom_question_version_id,
	ADD INDEX (comment_custom_question_id),
	ADD FOREIGN KEY (comment_custom_question_id) REFERENCES COMMENT_CUSTOM_QUESTION (id)
;

UPDATE COMMENT INNER JOIN COMMENT_CUSTOM_QUESTION_VERSION
	ON COMMENT.comment_custom_question_version_id = COMMENT_CUSTOM_QUESTION_VERSION.id
SET COMMENT.comment_custom_question_id = COMMENT_CUSTOM_QUESTION_VERSION.comment_custom_question_id
;

ALTER TABLE COMMENT
	DROP FOREIGN KEY comment_ibfk_9,
	DROP COLUMN comment_custom_question_version_id
;

DROP TABLE COMMENT_CUSTOM_QUESTION_VERSION
;
