ALTER TABLE APPLICATION
	DROP INDEX sequence_identifier_2
;

ALTER TABLE PROJECT
	DROP INDEX sequence_identifier_2
;

ALTER TABLE PROGRAM
	DROP INDEX sequence_identifier_2
;

ALTER TABLE INSTITUTION
	DROP INDEX sequence_identifier_2
;

ALTER TABLE SYSTEM
	DROP INDEX sequence_identifier,
	ADD INDEX (sequence_identifier)
;

ALTER TABLE COMMENT_CUSTOM_QUESTION
	MODIFY COLUMN locale VARCHAR(10)
;

ALTER TABLE DISPLAY_VALUE
	MODIFY COLUMN locale VARCHAR(10)
;

ALTER TABLE NOTIFICATION_CONFIGURATION
	MODIFY COLUMN locale VARCHAR(10)
;

ALTER TABLE STATE_DURATION
	MODIFY COLUMN locale VARCHAR(10)
;

ALTER TABLE WORKFLOW_PROPERTY_CONFIGURATION
	MODIFY COLUMN locale VARCHAR(10)
;
