ALTER TABLE APPLICATION_LANGUAGE_QUALIFICATION
	CHANGE COLUMN imported_language_qualification_type_id language_qualification_type_id INT(10) UNSIGNED
;

INSERT INTO IMPORTED_LANGUAGE_QUALIFICATION_TYPE (institution_id, code, name, enabled)
VALUES(5243, "OTHER", "Other Language Qualification", 1),
	(5831, "OTHER", "Other Language Qualification", 1)
;

UPDATE APPLICATION_LANGUAGE_QUALIFICATION 
INNER JOIN APPLICATION_PERSONAL_DETAIL
	ON APPLICATION_LANGUAGE_QUALIFICATION.id = APPLICATION_PERSONAL_DETAIL.application_language_qualification_id
INNER JOIN APPLICATION
	ON APPLICATION_PERSONAL_DETAIL.id = APPLICATION.application_personal_detail_id
SET APPLICATION_LANGUAGE_QUALIFICATION.language_qualification_type_id = (
	SELECT id
	FROM IMPORTED_LANGUAGE_QUALIFICATION_TYPE
	WHERE code = "OTHER"
		AND institution_id = 5243)
WHERE language_qualification_type_id NOT IN (
	SELECT id
	FROM IMPORTED_LANGUAGE_QUALIFICATION_TYPE
	WHERE code IN ("IELTS_ACADEMIC", "TOEFL_INTERNET", "TOEFL_PAPER")
		AND institution_id = 5243)
	AND APPLICATION.institution_id = 5243
;

UPDATE APPLICATION_LANGUAGE_QUALIFICATION 
INNER JOIN APPLICATION_PERSONAL_DETAIL
	ON APPLICATION_LANGUAGE_QUALIFICATION.id = APPLICATION_PERSONAL_DETAIL.application_language_qualification_id
INNER JOIN APPLICATION
	ON APPLICATION_PERSONAL_DETAIL.id = APPLICATION.application_personal_detail_id
SET APPLICATION_LANGUAGE_QUALIFICATION.language_qualification_type_id = (
	SELECT id
	FROM IMPORTED_LANGUAGE_QUALIFICATION_TYPE
	WHERE code = "OTHER"
		AND institution_id = 5831)
WHERE language_qualification_type_id NOT IN (
	SELECT id
	FROM IMPORTED_LANGUAGE_QUALIFICATION_TYPE
	WHERE code IN ("IELTS_ACADEMIC", "TOEFL_INTERNET", "TOEFL_PAPER")
			AND institution_id = 5831)
	AND APPLICATION.institution_id = 5831
;

DELETE FROM IMPORTED_LANGUAGE_QUALIFICATION_TYPE
WHERE code NOT IN ("IELTS_ACADEMIC", "TOEFL_INTERNET", "TOEFL_PAPER", "OTHER")
;
