DROP TABLE ACTION_TRIGGER_STATE
;

CREATE TABLE STATE_DURATION_DEFINITION (
	id VARCHAR(50) NOT NULL,
	scope_id VARCHAR(50) NOT NULL,
	PRIMARY KEY (id),
	INDEX (scope_id),
	FOREIGN KEY (scope_id) REFERENCES SCOPE (id)
) ENGINE = INNODB
;

RENAME TABLE STATE_DURATION TO STATE_DURATION_CONFIGURATION
;

DELETE
FROM STATE_DURATION_CONFIGURATION
;

ALTER TABLE STATE_DURATION_CONFIGURATION
	DROP FOREIGN KEY state_duration_configuration_ibfk_4,
	CHANGE COLUMN state_id state_duration_definition_id VARCHAR(50) NOT NULL,
	ADD FOREIGN KEY (state_duration_definition_id) REFERENCES STATE_DURATION_DEFINITION (id)
;

RENAME TABLE DISPLAY_PROPERTY TO DISPLAY_PROPERTY_DEFINITION
;

RENAME TABLE DISPLAY_VALUE TO DISPLAY_PROPERTY_CONFIGURATION
;
