DROP TABLE RESOURCE_PROPERTY_CONFIGURATION
;

DROP TABLE RESOURCE_PROPERTY_DEFINITION
;

ALTER TABLE WORKFLOW_PROPERTY_CONFIGURATION
	ADD COLUMN version INT(10) UNSIGNED AFTER workflow_property_definition_id,
	ADD INDEX (version)
;
