ALTER TABLE WORKFLOW_PROPERTY_DEFINITION
	ADD COLUMN can_be_optional INT(1) UNSIGNED NOT NULL DEFAULT 0 AFTER can_be_disabled
;

ALTER TABLE WORKFLOW_PROPERTY_DEFINITION
	MODIFY COLUMN can_be_optional INT(1) UNSIGNED NOT NULL
;
