ALTER TABLE RESOURCE_PREVIOUS_STATE
	CHANGE COLUMN previous_state_id state_id VARCHAR(50) NOT NULL
;

ALTER TABLE COMMENT_TRANSITION_STATE
	CHANGE COLUMN transition_state_id state_id VARCHAR(50) NOT NULL
;
