ALTER TABLE COMMENT_TRANSITION_STATE
	DROP FOREIGN KEY comment_transition_state_ibfk_2,
	CHANGE COLUMN transition_state_id state_id VARCHAR(50) NOT NULL
;

ALTER TABLE COMMENT_TRANSITION_STATE
	ADD FOREIGN KEY (state_id) REFERENCES STATE (id)
;
