ALTER TABLE APPLICATION_PERSONAL_DETAIL
	MODIFY COLUMN first_language_locale INT(1) UNSIGNED,
	MODIFY COLUMN visa_required INT(1) UNSIGNED
;

ALTER TABLE APPLICATION_DOCUMENT
	MODIFY COLUMN cv_id INT(10) UNSIGNED,
	MODIFY COLUMN personal_statement_id INT(10) UNSIGNED
;
