SET FOREIGN_KEY_CHECKS = 0
;

UPDATE WORKFLOW_PROPERTY_DEFINITION
SET id = "APPLICATION_DEMOGRAPHIC"
WHERE id = "APPLICATION_CREATOR_DEMOGRAPHIC"
;

UPDATE WORKFLOW_PROPERTY_CONFIGURATION
SET workflow_property_definition_id = "APPLICATION_DEMOGRAPHIC"
WHERE workflow_property_definition_id = "APPLICATION_CREATOR_DEMOGRAPHIC"
;

SET FOREIGN_KEY_CHECKS = 1
;
