ALTER TABLE APPLICATION_QUALIFICATION
	MODIFY title VARCHAR(200)
;

UPDATE APPLICATION_QUALIFICATION
SET title = NULL
WHERE LENGTH(title) = 0
;

ALTER TABLE APPLICATION_EMPLOYMENT_POSITION
	CHANGE COLUMN is_current current INT(1) UNSIGNED NOT NULL
;
