ALTER TABLE STATE
	ADD COLUMN hidden INT(1) UNSIGNED NOT NULL DEFAULT 0 AFTER parallelizable,
	DROP FOREIGN KEY state_ibfk_2,
	DROP INDEX scope_id
;

ALTER TABLE STATE
	MODIFY COLUMN hidden INT(1) UNSIGNED NOT NULL,
	ADD INDEX (scope_id, hidden),
	ADD FOREIGN KEY (scope_id) REFERENCES SCOPE (id)
;
