DELETE FROM DISPLAY_PROPERTY_CONFIGURATION
WHERE display_property_definition_id IN (
	SELECT id
	FROM DISPLAY_PROPERTY_DEFINITION
	WHERE category = "PROJECT_WORKFLOW")
;

DELETE 
FROM DISPLAY_PROPERTY_DEFINITION
WHERE category = "PROJECT_WORKFLOW"
;
