UPDATE PROGRAM INNER JOIN (
	SELECT MAX(application_close_date) AS end_date,
		program_id AS program_id
	FROM PROGRAM_STUDY_OPTION
	GROUP BY program_id) AS PROGRAM_END_DATE
	ON PROGRAM.id = PROGRAM_END_DATE.program_id
SET PROGRAM.end_date = PROGRAM_END_DATE.end_date
WHERE PROGRAM.imported_code IS NOT NULL
;

UPDATE PROGRAM
SET due_date = NULL
WHERE imported_code IS NOT NULL
AND state_id IN ("PROGRAM_APPROVED", "PROGRAM_DEACTIVATED")
;

UPDATE PROJECT INNER JOIN PROGRAM
	ON PROJECT.program_id = PROGRAM.id
SET PROJECT.end_date = PROGRAM.end_date
WHERE PROGRAM.imported_code IS NOT NULL
	AND PROGRAM.end_date IS NOT NULL
	AND PROJECT.state_id IN ("PROJECT_APPROVED", "PROJECT_DEACTIVATED")
;
