UPDATE APPLICATION
SET state_id = "APPLICATION_WITHDRAWN_COMPLETED_UNSUBMITTED"
WHERE state_id = "APPLICATION_WITHDRAWN_COMPLETED"
AND previous_state_id IN ("APPLICATION_UNSUBMITTED", "APPLICATION_UNSUBMITTED_PENDING_COMPLETION")
;
