ALTER TABLE APPLICATION_ADDITIONAL_INFORMATION
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_ADDRESS
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_DOCUMENT
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_EMPLOYMENT_POSITION
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_FUNDING
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_LANGUAGE_QUALIFICATION
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_PASSPORT
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_PERSONAL_DETAIL
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_PRIZE
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_PROGRAM_DETAIL
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_QUALIFICATION
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_REFEREE
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_SUPERVISOR
	ADD COLUMN last_edited_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
;

ALTER TABLE APPLICATION_ADDITIONAL_INFORMATION
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_ADDRESS
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_DOCUMENT
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_EMPLOYMENT_POSITION
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_FUNDING
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_LANGUAGE_QUALIFICATION
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_PASSPORT
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_PERSONAL_DETAIL
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_PRIZE
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_PROGRAM_DETAIL
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_QUALIFICATION
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_REFEREE
	MODIFY COLUMN last_edited_timestamp DATETIME
;

ALTER TABLE APPLICATION_SUPERVISOR
	MODIFY COLUMN last_edited_timestamp DATETIME
;
