package com.zuehlke.pgadmissions.domain.enums;

public enum ActionType {

    ASSIGN_INTERVIEWERS,
    ASSIGN_REVIEWERS,
    ASSIGN_SUPERVISORS,
    COMMENT,
    COMPLETE_APPROVAL_STAGE,
    COMPLETE_INTERVIEW_STAGE,
    COMPLETE_REVIEW_STAGE,
    COMPLETE_VALIDATION_STAGE,
    CONFIRM_ELIGIBILITY,
    CONFIRM_INTERVIEW_ARRANGEMENTS,
    CONFIRM_OFFER_RECOMMENDATION,
    CONFIRM_PRIMARY_SUPERVISION,
    CONFIRM_REJECTION,
    EMAIL_APPLICANT,
    MOVE_TO_DIFFERENT_STAGE,
    PROVIDE_INTERVIEW_AVAILABILITY,
    PROVIDE_INTERVIEW_FEEDBACK,
    PROVIDE_REFERENCE,
    PROVIDE_REVIEW,
    RETRACT_INTERVIEW_AVAILABILITY,
    VIEW_EDIT,
    WITHDRAW

}
