package com.zuehlke.pgadmissions.domain.enums;

public enum ApplicationFormTransferErrorType {
    WEBSERVICE_APPLICATION_VALIDATION_FAILED,
    WEBSERVICE_PUBLISHER_SECURITY_PROBLEM,
    WEBSERVICE_HOST_UNREACHABLE,
    WEBSERVICE_UNEXPECTED_EXCEPTION,
    SFTP_HOST_UNREACHABLE,
    SFTP_LOGIN_FAILED,
    SFTP_UNEXPECTED_EXCEPTION
}
