package com.zuehlke.pgadmissions.domain.enums;


public enum ApplicationFormAction {

    COMMENT, 
    EMAIL_APPLICANT, 
    MOVE_TO_DIFFERENT_STAGE, 
    RETRACT_INTERVIEW_AVAILABILITY, 
    VIEW, 
    VIEW_EDIT, 
    WITHDRAW, 
    PROVIDE_INTERVIEW_AVAILABILITY, 
    PROVIDE_REFERENCE, 
    ASSIGN_INTERVIEWERS, 
    ASSIGN_REVIEWERS, 
    ASSIGN_SUPERVISORS, 
    COMPLETE_APPROVAL_STAGE, 
    COMPLETE_INTERVIEW_STAGE, 
    COMPLETE_REVIEW_STAGE, 
    COMPLETE_VALIDATION_STAGE, 
    CONFIRM_ELIGIBILITY, 
    CONFIRM_INTERVIEW_ARRANGEMENTS, 
    CONFIRM_OFFER_RECOMMENDATION, 
    CONFIRM_PRIMARY_SUPERVISION, 
    CONFIRM_REJECTION, 
    PROVIDE_INTERVIEW_FEEDBACK, 
    PROVIDE_REVIEW,
    CREATE_APPLICATION,
    COMPLETE_APPLICATION,
    CORRECT_APPLICATION;

}