package com.zuehlke.pgadmissions.domain.enums;


public enum ApplicationFormAction {

    APPLICATION_ASSIGN_INTERVIEWERS,
    APPLICATION_ASSIGN_REVIEWERS,
    APPLICATION_ASSIGN_SUPERVISORS,
    APPLICATION_COMMENT,
    APPLICATION_COMPLETE_APPROVAL_STAGE_AS_APPLICATION_ADMINISTRATOR,
    APPLICATION_COMPLETE_APPROVAL_STAGE_AS_PROGRAM_ADMINISTRATOR,
    APPLICATION_COMPLETE_APPROVAL_STAGE_AS_PROGRAM_APPROVER,
    APPLICATION_COMPLETE_INTERVIEW_STAGE_AS_APPLICATION_ADMINISTRATOR,
    APPLICATION_COMPLETE_INTERVIEW_STAGE_AS_PROGRAM_ADMINISTRATOR,
    APPLICATION_COMPLETE_REVIEW_STAGE_AS_APPLICATION_ADMINISTRATOR,
    APPLICATION_COMPLETE_REVIEW_STAGE_AS_PROGRAM_ADMINISTRATOR,
    APPLICATION_COMPLETE_VALIDATION_STAGE,
    APPLICATION_CONFIRM_ELIGIBILITY,
    APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS,
    APPLICATION_CONFIRM_OFFER_RECOMMENDATION,
    APPLICATION_CONFIRM_PRIMARY_SUPERVISION,
    APPLICATION_CONFIRM_REJECTION,
    APPLICATION_EMAIL_APPLICANT,
    APPLICATION_MOVE_TO_DIFFERENT_STAGE,
    APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY,
    APPLICATION_PROVIDE_INTERVIEW_FEEDBACK,
    APPLICATION_PROVIDE_REFERENCE,
    APPLICATION_PROVIDE_REVIEW,
    APPLICATION_RETRACT_INTERVIEW_AVAILABILITY,
    APPLICATION_COMPLETE_APPLICATION,
    APPLICATION_CORRECT_APPLICATION,
    APPLICATION_EDIT_AS_ADMINISTRATOR,
    APPLICATION_EDIT_AS_APPLICANT,
    APPLICATION_VIEW_AS_APPLICANT,
    APPLICATION_VIEW_AS_RECRUITER,
    APPLICATION_VIEW_AS_REFEREE,
    APPLICATION_WITHDRAW,
    INSTITUTION_CONFIGURE,
    PROGRAM_COMPLETE_APPROVAL_STAGE,
    PROGRAM_CONFIGURE,
    PROGRAM_CREATE_PROJECT,
    PROGRAM_EMAIL_APPLICANT,
    PROJECT_CONFIGURE,
    SYSTEM_CONFIGURE
    ;

}