package com.zuehlke.pgadmissions.domain.enums;

public enum ApplicationFormAction {

    APPAPPLICATION_ASSESS_ELIGIBILITY, //
    APPLICATION_ASSIGN_INTERVIEWERS, //
    APPLICATION_ASSIGN_REVIEWERS, //
    APPLICATION_ASSIGN_SUPERVISORS, //
    APPLICATION_COMMENT, //
    APPLICATION_COMPLETE, //
    APPLICATION_COMPLETE_APPROVAL_STAGE, //
    APPLICATION_COMPLETE_INTERVIEW_STAGE, //
    APPLICATION_COMPLETE_REVIEW_STAGE, //
    APPLICATION_COMPLETE_VALIDATION_STAGE, //
    APPLICATION_CONFIRM_ELIGIBILITY, //
    APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS, //
    APPLICATION_CONFIRM_OFFER_RECOMMENDATION, //
    APPLICATION_CONFIRM_PRIMARY_SUPERVISION, //
    APPLICATION_CONFIRM_REJECTION, //
    APPLICATION_CORRECT, //
    APPLICATION_EDIT_AS_ADMINISTRATOR, //
    APPLICATION_EDIT_AS_CREATOR, //
    APPLICATION_EMAIL_CREATOR, //
    APPLICATION_ESCALATE, //
    APPLICATION_EXPORT, //
    APPLICATION_MOVE_TO_DIFFERENT_STAGE, //
    APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY, //
    APPLICATION_PROVIDE_INTERVIEW_FEEDBACK, //
    APPLICATION_PROVIDE_REFERENCE, //
    APPLICATION_PROVIDE_REVIEW, //
    APPLICATION_UPDATE_INTERVIEW_AVAILABILITY, //
    APPLICATION_VIEW_AS_CREATOR, //
    APPLICATION_VIEW_AS_RECRUITER, //
    APPLICATION_VIEW_AS_REFEREE, //
    APPLICATION_WITHDRAW, //
    INSTITUTION_CONFIGURE, //
    INSTITUTION_CREATE_PROGRAM, //
    INSTITUTION_SUGGEST_PROGRAM, //
    PROGRAM_COMPLETE_APPROVAL_STAGE, //
    PROGRAM_CONFIGURE, //
    PROGRAM_CREATE_APPLICATION, //
    PROGRAM_CREATE_PROJECT, //
    PROGRAM_EMAIL_CREATOR, //
    PROGRAM_ESCALATE, //
    PROGRAM_REACTIVATE, //
    PROJECT_CONFIGURE, //
    PROJECT_CREATE_APPLICATION, //
    PROJECT_ESCALATE, //
    PROJECT_REACTIVATE, //
    SYSTEM_CONFIGURE;

}