package com.zuehlke.pgadmissions.domain.enums;

import org.apache.commons.lang.StringUtils;

public enum ApplicationFormStatus {

    APPLICATION_APPROVAL, //
    APPLICATION_APPROVAL_PENDING_COMPLETION, //
    APPLICATION_APPROVAL_PENDING_FEEDBACK, //
    APPLICATION_APPROVED, //
    APPLICATION_APPROVED_COMPLETED, //
    APPLICATION_APPROVED_PENDING_CORRECTION, //
    APPLICATION_APPROVED_PENDING_EXPORT, //
    APPLICATION_INTERVIEW, //
    APPLICATION_INTERVIEW_PENDING_AVAILABILITY, //
    APPLICATION_INTERVIEW_PENDING_COMPLETION, //
    APPLICATION_INTERVIEW_PENDING_FEEDBACK, //
    APPLICATION_INTERVIEW_PENDING_INTERVIEW, //
    APPLICATION_INTERVIEW_PENDING_SCHEDULING, //
    APPLICATION_REJECTED, //
    APPLICATION_REJECTED_COMPLETED, //
    APPLICATION_REJECTED_PENDING_CORRECTION, //
    APPLICATION_REJECTED_PENDING_EXPORT, //
    APPLICATION_REVIEW, //
    APPLICATION_REVIEW_PENDING_COMPLETION, //
    APPLICATION_REVIEW_PENDING_FEEDBACK, //
    APPLICATION_UNSUBMITTED, //
    APPLICATION_UNSUBMITTED_PENDING_COMPLETION, //
    APPLICATION_VALIDATION, //
    APPLICATION_VALIDATION_PENDING_COMPLETION, //
    APPLICATION_VALIDATION_PENDING_FEEDBACK, //
    APPLICATION_WITHDRAWN, //
    APPLICATION_WITHDRAWN_COMPLETED, //
    APPLICATION_WITHDRAWN_PENDING_CORRECTION, //
    APPLICATION_WITHDRAWN_PENDING_EXPORT, //
    INSTITUTION_APPROVED, //
    PROGRAM_APPROVAL, //
    PROGRAM_APPROVED, //
    PROGRAM_DEACTIVATED, //
    PROGRAM_DISABLED, //
    PROGRAM_DISABLED_COMPLETED, //
    PROGRAM_DISABLED_PENDING_COMPLETION, //
    PROGRAM_REJECTED, //
    PROJECT_APPROVED, //
    PROJECT_DEACTIVATED, //
    PROJECT_DISABLED, //
    PROJECT_DISABLED_COMPLETED, //
    PROJECT_DISABLED_PENDING_COMPLETION, //
SYSTEM_APPROVED;

    
}
