package com.zuehlke.pgadmissions.domain.enums;

public enum Authority {

	ADMINISTRATOR,
	ADMITTER,
	APPROVER,
	INTERVIEWER,
	PRIMARYSUPERVISOR,
	PROJECTADMINISTRATOR,
	PROJECTAUTHOR,
	PROJECTPRIMARYSUPERVISOR,
	PROJECTSECONDARYSUPERVISOR,
	REFEREE,
	REVIEWER,
	SAFETYNET,
	SECONDARYSUPERVISOR,
	STATEADMINISTRATOR,
	SUGGESTEDSUPERVISOR,
	SUPERADMINISTRATOR,
	VIEWER,
	APPLICANT;
    
}