package com.zuehlke.pgadmissions.domain.enums;

public enum AuthorityGroup {

	ADMITTERADMINISTRATOR,
	COMMENTER,
	CRIMINALCONVICTIONSVIEWER,
	EQUALOPPORTUNITIESVIEWER,
	POTENTIALSUPERVISOR,
	PROGRAMADMINISTRATOR,
	PROGRAMAUTHOR,
	PROJECTADMINISTRATOR,
	PROJECTAUTHOR,
	PROJECTEDITOR,
	PROJECTSUPERAUTHOR,
	RECRUITER,
	REFEREE,
	SYSTEMADMINISTRATOR;
	
}