package com.zuehlke.pgadmissions.domain.enums;

public enum Authority {

    APPLICATION_ADMINISTRATOR, //
    APPLICATION_CREATOR, //
    APPLICATION_INTERVIEWEE, //
    APPLICATION_INTERVIEWER, //
    APPLICATION_POTENTIAL_INTERVIEWEE, //
    APPLICATION_POTENTIAL_INTERVIEWER, //
    APPLICATION_PRIMARY_SUPERVISOR, //
    APPLICATION_REFEREE, //
    APPLICATION_REVIEWER, //
    APPLICATION_SECONDARY_SUPERVISOR, //
    APPLICATION_SUGGESTED_SUPERVISOR, //
    APPLICATION_VIEWER_RECRUITER, //
    APPLICATION_VIEWER_REFEREE, //
    INSTITUTION_ADMINISTRATOR, //
    INSTITUTION_ADMITTER, //
    INSTITUTION_PROGRAM_CREATOR, //
    PROGRAM_ADMINISTRATOR, //
    PROGRAM_APPLICATION_CREATOR, //
    PROGRAM_APPROVER, //
    PROGRAM_PROJECT_CREATOR, //
    PROGRAM_VIEWER, //
    PROJECT_ADMINISTRATOR, //
    PROJECT_APPLICATION_CREATOR, //
    PROJECT_PRIMARY_SUPERVISOR, //
    PROJECT_SECONDARY_SUPERVISOR, //
    SYSTEM_ADMINISTRATOR, //
    SYSTEM_APPLICATION_CREATOR, //
    SYSTEM_PROGRAM_CREATOR;

}