package com.zuehlke.pgadmissions.domain.enums;

public enum CommentType {
    GENERIC, ADMITTER_COMMENT, VALIDATION, REVIEW, REVIEW_EVALUATION, INTERVIEW, INTERVIEW_EVALUATION, APPROVAL, APPROVAL_EVALUATION, REFERENCE, REQUEST_RESTART, SUPERVISION_CONFIRMATION, INTERVIEW_VOTE, INTERVIEW_SCHEDULE, STATE_CHANGE_SUGGESTION;
}
