package com.zuehlke.pgadmissions.domain.enums;

public enum CommentType {
    GENERIC, VALIDATION, REVIEW, REVIEW_EVALUATION, INTERVIEW, INTERVIEW_EVALUATION, APPROVAL, APPROVAL_EVALUATION, REFERENCE, REQUEST_RESTART, SUPERVISION_CONFIRMATION, INTERVIEW_VOTE;
}
