package com.zuehlke.pgadmissions.domain.enums;

public enum CommentPropertyType {
	
	ACADMEMICALLYQUALIFIED,
	LINGUISTICALLYQUALIFIED,
	FEESTATUS,
	PRIMARYSUPERVISOR,
	SECONDARYSUPERVISOR,
	PROJECTDESCRIPTIONAVAILABLE,
	PROJECTTITLE,
	PROJECTABSTRACT,
	RECOMMENDEDOFFERCONDITIONSAVAILABLE,
	RECOMMENDEDSTARTDATE,
	RECOMMENDEDOFFERCONDITIONS,
	WILLINGTOINTERVIEW,
	WILLINGTOSUPERVISE,
	SUITABLEFORINSTITUTION,
	SUITABLEFORPROGRAMME,
	APPLICANTRATING,
	INTERVIEWEEINSTRUCTIONS,
	INTERVIEWERINSTRUCTIONS,
	INTERVIEWLOCATION,
	PROPOSEDINTERVIEWDATETIME,
	CONFIRMEDINTERVIEWDATETIME,
	PROPOSEDINTERVIEWDATETIMEAVAILABILITY,
	REASONFORREJECTION,
	PROPOSEDNEXTSTATUS,
	CONFIRMEDNEXTSTATUS,
	DELEGATEADMINISTRATOR,
	SECONDSINREVIEWSTATE,
	SECONDSININTERVIEWSTATE,
	SECONDSINAPPROVALSTATE;
	
}