package com.zuehlke.pgadmissions.domain.enums;

public enum NotificationType {
	VALIDATION_REMINDER, UPDATED_NOTIFICATION,APPLICANT_SUBMISSION_NOTIFICATION, REFEREE_RESPONDED_NOTIFICATION, APPLICANT_MOVED_TO_REVIEW_NOTIFICATION, REVIEWER_ADDED_REVIEW_COMMENT_NOTIFICATION;
}
