package com.zuehlke.pgadmissions.domain.enums;

public enum NotificationType {
	VALIDATION_REMINDER,
	REVIEW_REMINDER,
	INTERVIEW_REMINDER,
	APPROVAL_REMINDER,
	UPDATED_NOTIFICATION,
	APPROVAL_NOTIFICATION,
	APPROVED_NOTIFICATION,
	APPLICANT_SUBMISSION_NOTIFICATION,
	REFEREE_RESPONDED_NOTIFICATION,
	APPLICANT_MOVED_TO_REVIEW_NOTIFICATION,
	APPLICATION_MOVED_TO_REJECT_NOTIFICATION,
	APPLICANT_MOVED_TO_INTERVIEW_NOTIFICATION, 
	APPLICATION_MOVED_TO_APPROVAL_NOTIFICATION,
	APPLICATION_MOVED_TO_APPROVED_NOTIFICATION,
	REGISTRY_HELP_REQUEST,
	APPROVAL_RESTART_REQUEST_NOTIFICATION, 
	APPROVAL_RESTART_REQUEST_REMINDER,
	INTERVIEW_ADMINISTRATION_REMINDER;
}
