package com.zuehlke.pgadmissions.domain.enums;

public enum NotificationType {
    
    APPLICANT_MOVED_TO_INTERVIEW_NOTIFICATION, 
    
    APPLICANT_MOVED_TO_REVIEW_NOTIFICATION,
    
    APPLICANT_SUBMISSION_NOTIFICATION,
    
    APPLICATION_MOVED_TO_APPROVAL_NOTIFICATION,
    
    APPLICATION_MOVED_TO_APPROVED_NOTIFICATION,
    
    APPLICATION_MOVED_TO_REJECT_NOTIFICATION,
    
    APPROVAL_NOTIFICATION,
    APPROVAL_REMINDER,
    
    APPROVAL_RESTART_REQUEST_NOTIFICATION, 
    APPROVAL_RESTART_REQUEST_REMINDER,
    
    APPROVED_NOTIFICATION,
    
    INTERVIEW_ADMINISTRATION_REMINDER,
    INTERVIEW_ADMINISTRATION_REQUEST,
    INTERVIEW_FEEDBACK_REQUEST,
    INTERVIEW_FEEDBACK_REMINDER,
    INTERVIEW_EVALUATION_REQUEST,
    INTERVIEW_EVALUATION_REMINDER,
    
    REFEREE_RESPONDED_NOTIFICATION,
    
    REGISTRY_HELP_REQUEST,
    
    @Deprecated
    INTERVIEW_REMINDER,
    
    REVIEW_REMINDER,
    REVIEW_REQUEST,
    REVIEW_EVALUATION_REMINDER,
    
    UPDATED_NOTIFICATION,
    
    VALIDATION_REMINDER,
    
    REPEAT_VALIDATION_REMINDER,
    
    REPEAT_VALIDATION_REQUEST;
}
