package com.zuehlke.pgadmissions.domain.enums;

public enum OpportunityListType {
    OPPORTUNITIESBYFEEDID,
    OPPORTUNITIESBYUSERUPI,
    OPPORTUNITIESBYUSERUSERNAME,
    RECOMMENDEDOPPORTUNTIIES,
    CURRENTOPPORTUNITYBYADVERTID,
    CURRENTOPPORTUNITYBYPROGRAMCODE;
}
