package com.zuehlke.pgadmissions.domain.enums;

public enum PrismAction {

    APPLICATION_ASSESS_ELIGIBILITY(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_ASSIGN_INTERVIEWERS(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_ASSIGN_REVIEWERS(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_ASSIGN_SUPERVISORS(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_COMMENT(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_COMPLETE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_COMPLETE_APPROVAL_STAGE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_COMPLETE_INTERVIEW_STAGE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_COMPLETE_REVIEW_STAGE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_COMPLETE_VALIDATION_STAGE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_CONFIRM_ELIGIBILITY(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_CONFIRM_INTERVIEW_ARRANGEMENTS(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_CONFIRM_OFFER_RECOMMENDATION(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_CONFIRM_REJECTION(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_CONFIRM_SUPERVISION(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_CORRECT(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_EMAIL_CREATOR(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_ESCALATE(PrismActionType.SYSTEM_ESCALATION, PrismScope.APPLICATION), //
    APPLICATION_EXPORT(PrismActionType.SYSTEM_ESCALATION, PrismScope.APPLICATION), //
    APPLICATION_MOVE_TO_DIFFERENT_STAGE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_PROVIDE_INTERVIEW_AVAILABILITY(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_PROVIDE_INTERVIEW_FEEDBACK(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_PROVIDE_REFERENCE(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_PROVIDE_REVIEW(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_TERMINATE(PrismActionType.SYSTEM_PROPAGATION, PrismScope.APPLICATION), //
    APPLICATION_UPDATE_INTERVIEW_AVAILABILITY(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_VIEW_EDIT(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    APPLICATION_WITHDRAW(PrismActionType.USER_INVOCATION, PrismScope.APPLICATION), //
    INSTITUTION_CONFIGURE(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_CREATE_PROGRAM(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_EXPORT_APPLICATIONS(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_EXPORT_PROGRAMS(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_IMPORT_PROGRAM(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_VIEW(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_VIEW_APPLICATION_LIST(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_VIEW_PROGRAM_LIST(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    INSTITUTION_VIEW_PROJECT_LIST(PrismActionType.USER_INVOCATION, PrismScope.INSTITUTION), //
    PROGRAM_COMPLETE_APPROVAL_STAGE(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_CONCLUDE(PrismActionType.SYSTEM_PROPAGATION, PrismScope.PROGRAM), //
    PROGRAM_CONFIGURE(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_CORRECT(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_CREATE_APPLICATION(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_CREATE_PROJECT(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_EMAIL_CREATOR(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_ESCALATE(PrismActionType.SYSTEM_ESCALATION, PrismScope.PROGRAM), //
    PROGRAM_EXPORT_APPLICATIONS(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_RESTORE(PrismActionType.SYSTEM_PROPAGATION, PrismScope.PROGRAM), //
    PROGRAM_VIEW_APPLICATION_LIST(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_VIEW(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_VIEW_PROJECT_LIST(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROGRAM_WITHDRAW(PrismActionType.USER_INVOCATION, PrismScope.PROGRAM), //
    PROJECT_CONCLUDE(PrismActionType.SYSTEM_PROPAGATION, PrismScope.PROJECT), //
    PROJECT_CONFIGURE(PrismActionType.USER_INVOCATION, PrismScope.PROJECT), //
    PROJECT_CREATE_APPLICATION(PrismActionType.USER_INVOCATION, PrismScope.PROJECT), //
    PROJECT_ESCALATE(PrismActionType.SYSTEM_ESCALATION, PrismScope.PROJECT), //
    PROJECT_RESTORE(PrismActionType.SYSTEM_PROPAGATION, PrismScope.PROJECT), //
    PROJECT_SUSPEND(PrismActionType.SYSTEM_PROPAGATION, PrismScope.PROJECT), //
    PROJECT_TERMINATE(PrismActionType.SYSTEM_PROPAGATION, PrismScope.PROJECT), //
    PROJECT_VIEW(PrismActionType.USER_INVOCATION, PrismScope.PROJECT), //
    PROJECT_VIEW_APPLICATION_LIST(PrismActionType.USER_INVOCATION, PrismScope.PROJECT), //
    SYSTEM_CONFIGURE(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_CREATE_INSTITUTION(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_EXPORT_APPLICATIONS(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_EXPORT_PROGRAMS(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_MANAGE_ACCOUNT(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_VIEW_APPLICATION_LIST(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_VIEW_INSTITUTION_LIST(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_VIEW_PROGRAM_LIST(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM), //
    SYSTEM_VIEW_PROJECT_LIST(PrismActionType.USER_INVOCATION, PrismScope.SYSTEM);
    
    private PrismActionType actionType;
    
    private PrismScope scope;

    private PrismAction(PrismActionType actionType, PrismScope scope) {
        this.actionType = actionType;
        this.scope = scope;
    }
    
    public PrismActionType getActionType() {
        return actionType;
    }

    public PrismScope getScope() {
        return scope;
    }
    
}
