package com.zuehlke.pgadmissions.domain.enums;

import java.util.HashMap;

import com.google.common.collect.Maps;


public enum PrismState {

    APPLICATION_APPROVAL(5, null, PrismScope.APPLICATION), //
    APPLICATION_APPROVAL_PENDING_COMPLETION(null, null, PrismScope.APPLICATION), //
    APPLICATION_APPROVAL_PENDING_FEEDBACK(null, 7, PrismScope.APPLICATION), //
    APPLICATION_APPROVED(6, null, PrismScope.APPLICATION), //
    APPLICATION_APPROVED_COMPLETED(null, null, PrismScope.APPLICATION), //
    APPLICATION_APPROVED_PENDING_CORRECTION(null, null, PrismScope.APPLICATION), //
    APPLICATION_APPROVED_PENDING_EXPORT(null, null, PrismScope.APPLICATION), //
    APPLICATION_INTERVIEW(4, null, PrismScope.APPLICATION), //
    APPLICATION_INTERVIEW_PENDING_AVAILABILITY(null, 3, PrismScope.APPLICATION), //
    APPLICATION_INTERVIEW_PENDING_COMPLETION(null, null, PrismScope.APPLICATION), //
    APPLICATION_INTERVIEW_PENDING_FEEDBACK(null, 7, PrismScope.APPLICATION), //
    APPLICATION_INTERVIEW_PENDING_INTERVIEW(null, null, PrismScope.APPLICATION), //
    APPLICATION_INTERVIEW_PENDING_SCHEDULING(null, null, PrismScope.APPLICATION), //
    APPLICATION_REJECTED(7, null, PrismScope.APPLICATION), //
    APPLICATION_REJECTED_COMPLETED(null, null, PrismScope.APPLICATION), //
    APPLICATION_REJECTED_PENDING_CORRECTION(null, null, PrismScope.APPLICATION), //
    APPLICATION_REJECTED_PENDING_EXPORT(null, null, PrismScope.APPLICATION), //
    APPLICATION_REVIEW(3, null, PrismScope.APPLICATION), //
    APPLICATION_REVIEW_PENDING_COMPLETION(null, null, PrismScope.APPLICATION), //
    APPLICATION_REVIEW_PENDING_FEEDBACK(null, 7, PrismScope.APPLICATION), //
    APPLICATION_UNSUBMITTED(1, 28, PrismScope.APPLICATION), //
    APPLICATION_UNSUBMITTED_PENDING_COMPLETION(null, null, PrismScope.APPLICATION), //
    APPLICATION_VALIDATION(2, null, PrismScope.APPLICATION), //
    APPLICATION_VALIDATION_PENDING_COMPLETION(null, null, PrismScope.APPLICATION), //
    APPLICATION_VALIDATION_PENDING_FEEDBACK(null, 3, PrismScope.APPLICATION), //
    APPLICATION_WITHDRAWN(0, null, PrismScope.APPLICATION), //
    APPLICATION_WITHDRAWN_COMPLETED(null, null, PrismScope.APPLICATION), //
    APPLICATION_WITHDRAWN_PENDING_CORRECTION(null, null, PrismScope.APPLICATION), //
    INSTITUTION_APPROVED(1, null, PrismScope.INSTITUTION), //
    PROGRAM_APPROVAL(1, null, PrismScope.PROGRAM), //
    PROGRAM_APPROVAL_PENDING_CORRECTION(null, null, PrismScope.PROGRAM), //
    PROGRAM_APPROVED(2, null, PrismScope.PROGRAM), //
    PROGRAM_DEACTIVATED(null, null, PrismScope.PROGRAM), //
    PROGRAM_DISABLED(4, 28, PrismScope.PROGRAM), //
    PROGRAM_DISABLED_COMPLETED(null, null, PrismScope.PROGRAM), //
    PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION(null, 28, PrismScope.PROGRAM), //
    PROGRAM_DISABLED_PENDING_REACTIVATION(null, 28, PrismScope.PROGRAM), //
    PROGRAM_REJECTED(3, null, PrismScope.PROGRAM), //
    PROGRAM_WITHDRAWN(0, null, PrismScope.PROGRAM), //
    PROJECT_APPROVED(1, null, PrismScope.PROJECT), //
    PROJECT_DEACTIVATED(null, null, PrismScope.PROJECT), //
    PROJECT_DISABLED(2, 28, PrismScope.PROJECT), //
    PROJECT_DISABLED_COMPLETED(null, null, PrismScope.PROJECT), //
    PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION(null, null, PrismScope.PROJECT), //
    PROJECT_DISABLED_PENDING_REACTIVATION(null, 28, PrismScope.PROJECT), //
    SYSTEM_APPROVED(1, null, PrismScope.SYSTEM);
    
    private Integer sequenceOrder;
    
    private Integer duration;
    
    private PrismScope scope;
    
    private static final HashMap<PrismState, PrismState> parentState = Maps.newHashMap();
    
    static {
        parentState.put(APPLICATION_APPROVAL,APPLICATION_APPROVAL);
        parentState.put(APPLICATION_APPROVAL_PENDING_COMPLETION,APPLICATION_APPROVAL);
        parentState.put(APPLICATION_APPROVAL_PENDING_FEEDBACK,APPLICATION_APPROVAL);
        parentState.put(APPLICATION_APPROVED,APPLICATION_APPROVED);
        parentState.put(APPLICATION_APPROVED_COMPLETED,APPLICATION_APPROVED);
        parentState.put(APPLICATION_APPROVED_PENDING_CORRECTION,APPLICATION_APPROVED);
        parentState.put(APPLICATION_APPROVED_PENDING_EXPORT,APPLICATION_APPROVED);
        parentState.put(APPLICATION_INTERVIEW,APPLICATION_INTERVIEW);
        parentState.put(APPLICATION_INTERVIEW_PENDING_AVAILABILITY,APPLICATION_INTERVIEW);
        parentState.put(APPLICATION_INTERVIEW_PENDING_COMPLETION,APPLICATION_INTERVIEW);
        parentState.put(APPLICATION_INTERVIEW_PENDING_FEEDBACK,APPLICATION_INTERVIEW);
        parentState.put(APPLICATION_INTERVIEW_PENDING_INTERVIEW,APPLICATION_INTERVIEW);
        parentState.put(APPLICATION_INTERVIEW_PENDING_SCHEDULING,APPLICATION_INTERVIEW);
        parentState.put(APPLICATION_REJECTED,APPLICATION_REJECTED);
        parentState.put(APPLICATION_REJECTED_COMPLETED,APPLICATION_REJECTED);
        parentState.put(APPLICATION_REJECTED_PENDING_CORRECTION,APPLICATION_REJECTED);
        parentState.put(APPLICATION_REJECTED_PENDING_EXPORT,APPLICATION_REJECTED);
        parentState.put(APPLICATION_REVIEW,APPLICATION_REVIEW);
        parentState.put(APPLICATION_REVIEW_PENDING_COMPLETION,APPLICATION_REVIEW);
        parentState.put(APPLICATION_REVIEW_PENDING_FEEDBACK,APPLICATION_REVIEW);
        parentState.put(APPLICATION_UNSUBMITTED,APPLICATION_UNSUBMITTED);
        parentState.put(APPLICATION_UNSUBMITTED_PENDING_COMPLETION,APPLICATION_UNSUBMITTED);
        parentState.put(APPLICATION_VALIDATION,APPLICATION_VALIDATION);
        parentState.put(APPLICATION_VALIDATION_PENDING_COMPLETION,APPLICATION_VALIDATION);
        parentState.put(APPLICATION_VALIDATION_PENDING_FEEDBACK,APPLICATION_VALIDATION);
        parentState.put(APPLICATION_WITHDRAWN,APPLICATION_WITHDRAWN);
        parentState.put(APPLICATION_WITHDRAWN_COMPLETED,APPLICATION_WITHDRAWN);
        parentState.put(APPLICATION_WITHDRAWN_PENDING_CORRECTION,APPLICATION_WITHDRAWN);
        parentState.put(INSTITUTION_APPROVED,INSTITUTION_APPROVED);
        parentState.put(PROGRAM_APPROVAL,PROGRAM_APPROVAL);
        parentState.put(PROGRAM_APPROVAL_PENDING_CORRECTION,PROGRAM_APPROVAL);
        parentState.put(PROGRAM_APPROVED,PROGRAM_APPROVED);
        parentState.put(PROGRAM_DEACTIVATED,PROGRAM_APPROVED);
        parentState.put(PROGRAM_DISABLED,PROGRAM_DISABLED);
        parentState.put(PROGRAM_DISABLED_COMPLETED,PROGRAM_DISABLED);
        parentState.put(PROGRAM_DISABLED_PENDING_IMPORT_REACTIVATION,PROGRAM_DISABLED);
        parentState.put(PROGRAM_DISABLED_PENDING_REACTIVATION,PROGRAM_DISABLED);
        parentState.put(PROGRAM_REJECTED,PROGRAM_REJECTED);
        parentState.put(PROGRAM_WITHDRAWN,PROGRAM_WITHDRAWN);
        parentState.put(PROJECT_APPROVED,PROJECT_APPROVED);
        parentState.put(PROJECT_DEACTIVATED,PROJECT_APPROVED);
        parentState.put(PROJECT_DISABLED,PROJECT_DISABLED);
        parentState.put(PROJECT_DISABLED_COMPLETED,PROJECT_DISABLED);
        parentState.put(PROJECT_DISABLED_PENDING_PROGRAM_REACTIVATION,PROJECT_DISABLED);
        parentState.put(PROJECT_DISABLED_PENDING_REACTIVATION,PROJECT_DISABLED);
        parentState.put(SYSTEM_APPROVED,SYSTEM_APPROVED);
    }

    private PrismState(Integer sequenceOrder, Integer duration, PrismScope scope) {
        this.sequenceOrder = sequenceOrder;
        this.duration = duration;
        this.scope = scope;
    }
    
    public Integer getSequenceOrder() {
        return sequenceOrder;
    }

    public Integer getDuration() {
        return duration;
    }

    public PrismScope getScope() {
        return scope;
    }
    
    public static PrismState getParentState(PrismState state) {
        return parentState.get(state);
    }
}
