package com.zuehlke.pgadmissions.domain.enums;

public enum PrismRole {

    APPLICATION_ADMINISTRATOR(PrismScope.APPLICATION), //
    APPLICATION_CREATOR(PrismScope.APPLICATION), //
    APPLICATION_INTERVIEWEE(PrismScope.APPLICATION), //
    APPLICATION_INTERVIEWER(PrismScope.APPLICATION), //
    APPLICATION_POTENTIAL_INTERVIEWEE(PrismScope.APPLICATION), //
    APPLICATION_POTENTIAL_INTERVIEWER(PrismScope.APPLICATION), //
    APPLICATION_PRIMARY_SUPERVISOR(PrismScope.APPLICATION), //
    APPLICATION_REFEREE(PrismScope.APPLICATION), //
    APPLICATION_REVIEWER(PrismScope.APPLICATION), //
    APPLICATION_SECONDARY_SUPERVISOR(PrismScope.APPLICATION), //
    APPLICATION_SUGGESTED_SUPERVISOR(PrismScope.APPLICATION), //
    APPLICATION_VIEWER_RECRUITER(PrismScope.APPLICATION), //
    APPLICATION_VIEWER_REFEREE(PrismScope.APPLICATION), //
    INSTITUTION_ADMINISTRATOR(PrismScope.INSTITUTION), //
    INSTITUTION_ADMITTER(PrismScope.INSTITUTION), //
    PROGRAM_ADMINISTRATOR(PrismScope.PROGRAM), //
    PROGRAM_APPROVER(PrismScope.PROGRAM), //
    PROGRAM_VIEWER(PrismScope.PROGRAM), //
    PROJECT_ADMINISTRATOR(PrismScope.PROJECT), //
    PROJECT_PRIMARY_SUPERVISOR(PrismScope.PROJECT), //
    PROJECT_SECONDARY_SUPERVISOR(PrismScope.PROJECT), //
    SYSTEM_ADMINISTRATOR(PrismScope.SYSTEM);
    
    private PrismScope scope;
    
    private PrismRole(PrismScope scope) {
        this.scope = scope;
    }

    public PrismScope getScope() {
        return scope;
    }

}
