package com.zuehlke.pgadmissions.domain.definitions.workflow;

import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_ADMINISTRATOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_INTERVIEWEE;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_INTERVIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_POTENTIAL_INTERVIEWEE;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_POTENTIAL_INTERVIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_PRIMARY_SUPERVISOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_REVIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_SECONDARY_SUPERVISOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.APPLICATION_VIEWER_RECRUITER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.DEPARTMENT_ADMINISTRATOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.DEPARTMENT_APPROVER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.DEPARTMENT_VIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.DEPARTMENT_VIEWER_UNVERIFIED;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.INSTITUTION_ADMINISTRATOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.INSTITUTION_APPROVER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.INSTITUTION_VIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.INSTITUTION_VIEWER_UNVERIFIED;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROGRAM_ADMINISTRATOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROGRAM_APPROVER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROGRAM_VIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROJECT_ADMINISTRATOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROJECT_APPROVER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROJECT_PRIMARY_SUPERVISOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROJECT_SECONDARY_SUPERVISOR;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.PROJECT_VIEWER;
import static com.zuehlke.pgadmissions.domain.definitions.workflow.PrismRole.SYSTEM_ADMINISTRATOR;

public enum PrismRoleGroup {
    
    APPLICATION_PARENT_ADMINISTRATOR_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR, PROJECT_ADMINISTRATOR), //
    APPLICATION_PARENT_APPROVER_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, DEPARTMENT_APPROVER, PROGRAM_ADMINISTRATOR, PROGRAM_APPROVER, //
            PROJECT_ADMINISTRATOR, PROJECT_APPROVER), //
    APPLICATION_ADMINISTRATOR_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR, PROJECT_ADMINISTRATOR, //
            APPLICATION_ADMINISTRATOR), //
    APPLICATION_APPROVER_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, DEPARTMENT_APPROVER, PROGRAM_ADMINISTRATOR, PROGRAM_APPROVER, //
            PROJECT_ADMINISTRATOR, PROJECT_APPROVER, APPLICATION_ADMINISTRATOR), //
    APPLICATION_PARENT_VIEWER_GROUP(INSTITUTION_ADMINISTRATOR, INSTITUTION_APPROVER, INSTITUTION_VIEWER, DEPARTMENT_ADMINISTRATOR, DEPARTMENT_APPROVER, //
            DEPARTMENT_VIEWER, PROGRAM_ADMINISTRATOR, PROGRAM_APPROVER, PROGRAM_VIEWER, PROJECT_ADMINISTRATOR, PROJECT_APPROVER, PROJECT_PRIMARY_SUPERVISOR, //
            PROJECT_SECONDARY_SUPERVISOR, PROJECT_VIEWER), //
    APPLICATION_CONFIRMED_SUPERVISOR_GROUP(PROJECT_PRIMARY_SUPERVISOR, PROJECT_SECONDARY_SUPERVISOR, APPLICATION_PRIMARY_SUPERVISOR, //
            APPLICATION_SECONDARY_SUPERVISOR), //
    APPLICATION_POTENTIAL_SUPERVISOR_GROUP(PROJECT_PRIMARY_SUPERVISOR, PROJECT_SECONDARY_SUPERVISOR, APPLICATION_REVIEWER, APPLICATION_INTERVIEWER, //
            APPLICATION_PRIMARY_SUPERVISOR, APPLICATION_SECONDARY_SUPERVISOR, APPLICATION_VIEWER_RECRUITER), //
    APPLICATION_POTENTIAL_INTERVIEW_GROUP(APPLICATION_POTENTIAL_INTERVIEWER, APPLICATION_POTENTIAL_INTERVIEWEE), //
    APPLICATION_CONFIRMED_INTERVIEW_GROUP(APPLICATION_INTERVIEWER, APPLICATION_INTERVIEWEE), //
    
    PROJECT_SUPERVISOR_GROUP(PROJECT_PRIMARY_SUPERVISOR, PROJECT_SECONDARY_SUPERVISOR), //
    PROJECT_PARENT_ADMINISTRATOR_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR), //
    PROJECT_ADMINISTRATOR_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR, PROJECT_ADMINISTRATOR), //
    PROJECT_VERIFIED_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR, PROJECT_ADMINISTRATOR, PROJECT_APPROVER, //
            PROJECT_VIEWER, PROJECT_PRIMARY_SUPERVISOR, PROJECT_SECONDARY_SUPERVISOR), //
    
    PROGRAM_PARENT_ADMINISTRATOR_GROUP(SYSTEM_ADMINISTRATOR, INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR), //
    PROGRAM_ADMINISTRATOR_GROUP(SYSTEM_ADMINISTRATOR, INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR), //
    PROGRAM_VERIFIED_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, PROGRAM_ADMINISTRATOR, PROGRAM_APPROVER, PROGRAM_VIEWER), //
    
    DEPARTMENT_PARENT_ADMINISTRATOR_GROUP(SYSTEM_ADMINISTRATOR, INSTITUTION_ADMINISTRATOR), //
    DEPARTMENT_ADMINISTRATOR_GROUP(SYSTEM_ADMINISTRATOR, INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR), //
    DEPARTMENT_VERIFIED_GROUP(INSTITUTION_ADMINISTRATOR, DEPARTMENT_ADMINISTRATOR, DEPARTMENT_APPROVER, DEPARTMENT_VIEWER), //
    
    INSTITUTION_ADMINISTRATOR_GROUP(SYSTEM_ADMINISTRATOR, INSTITUTION_ADMINISTRATOR), //
    INSTITUTION_VERIFIED_GROUP(INSTITUTION_ADMINISTRATOR, INSTITUTION_APPROVER, INSTITUTION_VIEWER), //
    
    UNVERIFIED(INSTITUTION_VIEWER_UNVERIFIED, DEPARTMENT_VIEWER_UNVERIFIED); //

    private PrismRole[] roles;

    private PrismRoleGroup(PrismRole... roles) {
        this.roles = roles;
    }

    public PrismRole[] getRoles() {
        return roles;
    }

}
