package com.zuehlke.pgadmissions.domain.definitions.workflow;

public enum PrismRoleGroup {

	APPLICATION_PARENT_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROJECT_ADMINISTRATOR), //

	APPLICATION_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROJECT_ADMINISTRATOR, PrismRole.APPLICATION_ADMINISTRATOR), //

	APPLICATION_PARENT_VIEWER_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.INSTITUTION_ADMITTER, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROGRAM_APPROVER, PrismRole.PROGRAM_VIEWER,
	        PrismRole.PROJECT_ADMINISTRATOR, PrismRole.PROJECT_PRIMARY_SUPERVISOR, PrismRole.PROJECT_SECONDARY_SUPERVISOR), //

	APPLICATION_VIEWER_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.INSTITUTION_ADMITTER, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROGRAM_APPROVER, PrismRole.PROGRAM_VIEWER,
	        PrismRole.PROJECT_ADMINISTRATOR, PrismRole.PROJECT_PRIMARY_SUPERVISOR, PrismRole.PROJECT_SECONDARY_SUPERVISOR, PrismRole.APPLICATION_ADMINISTRATOR), //

	APPLICATION_CONFIRMED_SUPERVISOR_GROUP(PrismRole.PROJECT_PRIMARY_SUPERVISOR, PrismRole.PROJECT_SECONDARY_SUPERVISOR, PrismRole.APPLICATION_PRIMARY_SUPERVISOR,
	        PrismRole.APPLICATION_SECONDARY_SUPERVISOR), //

	APPLICATION_POTENTIAL_SUPERVISOR_GROUP(PrismRole.PROGRAM_APPROVER, PrismRole.PROGRAM_VIEWER, PrismRole.PROJECT_PRIMARY_SUPERVISOR, PrismRole.PROJECT_SECONDARY_SUPERVISOR,
	        PrismRole.APPLICATION_ADMINISTRATOR, PrismRole.APPLICATION_REVIEWER, PrismRole.APPLICATION_INTERVIEWER, PrismRole.APPLICATION_PRIMARY_SUPERVISOR, PrismRole.APPLICATION_SECONDARY_SUPERVISOR,
	        PrismRole.APPLICATION_VIEWER_RECRUITER), //

	APPLICATION_POTENTIAL_INTERVIEW_GROUP(PrismRole.APPLICATION_POTENTIAL_INTERVIEWER, PrismRole.APPLICATION_POTENTIAL_INTERVIEWEE), //

	APPLICATION_CONFIRMED_INTERVIEW_GROUP(PrismRole.APPLICATION_INTERVIEWER, PrismRole.APPLICATION_INTERVIEWEE), //

	PROJECT_SUPERVISOR_GROUP(PrismRole.PROJECT_PRIMARY_SUPERVISOR, PrismRole.PROJECT_SECONDARY_SUPERVISOR),

	PROJECT_PARENT_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMITTER, PrismRole.PROGRAM_ADMINISTRATOR),

	PROJECT_ADMINISTRATOR_GROUP(PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR, PrismRole.PROJECT_ADMINISTRATOR),

	PROGRAM_PARENT_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR),

	PROGRAM_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR, PrismRole.PROGRAM_ADMINISTRATOR),

	INSTITUTION_ADMINISTRATOR_GROUP(PrismRole.SYSTEM_ADMINISTRATOR, PrismRole.INSTITUTION_ADMINISTRATOR);

	private PrismRole[] roles;

	private PrismRoleGroup(PrismRole... roles) {
		this.roles = roles;
	}

	public PrismRole[] getRoles() {
		return roles;
	}

}