package com.zuehlke.pgadmissions.domain.definitions.workflow;

public enum PrismActionCommentField {

    CONTENT, //
    TRANSITION_STATE, //
    ASSIGNED_USERS, //
    DOCUMENTS, //
    APPLICATION_ELIGIBLE, //
    APPLICATION_INTERESTED, //
    APPLICATION_RATING, //
    INTERVIEW_DATE_TIME, //
    INTERVIEW_TIME_ZONE, //
    INTERVIEW_DURATION, //
    INTERVIEWEE_INSTRUCTIONS, //
    INTERVIEWER_INSTRUCTIONS, //
    INTERVIEW_LOCATION, //
    APPOINTMENT_TIMESLOTS, //
    APPOINTMENT_PREFERENCES, //
    RECRUITER_ACCEPT_APPOINTMENT, //
    DECLINED_RESPONSE, //
    REJECTION_REASON;

}
