package com.zuehlke.pgadmissions.domain.definitions.workflow;

public enum PrismActionCommentField {

    CONTENT, //
    TRANSITION_STATE, //
    ASSIGNED_USERS, //
    DOCUMENTS, //
    QUALIFIED, //
    COMPETENT_IN_WORK_LANGUAGE, //
    RESIDENCE_STATE, //
    SUITABLE_FOR_INSTITUTION, //
    SUITABLE_FOR_OPPORTUNITY, //
    DESIRE_TO_INTERVIEW, //
    DESIRE_TO_RECRUIT, //
    RATING, //
    INTERVIEW_DATE_TIME, //
    INTERVIEW_TIME_ZONE, //
    INTERVIEW_DURATION, //
    INTERVIEWEE_INSTRUCTIONS, //
    INTERVIEWER_INSTRUCTIONS, //
    INTERVIEW_LOCATION, //
    APPOINTMENT_TIMESLOTS, //
    APPOINTMENT_PREFERENCES, //
    RECRUITER_ACCEPT_APPOINTMENT, //
    POSITION_TITLE, //
    POSITION_DESCRIPTION, //
    POSITION_PROVISIONAL_START_DATE, //
    APPOINTMENT_CONDITIONS, //
    DECLINED_RESPONSE, //
    REJECTION_REASON;

}
